### ISSUE TITLE
promtool fail to creat block with out of bounds - maybe becaue the data is old 

### ISSUE THREAD

**Issue by amnonh** [prometheus/prometheus#8476] opened 2021-02-11 17:21 UTC
**What did you do?**
I run
```
$ promtool tsdb create-blocks-from openmetrics metrics.1.txt
block creation: process blocks: add sample: out of bounds
```
[metrics.1.txt](https://github.com/prometheus/prometheus/files/5967214/metrics.1.txt)

**What did you expect to see?**
promtool should have created the blocks from the metrics
**What did you see instead? Under which circumstances?**
```
block creation: process blocks: add sample: out of bounds
```
**Environment**
Prometheus over docker with centos as a host
* System information:

Linux 3.10.0-1062.12.1.el7.x86_64 x86_64

* Prometheus version:

prometheus, version 2.24.1 (branch: HEAD, revision: e4487274853c587717006eeda8804e597d120340)
  build user:       root@0b5231a0de0f
  build date:       20210120-00:09:36
  go version:       go1.15.6
  platform:         linux/amd64

* Prometheus configuration file:
```
global:
  scrape_interval: 20s # By default, scrape targets every 20 second.
  scrape_timeout: 15s # Timeout before trying to scape a target again

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'scylla-monitor'
rule_files:
  - /etc/prometheus/prometheus.rules.yml
    #
# Alerting specifies settings related to the Alertmanager.
alerting:
        #  alert_relabel_configs:
        #    [ - <relabel_config> ... ]
  alertmanagers:
  - static_configs:
    - targets:
        - 172.17.0.2:9093

scrape_configs:
- job_name: scylla
  honor_labels: false
  file_sd_configs:
    - files:
      - /etc/scylla.d/prometheus/scylla_servers.yml
  relabel_configs:
    - source_labels: [__address__]
      regex:  '([^:]+)'
      target_label: __address__
      replacement: '${1}:9180'

    - source_labels: [__address__]
      regex:  '(.*):.+'
      target_label: instance
      replacement: '${1}'
  metric_relabel_configs:
    - source_labels: [version]
      regex:  '(.+)'
      target_label: CPU
      replacement: 'cpu'
    - source_labels: [version]
      regex:  '(.+)'
      target_label: CQL
      replacement: 'cql'
    - source_labels: [version]
      regex:  '(.+)'
      target_label: OS
      replacement: 'os'
    - source_labels: [version]
      regex:  '(.+)'
      target_label: IO
      replacement: 'io'
    - source_labels: [version]
      regex:  '(.+)'
      target_label: Errors
      replacement: 'errors'
    - regex: 'help|exported_instance|type'
      action: labeldrop
    - source_labels: [version]
      regex: '([0-9]+\.[0-9]+)(\.?[0-9]*).*'
      replacement: '$1$2'
      target_label: svr

- job_name: node_exporter
  honor_labels: false
  scrape_interval: 1m # By default, scrape targets every 20 second.
  scrape_timeout: 20s # Timeout before trying to scape a target again
  file_sd_configs:
    - files:
      - /etc/scylla.d/prometheus/node_exporter_servers.yml
  relabel_configs:
    - source_labels: [__address__]
      regex:  '(.*):\d+'
      target_label: instance
      replacement: '${1}'
    - source_labels: [__address__]
      regex:  '([^:]+)'
      target_label: instance
      replacement: '${1}'
    - source_labels: [instance]
      regex:  '(.*)'
      target_label: __address__
      replacement: '${1}:9100'
- job_name: manager_agent
  honor_labels: false
  file_sd_configs:
    - files:
      - /etc/scylla.d/prometheus/scylla_servers.yml
  relabel_configs:
    - source_labels: [__address__]
      regex:  '(.*):\d+'
      target_label: instance
      replacement: '${1}'
    - source_labels: [__address__]
      regex:  '([^:]+)'
      target_label: instance
      replacement: '${1}'
    - source_labels: [instance]
      regex:  '(.*)'
      target_label: __address__
      replacement: '${1}:56090'

- job_name: manager_agent1
  honor_labels: false
  file_sd_configs:
    - files:
      - /etc/scylla.d/prometheus/scylla_servers.yml
  relabel_configs:
    - source_labels: [__address__]
      regex:  '(.*):\d+'
      target_label: instance
      replacement: '${1}'
    - source_labels: [__address__]
      regex:  '([^:]+)'
      target_label: instance
      replacement: '${1}'
    - source_labels: [instance]
      regex:  '(.*)'
      target_label: __address__
      replacement: '${1}:5090'

- job_name: scylla_manager
  honor_labels: false
  file_sd_configs:
    - files:
      - /etc/scylla.d/prometheus/scylla_manager_servers.yml
  metric_relabel_configs:
    - source_labels: [host]
      target_label: instance

- job_name: 'prometheus'
  # Override the global default and scrape targets from this job every 5 seconds.
  scrape_interval: 5s
  static_configs:
    - targets:
      - localhost:9090
```

**Comment by roidelapluie** [comment] 2021-02-11 20:45
Thank you, I can indeed reproduce this.

**Comment by roidelapluie** [comment] 2021-02-11 20:45
cc @codesome @aSquare14 @beorn7 Could someone look into this?

**Comment by beorn7** [comment] 2021-02-15 16:04
This seems to be more complicated than it looks. We probably need to loop in our TSDB experts, like @codesome.

**Comment by codesome** [comment] 2021-02-16 07:47
When you set block duration as 2h, then the max that you can go back when ingesting sample into TSDB is 1h from the max timestamp in TSDB. So I guess this is what is happening: One series has samples spanning the entire 2h block, so when we go to the next series to backfill, the first samples will be >1h old than the max ingested in the TSDB.

Since the backfill code controls the samples going into the TSDB, the fix would be creating the block writer for 4h instead of 2h.

**Comment by codesome** [comment] 2021-02-16 08:07
https://github.com/prometheus/prometheus/pull/8496 should fix it

**Comment by beorn7** [comment] 2021-02-17 12:40
This is now fixed in release-2.25 (and will be merged forward into the main branch any moment).

**Closed** 2021-02-17 12:39 UTC
Labels: component/promtool, component/tsdb, kind/bug, not-as-easy-as-it-looks

**Comment by amnonh** [comment] 2021-02-17 14:08
I would be happy to test it, once a docker with this fix is available

**Comment by aSquare14** [comment] 2021-02-20 03:39
@codesome Thanks for fixing this !
