### ISSUE TITLE
Weird behaviour of prometheus expression evaluation.

### ISSUE THREAD

**Issue by nchern** [prometheus/prometheus#1294] opened 2016-01-08 10:51 UTC
Hi @juliusv 

I've spotted a weird behaviour of prometheus expression evaluation.
Using prometheus web ui
`http://prometheus.<domain>/graph#<...>`
I queried a metric `xxx_requests_total{code=~"^500"}`. Metric with this exact name did not exist in my prometheus. But it returned all of OTHER existed metrics like `http_requests_total{code="500"}`, `mysvc_requests_tota{code="500"}` with the `code="500"` label. Behaviour would be the same even if I put smth like  `abc{code=~"^500"}`
Can you please clarify if this is expected behaviour or a bug?

Thanks

**Comment by fabxc** [comment] 2016-01-08 11:26
What version/revision are you running. I cannot reproduce this.

**Comment by nchern** [comment] 2016-01-08 11:46
0.15.0rc1

**Comment by beorn7** [comment] 2016-01-08 11:48
This behavior was fixed in 0.15.1.

**Closed by beorn7** 2016-01-08 11:48 UTC
