### ISSUE TITLE
prometheus agent must not be restarted when remote write server is down for long time

### ISSUE THREAD

**Issue by ad-c2-5083ud-j** [prometheus/prometheus#13539] opened 2024-02-05 11:34 UTC
### What did you do?

1. deploy prometheus in agent mode and remote write time series to remote tsdb
2. remote tsdb is down but scrape manager is working normally and write more data to wal segments
3. mutiple new wal segments are created when remote tsdb is down
4. restart prometheus

### What did you expect to see?

time series collected while tsdb is down should be sent to remote tsdb when it is back to online.

### What did you see instead? Under which circumstances?

time series collected while tsdb is down are not fully sent to tsdb. Only time series in latest wal segment are sent to tsdb

### System information

Debian 11

### Prometheus version

```text
2.49.0
```

**Comment by ad-c2-5083ud-j** [comment] 2024-02-06 01:17
I mean prometheus agent can not tolerate restart when tsdb is down, especially mutiple new wal segments are created during the 'tsdb-down-time'. When prometheus restart, it only sends timeseries in latest wal segment, because it does not have marker for 'time series have been sent last time'.

**Comment by darshanime** [comment] 2024-02-06 02:54
> it only sends timeseries in latest wal segment instead of all newly created segments

Can you share more info like config, flags with which you run the agent, how long does the tsdb remain down?

It could be expected behavior (from the docs I linked above):
> Failures will be retried without loss of data unless the remote endpoint remains down for more than 2 hours. After 2 hours, the WAL will be compacted and data that has not been sent will be lost.

**Comment by ad-c2-5083ud-j** [comment] 2024-02-06 03:58
From the wal code, when prometheus restart, it only send samples in newest wal segment file. So it has no relationship with 2 hours. If new segments are created(perhaps less than 1 hour), then samples that are not in newest segment will not be sent when restart happens.

**Comment by ad-c2-5083ud-j** [comment] 2024-02-06 04:01
So I have a question, why we need wal in prometheus agent mode?  what does wal in agent mode can give us?
why not we just scrape metrics from exporter and directly proxy to remote tsdb?

**Comment by cstyan** [comment] 2024-02-06 17:38
>So I have a question, why we need wal in prometheus agent mode? what does wal in agent mode can give us?
why not we just scrape metrics from exporter and directly proxy to remote tsdb?

The WAL is used as an additional on-disk buffer for remote write, regardless of whether agent mode is being used. If you disabled the WAL you'd need to buffer all data in memory and then either start dropping samples when the buffer is full or buffer infinitely and OOM the process. The no WAL implementation was what we had in the past (~6y ago). 

Closing as a duplicate, since we have an issue already to track the feature needed to solve this. What you're describing is unfortunately by design currently, until https://github.com/prometheus/prometheus/issues/8809 is implemented.

**Closed by cstyan** 2024-02-06 17:38 UTC

**Comment by ad-c2-5083ud-j** [comment] 2024-02-07 02:46
Thanks for your explanation.
