### ISSUE TITLE
Validate samples coming from remote read?

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#2601] opened 2017-04-07 18:49 UTC
Although slightly different, https://groups.google.com/forum/#!topic/prometheus-users/ajWG7y-DtCg made me note that a remote read endpoint could send us back invalid metric or label names. Should we check their validity when receiving the read response? If so, what do we do with invalid samples? Fail the query?

**Comment by brian-brazil** [comment] 2017-04-07 19:57
Dupe of #2586

**Closed by brian-brazil** 2017-04-07 19:57 UTC
Labels: area/stability, component/remote storage, kind/design
