### ISSUE TITLE
BUG : alert always in pending state

### ISSUE THREAD

**Issue by jdelvecchio** [prometheus/prometheus#5980] opened 2019-09-03 09:40 UTC
## Proposal
I'm encountering a bug with one or more alerts that stay in pending state, and never go firing.
Pretty annoying since when an alert isn't firing, the sysadmins don't get notified :')

## Bug Report
**What did you do?**
I created an alert :
```
- alert: vm_mem_usage_critical
    expr: ((vmware_vm_mem_usage_average / 100) >= on(vm_name) group_left() (vm_mem_high_threshold_critical or on(vm_name) count by(vm_name) (vmware_vm_mem_usage_average) * 0 + scalar(vm_mem_high_threshold_critical_DEFAULT)))
    for: 5m
    labels:
      severity: critical
    annotations:
      title: 'Critical : very High memory usage on {{ $labels.vm_name }}: {{ $value | printf "%.2f" }}%'
```
And it's always in "pending" state, cannot figure out why. I've spoke about it on irc and we couldn't find out why either.
I've **checked other similar issues, usually this issue is when an alert has a variable inside a label, in my case I do not have this.**

Note : this alert is just an example of one that stays in pending state, but this bug happens on other alerts too, it seems pretty random, instead of having usually ~450 firing alerts I only have ~200 and ~250 pending that always stay pending.

Here is a screenshot of the webui showing it's in pending state :
![image](https://user-images.githubusercontent.com/11552866/64162206-304b1800-ce3f-11e9-9213-fd960f8038b5.png)
The "Active since" resets after every scrape to the time of the scrape.

Here is another screenshot of the webui graph of the same element showing it value stays the same and above the threshold (95), but still doesn't go firing :
![image](https://user-images.githubusercontent.com/11552866/64162327-6092b680-ce3f-11e9-86e0-809eb5a8be44.png)

I expect the alert to be in firing state instead.
A while ago I had this issue and resolved it by restarting the prometheus process, but now I have it again and a processus restart doesn't change anything, even after I wait a few hours.

**Environment**

* System information:

Linux 3.10.0-957.27.2.el7.x86_64 x86_64

* Prometheus version:

Had the issue with 2.11.0 and 2.12.0
prometheus, version 2.11.0 (branch: HEAD, revision: 4ef66003d9855ed2b7a41e987b33828ec36db34d)
  build user:       root@0dc27cf95f36
  build date:       20190709-09:54:35
  go version:       go1.12.7

prometheus, version 2.12.0 (branch: HEAD, revision: 43acd0e2e93f9f70c49b2267efa0124f1e759e86)
  build user:       root@7a9dbdbe0cc7
  build date:       20190818-13:53:16
  go version:       go1.12.8

* Prometheus configuration file:
```yaml
global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s

  external_labels:
    environment: preproduction

rule_files:
  - /etc/prometheus/rules/*.rules

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 172.10.10.100:9093


scrape_configs:
  - job_name: prometheus
    scrape_interval: 10s
    static_configs:
    - targets:
      - localhost:9090
  - job_name: VMWare
    metrics_path: /metrics
    relabel_configs:
    - source_labels:
      - __address__
      target_label: __param_section
    - source_labels:
      - __param_target
      target_label: instance
    - replacement: localhost:9272
      target_label: __address__
    scrape_interval: 5m
    scrape_timeout: 30s
    static_configs:
    - targets:
      - vc1
      - vc2
      - vc3
      - vc4
      - vc5
      - vc6
```

**Comment by simonpasquier** [comment] 2019-09-03 14:39
`scrape_interval: 5m` => this is too high, the maximum recommended value is 2 minutes to deal with staleness.

**Comment by jdelvecchio** [comment] 2019-09-04 12:34
Thanks. I changed it to 2m and I don't get any more alerts that stay in pending state for now. Will re-open if it happens again

**Comment by jdelvecchio** [comment] 2019-10-07 15:46
Hi, 

Even with `scrape_interval` to 2m - I still get alarms that get stuck in pending state forever, please see :
![image](https://user-images.githubusercontent.com/11552866/66326949-38a8de00-e92a-11e9-9944-075e03cccb9d.png)
All 44 are stuck in 'pending' state. It also happens for some other alerts.

I still don't know why it's happening, could 2m still be too high ?

**Comment by hoffie** [comment] 2019-10-07 17:09
@jdelvecchio
I suggest checking all time series which are referenced in the affected alerts. Are they stable over time? Are they all available consistently over time? Are there maybe recording rules with very long evaluation times?
If checking this does not yield a result yet, I recommend posting to the prometheus-users list (or IRC) so that we can track this down and provide more details in this bug tracker if it turns out to be an actual bug.

**Comment by simonpasquier** [comment] 2019-10-08 09:01
@jdelvecchio please use the prometheus users mailing list which is more relevant to answer this type of question.

**Comment by aloababa** [comment] 2019-11-28 12:14
It seems that the problem is your scrape_interval being higher than your evaluation_interval.
So if your scrape takes more than 15 seconds, your alert will be evaluated and will disappear from pending alerts.
And when your scrape is done, there is no pending alert so a new one is created as pending.

Safe thing to do is to set your evaluation_interval to the same value as your scrape_interval.

**Comment by brian-brazil** [comment] 2020-05-18 14:44
We looked at this as part of the bug scrub, and this appears to be a handled support request so closing.

**Closed by brian-brazil** 2020-05-18 14:44 UTC
