### ISSUE TITLE
promtool tsdb dump in OpenMetrics format

### ISSUE THREAD

**Issue by ArthurSens** [prometheus/prometheus#8280] opened 2020-12-12 21:18 UTC
## Proposal
With the new backfilling functionality, it is now possible to create Prometheus compatible blocks from an OpenMetrics file :rocket:
We can also dump data from Prometheus with `promtool tsdb dump`, but unfortunately it is not in OpenMetrics format so we can't re-use this file to import that data into another Prometheus server. The proposal is to add support for dumping Prometheus data in OpenMetrics format with promtool.

**Use case. Why is this important?**
Where I work, a decision was made in the past that we'd have one Prometheus server for each application/exporter and it's not scaling too well. We'd like to consolidate all that data into a single Prometheus that will now scrape all our metrics endpoints. We want to shut down several Prometheus, but we'd like to keep their data in our new centralized one.

With this proposal, it will be a lot easier to dump and import data from one prometheus instance to another.

**Comment by roidelapluie** [comment] 2020-12-12 21:21
The correct way to to this is to take a snapshot of TSDB and copy it over to the other prometheus server.

**Comment by ArthurSens** [comment] 2020-12-12 21:31
> The correct way to to this is to take a snapshot of TSDB and copy it over to the other prometheus server.

yes, but copying the whole snapshot will copy the whole TSDB. With dump/import I can fine grain what I want with timestamp filters.

**Comment by roidelapluie** [comment] 2021-01-04 15:44
We have looked at this during our bug scrub and decided to close this as duplicate of #8281. Thanks!

**Closed by roidelapluie** 2021-01-04 15:44 UTC
Labels: component/promtool, priority/Pmaybe

**Comment by Davidrjx** [comment] 2021-09-17 12:40
if data dumped and restore after being updated, any solution?
