### ISSUE TITLE
Dockerfile not up to date on Dockerhub

### ISSUE THREAD

**Issue by zekth** [prometheus/prometheus#5581] opened 2019-05-20 09:41 UTC
see: https://hub.docker.com/r/prom/prometheus/dockerfile/

This fix has not been applied on dockerhub: https://github.com/prometheus/prometheus/pull/2942/files

ref: https://github.com/prometheus/prometheus/issues/2878

**Comment by simonpasquier** [comment] 2019-05-20 13:32
This is a long-standing issue... We got the Dockefile tab removed with https://github.com/docker/hub-feedback/issues/1792 but unfortunately the page itself can't be deleted.

**Comment by zekth** [comment] 2019-05-20 13:38
Ok i see. May i suggest to add an example of a docker-compose deployement here : https://prometheus.io/docs/prometheus/latest/installation/ ?

Just explaining the case. I wanted to use the default command and arguments in my deployement but just to enable the admin api in addition. Problem is i've found the ressource on dockerhub and tried to reproduce. I think it has its place in the doc.

**Comment by gouthamve** [comment] 2020-04-27 14:53
Dupe of https://github.com/prometheus/prometheus/issues/5348 as discussed in our bugscrub.

**Closed by gouthamve** 2020-04-27 14:53 UTC
