### ISSUE TITLE
offset not honored with recording rules

### ISSUE THREAD

**Issue by xbglowx** [prometheus/prometheus#1234] opened 2015-11-23 19:52 UTC
I have the following recording rules

`node_cpu_usage_user_prometheus = ((sum(node_cpu{tags=~',prometheus,',mode='user'}) - sum(node_cpu{tags=~',prometheus,',mode='user'} offset 15s)) / 150) * 100
node_cpu_usage_nice_prometheus = ((sum(node_cpu{tags=~',prometheus,',mode='nice'}) - sum(node_cpu{tags=~',prometheus,',mode='nice'} offset 15s)) / 150) * 100
node_cpu_usage_iowait_prometheus = ((sum(node_cpu{tags=~',prometheus,',mode='iowait'}) - sum(node_cpu{tags=~',prometheus,',mode='iowait'} offset 15s)) / 150) * 100
node_cpu_usage_idle_prometheus = ((sum(node_cpu{tags=~',prometheus,',mode='idle'}) - sum(node_cpu{tags=~',prometheus,',mode='idle'} offset 15s)) / 150) * 100
node_cpu_usage_softirq_prometheus = ((sum(node_cpu{tags=~',prometheus,',mode='softirq'}) - sum(node_cpu{tags=~',prometheus,',mode='softirq'} offset 15s)) / 150) * 100
node_cpu_usage_system_prometheus = ((sum(node_cpu{tags=~',prometheus,',mode='system'}) - sum(node_cpu{tags=~',prometheus,',mode='system'} offset 15s)) / 150) * 100
node_cpu_usage_irq_prometheus = ((sum(node_cpu{tags=~',prometheus,',mode='irq'}) - sum(node_cpu{tags=~',prometheus,',mode='irq'} offset 15s)) / 150) * 100
node_cpu_usage_guest_prometheus = ((sum(node_cpu{tags=~',prometheus,',mode='guest'}) - sum(node_cpu{tags=~',prometheus,',mode='quest'} offset 15s)) / 150) * 100
node_cpu_usage_steal_prometheus = ((sum(node_cpu{tags=~',prometheus,',mode='steal'}) - sum(node_cpu{tags=~',prometheus,',mode='steal'} offset 15s)) / 150) * 100`

A Prometheus reload works fine, but the status doesn't show 'offset 15s'. So the end recording rule ends up being:

`node_cpu_usage_user_prometheus = ((sum(node_cpu{mode="user",tags=~",prometheus,"}) - sum(node_cpu{mode="user",tags=~",prometheus,"})) / 150) * 100
node_cpu_usage_nice_prometheus = ((sum(node_cpu{mode="nice",tags=~",prometheus,"}) - sum(node_cpu{mode="nice",tags=~",prometheus,"})) / 150) * 100
node_cpu_usage_iowait_prometheus = ((sum(node_cpu{mode="iowait",tags=~",prometheus,"}) - sum(node_cpu{mode="iowait",tags=~",prometheus,"})) / 150) * 100
node_cpu_usage_idle_prometheus = ((sum(node_cpu{mode="idle",tags=~",prometheus,"}) - sum(node_cpu{mode="idle",tags=~",prometheus,"})) / 150) * 100
node_cpu_usage_softirq_prometheus = ((sum(node_cpu{mode="softirq",tags=~",prometheus,"}) - sum(node_cpu{mode="softirq",tags=~",prometheus,"})) / 150) * 100
node_cpu_usage_system_prometheus = ((sum(node_cpu{mode="system",tags=~",prometheus,"}) - sum(node_cpu{mode="system",tags=~",prometheus,"})) / 150) * 100
node_cpu_usage_irq_prometheus = ((sum(node_cpu{mode="irq",tags=~",prometheus,"}) - sum(node_cpu{mode="irq",tags=~",prometheus,"})) / 150) * 100
node_cpu_usage_guest_prometheus = ((sum(node_cpu{mode="guest",tags=~",prometheus,"}) - sum(node_cpu{mode="quest",tags=~",prometheus,"})) / 150) * 100
node_cpu_usage_steal_prometheus = ((sum(node_cpu{mode="steal",tags=~",prometheus,"}) - sum(node_cpu{mode="steal",tags=~",prometheus,"})) / 150) * 100`

I am running prometheus version 0.15.1

![screen shot 2015-11-23 at 11 48 28 am](https://cloud.githubusercontent.com/assets/1020898/11347921/6ee9a790-91d8-11e5-9b70-3c72b9c2372e.png)

![screen shot 2015-11-23 at 11 50 52 am](https://cloud.githubusercontent.com/assets/1020898/11347944/8a3d8746-91d8-11e5-9e52-1f40dd71232f.png)

**Comment by brian-brazil** [comment] 2015-11-23 19:56
Dupe of #1223 

You should be using the `rate()` function rather than trying to handle counters yourself.

**Closed by brian-brazil** 2015-11-23 19:56 UTC

**Comment by xbglowx** [comment] 2015-11-24 01:48
@brian-brazil thanks for the tip and the quick update.
