### ISSUE TITLE
promtool doesn't validate rule_group keys

### ISSUE THREAD

**Issue by SuperQ** [prometheus/prometheus#7283] opened 2020-05-22 10:21 UTC
**What did you do?**

Accidentally created an invalid rule group

```yaml
groups:
- name: Alerts
  rules:
  - alert: SnitchHeartBeat
    expr: vector(1)
  labels:
  - alert: TargetDown
    expr: up == 0
```

**What did you expect to see?**

That `promtool check rules` rejects rule file as invalid.

**What did you see instead? Under which circumstances?**

Valid rules file

**Environment**

* Prometheus version:

2.18.1

**Comment by roidelapluie** [comment] 2020-05-22 10:24
Dupe of #7042. There is an active PR.

**Closed by roidelapluie** 2020-05-22 10:24 UTC
Labels: component/promtool, kind/bug
