### ISSUE TITLE
Unexpected EOF with Istio mTLS and HTTP2

### ISSUE THREAD

**Issue by Shini31** [prometheus/prometheus#10213] opened 2022-01-26 13:57 UTC
**What did you do?**
I want to monitor some apps (with servicemonitor) hosted in namespaces with Istio mTLS (sidecar injection). I have added Istio TLS certificates into the Prometheus pods with a secret t(there are hosted in a namespace without sidecar injection).

**What did you expect to see?**
All the targets with Istio mTLS will be OK

**What did you see instead? Under which circumstances?**

-  All the targets with Istio mTLS are KO with `unexpected EOF` error
![prometheus_http2_eof](https://user-images.githubusercontent.com/333820/151170325-26a68a42-a378-4a27-9e39-f53befe94a5e.png)

 - If I add the ` PROMETHEUS_COMMON_DISABLE_HTTP2=1` environment variable, all targets with mTLS will recover to OK
 - If I downgrade Prometheus to v2.30.x version, all targets with mTLS will recover to OK

**Environment**
```
GKE 1.19.14
Prometheus-operator v0.53.1
Istio 1.15.1
```

* Prometheus version:
```
Version | 2.32.1
Revision | 41f1a8125e664985dd30674e5bdf6b683eff5d32
Branch | HEAD
BuildUser | root@54b6dbd48b97
BuildDate | 20211217-22:08:06
GoVersion | go1.17.5
```

* Prometheus configuration file:
```
- job_name: serviceMonitor/b3s/gateway/0
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 30s
  metrics_path: /metrics
  scheme: https
  tls_config:
    ca_file: /etc/prometheus/secrets/istio.default/root-cert.pem
    cert_file: /etc/prometheus/secrets/istio.default/cert-chain.pem
    key_file: /etc/prometheus/secrets/istio.default/key.pem
    insecure_skip_verify: true
  follow_redirects: true
  relabel_configs:
  ...
  kubernetes_sd_configs:
  - role: endpoints
    kubeconfig_file: ""
    follow_redirects: true
    namespaces:
      names:
      - b3s
```

* Logs:
```
{"caller":"scrape.go:1292","component":"scrape manager","err":"Get \"https://x.x.x.x:yyyy/metrics\": unexpected EOF","level":"debug","msg":"Scrape failed","scrape_pool":"serviceMonitor/b3s/gateway/0","target":"https://x.x.x.x:yyyy/metrics","ts":"2022-01-26T13:53:52.593Z"}

```

**Comment by roidelapluie** [comment] 2022-02-02 14:03
Could you provide a pcap file, when you have the EOF error ?

**Comment by Shini31** [comment] 2022-02-04 14:15
Here is the pcap file: http://ovh.to/8vRA7c

Don't hesitate to tell me if I should add filters.

PS: Please tell me when you got the file back so I can delete it.

**Comment by roidelapluie** [comment] 2022-02-04 15:24
I have the file. thanks.

**Comment by roidelapluie** [comment] 2022-03-02 14:41
I am looking into this, there is a lot in the file. Do you have the IP addresses that cause issue, so i can filter the pcap file? Thanks!

**Comment by Shini31** [comment] 2022-03-02 15:15
I will not have the IP because they have changed since but I can give you the destination ports:

- 8081
- 9050
- 9052
- 28070
- 28071
- 28090

**Comment by yuliyantsvetkov** [comment] 2022-03-09 15:36
I have the same issue. I have configured pod annotations of the StatefulSet for prometheus-operator to inject the certificates from the sidecar in a memory volume. 

While the cert mount works, this is what I get from the sidecar when I try to cURL the metrics endpoint:
```
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

**Comment by rodrigorfk** [comment] 2022-03-10 16:52
Hi there, I was facing what I judge to be the exact same issue discussed here, after proper configuring and injecting the Istio sidecar in the Prometheus pod and also configuring the `tls_config` at the scrapping job level, I started to get `unexpected EOF` on Prometheus side. 

In the end, it runs to be an issue on the configuration of the Kubernetes Service for the deployment/pods Prometheus is supposed to be scrapping, the issue is related to [Istio Protocol Selection](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/), my Service was not properly defining the port as HTTP and then the ALPN between Prometheus and the Service endpoint was failing.

So this is pretty much what I had and what I did to fix it:

## What I had
```
apiVersion: v1
kind: Service
metadata:
  name: some-service
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9898
    protocol: TCP
    targetPort: 9898
```

## What fixed the issue:
Adding the `appProtocol: http` to the `ports` item as following:
```
apiVersion: v1
kind: Service
metadata:
  name: some-service
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9898
    protocol: TCP
    targetPort: 9898
    appProtocol: http
```

**Comment by johgoe** [comment] 2022-04-01 11:00
I have the same issue. Is it possible to deactive http2 per scrape config (or servicemonitor in kubernetes operator)? `appProtocol: http` does not work for me. Looks like it's always a http2 connection.

**Comment by roidelapluie** [comment] 2022-04-01 11:53
hello,

the possibility to deactivate http2 per scrape config will be available in prometheus 2.35. You could give it a try now by using the `:main` docker tag (documentation: https://github.com/prometheus/prometheus/blob/main/docs/configuration/configuration.md )

**Comment by roidelapluie** [comment] 2022-04-01 11:53
The config option is
```
# Whether to enable HTTP2.
[ enable_http2: <bool> | default: true ]
```

**Comment by roidelapluie** [comment] 2022-04-22 11:11
Prometheus 2.35 is released with the enable_http2 option.

**Closed by roidelapluie** 2022-04-22 11:11 UTC
Labels: kind/bug, priority/P3, component/scraping

**Comment by mikednight** [comment] 2022-05-09 22:07
thanks, we use prometheus operator, is there a way to set this globally for all our servicemonitors? i don't see an option in the servicemonitor spec

**Comment by RafalMaleska** [comment] 2022-06-30 15:05
spend one day on this issue. this env helped: 

ROMETHEUS_COMMON_DISABLE_HTTP2=1 


thank you!

**Comment by roidelapluie** [comment] 2022-06-30 15:55
Note that now you can just use `enable_http2: false`

**Comment by etalkishere** [comment] 2023-03-30 16:58
Just wanting to shared my experience.  We have a flask/nginx application that has serving api endpoints.  Prometheus scrapes some of these endpoints, then grafana pulls Prometheus data for graphing/alerting.  

I got the same, or rather similar, EOF errors for some of my endpoints, more frequently than not.  After wasting hours  with prometheus/alertmanager configs with no success, I saw a suggestion of setting proxy_http_version to 1.1.  I did just that, and it solved my issue!  No more EOF error, and data is coming into prometheus much more consistently now, no more missing data points because of the EOF error.   So try it out.  Below is reference to that tip.  I set 'proxy_http_version 1.1;' in the server {} config of the nginx.conf file.

Just wanting to share so you won't waste too much time.  Hopefully, it solves your issue too.

https://groups.google.com/g/prometheus-users/c/2cBX3mpJiiY

**Comment by infa-ddeore** [comment] 2023-07-28 09:05
> Hi there, I was facing what I judge to be the exact same issue discussed here, after proper configuring and injecting the Istio sidecar in the Prometheus pod and also configuring the `tls_config` at the scrapping job level, I started to get `unexpected EOF` on Prometheus side.
> 
> In the end, it turns to be an issue on the configuration of the Kubernetes Service for the deployment/pods Prometheus is supposed to be scrapping, the issue is related to [Istio Protocol Selection](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/), my Service was not properly defining the port as HTTP and then the ALPN between Prometheus and the Service endpoint was failing.
> 
> So this is pretty much what I had and what I did to fix it:
> 
> ## What I had
> ```
> apiVersion: v1
> kind: Service
> metadata:
>   name: some-service
> spec:
>   type: ClusterIP
>   ports:
>   - name: web
>     port: 9898
>     protocol: TCP
>     targetPort: 9898
> ```
> 
> ## What fixed the issue:
> Adding the `appProtocol: http` to the `ports` item as following:
> 
> ```
> apiVersion: v1
> kind: Service
> metadata:
>   name: some-service
> spec:
>   type: ClusterIP
>   ports:
>   - name: web
>     port: 9898
>     protocol: TCP
>     targetPort: 9898
>     appProtocol: http
> ```

worked for me as well, thanks a lot

**Comment by smacktoid** [comment] 2023-08-24 13:47
I wanted to add to the conversation here. I was seeing these EOF errors as well. For us, it turned out that prometheus was slightly misconfigured in how it's Istio proxy was configured.

Our installation had the istio `traffic.sidecar.istio.io/excludeOutboundPorts` and `traffic.sidecar.istio.io/includeOutboundPorts` set in such a way that the scrape requests going from prometheus to the target were being routed through the service mesh.

In our particular case, port 8080 was being included. This seems to go against the recommendation in the documentation, which talks about the sidecar providing the mTLS certificates but not sending the traffic through the mesh.

Once we added port 8080 to the exclude ports list our scraping targets started to work.
