### ISSUE TITLE
Expose cardinality metrics

### ISSUE THREAD

**Issue by hagen1778** [prometheus/prometheus#6439] opened 2019-12-10 15:14 UTC
## Proposal
Current status page with `Head Cardinality` tables contains very useful information. It would be great if Prometheus could expose these values as metrics, so one could build a dashboard or define thresholds and set up alerts.

**Comment by brian-brazil** [comment] 2019-12-10 15:18
Dupe of #6317

**Closed by brian-brazil** 2019-12-10 15:18 UTC
