### ISSUE TITLE
Prometheues v2.16.0: Duplicated metrics from remote storage due to external labels

### ISSUE THREAD

**Issue by clausa20** [prometheus/prometheus#6967] opened 2020-03-11 16:14 UTC
Hello,
I have 3 Prometheus instances with a load balancer in the front. Each of these Prometheus has set external labels in their settings, for example:
```
external_labels:
    external_label_1: external_label_value
    external_label_2: external_label_value_0  (changes to 1 and 2 corresponding)
```
Also I have set a remote storage using CrateDB.

I've tried to update Prometheus version from v2.14.0 to v2.16.0 but....

When I perform a query of a metric saved in remote storage in version 2.14.0, I have a single result, for example:
`metric1{label1="value1",label2="value2"}`

but when I run the same query with version 2.16.0 I have 4 results, 3 of these results specifying the external label and 1 result without the external labels (the same as version 2.14.0):
```
metric1{label1="value1",label2="value2",external_label_1="external_label_value",external_label_2="external_label_value_0"}
metric1{label1="value1",label2="value2",external_label_1="external_label_value",external_label_2="external_label_value_1"}
metric1{label1="value1",label2="value2",external_label_1="external_label_value",external_label_2="external_label_value_2"}
metric1{label1="value1",label2="value2"}
```

For both version I see that in CrateDB metrics are saved with external labels, but for version 2.14.0 Prometheus is able to de-duplicate.

I would expect that version 2.16.0 has a single result as version 2.14.0.
Was something changed in version 0.16.0 that it cannot deduplicate metrics from external labels?

Thanks.

**Comment by csmarchbanks** [comment] 2020-03-12 14:24
You mean v2.14.0 and v2.16.0 not 0.X.0 correct?

**Comment by clausa20** [comment] 2020-03-12 14:33
@csmarchbanks yes correct. my bad, I meant v2.14.0 and v2.16.0 . I will try to update the description to correct it. Also I want to add that I tested the version v2.15.2 and it seems to have the same behaviour as v2.14.0, so I only see the duplicated metrics in version v2.16.0. Thanks.

**Comment by csmarchbanks** [comment] 2020-03-16 17:39
Hello @clausa20, I finally dug into this and I could reproduce it before https://github.com/prometheus/prometheus/pull/6971 was merged, but not afterward. Could you could verify that this has been fixed on the latest master build of Prometheus?

**Comment by clausa20** [comment] 2020-03-16 19:50
@csmarchbanks  yes I can test it.
In this release is the fix? v2.17.0-rc.1 
Or where is the build you mention? thanks.

**Comment by roidelapluie** [comment] 2020-03-16 19:52
You can test with the artefacts here: https://circleci.com/gh/prometheus/prometheus/28102#artifacts/containers/0

e.g.: https://28102-6838921-gh.circle-artifacts.com/0/build/linux-amd64/prometheus

**Comment by clausa20** [comment] 2020-03-17 16:40
Thanks @roidelapluie for giving me the place to get build.
@csmarchbanks I have tested the master build and now it is working ok, I get just 1 result as expected.
Thank you.
When do you think there will be a new prometheus version to start implementing this change?
Thanks.

**Comment by csmarchbanks** [comment] 2020-03-17 16:44
This will likely be in 2.18 (about 6 weeks from now). Since the bug was already present in 2.16 I am not sure it is worth cutting another release candidate for 2.17. Up to @roidelapluie though as he is the release shepherd.

**Comment by csmarchbanks** [comment] 2020-03-17 16:45
Fixed by #6971

**Closed by csmarchbanks** 2020-03-17 16:45 UTC
Labels: component/remote storage, kind/bug

**Comment by roidelapluie** [comment] 2020-03-17 16:47
@csmarchbanks what about keeping this open and see if we need a test for it?

**Comment by csmarchbanks** [comment] 2020-03-17 17:24
The root cause of this issue is that `remote.externalLabelQuerier` only overrode the `Select` method, not `SelectSorted`. The code path for `SelectSorted` no longer exists, and the `Select` path is already covered by tests. Do you think it is valuable to add a test with that knowledge?

**Comment by roidelapluie** [comment] 2020-03-17 18:17
Thanks for your insights. It is indeed not needed.

**Comment by roidelapluie** [comment] 2020-03-21 21:33
Since we had another bug, I decided to take this with me in the 2.17 release.
