### ISSUE TITLE
Internal plotting error for area plots within console templates

### ISSUE THREAD

**Issue by StephanErb** [prometheus/prometheus#1837] opened 2016-07-20 14:28 UTC
**What did you do?**

I tried to render the following area graph within a console template:
```
  <script>
  new PromConsole.Graph({
    node: document.querySelector("#greedy"),
    expr: "topk(5, service:mem_limit_bytes:sum)",
    min: 0,
    renderer: "area",
    yAxisFormatter: PromConsole.NumberFormatter.humanize1024,
    yHoverFormatter: PromConsole.NumberFormatter.humanize1024,
    yTitle: 'RAM',
    yUnits: 'B'
  })
  </script>
```

**What did you expect to see?**

My expression rendered as an area plot within a console template.

**What did you see instead? Under which circumstances?**

* if plotted as an area plot, the graph does not show any content.
* the same expression works great:
    - as a line plot within the console templates
    - as a line plot and even as area plot within the interactive graph viewer
* for every failed rendering attempt, the following log entry can be found within the browser console log:
``` 
rickshaw.min.js:1 Uncaught stacked series cannot have differing numbers of points: 43 vs 591; see Rickshaw.Series.fill()
```
**Environment**

* Prometheus version: 

	0.20.0

**Comment by brian-brazil** [comment] 2016-07-20 16:00
Dupe of #586. Topk/bottomk don't work well in graphs.

**Closed by brian-brazil** 2016-07-20 16:00 UTC

**Comment by StephanErb** [comment] 2016-07-20 19:35
This issue is different here. Plotting doesn't work even if strip the `topk` and just try to plot `service:mem_limit_bytes:sum` as an area plot. 

The error message indicates that we might be missing this code in console templates well https://github.com/prometheus/prometheus/pull/800/files?
