### ISSUE TITLE
grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::]:9090: connect: no route to host"; Reconnecting to {[::]:9090 <nil>}

### ISSUE THREAD

**Issue by Gitbini** [prometheus/prometheus#3149] opened 2017-09-08 03:57 UTC
**What did you do?**
Attempted to start Prometheus with ./prometheus --config.file=prometheus.yml
**What did you expect to see?**
and expected it to start normally, but received this error:
**What** I saw **instead**

grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::]:9090: connect: no route to host"; Reconnecting to {[::]:9090 <nil>}

**Environment**
CentOS Linux release 7.3.1611 (Core)
* System information:

	insert output of `uname -srm` here
Linux 3.10.0-514.26.2.el7.x86_64 x86_64

* Prometheus version:
 prometheus version=2.0.0-beta.2

* Prometheus configuration file:
```I used the deafult, just to get it working 
insert configuration here
```# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']




```

**Comment by Gitbini** [comment] 2017-09-08 03:59
If anyone has seen this and knows what could be the issue here (?), I would love to hear back from you.

**Comment by aliasmee** [comment] 2017-09-11 08:58
hi,View this issue,May be helpful to you [https://github.com/prometheus/prometheus/issues/3004](url)

**Comment by htdvisser** [comment] 2017-09-14 15:28
I created Pull Request #3174 that fixes this issue (at least, for me)

**Comment by brian-brazil** [comment] 2017-09-28 08:22
Dupe of #3004

**Closed by brian-brazil** 2017-09-28 08:22 UTC
