### ISSUE TITLE
Improve health detection of /-/healthy endpoint

### ISSUE THREAD

**Issue by jeremyeder** [prometheus/prometheus#3807] opened 2018-02-07 01:04 UTC
We're trying to find the best way to monitor prometheus itself.  We were evaluating using the /healthy and /ready endpoints.  But we have a case where prometheus was failed, yet the endpoints still reported back as healthy.

**What did you do?**
Used Prometheus 2.0, ran out of disk space.

**What did you expect to see?**
I expected to see prometheus marked unhealthy when querying the /-/healthy endpoint.

**What did you see instead? Under which circumstances?**
Prometheus responded "Prometheus is Healthy."

**Environment**
- RHEL/OpenShift

* System information:
```Linux 3.10.0-693.11.6.el7.x86_64 x86_64```

* Prometheus version:
prometheus:v2.0.0

* Logs:
```
level=error ts=2018-02-05T21:42:18.480373214Z caller=wal.go:713 component=tsdb msg="sync failed" err="flush buffer: write data/wal/000001: file already closed"
level=warn ts=2018-02-05T21:42:21.495046779Z caller=scrape.go:673 component="target manager" scrape_pool=kubernetes-service-endpoints target=https://10.131.12.9:8443/metrics msg="append failed" err="WAL log samples: log series: write data/wal/000001: file already closed"
```

**Comment by krasi-georgiev** [comment] 2018-11-09 14:09
I think `tsdb` is out of scope here so removed the local storage label.

**Comment by gertvdijk** [comment] 2020-01-09 10:14
I can confirm this is still an issue with latest stable (tested 2.15.1). Encountering a disk-full event with Prometheus is really bad from an ops situation on two more aspects imo:

- VERY spammy logs, multiple lines per second. Why keep trying for every single write over and over?
- No exit, keeps running. Process manager thinks everything is OK. Why not exit status > 0?
- Liveness / health check says OK. (That's what this issue is about.)

**Comment by brian-brazil** [comment] 2020-01-09 11:00
If your disk has filled up, you're already in a really bad place. You should aim to avoid getting into that situation, rather than trying to rearrange the deckchairs when it happen. For example on restart Prometheus will still have a full disk.

**Comment by gertvdijk** [comment] 2020-01-09 11:25
> If your disk has filled up, you're already in a really bad place. You should aim to avoid getting into that situation, rather than trying to rearrange the deckchairs when it happen. For example on restart Prometheus will still have a full disk.

Of course, I agree, shit hit the fan already. But that doesn't mean the process has to continue running and pretend everything is OK.

**Comment by krasi-georgiev** [comment] 2020-01-09 14:09
Yep , don't see how a restart improves anything. Setup some node monitoring and alerting when it reached some thresholds for CPU/RAM/HDD

**Comment by dongwangdw** [comment] 2020-01-11 07:59
I do not think prometheus in this situation should exit. 
There should be a alert when the storage hits some threshold and storage should be expanded.

**Comment by krasi-georgiev** [comment] 2020-01-13 12:26
yep and this is the logic we followed to make Prom just log errors instead of exit as AFAIC come storages can be expanded dinamicly so the whole process could be automated - an alert -> expand storage -> happy end :)

**Comment by brian-brazil** [comment] 2020-03-16 15:50
Dupe of #3650

**Closed by brian-brazil** 2020-03-16 15:50 UTC
Labels: component/api, kind/enhancement, priority/P3
