### ISSUE TITLE
prometheus CLI: Add an help-long flag to be able to list hidden flags

### ISSUE THREAD

**Issue by ahurtaud** [prometheus/prometheus#14928] opened 2024-09-18 08:51 UTC
### Proposal

Hello,
There is in my opinion very interesting customisations of prometheus through all the hidden flags implementations. 
Those hidden flags propose some human readable helpers in their definitions, but AFAIK there is no way except at looking at the code to know them.

I would like to propose something like:
`prometheus --help-long` or `prometheus --help-show-hidden` to expose to users the hidden flags definitions as part of the helper output.

Thanks
Alban

**Comment by ahurtaud** [comment] 2024-09-18 08:53
I think as of today, `prometheus --help-long` provide exactly the same output as --help

**Comment by beorn7** [comment] 2024-09-18 13:31
Yes, `--help-long` isn't changing anything, and note that it is also hidden itself.

The templating could be changed to let `--help-long` show hidden flags. That also seems to be the recommended way of showing hidden flags in Kingpin.

However, the question here is _why_ the hidden flags are hidden. If they are hidden because they aren't that interesting for most users and we mostly didn't want to clutter the help page, it would make perfect sense to show them with `--help-long`. However, it could also be that those flags are hidden because you shouldn't really use them in normal use cases. Or in other words, it's actually expected that you look at the code to understand their meaning because you would only use them as somebody looking at the code anyway (experimenting, developing, …). My suspicion is the latter is closer to the truth, but I don't know.

@jesusvazquez @codesome @bwplotka as the hidden flags are mostly about TSDB, what do you think?

**Comment by ahurtaud** [comment] 2024-09-20 10:36
From my point of view, we are using specific hidden flags that can be specific to "niche" usecases only. In my case "super large deployments".
For example we are using:
`--scrape.discovery-reload-interval=30s` to ease the kubernetes API and I created this PR https://github.com/prometheus/prometheus/pull/14919 with the hope to be able to delay compaction across multiple prometheus instances.

Unhiding these flags would make prometheus config very complex for people not searching for info. But for people seeking for something, I was thinking `help-long` to be interesting. Still open to discussions :) Thank you

**Comment by beorn7** [comment] 2024-09-25 16:47
@roidelapluie essentially confirmed my suspicion that we never want to un-hide the hidden flags. Since nobody else has chimed in, I take that as the opinion of the infallible hive mind and close this.

 @jesusvazquez @codesome @bwplotka (and anyone else) you are of course still free to follow up here if you see reasons to revise the decision.

**Closed by beorn7** 2024-09-25 16:47 UTC
