### ISSUE TITLE
fix prometheus out of bound bug

### ISSUE THREAD

**Issue by chris-fengtian-guo** [prometheus/prometheus#12182] opened 2023-03-27 09:32 UTC
### What did you do?

A16 Conclusion For the fix out of bound problem - this problem has two triggers - the experiment also illustrates the principle of prometheus -
1) When prometheus is running - the data will be stored in the /data/prome_db directory - wal is the temporary storage record file of the data collected by the tsdb head from the exporter - (the situation that triggers the bug - such as modifying the system time from 2023-03-22 To the future time 2024-03-22, the timestamp of these new indicator data will start from 2024-03-22 and be recorded in the wal or checkpoint file under wal)
2) When prometheus runs longer than 2 hours, it will write the tsdb head memory data to the permanent disk block block file - for example, the timestamp of the indicator data in the block is the time in the next 1 year - 2024-03-21 20:00: 00 Therefore - when prometheus starts - the memory database tsdb head requires that the newly added timestamp must be greater than this - otherwise, an out of bound error will be reported
-/data/prome_db/01HSHD0NXQKH1Y4V0AZ8J2V69P 2024-03-21 18:00:01 +0000 UTC 2024-03-21 20:00:00 +0000 UTC 1h59m58.514s
3) Solution - it is a tool - stop promehteus service - delete /data/prome_db/wal, /data/prome_db/ disk block block if the timestamp is newer than the current now() time, delete it - for example 01HSHD0NXQKH1Y4V0AZ8J2V69P - restart promethes

### What did you see instead? Under which circumstances?

fix out of bound

### Alertmanager configuration file

```yaml
The following scrpit to fix out of bound

import os
import re
import shutil
import subprocess
import time
import os
import subprocess
import time
import shutil
from datetime import datetime
import argparse
import re

def delete_newer_blocks(prometheus_data_path):
    # promtool 命令和数据目录
    promtool_cmd = "promtool"
    blocks_path = prometheus_data_path

    # 获取当前时间戳 (毫秒)
    current_timestamp = int(time.time() * 1000)

    # 执行 promtool 命令，获取 block 列表
    cmd = [promtool_cmd, "tsdb", "list", prometheus_data_path]
    print(f"Executing command: {' '.join(cmd)}")
    cmd_output = subprocess.check_output(cmd).decode('utf-8')

    # 解析命令输出，逐行处理
    for line in cmd_output.splitlines():
        # 跳过标题行
        if line.startswith("BLOCK") or line.startswith("====="):
            continue

        # 分割行数据
        fields = line.split()

        # 获取 block 目录、min 时间戳和 max 时间戳
        block_dir = fields[0]
        min_timestamp = int(fields[1])
        max_timestamp = int(fields[2])

        # 将时间戳转换为可读格式
        min_time_readable = datetime.fromtimestamp(min_timestamp / 1000).strftime('%Y-%m-%d %H:%M:%S')
        max_time_readable = datetime.fromtimestamp(max_timestamp / 1000).strftime('%Y-%m-%d %H:%M:%S')

        # 输出 block 目录、时间戳信息和可读时间格式
        print(f"Block directory: {block_dir}, Min time: {min_timestamp} ({min_time_readable}), Max time: {max_timestamp} ({max_time_readable})")

        # 如果 max 时间戳比当前时间新，删除 block 目录
        if max_timestamp > current_timestamp:
            block_path = os.path.join(blocks_path, block_dir)
            print(f"Removed newer block: {block_path}")
            shutil.rmtree(block_path)
        else:
            print(f"Keeping block: {block_dir}")


parser = argparse.ArgumentParser()
parser.add_argument('--storage_path', default=None, help='Prometheus database storage directory.')
args = parser.parse_args()

if args.storage_path:
    storage_path = args.storage_path
else:
    with open('/etc/default/prometheus', 'r') as f:
        contents = f.read()

    pattern = r'storage\.tsdb\.path=(\S+)'
    match = re.search(pattern, contents)
    if match:
        storage_path = match.group(1)
        print(storage_path)  # 输出 /data/prome_db
    else:
        print('未找到 storage.tsdb.path')


# 停止 prometheus 服务
print("停止 prometheus 服务")
subprocess.run(["systemctl", "stop", "prometheus"])

WAIT_TIME = 5
print(f"sleep {WAIT_TIME} seconds")
time.sleep(WAIT_TIME)

# 删除 wal 目录
print("删除 wal 目录")
wal_path = os.path.join(storage_path, "wal")
if os.path.exists(wal_path):
    shutil.rmtree(wal_path)

# 删除 chunks_head 目录
print("删除 chunks_head 目录")
chunks_head_path = os.path.join(storage_path, "chunks_head")
if os.path.exists(chunks_head_path):
    shutil.rmtree(chunks_head_path)

# 删除 lock 文件
print("删除 lock 文件")
lock_file = os.path.join(storage_path, "lock")
if os.path.isfile(lock_file):
    os.remove(lock_file)

# 删除 queries.active 文件
print("删除 queries.active 文件")
queries_active_file = os.path.join(storage_path, "queries.active")
if os.path.isfile(queries_active_file):
    os.remove(queries_active_file)

print("删除 未来时间戳的tsdb block")
delete_newer_blocks(storage_path)

#启动 prometheus 服务
print("启动 prometheus 服务")
subprocess.run(["systemctl", "start", "prometheus"])
```

**Comment by bboreham** [comment] 2023-04-23 15:13
Seems to be a duplicate of #12183

**Closed by bboreham** 2023-04-23 15:13 UTC
