### ISSUE TITLE
tls_config.server_name documentation is misleading

### ISSUE THREAD

**Issue by dmitrygusev** [prometheus/prometheus#10868] opened 2022-06-14 16:03 UTC
### What did you do?

I was expecting the `server_name` to pass hostname as an SNI extension with scrape requests, at least this is what documentation suggests https://prometheus.io/docs/prometheus/latest/configuration/configuration/#tls_config:

```
# ServerName extension to indicate the name of the server.
# https://tools.ietf.org/html/rfc4366#section-3.1
[ server_name: [<string>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#string) ]
```

### What did you expect to see?

I spent some time debugging why `server_name` isn't sent with scrape requests, e.g. I enabled logging of the `$host` variables in my Nginx and it was empty. I could see the $host value when I used SNI with curl, so I believe my Nginx config was correct.

### What did you see instead? Under which circumstances?

I checked the code just to find out that this field is only used to verify TLS connection
https://github.com/prometheus/common/blob/3763a1ded109d63be8a27824983c41413e056e1b/config/http_config.go#L778-L779:

```
// TLSConfig configures the options for TLS connections.
type TLSConfig struct {
...
	// Used to verify the hostname for the targets.
	ServerName string `yaml:"server_name,omitempty" json:"server_name,omitempty"`
```

I'd either made it clear in the documentation that the fields has nothing to do with SNI, or maybe implement the SNI support for scrapers?

### System information

Linux 4.14.273-207.502.amzn2.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.33.4 (branch: HEAD, revision: 83032011a5d3e6102624fe58241a374a7201fee8)
  build user:       root@d13bf69e7be8
  build date:       20220222-16:51:28
  go version:       go1.17.7
  platform:         linux/amd64
```

**Comment by roidelapluie** [comment] 2022-06-17 12:42
```
	// ServerName is used to verify the hostname on the returned
	// certificates unless InsecureSkipVerify is given. It is also included
	// in the client's handshake to support virtual hosting unless it is
	// an IP address.
```

It should be also SNI.

**Comment by roidelapluie** [comment] 2022-06-21 12:03
Do you have more feedback here ? Did you run a test about this or should we clarify the documentation *in the code*?

**Comment by dmitrygusev** [comment] 2022-06-21 12:29
Hi @roidelapluie -- the thing is it wasn't included in the client's handshake.

I don't have any problems with this anymore, because I've implemented a workaround already, but I had to do an extra research to understand it's not working as expected and thought I would raise this as an issue so you could clarify the behaviour in documentation for future users.

Or are you saying it should pass the `server_name` already in version 2.33.4? If so -- I couldn't get it working, I didn't have `InsecureSkipVerify`, and I also cannot find the comment you're citing in this git repo. I guess I'm confused now :)

**Comment by roidelapluie** [comment] 2022-06-21 12:41
The comment is from https://pkg.go.dev/crypto/tls , sorry :-) please note that in TLS1.3, SNI is also encrypted I think.

**Comment by DennyGDeChef** [comment] 2023-03-14 09:20
I have the same problem doing a mTLS scrape configuration with kubernetes service discovery

`curl --cacert myCAchain.pem --cert mycert.pem --key mykey.key --resolve original-sni:443:pod.namespace https://original-sni:443/metrics `

works, but putting the same in prometheus configuration
```yaml  
  - job_name: kubernetes-pods-mtls
    tls_config:
      ca_file: /etc/prometheus/certs/myCAchain.pem
      cert_file: /etc/prometheus/certs/mycert.pem
      key_file: /etc/prometheus/certs/mykey.key
      server_name: original-sni
    kubernetes_sd_configs:
    ...
```

results in:
**server returned HTTP status 400 Host does not match SNI**

**Comment by wbollock** [comment] 2024-05-21 19:44
Hello, I was worried I'd hit this issue using `server_name` for SNI so I performed a simple demo using docker-compose, nginx, Prometheus, and some self-signed certificates. I couldn't reproduce this problem: https://github.com/wbollock/prometheus_sni_test

**Comment by bboreham** [comment] 2024-09-03 11:55
Hello from the bug-scrub!  Since most of the discussion 2 years ago was inconclusive, and the most recent comment says this is not a problem, we'll close this.

**Closed by bboreham** 2024-09-03 11:55 UTC
Labels: kind/more-info-needed

**Comment by zarath** [comment] 2024-10-02 09:44
I have the same issue, trying to run a blackbox exporter as a cloud run service on google cloud. Using host routing with SNI on the load balancing works with curl, but not with the prometheus scraper. So it is still a problem, no matter what @bboreham said.
