### ISSUE TITLE
Instrumenting "time series examined" for queries and rules

### ISSUE THREAD

**Issue by matthiasr** [prometheus/prometheus#4374] opened 2018-07-12 14:26 UTC
## Proposal

As a user, I often wish to know the number of time series that were _considered_ for a query, even if they are later discarded by label matching or operators.

The number should be the straight-up sum of the number of time series matched by all time series selectors in the expression, in the time frame of the query.

I believe passing up this information is relevant to https://github.com/prometheus/prometheus/issues/3922#issuecomment-375416059 as well, but in addition I would like to see it exposed. For queries through the API, this can be returned with the query result (or the error, if the query is aborted). For alert and recording rules, I would like to have this information in a per-rule metric, broken out by the rule group and type, the alert name or the "record" string respectively (or an equivalent identifier).

**Use case. Why is this important?**

The main use case, for me, is to catch rules that accidentally do not match any time series in the first place. For example, consider the alert expression `rate(http_errors_total[1m]) > 0`.  In steady state operation, there would always _be_ some time series with the name `http_errors_total`, so the number of time series matched should never be zero.

Currently, if for some reason nothing matches, then there will be no alert even if the world is on fire. This can happen for a number of reasons – a typo in the rule (which no syntax checker can catch), the application may have changed and emit a different name, the application may have been scaled down accidentally, or the scrape configuration may be wrong (potentially in a way that does not cause scrape errors).

As a Prometheus operator, I would like to be able to formulate an alert that notifies me if there are any (unexpected) rules that do not match anything in the first place. In my experience, only a small number of alert rules would need to be excluded from this, and the labelling outlined above would allow to do that. This alert would neatly cover all the various reasons an alert or recording rule has become ineffective, without having to alert on each possible cause individually.

I don't have a direct use case for the information in ad-hoc queries, although I can see it being useful to understand why a query may be expensive.

**Alternative**

A similar effect could be achieved by pairing each rule with another rule that checks `absent(…)` on every single time series matcher. However, this is error prone (won't catch typos, how do you keep them in sync?), easy to forget, more computationally expensive (everything needs to be matched _again_), and verbose. If we instrument PromQL to collect this information anyway, it would be a great additional benefit to expose it in this way.

**Comment by brian-brazil** [comment] 2018-07-12 14:41
> in a per-rule metric, 

We explicitly don't have per-rule metrics, as they'd be too high cardinality. This is debug and performance data which we could expose it in some form in the UI. It doesn't belong on /metrics as it's not information about the performance of the Prometheus server, it sounds like a linter of some form is what you want.

**Comment by matthiasr** [comment] 2018-07-13 08:16
How would a linter know what metrics and label values are being exposed by applications?

**Comment by matthiasr** [comment] 2018-07-13 08:17
The ALERTS metric is also per-rule? I would want even less granularity than that, just one metric per rule definition (sorry, that wasn't formulated clearly)

**Comment by brian-brazil** [comment] 2018-07-13 08:35
> How would a linter know what metrics and label values are being exposed by applications?

It could run the queries against a live Prometheus, I've seen such things developed before for this purpose.

> The ALERTS metric is also per-rule?

It's per alert, but it's not on /metrics. I don't think this sort of profiling information belongs anywhere beyond the API.

**Comment by matthiasr** [comment] 2018-07-13 11:18
Ooooh sorry now I understand that I didn't formulate that cleanly. I never intended this to be on `/metrics`, for the use case outlined that's not really necessary. Just recording it as a time series or something would be fine, but I do want to formulate alert rules over this.

The linter would only catch cases where the rule is off target at the time the linter is run, but not if the ground has shifted under it.

**Comment by matthiasr** [comment] 2018-07-13 11:30
Fair point, we can work out the exact implementation of this then. The main point for me was that I would like to have this particular piece of data collected and available in the first place.

**Comment by matthiasr** [comment] 2018-07-13 11:32
It would be kind of weird to have a `prometheus_exporter` though. Maybe this is something we could build in on a separate on-demand metrics endpoint, possibly with selectable collectors/modules?

**Comment by brian-brazil** [comment] 2018-07-13 12:21
My current idea is to include these sort of stats with the existing rule/query duration stats on the Rule status page (and thus the API when that gets in), and beyond that offer per-promql node in some sane way too.

**Comment by roidelapluie** [comment] 2018-07-18 09:41
What about a «promtool explain» command that would run a query against a specific api endpoint that would give all that info?

**Comment by roidelapluie** [comment] 2018-07-18 09:42
e.g. "promtool explain 'up unless on(job,instance) my_great_metric'"

**Comment by matthiasr** [comment] 2018-07-18 09:43
That would be useful while developing / checking expressions, but since rules are being evaluated constantly anyway I'd rather have access to the statistics of that in some way.

**Comment by roidelapluie** [comment] 2018-07-18 09:44
rules are just the tip of the iceberg.

**Comment by brian-brazil** [comment] 2018-07-18 10:03
Once these stats are there I'd expect it to end up in the U (for rules)I, and in the APIs (for rules and query/query_range).

**Comment by roidelapluie** [comment] 2018-07-18 10:12
![exp](https://user-images.githubusercontent.com/291750/42875345-cf854298-8a83-11e8-8a00-2c8910836d47.png)

**Comment by brian-brazil** [comment] 2018-07-18 10:15
That's yet another feature again, which is not what we're talking about here (but I've also on the cards). With the current  browser expression UI these would be additional stats in the top right corner with the series returned and duration.

**Comment by RichiH** [comment] 2020-03-23 14:34
Currently doing a bug scrub. Any update on this?

**Comment by matthiasr** [comment] 2020-03-23 14:43
It's not really a bug not to have this, but I still think it would be a useful feature. I find an alert rule that doesn't match anything at all anymore every now and then…

**Comment by roidelapluie** [comment] 2020-04-09 22:17
> Currently doing a bug scrub. Any update on this?

https://github.com/prometheus/prometheus/pull/6890

**Comment by roidelapluie** [comment] 2020-04-09 22:24
Closing as duplicate of #6668

**Closed by roidelapluie** 2020-04-09 22:24 UTC
Labels: component/promql, kind/enhancement, priority/P3
