### ISSUE TITLE
promethes target error

### ISSUE THREAD

**Issue by withqingshao** [prometheus/prometheus#6740] opened 2020-02-02 10:51 UTC
WAL log samples: log series: write data/wal/000007: file already closed

**Comment by roidelapluie** [comment] 2020-02-02 11:03
We would like to help you but we will need more details:


**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:

insert configuration here


* Alertmanager configuration file:

insert configuration here (if relevant to the issue)



* Logs:

insert Prometheus and Alertmanager logs relevant to the issue here

**Comment by withqingshao** [comment] 2020-02-02 11:05
prometheus version 2.3.0


the target is setting to pull pushgateway target


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Julien Pivotto"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月2日(星期天) 晚上7:03
收件人:&nbsp;"prometheus/prometheus"<prometheus@noreply.github.com&gt;;
抄送:&nbsp;"张绍青"<1311204171@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [prometheus/prometheus] promethes target error (#6740)




We would like to help you but we will need more details:
 
What did you do?
 
What did you expect to see?
 
What did you see instead? Under which circumstances?
 
Environment
  
 
System information:
 
insert output of uname -srm here
 
 
 
Prometheus version:
 
insert output of prometheus --version here
 
 
 
Alertmanager version:
 
insert output of alertmanager --version here (if relevant to the issue)
 
 
 
Prometheus configuration file:
 
  
insert configuration here
  
Alertmanager configuration file:
  
insert configuration here (if relevant to the issue)
  
Logs:
  
insert Prometheus and Alertmanager logs relevant to the issue here

**Comment by roidelapluie** [comment] 2020-02-02 11:10
Prometheus 2.3.0 had several known TSDB bugs.

Could you try updating to a more recent release? It you can't at least move to 2.3.2.

**Comment by withqingshao** [comment] 2020-02-02 11:12
ok&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Julien Pivotto"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月2日(星期天) 晚上7:10
收件人:&nbsp;"prometheus/prometheus"<prometheus@noreply.github.com&gt;;
抄送:&nbsp;"张绍青"<1311204171@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [prometheus/prometheus] promethes target error (#6740)




Prometheus 2.3.0 had several known TSDB bugs.
 
Could you try updating to a more recent release? It you can't at least move to 2.3.2.

**Comment by withqingshao** [comment] 2020-02-02 11:14
which is the best version to update ?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Julien Pivotto"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月2日(星期天) 晚上7:10
收件人:&nbsp;"prometheus/prometheus"<prometheus@noreply.github.com&gt;;
抄送:&nbsp;"张绍青"<1311204171@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [prometheus/prometheus] promethes target error (#6740)




Prometheus 2.3.0 had several known TSDB bugs.
 
Could you try updating to a more recent release? It you can't at least move to 2.3.2.

**Comment by roidelapluie** [comment] 2020-02-02 11:15
The current stable release is 2.15.2 and has no important bug. As we enter into that range of questions you can ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by roidelapluie** [comment] 2020-02-02 11:21
Duplicate of https://github.com/prometheus/prometheus/issues/4303

**Comment by roidelapluie** [comment] 2020-02-02 11:23
Also: https://github.com/prometheus/prometheus/wiki/FAQ#error-file-already-closed

**Comment by roidelapluie** [comment] 2020-02-02 11:32
The current stable release is 2.15.2 and has no important known bug. As we enter into that range of questions you can ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

Duplicate of https://github.com/prometheus/prometheus/issues/4303

UPDATE: After doing more research, you are more than probably hitting this: https://github.com/prometheus/prometheus/wiki/FAQ#error-file-already-closed

**Comment by withqingshao** [comment] 2020-02-02 11:33
thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Julien Pivotto"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月2日(星期天) 晚上7:32
收件人:&nbsp;"prometheus/prometheus"<prometheus@noreply.github.com&gt;;
抄送:&nbsp;"张绍青"<1311204171@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [prometheus/prometheus] promethes target error (#6740)




The current stable release is 2.15.2 and has no important known bug. As we enter into that range of questions you can ask questions like this on the prometheus-users mailing list rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
 
Duplicate of #4303
 
UPDATE: After doing more research, you are more than probably hitting this: https://github.com/prometheus/prometheus/wiki/FAQ#error-file-already-closed

**Closed** 2020-02-03 08:35 UTC
