### ISSUE TITLE
The recovery alarm cannot display the current value.

### ISSUE THREAD

**Issue by hellobobo9** [prometheus/prometheus#3759] opened 2018-01-30 05:39 UTC
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to t
![qq 20180130132327](https://user-images.githubusercontent.com/35948528/35549945-f4b30e2e-05c2-11e8-8820-f9ee06590672.png)
![qq 20180130132348](https://user-images.githubusercontent.com/35948528/35549946-f4dd31e0-05c2-11e8-8f82-323246b651af.png)
![qq 20180130132352](https://user-images.githubusercontent.com/35948528/35549947-f5084e70-05c2-11e8-93ff-49e5acf5bd17.png)


he issue here
```

**Comment by hellobobo9** [comment] 2018-01-30 05:39
hello

**Comment by brian-brazil** [comment] 2018-02-02 10:39
Dupe of #3308

**Closed by brian-brazil** 2018-02-02 10:39 UTC
