### ISSUE TITLE
log.level is set but not picked up

### ISSUE THREAD

**Issue by reachlin** [prometheus/prometheus#2632] opened 2017-04-18 08:22 UTC
[NOTICE]: <> (If your question is around usage and not a bug in Prometheus please use: https://groups.google.com/forum/#!forum/prometheus-users)

**What did you do?**
pass in -log.level=debug, but the logs have no debug messages
```
te$ docker inspect prometheus|grep -10 Cmd
            "AttachStderr": false,
            "ExposedPorts": {
                "9090/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "-config.file=/etc/prometheus/prometheus.yml",
                "-storage.local.path=/prometheus",
                "-web.console.libraries=/usr/share/prometheus/console_libraries",
                "-web.console.templates=/usr/share/prometheus/consoles",
                "-log.level=debug"
            ],
```
**What did you expect to see?**
debug messages in log

**What did you see instead? Under which circumstances?**
```
te$ docker logs prometheus
time="2017-04-18T08:09:05Z" level=info msg="Starting prometheus (version=1.5.2, branch=master, revision=bd1182d29f462c39544f94cc822830e1c64cf55b)" source="main.go:75" 
time="2017-04-18T08:09:05Z" level=info msg="Build context (go=go1.7.5, user=root@1a01c5f68840, date=20170210-16:23:28)" source="main.go:76" 
time="2017-04-18T08:09:05Z" level=info msg="Loading configuration file /etc/prometheus/prometheus.yml" source="main.go:248" 
time="2017-04-18T08:09:05Z" level=info msg="Loading series map and head chunks..." source="storage.go:373" 
time="2017-04-18T08:09:05Z" level=info msg="0 series loaded." source="storage.go:378" 
time="2017-04-18T08:09:05Z" level=info msg="Starting target manager..." source="targetmanager.go:61" 
time="2017-04-18T08:09:05Z" level=info msg="Listening on :9090" source="web.go:259" 
time="2017-04-18T08:14:05Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:612" 
time="2017-04-18T08:14:05Z" level=info msg="Done checkpointing in-memory metrics and chunks in 15.265889ms." source="persistence.go:639" 
time="2017-04-18T08:19:05Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:612" 
time="2017-04-18T08:19:05Z" level=info msg="Done checkpointing in-memory metrics and chunks in 14.846808ms." source="persistence.go:639" 
```
**Environment**

* System information:

	run in docker

* Prometheus version: 

```
te$ docker exec -it prometheus prometheus -version
prometheus, version 1.5.2 (branch: master, revision: bd1182d29f462c39544f94cc822830e1c64cf55b)
  build user:       root@1a01c5f68840
  build date:       20170210-16:23:28
  go version:       go1.7.5
```

* Alertmanager version:

	insert output of `alertmanager -version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
n/a
```

* Logs:
```
n/a
```

**Comment by brian-brazil** [comment] 2017-04-18 08:59
Dupe of #2330

**Closed by brian-brazil** 2017-04-18 08:59 UTC
