### ISSUE TITLE
Feature request: Add a resolve threshold

### ISSUE THREAD

**Issue by P0sa** [prometheus/prometheus#6504] opened 2019-12-22 14:03 UTC
## Proposal

So it happens quite often that I have to too much noise with flapping Alerts. I know that this can be reduced by using a longer `FOR` or by using thresholds over time e.g. `mean_over_time ``, but sometimes there are Situations where it is difficult to reduce noise and still have a fast response time of the alert itself.

So my Proposal is to add an optional `resolve_expr` to the rules where an secondary expression can be defined that resolves the alert.

Example:

```yaml
  - alert: OutOfDiskSpace
    for: 10m
    expr: node_filesystem_free_bytes{mountpoint ="/"} / node_filesystem_size_bytes{mountpoint ="/"} * 100 < 10
    resolve_expr: node_filesystem_free_bytes{mountpoint ="/"} / node_filesystem_size_bytes{mountpoint ="/"} * 100 > 15
    labels:
      severity: warning
    annotations:
      summary: "Out of disk space (instance {{ $labels.instance }})"
      description: "Disk is almost full (< 10% left)\n  Space left = {{ $value }}%"

```

This Alert would only trigger if there is less than 10 % of Disk Space left and only resolve if there is more than 15% available. So If my Alert is fluctuating between 10% I don't get spammed by alerts. Assuming of course in this example, that the alerting on the 10% is important, so the Threshold can't be adapted.

**Comment by roidelapluie** [comment] 2019-12-22 14:23
Thank you for your report.

This is a duplicate of #4681 and can therefore be closed.

Alternatilively, you can do Hysteriesis like describe in the following blog post I wrote https://sysadvent.blogspot.com/2019/12/day-1-alerting-with-prometheus.html . Keep in mind however that you should get your alerts as simple as possible.

Another interesting resource regarding this is @brian-brazil 's blog post https://www.robustperception.io/running-into-burning-buildings-because-the-fire-alarm-stopped

**Closed** 2019-12-22 14:23 UTC
