### ISSUE TITLE
Another test failure on 32bit architectures

### ISSUE THREAD

**Issue by TheTincho** [prometheus/prometheus#1031] opened 2015-08-26 08:59 UTC
Hi,

I've got reports of prometheus 0.15.1 failing to build due to tests not passing on i386. armel, and armhf. In the three cases the message is the same:

```
=== RUN TestEvictAndLoadChunkDescsType0
time="2015-08-25T03:56:13Z" level=info msg="Loading series map and head chunks..." file=storage.go line=263 
time="2015-08-25T03:56:13Z" level=info msg="0 series loaded." file=storage.go line=268 
time="2015-08-25T03:56:13Z" level=info msg="Stopping local storage..." file=storage.go line=284 
time="2015-08-25T03:56:13Z" level=info msg="Stopping maintenance loop..." file=storage.go line=286 
time="2015-08-25T03:56:13Z" level=info msg="Maintenance loop stopped." file=storage.go line=858 
time="2015-08-25T03:56:13Z" level=info msg="Stopping chunk eviction..." file=storage.go line=290 
time="2015-08-25T03:56:13Z" level=info msg="Chunk eviction stopped." file=storage.go line=678 
time="2015-08-25T03:56:13Z" level=info msg="Checkpointing in-memory metrics and chunks..." file=persistence.go line=541 
time="2015-08-25T03:56:13Z" level=info msg="Done checkpointing in-memory metrics and chunks in 589.913µs." file=persistence.go line=561 
time="2015-08-25T03:56:13Z" level=info msg="Local storage stopped." file=storage.go line=302 
--- FAIL: TestEvictAndLoadChunkDescsType0 (0.21s)
	storage_test.go:1176: Expected number of chunkDescs to decrease, old number 79, current number 79.
```

Any idea of what can be causing this? Another unspecified behaviour maybe?

You can get the full logs here:
https://buildd.debian.org/status/fetch.php?pkg=prometheus&arch=armel&ver=0.15.1%2Bds-1&stamp=1440475230
https://buildd.debian.org/status/fetch.php?pkg=prometheus&arch=armhf&ver=0.15.1%2Bds-1&stamp=1440474989
https://buildd.debian.org/status/fetch.php?pkg=prometheus&arch=i386&ver=0.15.1%2Bds-1&stamp=1440474999

**Comment by beorn7** [comment] 2015-08-26 16:48
Thanks for the report. I guess I'm most qualified to investigate. As usual, very overloaded, so despite this being assigned to me, anybody feel free to jump in... :)

**Comment by swsnider** [comment] 2015-08-27 23:13
This happens on 64bit as well: #944 -- I hold a local patch that disables the test.

**Comment by TheTincho** [comment] 2015-08-28 08:22
If this is a time-dependant test, then I guess I will disable it completely for the Debian build...

**Comment by juliusv** [comment] 2015-09-14 15:38
Closing this one, as it is a dupe of https://github.com/prometheus/prometheus/issues/944.

**Closed by juliusv** 2015-09-14 15:38 UTC
