### ISSUE TITLE
Remote File SD

### ISSUE THREAD

**Issue by Fluepke** [prometheus/prometheus#7528] opened 2020-07-07 12:29 UTC
## Proposal
Hej,

analogue to the `file_sd_config`, I would like to implement a `remote_file_sd_config` option, which allows the scrape target configuration file to be stored on a remote server.

Various transport protocols (like `HTTP`, `FTP`, etc.) should be supported and derived from the URI. The file's format would be the same as for `file_sd_config`.

Shall I extend the existing `file_sd` code to handle URI that start with `http(s)://` or shall I rather implement a new `remote_file_sd` option?

## Use Cases
This allows for **simple** and **generic** integration into other software. For example, a Prometheus instance could query:
* an HTTP API of a CPE provisioning tool at regular intervals for a list of devices
* [Netbox](https://github.com/netbox-community/netbox) for a list of devices (would require another pull request on netbox once this feature is implemented for prometheus).

What are your thoughts on this? Shall I go ahead and make a proposal by creating a PR?

**Comment by roidelapluie** [comment] 2020-07-07 12:40
This has been discussed in the past.


Closing as dupe of https://github.com/prometheus/prometheus/issues/2514 https://github.com/prometheus/prometheus/issues/7371 https://github.com/prometheus/prometheus/pull/4390

You can read the resons in the mentioned threads.

**Closed by roidelapluie** 2020-07-07 12:40 UTC

**Comment by hellerve** [comment] 2020-07-08 08:04
While I appreciate that this has been discussed often before, but maybe that’s a sign that this is a feature that many people actually want and need?

In any event, I’d like to provide a little bit more reasoning why this might be a good idea. If your heart is set that there are no good reasons to consider something like this feature, feel free not to read it. (I won’t be mad if I don’t receive any replies! Promise!)

Sure, you can do many things to work around this, like `curl` and `wget`. You could also do such workarounds for other, “supported” services, though, by just writing a “small“ worker that compiles `file_sd_config`s from those services. You normally don’t want to do this, because having a service (or many tiny helpers) for configuration management on top of prometheus feels like a massive anti-pattern, and it’s the kind of undocumented received wisdom I’d like to avoid.

I don’t think “there should be one way of doing things” as an argument trumps very much, and it certainly doesn’t trump "but this means that we have to work around the tool to get what we want”. I’m all for considering the æsthetics of the interface (and I appreciate hwo keeping it small helps robustness), but if that leads to people having to do the same clumsy workaround over and over again, maybe it doesn’t capture the intent properly or fully, and it might be time to reconsider.

**Comment by roidelapluie** [comment] 2021-06-02 14:03
This is being implemented in #8839
