### ISSUE TITLE
Remote write - support dns_sd_config for load balancing

### ISSUE THREAD

**Issue by aned** [prometheus/prometheus#11206] opened 2022-08-23 23:49 UTC
Currently the [remote write](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) does not load balance if in the `url` one were to put `dns vip`, it just caches the fist address and sticks to it. 
It would be nice if there was a way to specify [dns_sd_config](https://prometheus.io/blog/2015/06/01/advanced-service-discovery/#discovery-with-dns-srv-records), similar to the way it's done in scraping jobs.

**Comment by roidelapluie** [comment] 2022-08-25 09:11
Closing as duplicate of #8402

**Closed by roidelapluie** 2022-08-25 09:11 UTC
