### ISSUE TITLE
Rule Group Restful APIs and autodiscovery

### ISSUE THREAD

**Issue by alburthoffman** [prometheus/prometheus#6175] opened 2019-10-18 06:01 UTC
## Proposal
**Use case. Why is this important?**
It is not very flexible to store rules in local config files. Each time we have to edit the rules if want to add/update/delete rules.

It would be good if prometheus can export APIs to do rule group CRUD. So we can store rules in a central place, and update different prometheus based on our configs. Auto discovery like scrape configs is also pretty cool.

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**
we added these APIs in our own customized version.

**What did you expect to see?**
An official APIs in prometheus.

**What did you see instead? Under which circumstances?**
most of installations still rely on file based and needs tools like ansible to help.

**Comment by alburthoffman** [comment] 2019-10-18 06:03
we can provide these:

- POST /config/groups
- POST /config/group/{name}
- PUT /config/groups
- PUT /config/group/{name}
- DELETE /config/groups
- DELETE /config/group/{name}
- GET /config/groups
- GET /config/group/{name}

**Comment by simonpasquier** [comment] 2019-10-18 08:54
By design, Prometheus assumes that the configuration is managed by tools like Puppet, Chef, Ansible, etc. Having 2 ways to configure rules would be confusing and hard to reconcile.

**Comment by alburthoffman** [comment] 2019-10-20 02:11
Actually not, APIs allows us to do the deployments in our own tools whenever needed. Not manually

**Comment by simonpasquier** [comment] 2019-10-23 09:20
What would happen when Prometheus restarts? What would the source of truth?

**Comment by alburthoffman** [comment] 2019-10-23 10:14
the API can persist the rule config as a local file. which will survive after restarting

**Comment by simonpasquier** [comment] 2019-10-23 13:47
It doesn't really answer my concern: there would still be 2 ways to modify the configuration which would be very confusing.
Such feature has already been proposed before in https://github.com/prometheus/prometheus/issues/1623 and dismissed by the maintainers. It is unlikely that the answer is going to be different, but feel free to raise this issue on our [developer mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) if you wish.

**Comment by brian-brazil** [comment] 2020-01-27 22:26
Dupe of #1623

**Closed by brian-brazil** 2020-01-27 22:26 UTC
