### ISSUE TITLE
promtool check rules does not take into account expression

### ISSUE THREAD

**Issue by gotjosh** [prometheus/prometheus#7301] opened 2020-05-27 14:18 UTC
**What did you do?**

Run `promtool check rules example.yaml` where `example.yaml` is:
```
groups:
  - name: example
    rules:
      - expr: |
          sum by (code, verb) (increase(apiserver_request_total{job="default/kubernetes",verb="LIST",code=~"2.."}[30d]))
        record: code_verb:apiserver_request_total:increase30d
      - expr: |
          sum by (code, verb) (increase(apiserver_request_total{job="default/kubernetes",verb="GET",code=~"2.."}[30d]))
        record: code_verb:apiserver_request_total:increase30d
```

**What did you expect to see?**

Rules are all good, with no duplicates.

**What did you see instead? Under which circumstances?**

```
Checking example.yaml
1 duplicate rules(s) found.
Metric: code_verb:apiserver_request_total:increase30d
Label(s):
Might cause inconsistency while recording expressions.
  SUCCESS: 2 rules found
````

The reason for this is that our duplicate check only takes into account metric names and added labels but not the actual expression. Is this correct? Happy to submit a fix if this is not the case.

https://github.com/prometheus/prometheus/blob/7a541bd9a73671c0233db1928106d8b839053d7a/cmd/promtool/main.go#L330-L344

**Comment by brian-brazil** [comment] 2020-05-27 14:39
Hmm, I had thought this was meant to check for the rule being identical.

**Comment by roidelapluie** [comment] 2020-05-27 15:11
I think that this is valid as long as it is a warning and it succeeds at the end.

The rule should be written as 
```
groups:
  - name: example
    rules:
      - expr: |
          sum by (code, verb) (increase(apiserver_request_total{job="default/kubernetes",verb="LIST",code=~"2.."}[30d]))
          or
          sum by (code, verb) (increase(apiserver_request_total{job="default/kubernetes",verb="GET",code=~"2.."}[30d]))
        record: code_verb:apiserver_request_total:increase30d
```

In which case it would not be able to produce identical results.

**Comment by gotjosh** [comment] 2020-05-27 15:22
> I think that this is valid as long as it is a warning and it succeeds at the end.

A warning or not, the message seems... Deceiving? Given we're saying this is a rule/alert is a duplicate when it actually isn't. The name is a duplicate but the queries are different.

**Comment by wbh1** [comment] 2022-06-08 14:04
Since v2.35.0, this is reporting failures instead of just warning.

### v2.34.0
```
Checking /tmp/default.yml
1 duplicate rule(s) found.
Metric: VeryLowDiskSpace
Label(s):
        severity: critical
Might cause inconsistency while recording expressions.
  SUCCESS: 54 rules found
```

### v2.35.0
```
Checking /tmp/default.yml
  FAILED:
lint error 1 duplicate rule(s) found.
Metric: VeryLowDiskSpace
Label(s):
        severity: critical
Might cause inconsistency while recording expressions
```

**Comment by dgl** [comment] 2022-06-09 07:59
@wbh1 sorry, yes, it was a regression, already fixed by https://github.com/prometheus/prometheus/pull/10815 -- we should probably backport that to a 2.36.1.

Note for the general issue, in most cases where rules are split along a label value you can provide a label to avoid the warning:

```yaml
groups:
  - name: example
    rules:
      - expr: |
          sum by (code, verb) (increase(apiserver_request_total{job="default/kubernetes",verb="LIST",code=~"2.."}[30d]))
         record: code_verb:apiserver_request_total:increase30d
         labels:
           verb: LIST
       - expr: |
          sum by (code, verb) (increase(apiserver_request_total{job="default/kubernetes",verb="GET",code=~"2.."}[30d]))
        record: code_verb:apiserver_request_total:increase30d
        labels:
           verb: GET
```

It might be nice for promtool to just not warn if it can work out the expression can't overlap, although PromQL semantics are such it's not guaranteed a queried label is in the returned set. However part of the reason for the `--lint` change is to make it possible for us to add more lint style warnings (on an opt-in basis) so we could do this while giving people with remote read setups (the main reason you'd find a "missing" label) a way to not get warnings.

**Comment by beorn7** [comment] 2024-04-30 11:25
Hello from the bug scrub.

We feel that the various additional flags address the issue sufficiently. If somebody wants to refine things even more, please follow up here and we'll re-open the issue.

**Closed by beorn7** 2024-04-30 11:25 UTC
Labels: kind/bug, component/promtool, priority/P3
