### ISSUE TITLE
Autocomplete on /graph interface slow with large numbers of metricnames

### ISSUE THREAD

**Issue by jacksontj** [prometheus/prometheus#3321] opened 2017-10-20 00:33 UTC
**What did you do?**
I have a cluster which returns ~150k names from `/api/v1/label/__name__/values`. This takes a decent amount of time for the browser to load, but then when you go to type it is slow to the point of unusable. For me at least (in both chrome and firefox) after I finish typing 2 characters it immediately pegs a CPU core for ~2m or so, rending the browser useless.

**What did you expect to see?**
I expect it to keep up :) A great example is from the grafana guys. They recently added ace editor support for promql (https://github.com/grafana/grafana/pull/9118) and that javascript typeahead doesn't have problems with my 150k names

**Comment by brian-brazil** [comment] 2017-10-20 07:20
Dupe of #2119

**Comment by jacksontj** [comment] 2017-11-05 23:31
This is actually not a duplicate, this is a separate issue.

The linked issue (#2119) is causing the browser to crash and requesting an addition of a limit to the API.

This issue is not showing as the browser crashing, but just that the javascript in the UI is slow. More interestingly (and as mentioned in the original issue description) the same number of metrics showing up in the response works fine performance-wise in grafana.

So, to re-iterate: this issue is client-side javascript slowness as the typeahead javascript library currently in use is horribly inefficient at handling large numbers of metrics (where there are many others-- including one example linked above) that handles it just fine.

**Comment by alkar** [comment] 2017-11-21 17:19
Experiencing the same, running v2.0.0.

**Comment by Stono** [comment] 2018-06-15 07:16
+1 to this, can we get it reopened?

**Comment by juliusv** [comment] 2018-12-29 22:42
Indeed, this is not a dupe of #2119 at all (that was about expression query results), reopening.

**Comment by brian-brazil** [comment] 2018-12-30 10:58
The discussion on #2119 is about autocomplete.

**Comment by juliusv** [comment] 2018-12-30 11:02
It was about limiting expression query results originally, but then it seems further down people started misunderstanding it and adding their thoughts about the metrics list and autocomplete. That seems like a separate issue though, despite it being similar.

**Closed** 2019-01-31 17:03 UTC
Labels: component/ui, kind/enhancement
