### ISSUE TITLE
2.3.0 significatnt memory usage increase.

### ISSUE THREAD

**Issue by tcolgate** [prometheus/prometheus#4254] opened 2018-06-12 08:15 UTC
## Bug Report
**What did you do?**
Upgraded to 2.3.0

**What did you expect to see?**
General improvements.

**What did you see instead? Under which circumstances?**
Memory usage, possibly driven by queries, has considerably increased. Upgrade at 09:27, the memory usage drops on the graph after then are from container restarts due to OOM.

container_memory_usage_bytes

![image](https://user-images.githubusercontent.com/76019/41278413-ac770e22-6e21-11e8-81ce-52eb8e123f97.png)

**Environment**

Prometheus in kubernetes 1.9

* System information:
Standard docker containers, on docker kubelet on linux.

* Prometheus version:
2.3.0
	insert output of `prometheus --version` here

**Comment by brian-brazil** [comment] 2018-06-12 08:20
Can you share your configuration, a snapshot of the benchmark dashboard, and if you've made any other changes?

**Comment by tcolgate** [comment] 2018-06-12 08:22
@brian-brazil where do I find the "benchmark dashboard", and the config for this is rather large are there any specific areas of interest?

**Comment by tcolgate** [comment] 2018-06-12 08:43
Found the dashboard

**Comment by brian-brazil** [comment] 2018-06-12 08:46
The entire config please, we don't know what might be relevant.

**Comment by tcolgate** [comment] 2018-06-12 10:20
Obfuscated by hand, hopefully didn't introduce any additional problems.
We also have a large'ish number of recording rules, due to the heritage of the tooling, these are all in individual rules groups, 1 per group. Not sure if that will have any bearing on things.
[config.yaml.txt](https://github.com/prometheus/prometheus/files/2093587/config.yaml.txt)

**Comment by brian-brazil** [comment] 2018-06-12 10:34
Summary of config: 15s interval, using 13 gce_sd_configs and I think 36 kuberentes_sd_configs.

**Comment by brian-brazil** [comment] 2018-06-12 10:36
How often is the config file being reloaded? Can you try running it without the rules to eliminate those?

**Comment by tcolgate** [comment] 2018-06-12 10:43
sounds about right.
We have a sidecar that discovers kube clusters within a gce project, we run a prom per project (this config also has some additional scrapes for non-kubernetes GKE instances. This is one of the larger instances but has been running fine on 2.2.1.
The kube scrapes can probably be simplified at this point to just the pod discovery, but I don't think the number of scrapes is the problems.

**Comment by tcolgate** [comment] 2018-06-12 10:49
config reload only occurs on recording rule publishing, (in the order of  < 1 / day).
Unfortunately it will be a while before I can spin up another 2.3 just to test.

Here's a before/after (the blue annotation shows when I reverted to 2.2.1)
https://snapshot.raintank.io/dashboard/snapshot/p9PmKT5K5D57RicIZOZQzdrAsez7vOF8

**Comment by brian-brazil** [comment] 2018-06-12 11:04
My primary suspicions would be on kuberentes_sd, as that changed a good bit. Query memory should only have gone down - which your graphs show.

**Comment by tcolgate** [comment] 2018-06-12 11:50
@fabxc I've up'd the memory request to 26GB, which I think is enough now that at least it doesn't get OOM'd (it's pretty much on a dedicated node now).
During the high memory usage spikes, I see scrap interval percentiles climb and sample ingestion drop significantly.
I got the attached capture during one of these spikes (or at least on the way to one)
[heap_inuse_break.svg.gz](https://github.com/prometheus/prometheus/files/2093835/heap_inuse_break.svg.gz)

**Comment by tcolgate** [comment] 2018-06-12 11:52
internal prom perf dashboard capture during that profile: https://snapshot.raintank.io/dashboard/snapshot/si3JoG47UshfAlbwdLg6GgCiXvFep4JQ
benchmark dashboard:
https://snapshot.raintank.io/dashboard/snapshot/tHqUYJjmoeAamZ5GtHTBrEFbL4Zu6tTS

**Comment by fabxc** [comment] 2018-06-12 11:55
Thanks for the quick response. That appears to be a 30s CPU profile, which looks fairly normal.
Are you sure you used a URL ending in `/heap` and not `/profile`?

**Comment by tcolgate** [comment] 2018-06-12 12:07
Doh
@fabxc I think I got this just as the scrape latency was increasing:
[heap_inuse_break.svg.gz](https://github.com/prometheus/prometheus/files/2093910/heap_inuse_break.svg.gz)

**Comment by fabxc** [comment] 2018-06-12 12:18
This profile does not show any service discovery at all, i.e. usage is probably very minor. The graph your first posted also indicates that usage didn't increase continuously but rather spikes a lot. The baseline seems to be a bit lower than before actually.

Can you get another profile with the `-alloc_space` flag added? Would be good if the server has been seeing those spikes already for a while.

**Comment by tcolgate** [comment] 2018-06-12 12:21
This is a alloc_space one from during the climbing memory
[allocs3.svg.gz](https://github.com/prometheus/prometheus/files/2093954/allocs3.svg.gz)

**Comment by brian-brazil** [comment] 2018-06-12 12:38
Do you have a normal heap_inuse and one during a spike?

**Comment by tcolgate** [comment] 2018-06-12 12:41
@brian-brazil I think the previous one was at the start of one. Timing is tricky as things become unresponsive. I've had to revert now as I've tested these on a prod instance (thanks to the kind patience of some devs).

**Comment by fabxc** [comment] 2018-06-12 13:17
The allocs profile only shows allocations, recording rule evaluations, and serving Prometheus's own `/metrics` endpoint. The rest is below the threshold for being displayed.

My best guess for now is thus PromQL. The CPU profile doesn't show much GC work, which indicates that generally the allocation improvements in 2.3 are working. But possibly the changed evaluation model pins to much memory for a single query at once? – I've no hard reasoning for this though.

@tcolgate any chance you can share (possibly privately) the recording rules that server is running so we can get an understanding of the queries that are running?

**Comment by brian-brazil** [comment] 2018-06-12 13:32
Could you also spin up a test server without the recording rules?

**Comment by tcolgate** [comment] 2018-06-12 13:34
@brian-brazil that's going to take me a while. I can try and find the time tomorrow

**Comment by brian-brazil** [comment] 2018-06-12 13:41
> But possibly the changed evaluation model pins to much memory for a single query at once? – I've no hard reasoning for this though.

I can only imaging that happening with very high churn in the underlying data, which the graphs don't show.

**Comment by krasi-georgiev** [comment] 2018-06-12 14:30
@tcolgate did you do any other changes apart from just upgrading the prom version?

**Comment by rajatjindal** [comment] 2018-06-13 04:01
@tcolgate , the graphs that you shared are very interesting. we are also using Prometheus and running into performance issues when we enabling remote storage. (it might be a completely different issue)

is there a place where we can import these dashboards from? will be interesting to see these metrics

**Comment by tcolgate** [comment] 2018-06-13 09:06
@rajatjindal The Prometheus Benchmark dashboard is available on grafana.net (make sure you get the 2.0 version), and the other dashboard is our internal prom dashboard, better dashboards exist on grafana.net (our is adapted from one of the earlier v1 prometheus perf dashboards)

**Comment by free** [comment] 2018-06-13 10:07
From the `-alloc_space` profile, it looks to me like more than half the memory allocations during scraping (16 of 29 GB, in `scrape.mutateSampleLabels`) and about a quarter of those during rule evaluation (14 of 55 GB, 10 GB in `promql.dropMetricName` and 4 GB in `promql.(*evaluator).aggregation`) are `labels.Builder` instances.

#4248 tries to optimize away the latter 4 GB (and I've seen it use 10x less memory for `query_range`requests for aggregated rate queries -- `sum by(foo) (rate(bar[5m]))`), but if that turns out not to be the main cause, I can think of a couple of ways of getting rid of the other, larger, allocations:
 * For `scrape.mutateSampleLabels`, barring any race conditions, reuse the labels in `scrape.scrapeCache.seriesPrev` where available, instead of creating new ones on each scrape.
 * For `promql.dropMetricName`, turn `labels.Labels` into an interface, with a base implementation (the current one) plus a wrapper around it, that dynamically filters away some labels.

Neither is a particularly difficult technical challenge and might be worth pursuing even if the root cause turns out to be totally different (which I actually doubt).

**Comment by free** [comment] 2018-06-13 10:17
Oh, and on a related note, while testing my humongous aggregated rate `query_range` requests, I'm seeing significantly more memory usage the first time I run said requests after long pauses (hours or days) than on subsequent runs. I.e. starting from a steady state `go_memstats_heap_inuse_bytes` of about 500 MB, the first spike goes to 2.3 GB, subsequent ones to only 1.1 GB.

I haven't managed to pinpoint the cause, but I imagine it's the TSDB loading everything.

**Comment by free** [comment] 2018-06-13 11:15
Just so you set your expectations right, you'll only see gains on `range_query` requests (i.e. dashboards and graphs) and not so much on recorded rules.

What it does is it tries to not materialize the resulting label set of an aggregation for as long as possible, but that's only really useful when you repeatedly aggregate samples of the same series. (It should also help when aggregating away most labels of a large number of series, but the benchmarks don't show much improvement in that case).

**Comment by free** [comment] 2018-06-13 11:42
> > For `scrape.mutateSampleLabels` barring any race conditions, reuse the labels in `scrape.scrapeCache.seriesPrev` where available, instead of creating new ones on each scrape.
>
> That should already be the case - that's the whole point of the cache.

True, sorry for jumping to conclusions. Why does it allocate almost 8 GB worth of `label.Builder` objects, though? There seem to be only ~1M time series, 8 KB per timeseries seems a lot.

**Comment by brian-brazil** [comment] 2018-06-13 11:52
> Why does it allocate almost 8 GB worth of label.Builder objects, though? There seem to be only ~1M time series, 8 KB per timeseries seems a lot.

You'd see that every time a target flapped, we drop everything on a failed scrape as part of staleness. Target churn would also affect that.

**Comment by tcolgate** [comment] 2018-06-13 11:52
@brian-brazil yes, in rules, I've mailed you our existing rules (please treat them as confidential). I tried passing them to Fabian, but I'm not convinced riot.im was doing anything I asked it to do.

**Comment by brian-brazil** [comment] 2018-06-13 12:06
There's some predict_linears on 18h, for filesystem metrics in alerts - doubt that's it. Every rule and alert has its own rule group, so there's high potential for concurrency here.

**Comment by tcolgate** [comment] 2018-06-13 12:15
@brian-brazil we use a system for devs to keep recording rules in their own repo, the current code converts existing stuff from prom1 format to prom2 and using a group per rule was the laziest/easiest option. We're moving that to a new setup that will make doing a group per-app easier, I figure that will improve locality of reference for data where groups can be run linearly). Might reduce some of the burstines, but it is probably 10 days off workable at the moment.

**Comment by tcolgate** [comment] 2018-06-13 12:17
@brian-brazil also, if it is relevant, some of the metrics there are high cardinality (the tracking_id and schema labels have cardinalities in the high 100s), and contariner churn is /relatively/ high (probably a few thousand containers a day.

**Comment by brian-brazil** [comment] 2018-06-13 12:32
> Is that a possible scenario or am I imagining things?

That's possible, but not a new thing in 2.3. It's a possible improvement but very unlikely to be what's going on here.

> or indefinitely, in a garbage collectable map of sorts

We already fixed that memory leak :)

**Comment by brian-brazil** [comment] 2018-06-13 12:34
I think at this stage we should start bisecting your config to see where the issue is.

**Comment by free** [comment] 2018-06-13 13:16
> That's possible, but not a new thing in 2.3. It's a possible improvement but very unlikely to be what's going on here.

It is highly unlikely to be the root cause, but if this cascade failure scenario is real, then it's possible it may make things worse e.g. by needlessly inflating the heap, causing Prometheus to get killed. And without it, things might otherwise stabilize after whatever causes the initial spike in heap and/or CPU usage blows over.

> We already fixed that memory leak :)

I was thinking of something along the lines of `sync.Pool`, but in the shape of a map. But apparently that beast doesn't exist in Go. An LRU/TLRU cache might do the job.

**Comment by brian-brazil** [comment] 2018-06-13 13:19
> needlessly inflating the heap,

It'd increase CPU usage due to GC, it wouldn't blow out the heap.

**Comment by tcolgate** [comment] 2018-06-14 08:59
I've set up an instance with a replica of the instance data, and the same polling configuration/rules.
The test instance is, rather predictably in these things, not seeing the spikes or crashing. The only up side of this that I can suggest is that this means it is /probably/ query related rather than recording rules.

**Comment by tcolgate** [comment] 2018-06-14 09:33
Okay, so I am seeing RSS spikes. They seem start and build during compactions (just after the head chunks swap I think). During this time, scrapes slow too, cpu also spikes. I'll leave it running for a couple of hours and post the dashboards and inuse heap dump again.

**Comment by tcolgate** [comment] 2018-06-14 11:17
What causes the head chunk GCs?

https://snapshot.raintank.io/dashboard/snapshot/UbLVei97syosvmaS19Gmzt7KSDbgLH7V

The first batch of head chunk GCs caused a large RSS spike, but it didn't occur on the next one. 
Note, there are no active queries against this instance,  The steady state memory usage is considerably lower than what we saw during running 2.3.0 with our normal active query load.
This makes me slightly more confident that it is query realted, but the RSS spike during that head GC would definitely cause issues if queries (even relatively well behaved small ones), were incoming at the time.

**Comment by brian-brazil** [comment] 2018-06-14 11:29
That's it performing compactions, see #4110. As it's RSS, that's likely the new mmaped blocks.

The GC didn't cause any noticeable memory increase.

**Comment by tcolgate** [comment] 2018-06-14 11:57
Okay, looking at the current production 2.2.1, I am seeing RSS spikes on compaction (some of which are causing very occasional OOMs). So the production run issues with 2.3.0 seem more likely related to the query load then.

**Comment by brian-brazil** [comment] 2018-06-14 12:38
Time to break out tcpdump and see what queries are hitting the main Prometheus then.

**Comment by tcolgate** [comment] 2018-06-14 13:00
This instance is scrape by our long term storage
`GET /federate?match%5B%5D=%7Bjob%3D%22prometheus%22%7D&match%5B%5D=%7B__name__%3D~%22job%3A.%2B%22%7D&match%5B%5D=%7B__name__%3D~%22kpi%3A.%2B%22%7D&match%5B%5D=%7B__name__%3D~%22sli%3A.%2B%22%7D HTTP/1.0`
I tried a single call to that and that seems to have blown our the server.

**Comment by free** [comment] 2018-06-14 13:00
@tcolgate: I am really eager to see you get to the bottom of this, but seeing how query load might be the root cause of your problems, just thought I would suggest [trickster](/Comcast/trickster) as a possible workaround (even after this issue is sorted out).

I'm not actually using it as my Prometheus instance gets relatively few queries, but it looks like it may be a good way of protecting Prometheus from taxing queries (assuming most of them come from dashboards).

**Comment by brian-brazil** [comment] 2018-06-14 13:09
How many time series is that matching?

**Comment by tcolgate** [comment] 2018-06-14 13:10
@brian-brazil  my first attempt to run our federation query against the 2.3.0 instance (which had been up for a good 4 hours), OOM'd the process. Subsequent federation calls after the restart seem to be fine. The number of TS returned from federate seems pretty stable at the moment. (4234 -> 4237 series)

**Comment by tcolgate** [comment] 2018-06-14 13:12
Top 10 by `__name__` ```
    221 job:container_cpu_seconds_per_spec_cpus:ratio_rate1m
    221 job:container_cpu_seconds:rate1m
    223 job:container_memory_usage_bytes_per_spec_memory_limit_bytes:ratio
    223 job:container_memory_usage_bytes:sum
    223 job:container_spec_cpus:sum
    223 job:container_spec_memory_limit_bytes:sum
    223 job:container_start_time_seconds:max
    224 job:container_start_time_seconds:changes5m
    250 prometheus_rule_group_interval_seconds
    250 prometheus_rule_group_last_duration_seconds
```

**Comment by tcolgate** [comment] 2018-06-14 13:14
@free I'll considering, I briefly looked at thanos too, to mitigate the need for a separate long term storage, but I think trickster + thanos + prom might be a little more complicated than I'm prepared to have to explain to anyone else.

**Comment by brian-brazil** [comment] 2018-06-14 13:37
4k is not large in this context. There's something weird there with the sampleRing.

This seems like a performance issue on our end, no need to make drastic changes to your architecture.

**Comment by tcolgate** [comment] 2018-06-14 13:41
@brian-brazil actually, rereading that heap dump, that's 6GB allocated by http.ServeHTTP, given that there are no other queries, other than the single (hanging) federate call, does that imply it has read 6GB of series data for  /federate

**Comment by brian-brazil** [comment] 2018-06-14 13:53
My best guess right now is that the TSDB is returning duplicate data points some times when it's being iterated over. This will require some deeper debugging.

**Comment by tcolgate** [comment] 2018-06-14 14:30
I've managed to trigger it again, got a allocs svg, but I don't think that is terriby useful (seems to be since the process started?)
[heap_allocs.svg.gz](https://github.com/prometheus/prometheus/files/2102715/heap_allocs.svg.gz)

There seems to be some kind of time/event element to this, but it doesn't obviously align with some other event having occurred. Basically, if I leave the thing alone for an hour or so, I can trigger the OOM by using the federate query. At some time before this, I can hammer federate mercilessly without issues (tried hitting it with hey).

I need to head off soon. Tomorrow I'll try and capture a CPU profile during a crash.

**Comment by brian-brazil** [comment] 2018-06-14 14:40
This is smelling like a TSDB issue and it doesn't align with blocks, so it's probably chunks.

**Comment by brian-brazil** [comment] 2018-06-15 10:50
I've looked through the code changes on the federation codepath between 2.3.0 and 2.2.1, there's a few changes on the path but none of them seem plausible.

**Comment by tcolgate** [comment] 2018-06-15 10:56
I've not been able to trigger a crash this morning as yet. I'll give it a try every 10 mins or so and see if I can get a trace during the crash, :crossed_fingers:

**Comment by brian-brazil** [comment] 2018-06-15 10:59
I'm currently suspecting it's #4185. If you can reproduce again, try rolling that one back.

**Comment by brian-brazil** [comment] 2018-06-15 11:31
Also if you could try the federate call without the {job="prometheus"}, to see if it's overlapping selectors that's the issue.

**Comment by tcolgate** [comment] 2018-06-15 12:05
removing the `{job="prometheus"}` doesn't seem to trigger the problem any more reliably. Not managed to crash it yet today.

**Comment by brian-brazil** [comment] 2018-06-15 12:13
I would expect the ` {job="prometheus"}` to reduce the chances of a crash, as it's a simpler code path.

**Comment by tcolgate** [comment] 2018-06-15 12:22
Any suggestions of how I can update the /federate to make it more likely to trigger your guess? I'd rather be able to reliably reproduce the problem.

**Comment by brian-brazil** [comment] 2018-06-15 12:30
Adding some duplicate matchers might do it, but it's a bit of a shot in the dark.

**Comment by tcolgate** [comment] 2018-06-15 12:39
I repeated one of the matchers a couple of times and boom, that did it. and I appear to be able to crash it on demand. Impressive in-the-dark shooting there!
[out.trace.gz](https://github.com/prometheus/prometheus/files/2106039/out.trace.gz)

**Comment by brian-brazil** [comment] 2018-06-15 12:46
Okay, I can reproduce locally now on a Prometheus scraping only itself.

**Comment by tcolgate** [comment] 2018-06-15 14:23
@brian-brazil great catch, cheers. I'll try a build from release-2.3 once you've merged

**Closed** 2018-06-18 16:34 UTC
Labels: component/local storage, kind/bug
