### ISSUE TITLE
Prometheus showing targets down when the sample_limit has reached

### ISSUE THREAD

**Issue by uvaisibrahim** [prometheus/prometheus#10484] opened 2022-03-24 15:20 UTC
**What did you do?**

Tested `sample_limit` configuration with prometheus. Once the sample limit has crossed, the endpoint has seen down in prometheus targets with a message `sample limit exceeded`

**What did you expect to see?**

The target shouldn't go un-available Instead the prometheus should scrape the metrics from the affected targets upto the sample limit. 

**What did you see instead? Under which circumstances?**

It just stopped scraping completely from the affected targets.

**Prometheus version:** 2.30.3

**Prometheus configuration file:**
```
- job_name: myjob
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  sample_limit: 2000
  follow_redirects: true
```

My assumption as per the current situation that the targets completely down when the `sample_limit` has reached is because,

- Once the `sample_limit` is configured, say it is 2000, and the target endpoint actually exposing 5000 samples for a single scrape, and as I said in my expectation above, if the prometheus continuing scraping from this affected target, there will be data ambiguity as given in the below points.
- As said the `sample_limit` has configured for 2000, first time prometheus scraps the first 2000 samples from the target. Next time when prometheus scraps, the sample may not be in the same order as in the first scrape, and hence in the second scrape, the prometheus may endup scraping the missed samples from the first scrape.(again, my assumption is that prometheus not getting the samples in a specific order always)

If this is not the logical reason for not enabling Prometheus to continue scrape samples up to `sample_limit`, please provide valuable points for the same. Or if this is a bug, is this fixed in the other later versions of prometheus?

**Comment by peterbourgon** [comment] 2022-03-25 04:29
> The target shouldn't go un-available Instead the prometheus should scrape the metrics from the affected targets upto the sample limit.

Which metrics should be scraped, and which ones ignored? It's a trick question: there is no good answer :) `sample_limit` is a way to let operators define absolute limits to protect their systems. It shouldn't be hit under normal operations.

**Comment by roidelapluie** [comment] 2022-03-25 14:25
Hello,

The reason why we drop all samples when we hit the limit is because it is a lot easier to deal with non-existing data than it is with incomplete data.

**Comment by roidelapluie** [comment] 2022-06-08 13:47
I will close this, because it works as designed as I explained. Thanks.

**Closed by roidelapluie** 2022-06-08 13:47 UTC
