### ISSUE TITLE
Return number of results in expression browser

### ISSUE THREAD

**Issue by RichiH** [prometheus/prometheus#1329] opened 2016-01-20 10:23 UTC
Along with the usual information like

````
Load time: 517ms 
Resolution: 14s
````

when running a query in `/graph`, it would be interesting to also see the number of results returned.

I was not able to find an existing Issue for this ;)

**Comment by brian-brazil** [comment] 2016-01-20 10:31
Dupe of #1284

**Closed by brian-brazil** 2016-01-20 10:31 UTC
