### ISSUE TITLE
Proposal: Alert Simulation

### ISSUE THREAD

**Issue by Nexucis** [prometheus/prometheus#8734] opened 2021-04-19 08:58 UTC
The idea would be in the Prometheus UI to have a sort of playground where you could create an alertRule and then to see when it would have been fired with which label value.

Today with the graph page, you are just able to run the PromQL query and then you have to deduce by yourself when the alertRule would have been fired specially when you have `for` condition. Same for the label value that could be used in the `annotations` of the alertRule.

I think it will be really helpful when you want to finetuned your alertRule by changing the threashold, the `for` condition, the potential context shared through the `labels` and the `annotations`.

WDYT ?

**Comment by roidelapluie** [comment] 2021-04-21 12:56
Duplicate of #1154 #1220

See also https://github.com/prometheus/prometheus/pull/4277 https://ganeshvernekar.com/gsoc-2018/alert-rule-testing-ui/

**Closed by roidelapluie** 2021-04-21 12:56 UTC

**Comment by Nexucis** [comment] 2021-04-21 13:05
ah cool, thanks !
