### ISSUE TITLE
More labels regarding docker compose for docker_sd_configs

### ISSUE THREAD

**Issue by rabbipigeon** [prometheus/prometheus#10924] opened 2022-06-28 06:59 UTC
# More Compose Meta Data Please

Some more labels would be useful for docker_sd_configs, Mostly Docker compose information  such as:

```yaml
__meta_docker_compose_project_name
__meta_docker_compose_config_hash
...
```

There are alot of use cases for such information.

**Comment by roidelapluie** [comment] 2022-09-05 11:51
If this is available to the API calls we are using now, we could expose it. Is it the case? We should in general try to avoid extra calls.

**Comment by MadVikingGod** [comment] 2022-10-27 16:06
It looks like these are already available as container labels.  

With just a default docker sd scrape config, and docker version `20.10.18+azure-2` I found meta labels called
```
_meta_docker_container_label_com_docker_compose_config_hash="7cd900f6f4df1b0cdf6a9f2865c7a4434d851e631975a5b786366d14b87d61e8"
__meta_docker_container_label_com_docker_compose_container_number="1"
__meta_docker_container_label_com_docker_compose_oneoff="False"
__meta_docker_container_label_com_docker_compose_project="hello-prometheus"
__meta_docker_container_label_com_docker_compose_project_config_files="/workspaces/hello-prometheus/docker-compose.yml"
__meta_docker_container_label_com_docker_compose_project_working_dir="/workspaces/hello-prometheus"
__meta_docker_container_label_com_docker_compose_service="apache"
__meta_docker_container_label_com_docker_compose_version="2.11.2"
```

If this is the data you are looking for, then a relabel config would be able to expose them.

Are you able to check if this data already exists from the SD?

**Comment by EmilyXinyi** [comment] 2023-12-25 03:07
Taking a look at this issue now, will follow up once I find these labels!

**Comment by nishchay-veer** [comment] 2023-12-30 11:07
Is this issue still persisting as it seems to still be open. I would like to work on it if possible

**Comment by EmilyXinyi** [comment] 2023-12-30 14:29
> Is this issue still persisting as it seems to still be open. I would like to work on it if possible

I am working on it right now and I think it is still a persisting issue

**Comment by EmilyXinyi** [comment] 2024-01-09 00:54
@MadVikingGod I just confirmed that these labels already exist in SD. I will give the relabel config a try as per your suggestion. Thank you!! 
![image](https://github.com/prometheus/prometheus/assets/52259856/62534d7a-7523-4f06-828b-6c3753b9fc0d)

**Comment by EmilyXinyi** [comment] 2024-03-24 20:17
![image](https://github.com/prometheus/prometheus/assets/52259856/a263b718-b7fd-4401-9d22-ae8ac312143f)
Hi @rabbipigeon I think I found a solution for you! So basically as @MadVikingGod suggested, you need to add a relabel_config section as a subsection under scrape_configs, for each specific job that you would like to scrape. In the screenshot I attached, I scraped for the project name and hash, but you can virtually scrape anything as long as it is already in SD, and you can rename the labels to anything as long as it doesn't start with __meta. The relabel_config also supports many other functions than simply fully replacing the labels, more details and can be found in theses documentations https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
https://github.com/prometheus/prometheus/blob/release-2.51/config/testdata/conf.good.yml

Hope this helps!

**Comment by beorn7** [comment] 2024-09-17 11:48
Hello from the bug scrub.

This sounds to us as all the required labels are actually available. We'll close this, but please follow up if there is anything missing.

**Closed by beorn7** 2024-09-17 11:48 UTC
Labels: help wanted, low hanging fruit, kind/enhancement, component/service discovery
