### ISSUE TITLE
Native histogram federation not working

### ISSUE THREAD

**Issue by kaber2** [prometheus/prometheus#12305] opened 2023-04-30 17:50 UTC
### What did you do?

I've added native histograms to some code of mine. The code is running on 40 servers, each one is running a prometheus instance which is scraped by a master server. "--enable-feature" native-histograms is enabled on all instances.

On each instance, I can see the values of the native histogram being properly ingested by prometheus. However on the master instance I can only see the values ingested locally, the entire series are missing for all servers being scraped. All other series from these servers is present.

### What did you expect to see?

Full time series from all servers being scrapped.

### What did you see instead? Under which circumstances?

Only locally ingested data present.

### System information

Linux 6.1.12-zen1+ #19 ZEN SMP PREEMPT Wed Mar 15 19:32:47 CET 2023 x86_64 x86_64 x86_64 GNU/Linux

### Prometheus version

```text
prometheus, version 2.44.0-rc.0 (branch: HEAD, revision: d70688038e5d444ab8beac53722df15d244038e4)
  build user:       root@c3e52c6dd464
  build date:       20230426-09:46:54
  go version:       go1.20.3
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
This is from the master server. As mentioned, each target node does have the data available, so I assume the problem is not on their side. 

  - job_name: 'federate'
    scrape_interval: 15s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job=~".*"}'

    static_configs:
      - targets:
        [...]
```

**Comment by kaber2** [comment] 2023-05-01 09:28
Two more observations:

- I turned on debug logging, but it showed nothing of interest, barely anything at all.
- I deleted the TSDB on all servers, including the master, and restarted prometheus as well as my own program. Did not change anything.

**Comment by beorn7** [comment] 2023-05-02 16:21
I tried to reproduce the bug with a minimal setup. But everything seems to work fine.

Can you double-checked that your master server also runs with `--enable-feature=native-histograms`?

I would also suspect that the query you use for the federate endpoint (`'{job=~".*"}'`) doesn't work. It violates the "vector selector must contain at least one non-empty matcher" thing.

**Comment by kaber2** [comment] 2023-05-02 16:38
Thanks for your response. Just double-checked:

$ ps ax|grep prometheus
2704193 ?        Ssl  284:04 /usr/bin/prometheus --storage.tsdb.retention.time 7d --config.file /etc/prometheus/prometheus.yml --storage.tsdb.path /var/lib/prometheus/metrics2/ --enable-feature native-histograms

I can also see it being enabled in the prometheus Web UI.

Not sure where to continue looking. All seems fine, the web UI on each server shows the time series being ingested, it just doesn't arrive on the master. The locally scraped one does however.

Regarding the query, that is a relict of when I installed prometheus two years ago and didn't really understand too much of how it works. I never had a reason to change it afterwards as so far things have been running smoothly.

**Comment by beorn7** [comment] 2023-05-03 13:43
I'd definitely try to remove all those extra things to see if federation works in a vanilla configuration. Maybe your relabeling creates some duplicates or something?

**Comment by beorn7** [comment] 2023-07-01 20:10
@kaber2 has any now evidence come up? I'll close this for now as I still cannot reproduce the issue. Feel free to follow up with any updates.

**Comment by kaber2** [comment] 2023-07-04 12:09
My apology for the delay. It appears the reason is the use of NativeHistogramZeroThreshold: prometheus.NativeHistogramZeroThresholdZero in my histograms. Without it, they are federated properly.

Let me dig down a bit more and verify.

**Comment by kaber2** [comment] 2023-07-04 12:25
Ok I've confirmed that this is the cause, simply removing it without any further changes makes it work properly

**Comment by beorn7** [comment] 2023-07-18 23:16
OK, I found the issue. Federation uses results coming from the PromQL engine. Native Histograms are always treated as float histograms in PromQL. So federation will expose float histograms. The parser identifies a native histogram by the presence of a populated zero bucket or a non-zero zero threshold or by the existence of integer buckets, but it doesn't check float buckets.

In your case, the federation produces a native histogram with a zero threshold of zero, nothing in the zero bucket, and only float buckets. That case is very rare in the usual instrumentation, and that's the reason why we haven't run into it.

https://github.com/prometheus/prometheus/pull/12577 adds tests and fixes the issue.

Thanks again for the precise report that helped hunting down a bug that would have affected many other use cases, too.

**Closed** 2023-07-19 14:44 UTC
Labels: kind/bug, priority/P1, component/scraping
