### ISSUE TITLE
Add `mad_over_time` function

### ISSUE THREAD

**Issue by hadjiski** [prometheus/prometheus#5514] opened 2019-04-25 16:01 UTC
## Proposal
**Use case. Why is this important?**
[MAD using median](https://en.wikipedia.org/wiki/Median_absolute_deviation)
[MAD using mean](https://en.wikipedia.org/wiki/Average_absolute_deviation)
Mean/Median absolute deviation around a central point (mean, median) is a very popular mechanism (MAD), which next to the `stddev_over_time` can be used to detect anomalies.

Now `stddev_over_time` is prone to huge outliers, since the standard deviation will increase, the bigger the ourliers are, leading to not being able to detect any anomalies if there are huge outliers.

That's why using one of the MADs would be really beneficial. The median absolute deviation around a median would resist the most huge outliers, whereas the mean absolute deviation around a mean or median would still be more resistant to huge outliers than the standard deviation, but they still will be affected.

I see two options here:
Either only one single `mad_over_time` is implemented, which implicitly calculates the median absolute deviation around a median, because it is the more robust out of the described above, which according to [MAD using median](https://en.wikipedia.org/wiki/Median_absolute_deviation) is:

> MAD is defined as the median of the absolute deviations from the data's median

```
Xm = median(X1, X2, ..., Xn)
For each X from (X1, X2, ..., Xn) -> build new set of abs(X - Xm)
MAD = median(new set of absolute deviations)

For example: Consider the data (1, 1, 2, 2, 4, 6, 999). It has a median value of 2.
The absolute deviations from 2 are (1, 1, 0, 0, 2, 4, 997)
which in turn have a median value of 1
(because the sorted absolute deviations are (0, 0, 1, 1, 2, 4, 997)).
So the MAD for this data is 1.
```

Or we introduce three MAD over time promQL functions, which calculate the:
median absolute deviation around median
mean absolute deviation around median
mean absolute deviation around mean

From the two options I think just one mad_over_time should be enough

**Comment by hadjiski** [comment] 2019-04-25 16:04
@brian-brazil @fabxc

**Comment by brian-brazil** [comment] 2019-04-25 16:18
This seems a bit niche considering the functions we already have cover this general use case, and attempting to do longitudinal anomaly detection is not likely to work out even with this function - partially because outliers (which is kinda what you're looking for) are ignored. I'd suggest doing this sort of deeper analysis in something like R.

**Comment by hadjiski** [comment] 2019-04-25 17:21
The MAD function would provide me useful threshold over historical data, then all new data points will be checked against the threshold, so 

> because outliers (which is kinda what you're looking for) are ignored

is not correct. For example:

Historical data:
`1, 1, 2, 10, 12, 12, 15, 18, 22, 23, 400, 500, 999`
Out of the above the MAD would be `8`
Now the lower threshold from the historical data would be `15 - 8 = 7`
The upper threshold would be `15 + 8 = 23`
So any new value below `7` and above `23` is considered an outlier.

**Makes more sense now?**

Nevertheless regarding 

> considering the functions we already have cover this general use case

My historical data is a range vector of maybe 100 values. How would I iterate over the 100 values in a `promql` in order to execute the calculations I need for the MAD?

**Comment by brian-brazil** [comment] 2019-04-25 17:26
The standard deviation for the "good" part of the above data is 7.8, which is pretty close and doesn't to me justify a new function.

**Comment by hadjiski** [comment] 2019-04-25 18:03
Stddev from `1, 1, 2, 10, 12, 12, 15, 18, 22, 23, 400, 500, 999`
is actually `290`

**Comment by brian-brazil** [comment] 2019-04-25 19:22
You're trying to edge trigger one way or the other, so you're going to presume some time period is "good".

**Comment by hadjiski** [comment] 2019-04-26 09:11
My time series are all seasonal per day of week, like every Friday the data behaves kind of the same, so in terms of historical data, when I watch at a dashboard for today and assuming today is a Friday, then I would take lets say last 7 weeks only the Fridays and build my range vector out of this data and on top of that the stddev or MAD in order to build my threshold for Friday. 
The moment I change the view to lets say 2 days ago, then the historical data promQL would switch to building the range vector out of all Wednesdays etc.
Now your proposal is to take only the "good" data like this?:
`stddev_over_time((<metric>[1h] < 999999 and on () day_of_week() == 5)[7w:1h])`
assuming `999999` is considered a very big outlier.

I agree this is a good way to deal with the drawback of a standard deviation, but I would need to always know what is a "good" candidate for a big outlier and this might change from time to time, whereas a MAD algorithm would do that for me out of the box and also would adapt to any change in the big outlier.
Also this MAD is so easy, that the PR can be done in a minute by someone who is familiar with Go and the internals of prometheus code (like you).

I even, that never used Go and never saw the prometheus internals before, managed to implemented in few minutes (of course probably not clean enough :))

**Comment by brian-brazil** [comment] 2019-04-26 09:59
Looking for data that far back for alerting is likely to be fragile. If you did want that using a separate exporter for that information is probably wiser rather than using `offset` etc. with Prometheus.

> managed to implemented in few minutes

Ease of implementation is not the guiding factor here. We already have around 50 functions, and every one increases cognitive load on our users. Adding a new function that is only mildly different from existing functionality in a way that only those with a good knowledge of statistics would know about is not overall good for our userbase.

**Comment by hadjiski** [comment] 2019-04-26 11:16
> Ease of implementation is not the guiding factor here. We already have around 50 functions, and every one increases cognitive load on our users. Adding a new function that is only mildly different from existing functionality in a way that only those with a good knowledge of statistics would know about is not overall good for our userbase.

Completely agree

> Looking for data that far back for alerting is likely to be fragile.

Why would be a data that far back fragile? Old data values are deterministic no matter when I ask for them. Asking today for 1 day ago should be the same like asking tomorrow for 2 days ago, right?

> rather than using offset

I am not using offset, but sub queries e.g. get metric[1h] for last some days

> If you did want that using a separate exporter for that information is probably wiser

I already have a nice query for building a threshold around a standard deviation looking some weeks back per `day_of_week()` using the sub query feature. And the metric comes from a spring boot service which is producing directly to prometheus. Why would I need an extra exporter, which is normally needed for 3rd party applications, which do not expose metrics directly to prometheus?

**Comment by hadjiski** [comment] 2019-05-21 13:13
@brian-brazil @fabxc we seem to have folks interested in this (according to the likes)

**Comment by roidelapluie** [comment] 2019-05-30 08:43
isnt quantile_over_time(0.5, x) this?

**Comment by hadjiski** [comment] 2019-05-30 09:09
@roidelapluie not quite. The quantile_over_time(0.5, x) is the median and just the first step fo the MAD algorithm.

**Comment by gouthamve** [comment] 2020-04-27 14:38
We've gone through this in our bug scrub and decided to close this as a wont-fix. We are not looking to extend the PromQL currently to support this.

**Comment by hadjiski** [comment] 2021-04-21 09:37
pls pls rethink it, 27 users seem to be awaiting it

**Comment by mnicky** [comment] 2021-05-21 07:29
For us this would be pretty useful as well :)

**Comment by hadjiski** [comment] 2021-05-23 22:40
Please reconsider (see above)

**Comment by mem** [comment] 2022-11-20 01:07
Interested in this as well...

Note that the algorithm requires computing the median twice.

The outer median is computed over the absolute differences wrt to the median of the values.

That means that you need to compute `quantile_over_time` twice.

The inner one is easy, as it's simply the median of the values. That's Xm in the original request.

The outer one is the median of the absolute difference of each value wrt to the median, it means you have to do this:

```
quantile_over_time(0.5,
    (
        abs(
            value - quantile_over_time(0.5, value[T:])
        )
    )[T:]
)
```

Can you spot what's wrong with this?

What's the time range for which the inner median is evaluated vs the outer median?

**Comment by beorn7** [comment] 2022-11-22 17:44
I think your query will work as an _instant_ query with the following modification:

```PromQL
quantile_over_time(0.5,
    (
        abs(
            value - quantile_over_time(0.5, value[T:] @ end())
        )
    )[T:]
)
```

But this only works “by accident”. What you need to do is to anchor the inner sub-query at the evaluation time of the outer sub-query. By coincidence, you can get that with `end()` or `start()` in an instant query, but if you use the same expressions in a range query, they take their actually intended value of the start and end parameter in the range query.

What we need is yet another “pseudo function”, let's say `query_time()`, that evaluates to the evaluation time of the (outer-most) query, i.e. the `time` parameter in an instant query, or the `start` plus _n_ times `step` in a range query. (In the case of an instant query, all three `start()`, `end()`, and `query_time()` will yield the same timestamp, but in a range query, they might all be different.)

I anticipated the need for something like that, and I would like to see it as an experimental feature behind a feature flag. Better naming suggestions are welcome, though. :)

**Comment by mem** [comment] 2022-11-22 21:33
@beorn7 thanks!

re: `query_time()`, for symmetry, wouldn't we want to add `query_start_time()` and `query_end_time()`?

I don't love those names. Same as `end()` doesn't convey want it does (I wasn't expecting it to be the end of the outermost range), I would guess `query_end_time()` suggests that it evaluates to the end of the outermost range, too (query = what the user typed, not what prometheus is evaluating).

Thinking out loud: what if we go for explicit? `eval_end_time()`?

**Comment by mem** [comment] 2022-11-22 21:51
Also, this issue is several years old...

Have we changed our stance on adding `mad(...)` and `mad_over_time(...)`? (mad meaning median absolute deviation, not mean absolute deviation).

The reason why MAD is interesting is because it provides ways to compute a better dispersion estimate if the distribution is not normal.

For example, there's a reasonable expectation that pings over a short time frame follow a normal distribution, but server error rates shouldn't, particularly unexpected (think 5xx, not 4xx) errors. From the observability point of view, *if* the distribution of errors were normal, you could take the average rate and set a threshold expressed as a multiple of the standard deviation. Since it's not normal, you could compute the median of the error rate to get a baseline, and then you can set a threshold for the dispersion as a multiple of MAD.

**Comment by beorn7** [comment] 2022-11-23 17:51
About naming:

I agree that `end()` and `start()` can be easily misunderstood if looked at out of context. We used the very same name as [the parameter names of a range query](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries). So from that perspective, the naming makes sense. Maybe `query_start_time()` and `query_end_time()` would be overall better as the names provide the context. However, `start()` and `end()` have already been declared stable, so changing them now would require a major version bump.

Note that `start()` and `end()` always resolve to the value of the `start` and `end` query parameter, no matter how deep you are nested in sub-queries. We do not have a pseudo function yet that would give you the start and end of a sub-query (and maybe that isn't needed, but that has been a different discussion, which we shouldn't open up here in this issue as it is already heavily overloaded). But if we had one, it might be called `eval_end_time()`. ;)

**Comment by beorn7** [comment] 2022-11-23 18:10
About adding `mad(...)` etc.:

The problem is that we already tried once to happily add a fairly advanced statistical function ([`holt_winters()`](https://prometheus.io/docs/prometheus/latest/querying/functions/#holt_winters)). The result was that many users were confused what it actually means (and it got even worse because there are different varieties of Holt Winters smoothing functions), while very few users actually found a use for it. However, since it is a stable feature, we now have to support the function at least until the next major version bump.

The immediate remedy for this would be to introduce new functions behind a feature flag and only declare them stable once they have proven their usefulness.

However, I'm afraid that's not really a solution to the fundamental problem we are facing here, which is that Prometheus is used in more and more very different scenarios, and there are thousands of functions out there that one or another user would like to see in PromQL. Having thousands of functions in core PromQL is probably not sustainable and definitely very confusing. If we add functions as an experimental feature, but then drop them again if they do not see enough usage, we would avoid the problem of adding functions that are only used by selected few, but we would still frustrate those selected few.

So the next idea is to allow some kind of custom defined function, where users can provide "libraries" of some kind that other users can load or something.

Along those lines, we had a discussion at the dev-summit on 2021-05-27 (again, quite some time ago). For reference, here are the notes (you could look them up in the [doc](https://docs.google.com/document/d/11LC3wJcVk00l8w5P3oLQ-m3Y37iom6INAMEu2ZAGIIE/edit?pli=1), but since it's so hard to deep-link into a Google doc, I repeat them here):

----------------

## RichiH: Analytics use cases

* PromQL extensions
* Batch processing
* Secondary Prometheus instance running on the same data read-only?
* RichiH: Like R and SciPython: take all the old Fortran and such functions, and allow them to be used in native PromQL with all the label matching
* Julien: Different use cases, and we should also consider vendors and others implementing PromQL. Where do we draw the line between functions we add or not?
* RichiH: Do not make it part of full PromQL to begin with - feature flag and experimental. xrate is orthogonal, but we can also just do that.
* Frederic: When I left, Red Hat was trying to import Prometheus data into other languages. Don’t know what the status is.
* Beorn: We can enable both directions
* Julien: https://github.com/thanos-community/obslytics exists
* RichiH/Chris/Frederic: Discussion on importing block data with other languages - did not have consensus now. Concerns around TSDB becoming an API. (See recording)

### CONSENSUS:

We want to explore supporting analytics use cases within PromQL behind a feature flag

We are open to wrapping other languages, e.g. R, Fortran, SciPython, given an accepted design doc

-----

So as so often, someone has to take some time to tackle the issue and describe their more or less elaborate thoughts in a design doc to continue the discussion. But nobody has done so so far.

Personally, I have entertained the thought of embedding some kind of scripting engine so you could implement PromQL function on the fly in something like Python, R, Lua, … (see last item of the consensus above). But getting the details of an embedded scripting engine right will be hard.

Still, while waiting for someone to pick up that ball, we cannot simply add thousands of statistical functions to PromQL directly. But maybe the point could be made that `mad(...)` is generally useful enough to do so. But note that the bar for that is quite high. Maybe a good agenda item for the dev summit.

**Comment by beorn7** [comment] 2022-11-24 17:15
I have added a dev summit agenda item. (Next dev summit is 2023-01-26.)

**Comment by valyala** [comment] 2023-02-01 21:28
FYI, VictoriaMetrics supports [mad()](https://docs.victoriametrics.com/MetricsQL.html#mad) and [outliers_mad()](https://docs.victoriametrics.com/MetricsQL.html#outliers_mad) functions. We are going to add `mad_over_time()` function in the near future. It would be great to have these functions in Prometheus as well.

**Comment by beorn7** [comment] 2023-10-31 17:19
The PR #12851 is a PoC for embedding a scripting engine. Triggered by that, the dev-summit discussed the topic once more.

The broad outcome is that we won't go down the "embedded scripting engine" road for now, but it was pretty clear that adding more functions behind a feature flag is fine (something like `enable-feature=promql-extensions`, i.e. not a separate flag for each function). So whoever feels like it, a PR to implement a mad aggregator and/or a mad_over_time function will be welcome. Please include some reasoning about what varieties of MAD to implement.

**Closed** 2023-12-08 11:53 UTC
