### ISSUE TITLE
Containerized scraping

### ISSUE THREAD

**Issue by RoyGershon100** [prometheus/prometheus#13926] opened 2024-04-13 08:35 UTC
### Proposal

Hello there!

I would like to request you to create a multi-container scraping option in the build-in Prometheus.

Our team uses a partial solution at the moment- we use kubernetes ports with the port name="metrics" as the indicator and than filter the ports in the relabeling config. 

but if it will be build-in it will be alot cleaner and will be easier to our clients.

Example usage:
We use fluentbit to log messages so we have a container of fluentbit on each pod of our application.
We want to monitor the container of fluentbit as well so it is not very convenient.

Suggestion: maybe you can create an annotation that we will add to each container and it will mark the container as scrapable

**Comment by machine424** [comment] 2024-04-14 20:11
You may want to take a look at https://github.com/prometheus/prometheus/issues/3756 (review the proposed solutions, especially the one involving [prometheus-operator](https://github.com/prometheus-operator/prometheus-operator))  https://github.com/prometheus/prometheus/issues/3756. Even though the issue is closed, the discussion is still ongoing.
(we may want to re-open it (wdyt @beorn7?))

This topic would also be discussed during the next dev summit: https://docs.google.com/document/d/11LC3wJcVk00l8w5P3oLQ-m3Y37iom6INAMEu2ZAGIIE/edit?usp=sharing

I’ll close this issue to avoid fragmenting the information.

**Closed by machine424** 2024-04-14 20:11 UTC
