### ISSUE TITLE
Setting limits for maximum label value length

### ISSUE THREAD

**Issue by hartfordfive** [prometheus/prometheus#8198] opened 2020-11-19 01:33 UTC
## Proposal
Ability to set limit in terms of maximum label value length.

I've recently come across an issue in Prometheus which was causing the relevant instances to sharply increase in memory usage, which I initially thought was due to large queries.  After some deeper investigation, it turns out this was caused by an endpoint being scraped which was returning very large values for one of the label values.  Long story short, the issue was caused because of a consul telemetry metric (consul.health.service.not-found) being directly exposed by an agent via its metrics endpoint.  The label in question, `service`, had values in some cases (from what I've found so far) that reached 400KB in size.   

I was quite disappointed when I noticed there was a [issue created to propose adding a feature](https://github.com/prometheus/prometheus/issues/1235) that would allow to safe-guard against this but was declined due to the fact there may be "some" valid use case out there that would justify a long label value.  In my opinion, just because there "may" be some valid use cases, it shouldn't mean there is no reason to add in a mechanism to allow users to protect instances against issues such as this one.  At this point, I suspect this is potentially an issue caused due to some user which is querying a service which doesn't exist (to be confirmed) although meanwhile I have no way of protecting against high mem usage (or OOM killing) this causes other than adding a relabeling rule to drop that metric. 

Could this not be considered a use case that validates the value of having the ability to set length limits to label values?

**Comment by vsliouniaev** [comment] 2021-02-26 15:55
+1 This is a good idea. Ran into a badly behaved exporter that proved to be difficult to track down because it was only intermittently exhibiting this behavior.

**Comment by Harkishen-Singh** [comment] 2021-04-13 03:15
Should we implement this safety check? 
We can add a parameter in scrape configs that takes care while we scrape the labelsets and report error on violation.

WDYT @beorn7 @matttproud

**Comment by Harkishen-Singh** [comment] 2021-04-13 05:36
Ah, this seems like a duplicate of #8291.

**Comment by beorn7** [comment] 2021-04-13 12:49
Yes, I think this is very clearly a duplicate of #8291. Let's close this one.

And BTW, Matt T. Proud has been an alumnus of the project for quite some time. It's probably very confusing for him if he gets @-mentioned.

**Closed by beorn7** 2021-04-13 12:49 UTC
Labels: component/scraping, kind/enhancement, priority/Pmaybe

**Comment by Harkishen-Singh** [comment] 2021-04-13 12:54
Ahh, my keyboard's autocorrection. I aimed to tag Julien but it ended up with Matt proud. Sorry for that.
