### ISSUE TITLE
Scrape errors are not logged

### ISSUE THREAD

**Issue by AlekSi** [prometheus/prometheus#2903] opened 2017-07-05 05:40 UTC
**What did you do?**
I run Prometheus with debug level logging. I stopped some exporter.

**What did you expect to see?**
Scrape error in the log.

**What did you see instead? Under which circumstances?**
Nothing about scrape error in the log. It's still present in `/target` page, but that's only current status, I would like to be able to find it in logs with timestamps.

prometheus-users thread: https://groups.google.com/d/topic/prometheus-users/Ut5gqYqGTgg/discussion

**Comment by brian-brazil** [comment] 2017-07-07 11:07
Dupe of #2820

**Closed by brian-brazil** 2017-07-07 11:07 UTC
