### ISSUE TITLE
When computing, how to handle null values.

### ISSUE THREAD

**Issue by laimeng-git** [prometheus/prometheus#15543] opened 2024-12-06 08:33 UTC
### Proposal

I have two metrics, A and B. I want the result of A + B to be as follows: for time points where A does not exist, the result should be the value of B at that time point; for time points where B does not exist, the result should be the value of A at that time point; and for time points where both A and B exist, the result should be A + B. How can I write this in PromQL? Currently, I can use (A + B) or A or B , but are there other ways to write it that are more performant and easier to read? If not, I would like to add an operator that specifies how to handle null values, such as A + null_as(0) B , which would be clearer, more readable, and potentially more performant.

**Comment by vpranckaitis** [comment] 2024-12-06 12:33
There's a similar discussion in this issue: https://github.com/prometheus/prometheus/issues/13625

**Comment by beorn7** [comment] 2024-12-10 14:47
Yeah, this is a duplicate of #13625.

**Closed by beorn7** 2024-12-10 14:47 UTC
