### ISSUE TITLE
Please sign your releases

### ISSUE THREAD

**Issue by udf2457** [prometheus/prometheus#13964] opened 2024-04-20 20:01 UTC
### Proposal

It is easier than ever to do in 2024 ! You can even do it fully-automated via Github Actions, Github OIDC and [Sigstore "keyless" signing](https://docs.sigstore.dev/signing/overview/).

**Comment by udf2457** [comment] 2024-04-23 12:21
Useful references:
https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/generic/README.md#provenance-for-goreleaser
https://goreleaser.com/blog/slsa-generation-for-your-artifacts/#slsa-github-generator

**Comment by machine424** [comment] 2024-04-23 17:48
Thanks but unfortunately, it's not something we can provide/guarantee given the current [build process](https://prometheus.io/docs/operating/security/#build-process)
I'll close this as a duplicate of the meta issue https://github.com/prometheus/prometheus/issues/11462
You can add your ideas there if you want.

**Closed by machine424** 2024-04-23 17:48 UTC
