### ISSUE TITLE
ErrInvalidSample is returned on duplicate labels even when the value is also duplicated

### ISSUE THREAD

**Issue by miltieIV2** [prometheus/prometheus#6853] opened 2020-02-20 23:10 UTC
This is clearly a bug in DC/OS / Mesos, but it caused a regression when ignoring the duplicate label (as long as the value is also duplicated) is the correct thing to do.

**What did you do?**
Upgraded from Prometheus v2.14.0 to v2.16.0.

**What did you expect to see?**
Successful parsing of DC/OS metrics on <IP>:61091/metrics.

**What did you see instead? Under which circumstances?**
Prometheus now returns ErrInvalidSample 'label name "container_id" is not unique', marks the target as down and fails to record metrics.

**Environment**
DC/OS OSS 1.11.6

* System information:
Linux 4.19.95-coreos x86_64

* Prometheus version:
Before upgrade (working):
prometheus, version 2.14.0 (branch: HEAD, revision: edeb7a44cbf745f1d8be4ea6f215e79e651bfe19)
  build user:       root@df2327081015
  build date:       20191111-14:27:12
  go version:       go1.13.4

After upgrade (duplicate label errors):
prometheus, version 2.16.0 (branch: HEAD, revision: b90be6f32a33c03163d700e1452b54454ddce0ec)
  build user:       root@7ea0ae865f12
  build date:       20200213-23:50:02
  go version:       go1.13.8

* Alertmanager version:
N/A

* Prometheus configuration file:
```
...
- job_name: master-metrics
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  dns_sd_configs:
  - names:
    - master.mesos
    refresh_interval: 30s
    type: A
    port: 61091
...
```

* Alertmanager configuration file:
N/A

* Logs:
```
level=warn ts=2020-02-20T22:52:46.911Z caller=scrape.go:972 component="scrape manager" scrape_pool=agent-metrics target=http://10.30.32.205:61091/metrics msg="append failed" err="label name \"container_id\" is not unique: invalid sample"
```

* Metric
The container_id label is duplicated, but so is the value (violent agreement).
```
# HELP net_rx_packets DC/OS Metrics Datapoint
# TYPE net_rx_packets gauge
net_rx_packets{cluster_id="33bced63-a344-4664-acac-c8f043f91da6",container_id="256aaa06-38d2-4164-b7ec-8619b628731f",container_id="256aaa06-38d2-4164-b7ec-8619b628731f",dcos_package_is_framework="false",dcos_package_name="cadvisor",dcos_package_version="0.3.0-0.27.2",dcos_service_name="cadvisor",executor_id="cadvisor.1f72bcf3-21e2-11ea-b36c-82d64e6d50ed",executor_id="cadvisor.1f72bcf3-21e2-11ea-b36c-82d64e6d50ed",executor_name="Command Executor (Task: cadvisor.1f72bcf3-21e2-11ea-b36c-82d64e6d50ed) (Command: sh -c '/usr/bin/cad...')",framework_id="0a9b8664-f7f6-41a4-93b1-01493ff62a49-0000",framework_id="0a9b8664-f7f6-41a4-93b1-01493ff62a49-0000",framework_name="marathon",framework_principal="dcos_marathon",framework_role="slave_public",hostname="10.30.35.218",mesos_id="1d24d8d1-52b7-4694-812c-d20a953180f9-S17",source="cadvisor.1f72bcf3-21e2-11ea-b36c-82d64e6d50ed",task_id="cadvisor.1f72bcf3-21e2-11ea-b36c-82d64e6d50ed",task_name="cadvisor"} 0
```

* Marathon JIRA bug:
https://jira.d2iq.com/browse/MARATHON-2381

**Comment by roidelapluie** [comment] 2020-02-20 23:41
Thank you for your report.

First of all, I would like to inform you that your historical data *might* be affected by #6655 . To be confirmed by our TSDB experts. This has not happened to you because you skipped version 2.15.x.

Second, I think that we should not accept duplicate labels even if they have the same value. That could lead to edge cases where a broken implementation would export:

```
t=1 service_status{status="running",status="running"}
t=2 service_status{status="running",status="stopped"}
t=3 service_status{status="running",status="running"}
```

That would mean that we would accept that target at t=1 and t=3, but not t=3. That would be hard to diagnose.

Third, our documentation says that:
https://prometheus.io/docs/concepts/data_model/

> Changing any label value, including adding or removing a label, will create a new time series.

That would imply that `service_status{status="running",status="running"}` is not equivalent to `service_status{status="running"}` and that changing that just for the sake of scraping it would be somehow strange.

Fourth, there is *still a bug* in prometheus that would let you workaround that:

```
    metric_relabel_configs:
        - source_labels: ['container_id']
          target_label: container_id
```

But you should not rely on that as we could break that in the future and your historical data might still be hit by #6655.

Instead, I would strongly suggest that you fix your DC/OS metrics.

**Comment by roidelapluie** [comment] 2020-02-21 10:43
https://jira.d2iq.com/browse/DCOS_OSS-5930

**Comment by roidelapluie** [comment] 2020-02-22 11:45
Update-

We take this issue very seriously. We hope to get in touch with DCOS to know if that bug has been fixed in the recent versions of DCOS and if a reasonable workaround can be applied.

On the Prometheus side, we should move forward on working on the "repair" of #6655 if that gets confirmed. We will also discuss the behaviour of scraping duplicate label values based on this.

For now, we are waiting for DCOS feedback on their jira, or here.

**Comment by roidelapluie** [comment] 2020-02-22 11:47
We will also clarify if that impacts mesos or only DCOS.

**Comment by roidelapluie** [comment] 2020-02-22 22:24
So, it looks like the latest release of DCOS is not impacted, at least:

![version](https://user-images.githubusercontent.com/291750/75100154-7dc46880-55ca-11ea-843a-7e5150559ba1.png)

I can successfully scrape metrics.

**Comment by roidelapluie** [comment] 2020-02-25 20:41
I will re-assess the priority if we get news from DCOS. My attempt to install 1.11 with minidcos did not succeed.

**Comment by roidelapluie** [comment] 2020-03-27 23:28
Somehow we still don't hear anything from other DCOS users/developers. Do you have other news from the community @miltieIV2 ?

**Comment by chancez** [comment] 2020-03-30 16:17
I seem to be hitting this error `label name "type" is not unique: invalid sample` after upgrading Prometheus from 2.14 to 2.16.0 for a custom metrics exporter. I've looked at the metrics but I am not seeing any labels nor metrics being duplicated. As far as I can tell the metrics look sensible.

Example of our metrics: [metrics.txt](https://github.com/prometheus/prometheus/files/4404024/metrics-modified.txt)

Example of the Prometheus UI error:
<img width="1597" alt="Screen Shot 2020-03-30 at 9 15 58 AM" src="https://user-images.githubusercontent.com/1400401/77936087-3be0af00-7267-11ea-884f-0ccb0823c61b.png">

**Comment by chancez** [comment] 2020-03-30 16:29
It also seems to have been introduces in 2.16.0, as 2.15.x doesn't have this same error.

**Comment by chancez** [comment] 2020-03-30 16:31
Seems like https://github.com/prometheus/prometheus/pull/6664 would be the change that introduced it.

**Comment by roidelapluie** [comment] 2020-03-30 16:33
pll_locked{slot="4",**type="qgsx2"**,dac_index="1",**type="dac"**,backplane_serial="52"} 1.000000

This is invalid.

**Comment by roidelapluie** [comment] 2020-03-30 16:34
The reported issue is about labels with the same value, in this case it is a label with different values, which is something which can create deeper issues in prometheus tsdb.

**Comment by miltieIV2** [comment] 2020-03-30 19:07
No other news from my side and nothing new on DCOS_OSS-5930.

The DC/OS folks have a fairly active presence on Slack: https://dcos.io/community/, so might be able to raise someone there.

BTW, I tried the relabel hack with container_id, then noticed that executor_id and framework_id have the same problem:
```blkio_cfq_io_serviced_total{
	blkio_device="total",
	cluster_id="0208000d-248e-40e3-9dd0-96151493b6c2",
	container_id="65d6832b-172e-41fd-9202-f5621fa94d92",
	container_id="65d6832b-172e-41fd-9202-f5621fa94d92",
	dcos_space="/timeline-kafka",
	executor_id="kafka__25db8cd2-63f7-419f-8071-683e0228379a",
	executor_id="kafka__25db8cd2-63f7-419f-8071-683e0228379a",
	executor_name="kafka",
	framework_id="ce111488-234d-4880-aa8c-ac45c54a66f1-0000",
	framework_id="ce111488-234d-4880-aa8c-ac45c54a66f1-0000",
	framework_name="timeline-kafka",
	framework_principal="timeline-kafka-principal",
	framework_role="timeline-kafka-role",
	hostname="10.10.34.98",
	mesos_id="ce111488-234d-4880-aa8c-ac45c54a66f1-S37",
	source="",
	task_id="",
	task_name=""} 0
```

**Comment by roidelapluie** [comment] 2020-03-30 19:16
You are right.

A better workaround:
```
    metric_relabel_configs:
      - regex: '(.*)'
        action: labelmap
```

**Comment by roidelapluie** [comment] 2020-04-06 17:30
@miltieIV2 can you confirm that the workaround works?

**Comment by roidelapluie** [comment] 2020-05-25 21:38
I could not reproduce this issue in my DC/OS setup, and upstream is not reacting neither: https://jira.d2iq.com/browse/DCOS_OSS-5930

I will close it for now. There is a workaround documented above even if I would *highly* recommend anyone to fix their metrics instead of using the workaround.

Thanks again for your report.

**Closed by roidelapluie** 2020-05-25 21:38 UTC
Labels: kind/bug

**Comment by MadEngineX** [comment] 2020-12-18 08:41
> 
> 
> You are right.
> 
> A better workaround:
> 
> ```
>     metric_relabel_configs:
>       - action: labelmap
> ```
> 
> NOTE: This is a workaround for John. I do not recommend running this for people who face the 'label name "" is not unique: invalid sample' error. Instead, you should fix the problematic exporter.

Thanks for the idea Julien!
In our case, we use the ServiceMonitor CRD to transfer the metrics of the JMX exporter to Prometheus. Therefore the labelmap setting was causing a conflict. We changed ServiceMonitor and everything worked.

![image](https://user-images.githubusercontent.com/67797566/102593337-c9ca3600-4125-11eb-87eb-c3c1e71286f7.png)
