### ISSUE TITLE
Scraping metrics that are behind a Basic Auth login

### ISSUE THREAD

**Issue by kmandeville** [prometheus/prometheus#697] opened 2015-05-14 19:43 UTC
I'm looking to monitor a Spring Boot app I have in production. Since it's in production, I didn't want people stumbling across the /metrics endpoints and others that come from actuator so I put them behind a username and password. I tried putting the username and password in the url in the config file which works in browsers: 

username:password@http://blah.com/metrics

But that fails in Prometheus saying that "username" is not a valid protocol. So obviously it's not supported. Is there some way to configure the username and password for the metrics that I want prometheus to scrape?

**Comment by fabxc** [comment] 2015-05-14 20:02
It's because the URL scheme has to move to the beginning.
`http://username:password@blah.com/metrics`

With the next version, basic auth can be configured in what now is the `job` configuration.

**Comment by kmandeville** [comment] 2015-05-14 20:04
Oh, duh. Let me try that, thanks.

**Comment by fabxc** [comment] 2015-05-14 22:07
I assume the issue is resolved with that.
If not, you can still comment.

**Closed by fabxc** 2015-05-14 22:07 UTC
