### ISSUE TITLE
How to get a correct per minute metric

### ISSUE THREAD

**Issue by siyigao1212** [prometheus/prometheus#11677] opened 2022-12-06 10:02 UTC
### Proposal

We are using `clamp_min(foo - foo offset 60s, 0)` at the Prometheus evalution rules to get the per minute metric, `foo` is a counter type metric. The scrape interval is 20s , and the evalution interval is 60s.

At most of the cases, the rule works well and we could get the value we expect, but now we noticed that sometimes we could get a reduced number, this already happened several times. For example, we have 3 VMs which are running the Prometheus, and 2 of them could get 200 (the value we expected), one of them get 133 (2/3 of the expected value).

We did some investigation about the wrong value problem, seems that the root cause is the rule processing delay which caused the two `foo` is different. For example, below is the trend of metric `foo`, we could see from 08:01:00 to 08:02:00 the metric changed 3 times. 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/103725329/205876537-24301bee-6ea7-4c96-86b5-b4514bd2f5e4.png)
The assumption at our side is
* Correct value: (value of 08:02:00) - (value of 08:01:00) = 4 - 1 = 3
* Wrong value: (value of 08:01:59) - (value of 08:01:00) = 3 -1 = 2 

which means we get per minute metric by (value of current timestamp)  - (value of current timestamp offset 60s), however the 2 "current  timestamp" could be different. 

**The workaround we tried**
use `clamp_min(foo - foo offset 61s, 0)`  to get the per minute metric, we could get the correct value. I think this is because we give 1 second overlap to fit the calcuation delay.

**Why we use offset operator**
We were using `increase(foo[60s])` before to get the per minute value, but when the traffic is very low, the value will be zero. So we follow this discussion https://github.com/prometheus/prometheus/issues/3746#issuecomment-361188960 to change the rule at our side.

**Questions**
1. Could you please help confirm if this is a known issue when using offset?
2. If yes, Is there any way we can instruct prometheus to account for the rule processing delay?

**Comment by siyigao1212** [comment] 2022-12-07 06:57
Hi @free , we learnt a lot about `increase`, `rate`, `offset` when checking this proposal https://github.com/prometheus/prometheus/issues/3746 you posted before. Could you please help check the issue we met？

**Comment by alexgreenbank** [comment] 2024-10-22 11:55
Hello from the bug scrub.

Apologies for the delay in getting to this issue.

Closing this issue as this is not a bug in Prometheus, this more a question about how PromQL works.

The best places to seek help on these kinds of issues are listed in the [Prometheus Community](https://prometheus.io/community/).

**Closed by alexgreenbank** 2024-10-22 11:55 UTC
