### ISSUE TITLE
Prometheus + (addition) operator not working

### ISSUE THREAD

**Issue by AlbMor** [prometheus/prometheus#9972] opened 2021-12-08 09:18 UTC
**What did you do?**
```
prometheus_http_requests_total{} + prometheus_http_requests_total{}
```

**What did you expect to see?**
The result vector with the sum of the values

**What did you see instead? Under which circumstances?**
```
Error executing query: invalid parameter "query": 1:36: parse error: unexpected identifier "prometheus_http_requests_total"
```
**Environment**

* System information:
OS: Windows 10 2004
Docker Desktop: 3.5.2

* Prometheus version:
Prometheus: Docker image 2.30.1

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"


# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

```

**Comment by roidelapluie** [comment] 2021-12-08 09:24
mmh.. it works for me: https://prometheus.demo.do.prometheus.io/graph?g0.expr=prometheus_http_requests_total%7B%7D%20%2B%20prometheus_http_requests_total%7B%7D%0A&g0.tab=1&g0.stacked=0&g0.range_input=1h
could you double check your input?

**Comment by AlbMor** [comment] 2021-12-08 10:05
Hi @roidelapluie 

Running on Microsoft Edge (Microsoft Edge 44.19041.423.0, Microsoft EdgeHTML 18.19041) gives

```
Error executing query: invalid parameter "query": 1:36: parse error: unexpected identifier "prometheus_http_requests_total"
```

Running on Chrome (Version 96.0.4664.93 (Official Build) (64-bit)) is working

Both Chrome and Edge running on the same PC with Windows 10 2004

I have also tested in others two  PCs with Windows 10 20H2 and Windows 10 1909 and running with Edge with Chromium-based version and all are working

I think it is the Old Microsoft Edge issue here...
Indeed I have installed the Chromium Based edge also on the Failing PC and now it is working

So Conclusion

I think the Prometheus has issue working with old Microsoft Edge (the one not based on Chromium)
I think is up to you if you want to address this issue since I think supporting old web browser is always hard and sometimes it does not have value

Thanks for your help

**Comment by roidelapluie** [comment] 2021-12-08 10:26
@juliusv @Nexucis as our UI experts, do you know if the new promql editor is compatible with old edge? Can you comment on this issue?

**Comment by Nexucis** [comment] 2021-12-08 13:07
Looking at what @AlbMor reported, it doesn't look like it's related to the editor itself, I think it's more related to react.
I will try to reproduce it first. That shouldn't be too hard thanks to the input gave here :).

Let's see then if there is a quick fix to do.
In case it's really related to the editor, probably then we will have to report the issue to codemirror and we won't be able to do much more.

**Comment by juliusv** [comment] 2021-12-08 16:07
It could of course be that CodeMirror (our editor component) doesn't work properly on the old Edge, and that it thus produces some weird non-expected characters when reading its content. Seems like part of the query gets sent correctly to the backend (thus the error message includes a metric name), but that some unexpected character was sent to the backend.

@AlbMor It could be interesting to see what exactly gets sent to the backend in the `query` parameter, if you look at the dev tools and check for the query request going either to `/api/query` or `/api/query_range`.

**Comment by AlbMor** [comment] 2021-12-08 20:41
@juliusv 

Of course. I would like to know what is the dev tool so I can help. Please let me know

**Comment by juliusv** [comment] 2021-12-08 20:45
I mean this: https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network/

But not sure if that exists or what that looks like in the non-Chromium-based Edge. But basically the part of your browser that lets you inspect the network requests that are actually happening.

**Comment by AlbMor** [comment] 2021-12-08 20:54
@juliusv 

I realize now that I have updated Microsoft Edge on the failing PC and therefore I cannot test it :-(. Sorry

But I have reported the Edge version before that is  (Microsoft Edge 44.19041.423.0, Microsoft EdgeHTML 18.19041)

I can eventually spin up a Virtual Machine to test it but it will take a bit

**Comment by Nexucis** [comment] 2021-12-10 11:23
mmm I can't reproduce it either my edge version is too up to date ...

I'm wondering how much it is complicated to upgrade edge. Probably it's not a so hard requirement to say : "please upgrade edge" ?

**Comment by juliusv** [comment] 2021-12-10 13:03
Yeah, I'd just wait and see if anyone ever reports it again, and then maybe we can reproduce something.

**Comment by roidelapluie** [comment] 2021-12-17 16:08
Thanks everyone. I will close this issue, I agree it is fine to expect a recent browser version, and no one has been able to reproduce it.

**Closed by roidelapluie** 2021-12-17 16:08 UTC
