### ISSUE TITLE
PromQL, binary operators for range vectors

### ISSUE THREAD

**Issue by Azmisov** [prometheus/prometheus#14069] opened 2024-05-09 03:41 UTC
### Proposal

AFAIK, binary operators only work on instant vectors. This is a feature request to add binary operators for range vectors as well.

**Use case:** I want to take the difference of two gauge metrics, and then take the moving average over 15m. Syntax could look like this in PromQL: `avg_over_time(foo[15m] - bar[15m])`. There is no way to compute this by eagerly converting to instant vectors first; e.g. `avg_over_time(foo[15m]) - avg_over_time(bar[15m])` is not equivalent; see [Simpson's paradox](https://en.wikipedia.org/wiki/Simpson%27s_paradox).

I'm imagining the range vectors the operator applies to must have the same number of points, or else it is disallowed or NaN's are given where one of the vectors has more points. Whatever is sensible given the current aggregation engine. E.g. Functionally, I would assume it behaves the same as though you were performing the operator on two instant vector time series, except this time it is repeated across many lookback ranges of a range vector.

**Comment by darshanime** [comment] 2024-05-11 13:42
dupe of https://github.com/prometheus/prometheus/issues/7263, see [comment](https://github.com/prometheus/prometheus/issues/7263#issuecomment-2085021687)

**Closed** 2024-05-15 13:28 UTC

**Comment by Azmisov** [comment] 2024-05-15 15:07
Okay interesting. I did try `avg_over_time((foo - bar)[15m])` but I get the error `expected object type` in Grafana. But adding an interval explicitly seems to do the trick. Perhaps resolution is not optional after all?
