### ISSUE TITLE
Head block overlapping: a bug that affects history but not current version of prometheus

### ISSUE THREAD

**Issue by bo-er** [prometheus/prometheus#11981] opened 2023-02-16 23:17 UTC
### What did you do?

Prometheus Version: 2.25 (Apologies for using this old version and bringing up an issue about it)
I took a snapshot of Prometheus and used it to migrate data from one machine to another, and got these kinds of errors:

```
level=error ts=2022-12-10T13:05:25.321Z caller=db.go:766 component=tsdb msg="compaction failed" err="compact head: reloadBlocks blocks: invalid block sequence: block time ranges overlap: [mint: 1669706744883, maxt: 1669708586106, range: 30m41s, blocks: 2]: <ulid: 01GK166NFQHD6NTVNASWCQ5HY5, mint: 1669701600235, maxt: 1669708586106, range: 1h56m25s>, <ulid: 01GKY27NJPEP56Q4B40SW0EZKJ, mint: 1669706744883, maxt: 1669708800000, range: 34m15s>
```
After a few days, Prometheus consumed hundreds of Gigabytes of disk space.

```
umon      23730 23883 actiontech-universe   41r      REG               0,56   22628589  104990728 /opt/umon/prometheus-data/01GSE6Y24AE3FZAJK7G1779GST/chunks/000001 (deleted)
umon      23730 23883 actiontech-universe   92r      REG               0,56    2489901  100684698 /opt/umon/prometheus-data/01GSE6Y24AE3FZAJK7G1779GST/index (deleted)
umon      23730 23884 actiontech-universe   41r      REG               0,56   22628589  104990728 /opt/umon/prometheus-data/01GSE6Y24AE3FZAJK7G1779GST/chunks/000001 (deleted)
umon      23730 23884 actiontech-universe   92r      REG               0,56    2489901  100684698 /opt/umon/prometheus-data/01GSE6Y24AE3FZAJK7G1779GST/index (deleted)
umon      23730 23885 actiontech-universe   41r      REG               0,56   22628589  104990728 /opt/umon/prometheus-data/01GSE6Y24AE3FZAJK7G1779GST/chunks/000001 (deleted)
umon      23730 23885 actiontech-universe   92r      REG               0,56    2489901  100684698 /opt/umon/prometheus-data/01GSE6Y24AE3FZAJK7G1779GST/index (deleted)
umon      23730 23886 actiontech-universe   41r      REG               0,56   22628589  104990728 /opt/umon/prometheus-data/01GSE6Y24AE3FZAJK7G1779GST/chunks/000001 (deleted)
umon      23730 23886 actiontech-universe   92r      REG               0,56    2489901  100684698 /opt/umon/prometheus-data/01GSE6Y24AE3FZAJK7G1779GST/index (deleted)
umon      23730 23887 actiontech-universe   41r      REG               0,56   22628589  104990728 /opt/umon/prometheus-data/01GSE6Y24AE3FZAJK7G1779GST/chunks/000001 (deleted)
umon      23730 23887 actiontech-universe   92r      REG               0,56    2489901  100684698 /opt/umon/prometheus-data/01GSE6Y24AE3FZAJK7G1779GST/index (deleted)
umon      23730 23900 actiontech-universe   41r      REG               0,56   22628589  104990728 /opt/umon/prometheus-data/01GSE6Y24AE3FZAJK7G1779GST/chunks/000001 (deleted)
umon      23730 23900 actiontech-universe   92r      REG               0,56    2489901  100684698 /opt/umon/prometheus-data/01GSE6Y24AE3FZAJK7G1779GST/index (deleted)
umon      23730 27339 actiontech-universe   41r      REG               0,56   22628589  104990728 /opt/umon/prometheus-data/01GSE6Y24AE3FZAJK7G1779GST/chunks/000001 (deleted)
umon      23730 27339 actiontech-universe   92r      REG               0,56    2489901  100684698 /opt/umon/prometheus-data/01GSE6Y24AE3FZAJK7G1779GST/index (deleted)
```
It seems that Prometheus opened a head block but didn't close it. Deletion in Linux simply unlinks a file, the linux kernel maintains link count for each i-node and also counts open file descriptors for that file, if the file is still open, the file wouldn't get deleted.

Maybe a fix should be like adding `db.Close()`:

```
if err := db.reloadBlocks(); err != nil {
		if errRemoveAll := os.RemoveAll(filepath.Join(db.dir, uid.String())); errRemoveAll != nil {
			return tsdb_errors.NewMulti(
				db.Close(),  <= THIS LINE IS ADDED
				errors.Wrap(err, "reloadBlocks blocks"),
				errors.Wrapf(errRemoveAll, "delete persisted head block after failed db reloadBlocks:%s", uid),
			).Err()
		}
		return errors.Wrap(err, "reloadBlocks blocks")
	}
```

Since the newest version has already removed the  `storage.tsdb.allow-overlapping-blocks` option and it's enabled now, this issue seems to be trivial.

Should there be any fix against it?

### What did you expect to see?

Disk usage shouldn't be keep going up, as a result, the disk is running out of its space.

### What did you see instead? Under which circumstances?

The disk is running out of space.

### System information

Linux 3.10.0-862.14.4.el7.x86_64 x86_64

### Prometheus version

```text
prometheus version 2.25
```

**Comment by roidelapluie** [comment] 2023-03-06 13:44
@codesome what do you think about the proposal that's being made in this issue to add `db.Close()` in this particular location in the code?

**Comment by codesome** [comment] 2023-03-15 13:32
> It seems that Prometheus opened a head block but didn't close it.

That is how the TSDB works - head block stays open. The issue is that the compaction is not happening. If you are backfilling data (which is another way to look at this migration of data), it is required to allow overlapping blocks explicitly in older versions by design. In the newer versions since it is enabled by default, it is not a problem. So I consider this issue as a no-op.

Regarding the proposed `db.Close()`, no that would be wrong, we don't want to close the DB because a compaction failed somewhere. The resolution to this issue is to either enable overlapping blocks. Hence closing this issue.

**Closed by codesome** 2023-03-15 13:32 UTC
Labels: component/tsdb
