### ISSUE TITLE
Kubernetes SD: Add scheduled node label to pod discovery

### ISSUE THREAD

**Issue by jimmidyson** [prometheus/prometheus#1834] opened 2016-07-20 10:34 UTC
Currently there is no way to filter pod metrics based on what host they are deployed on to. Adding the hostname (available from the Kubernetes API) will let users do this. This is especially useful for node exporters, deployed using a daemonset so that the instance name can be relabelled to the hostname the pod is running on, but will also allow users to drill down into the metrics of all pods running on a particular node if desired.

**Comment by brian-brazil** [comment] 2016-07-20 10:36
Dupe of #1604

**Closed by brian-brazil** 2016-07-20 10:36 UTC
