### ISSUE TITLE
Provide Different Resolve timer for each Rule similar to Firing (FOR) timer and also capability to fire/resolve an alert based on no.of occurrences

### ISSUE THREAD

**Issue by rnachire** [prometheus/prometheus#7246] opened 2020-05-12 06:10 UTC
Provide Different Resolve timer for each Rule similar to Firing (FOR) timer and also capability to fire/resolve an alert based on no.of occurrences

**Usecase**: Each organization has their alert rules defined with different thresholds each with different time to raise and clear an alert

> 

AlertName:UserCount |   |   |   |  
-- | -- | -- | -- | --
Severity | Threshold | Interval | Resolve /Clear Threshold | Resolver timer
Informational | Users count between 10 - 99 | for 60 minutes | <= 10 | for 5 minutes
Warning | Users count between 100 - 999 | for 60 minutes | <= 99 | for 15 minutes
Exception | Users count equal to 999 or higher | for 60 minutes | <= 999 | for 25 minutes

In this, as we have default stale timer has 5 minutes then it is will cause the alert to resolved due to absence of metric.

So, it is always is expected user to set the no.of times it has to match to Fire or Resolve as alert. I do see similar capability in Kapacitor in InfluxDB.

Please let me know, if you need further details on usecase to implement this

Regards,
Rajesh

**Comment by brian-brazil** [comment] 2020-05-12 08:35
This has been proposed in various forms over the years, and is not something we plan on implementing. Dupe of #4681.

**Closed by brian-brazil** 2020-05-12 08:35 UTC
