### ISSUE TITLE
Incorrect very large values for time series

### ISSUE THREAD

**Issue by phillebaba** [prometheus/prometheus#10445] opened 2022-03-14 09:52 UTC
**What did you do?**

I am running a setup with two Prometheus instances in a cluster that remote write to a Thanos receiver setup. The Prometheus instances are run in agent mode and have a disk to persist the WAL cache. At random times one of the Prometheus instances start sending absurd values that are not possible.

**What did you expect to see?**

I expected to see normal reasonable values that are actually possible.

**What did you see instead? Under which circumstances?**

It seems to mostly affect the Prometheus meta metrics for the most parts but can also happen to other time series. Randomly a Prometheus instance will enter a weird mode where it starts sending unreasonable metrics values. I have drilled down and verified that the issue is not on the receiver end but on the writer side. It will only affects one of the Prometheus instances.

Here is an example of what happens. The graph is created from the following query `max (prometheus_remote_storage_shards) by (tenant_id)`.

![image](https://user-images.githubusercontent.com/10550243/158146854-039c8178-c01f-4067-aaf5-a506bdc05d5a.png)

The example shows an issue related to meta metrics, but I have observed this behavior with other scraped metrics also, where all of a sudden the node count in a cluster is reported as 5k instead of 10 which is the actual value.

**Environment**

* System information:

Linux 5.4.0-1067-azure x86_64

* Prometheus version:

prometheus, version 2.33.5 (branch: HEAD, revision: 03831554a51946f28c7cdc6be7282c687092327b)
  build user:       root@773960a14680
  build date:       20220308-16:57:09
  go version:       go1.17.8
  platform:         linux/amd64

* Alertmanager version:

N/A

* Prometheus configuration file:

```
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
  external_labels:
    cluster_name: <cluster-name>
    environment: <environment>
    prometheus: <prometheus>
    prometheus_replica: <prometheus-replica>
scrape_configs: <configs>
remote_write:
- url: <url>
  remote_timeout: 30s
  headers:
    THANOS-TENANT: <tenant>
  name: thanos
  tls_config:
    cert_file: /mnt/tls/tls.crt
    key_file: /mnt/tls/tls.key
    insecure_skip_verify: false
  follow_redirects: true
  queue_config:
    capacity: 3000
    max_shards: 100
    min_shards: 1
    max_samples_per_send: 1000
    batch_send_deadline: 5s
    min_backoff: 30ms
    max_backoff: 5s
  metadata_config:
    send: true
    send_interval: 1m
    max_samples_per_send: 500
```

* Alertmanager configuration file:

N/A

* Logs:

N/A

**Comment by SiminMu** [comment] 2022-03-23 08:39
Did you see any error log from Prometheus or Thanos such as "out of order" or "duplicate timestampe"?
I also got this [issue](https://github.com/prometheus/prometheus/issues/10456) after I saw a a lot of error messages of "out of order" or "duplicate timestampe".

**Comment by phillebaba** [comment] 2022-03-24 15:19
@SiminMu yes I am seeing the same out of order issues from cadvisor that you have seen. My expectation has been that both Prometheus and Thanos should handle this gracefully and eventually recover. But all I see is that metric values go a bit crazy when the cadvisor issues start appearing in the cluster.

**Comment by phillebaba** [comment] 2022-03-29 20:13
@SiminMu looked at your issue and I dont think the configuration is the issue. I am still seeing problems with wildly inaccurate values being sent at times when cadvisor seems to start failing. Would love help from anyone else if they have some other suggestion.

**Comment by liujing1087** [comment] 2022-04-07 01:06
I do have the same issue, after trying multiple prometheus versions, I found that it works fine without using agent mode.

**Comment by SiminMu** [comment] 2022-04-07 01:54
Used Grafana-agent, I didn't see this issue. Prometheus agent uses most of the code of Grafana agent, but it seems Prometheus agent is still not so stable now.

**Comment by roidelapluie** [comment] 2022-04-12 08:22
cc @rfratto any idea here?

**Comment by liujing1087** [comment] 2022-04-13 08:31
> 

As I configured some alert rules for the OS metrics, I found that the error occurs when logs such as "WAL truncated... New checkpoint created" are recorded in the log file, then I got some alerts like disk space usage greater an impossibly very large value. Everything goes fine after disable agent mode.

**Comment by liujing1087** [comment] 2022-04-13 08:32
> So I guess we can say that this is a Prometheus agent mode issue then? I am still currently trying to figure out at which end I should look. There are a lot of false flags in the form of warnings and error logs which probably have no affect on this issue. I see this issue when Prometheus ends up in a crashing loop. This can be caused by OOM Kill or running out of disk, not sure how these affect Prometheus, and it is difficult to determine what these two cases have in common other than the application restarting all the time.

As I configured some alert rules for the OS metrics, I found that the error occurs when logs such as "WAL truncated... New checkpoint created" are recorded in the log file, then I got some alerts like disk space usage greater than an impossibly very large value. Everything goes fine after disable agent mode.

**Comment by phillebaba** [comment] 2022-04-13 10:41
I just caught another occurrence of this now. The image below shows values for `gotk_reconcile_condition` which can impossibly have the value 19000.

![image](https://user-images.githubusercontent.com/10550243/163161362-c26b020e-257f-42b5-9ae9-bcabed3200e7.png)

Checking the logs of the offending Prometheus instance I see this.

```
s=2022-04-13T08:02:17.946Z caller=checkpoint.go:98 level=info msg="Creating checkpoint" from_segment=796 to_segment=797 mint=1649836937000
ts=2022-04-13T08:02:21.031Z caller=db.go:628 level=info msg="WAL checkpoint complete" first=796 last=797 duration=3.241522143s
ts=2022-04-13T10:02:21.287Z caller=db.go:557 level=info msg="series GC completed" duration=252.637017ms
ts=2022-04-13T10:02:21.287Z caller=checkpoint.go:98 level=info msg="Creating checkpoint" from_segment=798 to_segment=799 mint=1649844140000
ts=2022-04-13T10:02:25.094Z caller=db.go:628 level=info msg="WAL checkpoint complete" first=798 last=799 duration=4.059638833s
ts=2022-04-13T10:03:13.380Z caller=scrape.go:1572 level=warn component="scrape manager" scrape_pool=serviceMonitor/prometheus/prometheus-kube-prometheus-kubelet/1 target=https://10.190.1.4:10250/metrics/cadvisor msg="Error on ingesting out-of-order samples" num_dropped=71
ts=2022-04-13T10:03:43.380Z caller=scrape.go:1572 level=warn component="scrape manager" scrape_pool=serviceMonitor/prometheus/prometheus-kube-prometheus-kubelet/1 target=https://10.190.1.4:10250/metrics/cadvisor msg="Error on ingesting out-of-order samples" num_dropped=139
ts=2022-04-13T10:04:13.362Z caller=scrape.go:1572 level=warn component="scrape manager" scrape_pool=serviceMonitor/prometheus/prometheus-kube-prometheus-kubelet/1 target=https://10.190.1.4:10250/metrics/cadvisor msg="Error on ingesting out-of-order samples" num_dropped=52
ts=2022-04-13T10:04:43.411Z caller=scrape.go:1572 level=warn component="scrape manager" scrape_pool=serviceMonitor/prometheus/prometheus-kube-prometheus-kubelet/1 target=https://10.190.1.4:10250/metrics/cadvisor msg="Error on ingesting out-of-order samples" num_dropped=40
ts=2022-04-13T10:05:13.361Z caller=scrape.go:1572 level=warn component="scrape manager" scrape_pool=serviceMonitor/prometheus/prometheus-kube-prometheus-kubelet/1 target=https://10.190.1.4:10250/metrics/cadvisor msg="Error on ingesting out-of-order samples" num_dropped=72
ts=2022-04-13T10:05:43.434Z caller=scrape.go:1572 level=warn component="scrape manager" scrape_pool=serviceMonitor/prometheus/prometheus-kube-prometheus-kubelet/1 target=https://10.190.1.4:10250/metrics/cadvisor msg="Error on ingesting out-of-order samples" num_dropped=49
ts=2022-04-13T10:06:13.394Z caller=scrape.go:1572 level=warn component="scrape manager" scrape_pool=serviceMonitor/prometheus/prometheus-kube-prometheus-kubelet/1 target=https://10.190.1.4:10250/metrics/cadvisor msg="Error on ingesting out-of-order samples" num_dropped=87
ts=2022-04-13T10:06:43.377Z caller=scrape.go:1572 level=warn component="scrape manager" scrape_pool=serviceMonitor/prometheus/prometheus-kube-prometheus-kubelet/1 target=https://10.190.1.4:10250/metrics/cadvisor msg="Error on ingesting out-of-order samples" num_dropped=76
ts=2022-04-13T10:07:13.359Z caller=scrape.go:1572 level=warn component="scrape manager" scrape_pool=serviceMonitor/prometheus/prometheus-kube-prometheus-kubelet/1 target=https://10.190.1.4:10250/metrics/cadvisor msg="Error on ingesting out-of-order samples" num_dropped=117
ts=2022-04-13T10:07:43.379Z caller=scrape.go:1572 level=warn component="scrape manager" scrape_pool=serviceMonitor/prometheus/prometheus-kube-prometheus-kubelet/1 target=https://10.190.1.4:10250/metrics/cadvisor msg="Error on ingesting out-of-order samples" num_dropped=66
```

The logs and the metrics correlate in time so obviously something is happening during the check pointing. I may have to roll back and disable agent mode if that is what is causing these issues. I just don't understand why just some specific metrics are affected and not others. Because some metrics still have reasonable values.

**Comment by rfratto** [comment] 2022-04-13 12:36
I'll do a comparison of Grafana Agent code vs Prometheus Agent code today to see what's going on. 

As an aside: ideally, long term, Grafana Agent will use Prometheus Agent code directly and won't get out of sync with fixes. That's not currently the case (we need to work on getting #10231 merged before we can do that), so the Grafana Agent team is currently a bit slow on catching issues like these.

**Comment by rfratto** [comment] 2022-04-13 14:34
grafana/agent#676 was a similar issue fixed in Grafana Agent that doesn't have a current upstream equivalent and needs to be fixed. But its conditions were a little different than what's being reported here: it only happened after a restart, and values never returned to normal. 

To make sure I understand, everyone is seeing incorrect values eventually resolve on their own without deleting the WAL or restarting the process? I haven't been able to reproduce that specific scenario yet or find something in the code which would indicate something is wrong.

**Comment by Reed-Wu** [comment] 2022-04-14 03:39
> [grafana/agent#676](https://github.com/grafana/agent/pull/676) was a similar issue fixed in Grafana Agent that doesn't have a current upstream equivalent and needs to be fixed. But its conditions were a little different than what's being reported here, since it happens at process start time and doesn't resolve itself.
> 
> To make sure I understand, everyone is seeing incorrect values eventually resolve on their own without deleting the WAL or restarting the process? I haven't been able to reproduce that specific scenario yet or find something in the code which would indicate something is wrong.

In my dev server, I met this issue sometimes, and I restarted the Prometheus agent, but the issue was still there.  Then I deleted the wal folder, the issue is gone after restarting.
I redirected the prometheus console log to a file, when this issue was seen, I found some error logs, like:
> ts=2022-03-09T06:03:43.620Z caller=dedupe.go:112 component=remote level=error remote_name=7c5f5f url=https://CORTEX/api/prom/push msg="non-recoverable error" count=366 exemplarCount=0 err="server returned HTTP status 400 Bad Request: user=CCN: sample with repeated timestamp but different value; last value: 1099, incoming value: 0 for series {__name__=\"prometheus_sd_kubernetes_events_total\", event=\"update\", instance=\"ccn000:9090\", job=\"prometheus\", role=\"ingress\"

**Comment by SiminMu** [comment] 2022-04-14 06:21
My case is similar with @Reed-Wu :
- I couldn't always reproduce this issue, but if I started 10 agents on 10 servers, I could get this issue on 1 or 2 of them after 1 or 2 days, restarted agent repeatedly is easier to reproduce this issue, but not 100%
- This issue would never disappear itself, unless I deleted the WAL file
- When I got this issue, I would see "out of order" & "duplicate timestamps" at the beginning, and then I saw "Dropped sample for series that was not explicitly dropped via relabelling".

**Comment by phillebaba** [comment] 2022-04-14 07:47
I think we are all seeing the same thing. I have not been able to reproduce the issue, but as I am running 30+ Prometheus instances in agent mode I am bound to experience this issue eventually in at least one of the instances in a couple of days. I have experienced a couple of times where the resolution was to just restart the instance but for the most part I have to delete the WAL.

**Comment by rfratto** [comment] 2022-04-18 15:54
Thanks for the extra information. Given the recent comments, I suspect that #10587 might fix this after all.

**Comment by ntimo** [comment] 2022-04-18 16:02
So you have a release timeline for 2.35? With the fix, this is sadly making my PagerDuty app flip out all over the place :(

**Comment by phillebaba** [comment] 2022-04-21 08:59
@ntimo looks like they are cutting a new release right now.

**Comment by roidelapluie** [comment] 2022-04-21 09:48
Yes, 2.35 is being released now.

**Comment by roidelapluie** [comment] 2022-04-22 11:37
Please reopen if 2.35 does not fix this issue.

**Closed by roidelapluie** 2022-04-22 11:37 UTC

**Comment by phillebaba** [comment] 2022-04-24 10:18
Rolled out 2.35 to the majority om Prom instances and have yet to experience the same problems. Will keep an eye out during next week.

**Comment by HaoKunT** [comment] 2022-05-12 09:52
@phillebaba hello, we use prometheus agent mode and also meet this issue. Have you ever meet the same problems after upgrade to 2.35 ?

**Comment by phillebaba** [comment] 2022-05-22 20:10
Nope so far so good. Upgrading has solved my problems, and have not seen any issues for the last month or so.

**Comment by HaoKunT** [comment] 2022-05-23 02:18
> Nope so far so good. Upgrading has solved my problems, and have not seen any issues for the last month or so.

Thanks! I'll have a try.
