### ISSUE TITLE
POST valid JSON object to alertmanager

### ISSUE THREAD

**Issue by diogogmt** [prometheus/prometheus#1694] opened 2016-05-31 16:43 UTC
The notifier.send function posts an array of alerts to the alert manager which is not a valid JSON object.
The format being posted is:

```
[{...}]
```

Instead of:

```
{alerts: [{...}]}
```

**Comment by fabxc** [comment] 2016-06-01 09:32
👍  thanks for reporting. Indeed very incorrect.

**Comment by juliusv** [comment] 2016-06-02 01:42
For my understanding, is it a bad design pattern for the top-level type of a transferred API value to a JSON array instead of an object? For later extensibility I guess?

**Comment by fabxc** [comment] 2016-06-02 05:53
Well, for browsers it was always considered bad practice due to security concerns (http://flask.pocoo.org/docs/0.10/security/#json-security).
Not directly the case here but one should just stick with best practice I think.

Plus extensibility as you said. I'm in favor of fixing that. We can make Alertmanager accept both for a while.

**Comment by diogogmt** [comment] 2016-06-02 14:36
Exactly, I would say that extensibility  is the biggest benefit.

The only reason we came across this was that in our application we were playing with the idea of receiving the alerts directly from prometheus instead of letting the alert-manager manage the aggregates.
However, when we pointed prometheus to send the alerts to our own internal server we had to make a little hack to be able to deserialize the body data to our struct since it wasn't coming as a JSON object but as a JSON array instead.

**Comment by fabxc** [comment] 2016-06-28 14:26
We should really resolve this for 1.0.0.
Ideas/opinions on migration path or breakage?

@brian-brazil @juliusv @beorn7

**Comment by brian-brazil** [comment] 2016-06-28 15:10
I'm unsure on this, tending towards migration path for a month or so.

**Comment by fabxc** [comment] 2016-06-28 17:21
That brings the question of which direction the migration path should go.

**Comment by brian-brazil** [comment] 2016-06-28 18:12
It has to be on the AM side accepting both, otherwise we'd be talking a flag on the Prometheus side.

**Comment by fabxc** [comment] 2017-08-10 09:27
@brian-brazil why on the 2.x milestone? This first needs AM changes, which would accept both for a while anyway.
It has not caused any practical problems so far, so I see no rush. It would be a compatibility matrix thing anyway. So I see no relation to the Prometheus major version.

**Comment by brian-brazil** [comment] 2017-08-10 09:28
It's on 2.x as if we're going to fix it we'll need breaking changes, so we need to decide if they're going to be in 2.x. As it stands 3.x seems more likely, but I wanted to put it on the table.

**Comment by fabxc** [comment] 2017-08-10 09:52
As it's not an atomic change to one component and hasn't caused practical problems so far, let's put it off.

**Comment by bboreham** [comment] 2024-02-13 11:52
Discussed at the bug-scrub.
I believe the issue is located here: https://github.com/prometheus/prometheus/blob/26b78da281fe9d67277107461a6cfeb4dd073754/notifier/notifier.go#L485-L486

Given that nobody found it important enough to work on in 6 years, let's close this.

**Closed by bboreham** 2024-02-13 11:52 UTC
Labels: kind/cleanup, component/notify, priority/P3
