### ISSUE TITLE
Web UI Long Autocomplete: Jumps as you click dropdown item

### ISSUE THREAD

**Issue by mhansen** [prometheus/prometheus#6396] opened 2019-11-30 02:17 UTC
## Bug Report
**What did you do?**

Open Prometheus Web UI (non-react). Monitoring a a node exporter (or any server with a long autocomplete list).

Type in a few characters (e.g. "node_"). Scroll down a full page, so the graph is off the screen.

Hold mousedown on one of the items in the autocomplete dropdown. Observe that the screen has jumped back to the top of the screen, and your mouse is now over a different element.

Release the mouse. Observe that you selected the different element, not the original one you mousedown'd over.

Looking in the dev tools, inspect element'ing a dropdown item, I see a `mousedown`/`mouseup` jQuery event handler and many other `click` event handlers. I'm guessing they're conflicting.pr

**Environment**

* System information:

	Linux 4.19.75-v7l+ armv7l

* Prometheus version:

	Built today from master with go get -u github.com/prometheus/prometheus/cmd/...

**Comment by juliusv** [comment] 2019-11-30 08:49
@mhansen Thanks for the report, I can reproduce it. Definitely buggy!

The old UI will probably not be around much longer and the new UI already exists, so I wonder if this is still worth fixing. It probably depends on whether someone finds an easy fix. My guess is that the bug is somewhere in the typeahead plugin we use. The `mousedown` / `mouseup` / `click` handlers are defined in there (http://demo.robustperception.io:9090/static/vendor/bootstrap3-typeahead/bootstrap3-typeahead.min.js?v=43acd0e2e93f9f70c49b2267efa0124f1e759e86).

**Comment by mhansen** [comment] 2019-11-30 10:03
Thanks! Yeah, I agree this may not be worth fixing if the new UI is
imminent.

**Comment by juliusv** [comment] 2020-01-04 16:54
Closing this for now, because we don't expect the old UI to be around for long.

**Closed by juliusv** 2020-01-04 16:54 UTC
