### ISSUE TITLE
Add AutoRefresh option in prometheus alert page.

### ISSUE THREAD

**Issue by AshishVarshneyy** [prometheus/prometheus#7257] opened 2020-05-13 20:09 UTC
## Proposal
There should be an auto-refresh button on the Prometheus alert page.
**Use case:**
By this, we can save time during monitoring the alerts.

**Comment by roidelapluie** [comment] 2020-05-13 20:11
Thanks for your request.

This is a duplicate of #4440.

**Closed by roidelapluie** 2020-05-13 20:11 UTC
