### ISSUE TITLE
Tolerate Exemplars in Unexpected Metric Types

### ISSUE THREAD

**Issue by dcoracle** [prometheus/prometheus#12035] opened 2023-03-01 19:10 UTC
### Proposal

As suggested in the following thread [https://github.com/helidon-io/helidon/issues/6318](https://github.com/helidon-io/helidon/issues/6318), Prometheus ServiceMonitors should not outright reject the entire /metrics EP that have unexpected exemplars in some of its data, especially since it is expressed as commented output.  

Would be better to log this as a WARNING and continue parsing the EP

This will help future proof metrics that could one day support examplars in the OpenMetrics specs

**Comment by roidelapluie** [comment] 2023-03-05 22:12
Duplicate of #11982

**Closed by roidelapluie** 2023-03-05 22:12 UTC
