### ISSUE TITLE
Still seeing "opening storage failed: block dir" on more recent version of prometheus

### ISSUE THREAD

**Issue by btai24** [prometheus/prometheus#7090] opened 2020-04-04 21:53 UTC
**What did you do?**
Restarted my prometheus-operator to increase the cpu limit. Once the restart was performed, my prometheus pod ended up in a CrashLoopBackOff state.

**What did you expect to see?**
Prometheus pod should have gracefully terminated and restarted with a higher cpu limit

**What did you see instead? Under which circumstances?**
Prometheus pod comes back in a CrashLoopBackOff state, many of the directories are missing meta.json file. 

Similar to this issue: https://github.com/prometheus/prometheus/issues/4058

```
$ k logs -f prometheus-prometheus-operator-prometheus-0 -n monitoring prometheus
level=error ts=2020-04-04T21:42:45.231Z caller=main.go:727 err="opening storage failed: block dir: \"/prometheus/01E4WDCD2S7Y7X77KZJNZ1S30T\": open /prometheus/01E4WDCD2S7Y7X77KZJNZ1S30T/meta.json: no such file or directory"
```
**Environment**

* System information:

	Linux 4.9.0-11-amd64 x86_64
        Kubernetes v1.15.10
        Kops v1.15.0
        Prometheus backend: NFS mount - AWS EFS (Elastic Filesystem)

* Prometheus version:
	v2.15.2

* Prometheus configuration file:
  default prometheus-operator config with increased cpu & memory limit/requests

* Logs:
```
level=error ts=2020-04-04T21:42:45.231Z caller=main.go:727 err="opening storage failed: block dir: \"/prometheus/01E4WDCD2S7Y7X77KZJNZ1S30T\": open /prometheus/01E4WDCD2S7Y7X77KZJNZ1S30T/meta.json: no such file or directory"
```

**Comment by brian-brazil** [comment] 2020-04-04 22:16
NFS is not a supported filesystem.

**Comment by AndresBott** [comment] 2020-05-21 14:24
I'm experiencing similar behavior with azure-file https://kubernetes.io/docs/concepts/storage/storage-classes/#azure-file randomly ending in CrashLoopBackOff state after a pod restart.

@brian-brazil  I wonder what are the supported / recommended file systems to be used with K8S; 
I haven't found anything on the documentation providing guidance, any advice? thanks

**Comment by andloh** [comment] 2020-06-06 21:45
Seeing the same on SMB (azurefiles) as well. I changed to Azure Disk. 

Are SMB supported?

**Comment by roidelapluie** [comment] 2020-06-22 14:31
We are closing this as per our bug scrub. NFS is not supported by prometheus.

For SMB, we don't know if it is Posix-compliant. Can we know more about your setup? If you are having issue, please open a dedicated bug with straces so we can determine if we can support it.

**Closed** 2020-06-22 14:31 UTC

**Comment by lcfang** [comment] 2020-10-10 06:07
Hi,@roidelapluie Is longhorn a supported filesystem?

**Comment by flenoir** [comment] 2020-10-28 14:05
Does anyone confirm that it's working on Azure file with SMB protocol ?

**Comment by AndresBott** [comment] 2020-10-31 15:26
@flenoir Based on my experience I can confirm that Azure file does NOT work.
I was running a K8S pod with Azure file (SMB) for some time, and I experienced random DB corruptions; at that point if you don't what to loose the whole DB manual intervention is needed.
I ended up migrating to Azure Disk, not having problems since then.

**Comment by zannxD** [comment] 2021-06-09 09:33
I'm getting the same error:

opening storage failed: block dir: \"/prometheus/01F6J0P4KBBWVJD2M8B1PE7C5E\": open /prometheus/01F6J0P4KBBWVJD2M8B1PE7C5E/meta.json: no such file or directory

is there a way to fix this?
