### ISSUE TITLE
delete persisted head block after failed db xxxx remove

### ISSUE THREAD

**Issue by bbker** [prometheus/prometheus#9038] opened 2021-07-02 08:08 UTC
### I am using the default configuration.
prometheus  Version 2.18.1 
Windows Server 2016
### image:
![image](https://user-images.githubusercontent.com/11703570/124239904-c25ffc80-db4c-11eb-804c-26a0cef3ca74.png)

### log: It's all that kind of information
level=error ts=2021-07-02T05:00:01.788Z caller=db.go:667 component=tsdb msg="compaction failed" err="delete persisted head block after failed db reload:01F9JSD0DPACPW09RGEWXPDC7Z: remove E:\\monitor\\server\\data\\prometheus\\01F9JSD0DPACPW09RGEWXPDC7Z\\chunks\\000001: The process cannot access the file because it is being used by another process."
level=error ts=2021-07-02T05:01:01.790Z caller=db.go:667 component=tsdb msg="compaction failed" err="plan compaction: open E:\\monitor\\server\\data\\prometheus\\01F8KWMCDQ1EEQGEVDGQ6KBSVH\\meta.json: The system cannot find the file specified."
level=error ts=2021-07-02T05:04:01.795Z caller=db.go:667 component=tsdb msg="compaction failed" err="plan compaction: open E:\\monitor\\server\\data\\prometheus\\01F8KWMCDQ1EEQGEVDGQ6KBSVH\\meta.json: The system cannot find the file specified."
level=error ts=2021-07-02T05:07:01.806Z caller=db.go:667 component=tsdb msg="compaction failed" err="plan compaction: open E:\\monitor\\server\\data\\prometheus\\01F8KWMCDQ1EEQGEVDGQ6KBSVH\\meta.json: The system cannot find the file specified."
level=info ts=2021-07-02T07:00:01.022Z caller=compact.go:495 component=tsdb msg="write block" mint=1625198400000 maxt=1625205600000 ulid=01F9K08QNXSAZFFRWEKS6QHZ87 duration=705.0403ms
level=error ts=2021-07-02T07:00:01.117Z caller=db.go:946 component=tsdb msg="failed to read meta.json for a block" dir=E:\monitor\server\data\prometheus\01F8KWMCDQ1EEQGEVDGQ6KBSVH err="open E:\\monitor\\server\\data\\prometheus\\01F8KWMCDQ1EEQGEVDGQ6KBSVH\\meta.json: The system cannot find the file specified."

**Comment by roidelapluie** [comment] 2021-07-04 22:48
Hello,

Could you please update your prometheus to the latest release and try to reproduce this issue? It is likely that the root cause is The process cannot access the file because it is being used by another process., but you should not lose data, compaction should just fail.

**Comment by roidelapluie** [comment] 2021-07-27 15:11
Any update on this? Please also confirm that the filesystem is NTFS.

**Comment by beorn7** [comment] 2024-06-25 11:50
Hello from the bug scrub!

With no new information provided in 3y, we are closing this.

**Closed by beorn7** 2024-06-25 11:50 UTC
Labels: kind/more-info-needed, component/tsdb
