### ISSUE TITLE
UI hangs for indefinite time

### ISSUE THREAD

**Issue by Loopy88** [prometheus/prometheus#6161] opened 2019-10-17 15:18 UTC
Greetings!

So the issue happens when we are trying to load Prometheus UI and it becomes unavailable (it's not possible to click on anything, to enter the queries or change tabs).

At the same time, the Prometheus is working very well, only UI is unavailable. I've tried to launch the performance check, and it shows that some jQuery loads infinitely - screenshot is attached below.

On the screenshot, you can see that XHR Load took 49 seconds, but it actually loads much longer, I just stopped the performance check after 60 seconds.

I was using an older version of Prometheus initially (2.7 or 2.8) and then I've tried to update to the latest version, but it didn't help.

Can you please recommend something on this?

Thank you!

**What did you do?**
Open Prometheus UI

**What did you expect to see?**
Interactive, accessible UI

**What did you see instead? Under which circumstances?**
Frozen, not accessible UI 

**Environment**

* System information:

	Linux 4.15.0-1045-aws x86_64

* Prometheus version:
	
```
prometheus, version 2.13.0 (branch: HEAD, revision: 6ea4252299f542669aca11860abc2192bdc7bede)
build user:       root@f30bdad2c3fd
build date:       20191004-11:25:34
go version:       go1.13.1
```

![PromPerformance](https://user-images.githubusercontent.com/12534674/67021644-3b60bb80-f100-11e9-913d-b95ec28ea91a.png)

**Comment by Loopy88** [comment] 2019-10-18 08:29
Hi,

* I tried on Safari, Firefox, and Chrome - results are the same. I'm able to reproduce this issue not only on my local machine - all my colleagues working on Mac/Linux laptops are experiencing the same. That makes me think that this is not browser-related. But just for the info:

- Chrome: 77.0.3865.120 (Official Build) (64-bit)
- Firefox: 69.0.3 (64-bit)

* Same issue with the incognito mode being enabled (and plugins disabled)

* This demo page works just fine for me.

**Comment by juliusv** [comment] 2019-10-18 08:33
Ohhhh, I see. So the issue is specific to that Prometheus server, not to the browser. The `initTypeahead` in your trace suggests this is about initializing the typeahead autocompletion from the metric names that your Prometheus server has. This in turn suggests that you might have a huge number of metric names and the UI cannot cope with it well.

How many metric names do you see under `/api/v1/label/__name__/values` on your server?

**Comment by Loopy88** [comment] 2019-10-18 08:50
Oh wow, 

I see there ~ 602233 metric names. Can you please suggest what could we do about this? Apart from reducing the number of the metric names :)

**Comment by juliusv** [comment] 2019-10-18 09:37
Ah yeah, Prometheus is not made for hundreds of thousands of metric names - normally you'd have a couple thousand at most :)

But this came up in these issues too: https://github.com/prometheus/prometheus/issues/5919 and https://github.com/prometheus/prometheus/issues/5421
It seems there's a PR out attempting to fix this: https://github.com/prometheus/prometheus/pull/6100

**Comment by juliusv** [comment] 2019-10-18 09:38
@Loopy88 As for what you can do in the short term: you might be able to use a browser plugin to block XHR requests going to `/api/v1/label/__name__/values`?

**Comment by Loopy88** [comment] 2019-10-21 15:15
Thank you for the help and information @juliusv, I hope this PR will fix this situation soon!

In the meantime, I'll try to figure out why we have so many metric names. 

And yes, blocking the requests coming to `*://*/api/v1/label/__name__/values?_=*` is helping as a temporary workaround.

**Comment by gouthamve** [comment] 2020-05-25 14:33
We went through this issue in our bug scrub and are closing this as a dupe of #5421

**Closed by gouthamve** 2020-05-25 14:33 UTC
Labels: component/ui
