### ISSUE TITLE
meta.json is not generated after network issues, still not generated even if network issue is resolved

### ISSUE THREAD

**Issue by shadowtudark** [prometheus/prometheus#8437] opened 2021-02-03 15:31 UTC
**What did you do?**

I'm using premium azure files as my prometheus storage, the problem happens when there is a network jitter a week ago, since then, all the meta.json file is not generated in all the directories, "wal" folder size becomes bigger and bigger. 

**This is the status of mount**

//xxxpremium.file.core.windows.net/prometheus-data  1.0T   12G 1013G   2% /prometheus-data

**What did you expect to see?**

even if network has issues, meta.json should be generated after the network issues are gone, clearly it's not, it's been almost a week, meta.json files are not generated, the capacity is never used as full.

I delete all the folder the without meta.json to start prometheus successfully, but folder doesnot seem to be loaded successfully, it's 100G, after restart, only several G size.

wal corruption need to resolve

What did you see instead? Under which circumstances?

**Environment**

linux, k8s v1.18, premium azure files with capacity 1G.

**Prometheus version: 2.16**

**Logs:**

When have network issues, 

plan compaction: readdirent: resource temporarily unavailable

When restart prometheus, the below logs showned,

level=error ts=2020-10-29T03:29:33.202Z caller=main.go:764 err="opening storage failed: block dir: \"/prometheus/01ENRA5TM45DGMR9PG0NF5R3M6\": open /prometheus/01ENRA5TM45DGMR9PG0NF5R3M6/meta.json: no such file or directory"

**Comment by roidelapluie** [comment] 2021-02-03 15:57
Thank you for your report.

As stated in https://prometheus.io/docs/prometheus/latest/storage/ , Prometheus is expecting a local disk and does not support NFS-like filesystems.

Can you please describe of Prometheus could restart without the meta.json, or if it simply stopped?

**Comment by shadowtudark** [comment] 2021-02-03 16:23
> Thank you for your report.
> 
> As stated in https://prometheus.io/docs/prometheus/latest/storage/ , Prometheus is expecting a local disk and does not support NFS-like filesystems.
> 
> Can you please describe of Prometheus could restart without the meta.json, or if it simply stopped?

hi thanks for replying, prometheus couldn't restart without the meta.json, it simply throws errors like below, then it crashedbackoff.

level=error ts=2021-02-03T03:29:33.202Z caller=main.go:764 err="opening storage failed: block dir: "/prometheus/01ENRA5TM45DGMR9PG0NF5R3M6": open /prometheus/01ENRA5TM45DGMR9PG0NF5R3M6/meta.json: no such file or directory"


actually I mount premium azure file ssd over smb protocol in my k8s container using cifs-utils,  is it not supported ? 

most of the time it's working fine, but after a network jitter, all the meta files are not generated since then, even after the network issue is resolved in short time, the meta files are still not generated, what I'm wondering is, prometheus doesn't support such edge case, like retry generating meta files after everything is ok ?

**Comment by roidelapluie** [comment] 2021-02-03 21:07
I would be really surprised that only meta.json is missing. I think you have way more serious corrupton and meta.json missing is only a symptom.

**Comment by roidelapluie** [comment] 2021-02-03 21:09
The fact that meta.json is missing does not mean that all the rest is here -- and the "what else is missing" is probably an issue.

You are not the first one reporting this kind of issue, and Prometheus really relies on local storage, for that kind of reasons.

**Comment by shadowtudark** [comment] 2021-02-04 02:15
> The fact that meta.json is missing does not mean that all the rest is here -- and the "what else is missing" is probably an issue.
> 
> You are not the first one reporting this kind of issue, and Prometheus really relies on local storage, for that kind of reasons.

local storage is not stable and cannot be scaled. 

that's why we need to write data to remote, @roidelapluie what's the best way to solve this issue ? or at least how to not crash even if meta.json files are missing.

**Comment by roidelapluie** [comment] 2021-02-04 23:49
> > The fact that meta.json is missing does not mean that all the rest is here -- and the "what else is missing" is probably an issue.
> > You are not the first one reporting this kind of issue, and Prometheus really relies on local storage, for that kind of reasons.
> 
> local storage is not stable and cannot be scaled.
> 
> that's why we need to write data to remote, @roidelapluie what's the best way to solve this issue ? or at least how to not crash even if meta.json files are missing.

If you need large storage, the most cost effective solution is probably to have remote write systems (e.g. thanos or cortex), which use object storage, and have a smaller local disk. You could parse the mailing list to see previous requests like yours being answered I think.

**Comment by beorn7** [comment] 2021-02-15 15:48
During our weekly bug scrub, we decided to close this as this is not a bug in Prometheus. For further questions about how to configure Prometheus with a remote storage solution, please use the [community channels](https://prometheus.io/community/) to get support.

**Closed by beorn7** 2021-02-15 15:48 UTC
Labels: kind/question
