### ISSUE TITLE
Validate rules_files:

### ISSUE THREAD

**Issue by kaihendry** [prometheus/prometheus#6310] opened 2019-11-13 06:43 UTC
Makefile
```
test:
        docker run -v $(shell pwd):/pingprom:rw -it --entrypoint=promtool prom/prometheus test rules /pingprom/test.yaml
```

test.yaml
```
rule_files:
    - doesnotexist.yaml
```
running `make`
```
Unit Testing:  /pingprom/test.yaml
  SUCCESS
```

I expected it to fail since the alert.rules.yml does not exist.

**Comment by simonpasquier** [comment] 2019-11-13 16:09
Thanks for the report! This is a duplicate of https://github.com/prometheus/prometheus/pull/6182 and https://github.com/prometheus/prometheus/pull/6075 should be the fix.

**Closed by simonpasquier** 2019-11-13 16:09 UTC

**Comment by kaihendry** [comment] 2019-11-14 01:50
Sidenote: assuming the alert rule file exists, will that file itself be parsed and validated?

**Comment by simonpasquier** [comment] 2019-11-14 15:58
> Sidenote: assuming the alert rule file exists, will that file itself be parsed and validated?
Yes

**Comment by kaihendry** [comment] 2019-11-19 05:37
<img src="https://s.natalian.org/2019-11-19/1574141709_2560x1440.png">

I can see the rules file was not opened. :/
