### ISSUE TITLE
Prometheus 2.24.1 on OpenBSD and database corruption

### ISSUE THREAD

**Issue by precurse** [prometheus/prometheus#8877] opened 2021-05-30 16:39 UTC
Prometheus 2.24.1 on OpenBSD is failing to compact data into blocks, resulting in a `compact head: persist head block: 2 errors: populate block: add series: read symbols: invalid checksum; read symbols: invalid checksum` error message.

After enough time, Prometheus will crash entirely and panic due to the checksum errors.

I've tested this multiple times using an empty Prometheus data directory, but the same issue recurs. I have validated this on 2 separate OpenBSD 6.9 installs, which rules out any disk corruption issues.

I believe #8799 is related, but I wanted to open a formal bug report for this issue.

**Environment**

* System information:

`OpenBSD 6.9 amd64`

* Prometheus version:
```
prometheus, version 2.24.1 (branch: non-git, revision: non-git)
  build user:       OpenBSD
  build date:       20210419-21:27:27
  go version:       go1.16.2
  platform:         openbsd/amd64

```

* Alertmanager version:

N/A

* Prometheus configuration file:
```
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090','localhost:9100']

```

* Alertmanager configuration file:
N/A

* Logs:
The following error repeats every minute:
```
prometheus[45178]: level=error ts=2021-05-30T16:28:18.965Z caller=db.go:745 component=tsdb msg="compaction failed" err="compact head: persist head block: 2 errors: populate block: add series: read symbols: invalid checksum; read symbols: invalid checksum"
prometheus[45178]: level=error ts=2021-05-30T16:29:19.014Z caller=db.go:745 component=tsdb msg="compaction failed" err="compact head: persist head block: 2 errors: populate block: add series: read symbols: invalid checksum; read symbols: invalid checksum"
prometheus[45178]: level=error ts=2021-05-30T16:30:19.059Z caller=db.go:745 component=tsdb msg="compaction failed" err="compact head: persist head block: 2 errors: populate block: add series: read symbols: invalid checksum; read symbols: invalid checksum"
```

Eventually Prometheus will panic with the following error:
```
panic: corruption in head chunk file /var/prometheus/chunks_head/000001: checksum mismatch expected:00000000, actual:d096d996
```

**Comment by roidelapluie** [comment] 2021-06-02 23:11
Thank you for your input. This seems a pretty important bug.

**Comment by roidelapluie** [comment] 2021-06-02 23:23
It seems that we would need to call msync() after writing to the mmap area.

**Comment by roidelapluie** [comment] 2021-06-15 13:39
https://groups.google.com/u/1/g/prometheus-developers/c/fFEnTout9Qw

**Comment by xhci** [comment] 2021-06-16 22:16
@roidelapluie Prometheus seems to be working for me other than the "compaction error" log messages that are being thrown around. Granted, I have a pretty simple use-case of weather data collection.

**Comment by j0holo** [comment] 2022-02-20 10:48
Is there a way I can help with testing this fix?

**Comment by minusf** [comment] 2022-04-04 21:44
would it be a possibility to have this (perhaps openbsd specific) mmap code "ifdefed" (whatever is the go equivalent) to the openbsd platform?

**Comment by j0holo** [comment] 2022-04-05 16:16
Maybe something with `if runtime.GOOS != "openbsd"`? But the whole mmap code is still compiled in the binary for OpenBSD. It just guarded by if statements in runtime.

**Comment by roidelapluie** [comment] 2022-04-15 11:00
It's not really the issue. The issue is that this takes time to review, which I don't really have at the moment.

**Comment by dohnuts** [comment] 2022-06-14 13:58
> `[tsdb: index write via mmap](/ston1th/prometheus/commit/bf930161eb7e3202564f2bbfac75466d70279087) ` …

so basically waiting help to validate that proposition ?

**Comment by dohnuts** [comment] 2022-06-20 15:01
> It's not really the issue. The issue is that this takes time to review, which I don't really have at the moment.

I contacted the person responsible for the mmap library currently used ( the library is designed to solve portability issue !), no answer after more that 5 days.
I think the commit from @ston1th is an improvement for Prometheus even outside OpenBSD use case.

@roidelapluie would it be possible to speed up resolution here given the relatively large amount of feedback !

( also see https://github.com/prometheus/prometheus/issues/8799 which is almost 100% duplicate )

**Comment by roidelapluie** [comment] 2022-07-05 07:37
Closing as duplicate of #8799

**Closed by roidelapluie** 2022-07-05 07:37 UTC
Labels: kind/bug, priority/P3, component/tsdb
