### ISSUE TITLE
Add e2e tests for basic Prometheus functionalities.

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#7227] opened 2020-05-08 08:04 UTC
Our test coverage is really poor, especially in main.go. [We just have regression which was easy to find](https://github.com/prometheus/prometheus/issues/7216)... if we had any test there. 

I would propose adding tests using the e2e framework we maintain as Thanos & Cortex maintainers. You can see [an example test in Thanos project.](https://github.com/thanos-io/thanos/blob/8fa2a4bed62037c19672b29013fc8a9ca4f3d416/test/e2e/query_test.go#L75 )

It allows a very quick spin-up of Prometheus in the form of docker container (and needed dependencies if needed) and running all needed APIs etc (e.g Snapshots) and asserting certain expectation (AND Prometheus metric values!). I would also propose a separate e2e test using Github actions [as we do in Thanos](https://github.com/thanos-io/thanos/blob/6e91dfd6a70f49ebab9cc6643572473885de3e37/.github/workflows/e2e.yaml#L11) to make sure it's parallel to the rest of the tests. (:

**Comment by bwplotka** [comment] 2020-05-08 08:05
IMO high priority.

**Comment by roidelapluie** [comment] 2020-05-08 15:29
We do have e2e for query log

**Comment by roidelapluie** [comment] 2020-05-08 15:29
And they do not have the overhead of docker.

**Comment by bwplotka** [comment] 2020-05-08 16:43
Sure, whatever that will make sense (:  Can you link the e2e tests that you have in mind? I might miss that.

However, docker overhead does not matter and is a small downside vs what it gives. And it gives a huge win - process isolation (no more leaked processes), network isolation and allows to test our docker image build as well. cc @pracucci

**Comment by roidelapluie** [comment] 2020-05-08 17:34
https://github.com/prometheus/prometheus/blob/master/cmd/prometheus/query_log_test.go

**Comment by brian-brazil** [comment] 2020-06-29 14:11
As part of the bug scrub this appears to be a duplicate of #3689

**Closed by brian-brazil** 2020-06-29 14:11 UTC
Labels: component/tests, help wanted, kind/enhancement, priority/P1
