### ISSUE TITLE
High memory in Prometheus 2.15.2

### ISSUE THREAD

**Issue by veer123prathap** [prometheus/prometheus#8108] opened 2020-10-24 16:19 UTC
<!--

**What did you do?**
we are scraping 170 jobs in Prometheus.
Memory---64GB
CPU: 5
scraping interval 60s
and remote write to victoria metrics (standalone machine).
After 2-day Prometheus server went down memory out

**What did you expect to see?**
Prometheus should run continuously without any downtime
**What did you see instead? Under which circumstances?**

**Environment**
PROD
* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here
2.15.2
* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by roidelapluie** [comment] 2020-10-24 17:19
Duplicate of #8108

**Closed by roidelapluie** 2020-10-24 17:19 UTC
