### ISSUE TITLE
Add time selector to Console UI

### ISSUE THREAD

**Issue by SuperQ** [prometheus/prometheus#4397] opened 2018-07-18 11:58 UTC
## Proposal

In the "Graph" view, you can select what time you want the graph to start. It would be very useful to have the same time selector in the "Console" view.

This would allow querying, and sharing links, for specific instant query times.

<img width="300" alt="time-picker" src="https://user-images.githubusercontent.com/1320667/42879917-9b07075e-8a92-11e8-856b-fd5ac1de2a1c.png">

**Comment by brian-brazil** [comment] 2018-07-18 12:00
Dupe of #1246

**Closed by brian-brazil** 2018-07-18 12:00 UTC
Labels: component/ui

**Comment by SuperQ** [comment] 2018-07-18 12:03
Sorta similar, that one seems to be more about graph queries.

**Comment by brian-brazil** [comment] 2018-07-18 12:07
I think it might have changed scope at some point, but I consider that one to be tracking console time selection.
