### ISSUE TITLE
Working set size increase on startup when remote write enabled

### ISSUE THREAD

**Issue by bismarck** [prometheus/prometheus#5709] opened 2019-06-26 18:54 UTC
## Bug Report
**What did you do?**
I enabled remote write, restarted the prometheus pod and it OOMed because the working set size increased 3x.

**What did you expect to see?**
Here's what `container_memory_working_set_bytes`, `process_resident_memory_bytes` and `go_memstats_alloc_bytes` looked like before enabling remote write:

![prom-2 10 0-mem](https://user-images.githubusercontent.com/1072760/60206376-5e99ef00-9821-11e9-8079-741e2255d5ef.png)

**What did you see instead? Under which circumstances?**
Here's after enabling remote write:

![prom-2 10 0-mem-rw](https://user-images.githubusercontent.com/1072760/60206515-b6d0f100-9821-11e9-872b-8f230e25da03.png)

After ~4 hours, working set size goes back to expected level:

![prom-2 10 0-mem-rw-4hr](https://user-images.githubusercontent.com/1072760/60206555-d9630a00-9821-11e9-92a2-b23f3938aa17.png)

**Environment**

* System information:
```
Linux 4.15.0-1037-azure x86_64
```
* Prometheus version:
```
prometheus, version 2.10.0 (branch: HEAD, revision: d20e84d0fb64aff2f62a977adc8cfb656da4e286)
  build user:       root@a49185acd9b0
  build date:       20190525-12:28:13
  go version:       go1.12.5
```
* Prometheus configuration file:
```
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    datacenter: eastus2
    environment: dev
    prometheus: kubernetes
    prometheus_replica: "0"
alerting:

... alerting configs ...

rule_files:
- /etc/prometheus/rules/prometheus-prometheus-kube-prometheus-rulefiles-0/*.yaml
scrape_configs:

... lots of scrape configs ...

remote_write:
- url: http://REDACTED:7201/api/v1/prom/remote/write
  remote_timeout: 30s
  queue_config:
    capacity: 10
    max_shards: 1000
    min_shards: 1
    max_samples_per_send: 100
    batch_send_deadline: 5s
    max_retries: 3
    min_backoff: 30ms
    max_backoff: 100ms
```

**Comment by bboreham** [comment] 2019-06-27 14:17
Somewhat similar to #5666

**Comment by cstyan** [comment] 2019-07-15 03:58
IME enabling remote write after the rewrite usually has about 25-35% memory increase. We haven't seen memory usage 3x with remote write on, but without more info I can't offer any suggestions. 

Are you able to show us logs from your Prometheus prior to it being OOM killed, or a pprof profile? How many active series do you have? I would assume not many based on the graphs you posted. You could also have a look at the metrics Tom mentions here: https://github.com/prometheus/prometheus/issues/5424#issuecomment-478550630

**Comment by Niksko** [comment] 2019-08-01 13:09
I'd like to add a little info here. We're seeing something very similar, and have been struggling all week to figure out why Prom is consistently using so much memory. Based on a bit of testing, we observe that on startup, Prometheus quickly reshards up to a large number of remote write shards (presumably to flush out the WAL into the remote write target). This uses up an immense amount of memory causing OOMs. Restricting the max number of shards seems to solve this problem for us.

Happy to provide metrics/pprofs that would help if this is unexpected behavior. We're running with about 1.2M timeseries, and with the default remote write settings we're getting OOMs at around 14GB of resident set. We've had to reduce our max shards to 50 and our max samples per send to 10000, and this gives us around 9GB rss.

**Comment by cstyan** [comment] 2019-08-01 14:49
@Niksko That sounds like expected behaviour to me. Remote Write isn't able to start sending metrics until after it's replayed the existing WAL, so it will want to upshard a lot initially.

As another data point for you, we have some Prometheus instances that have about 1.35mil active series. We use the default max and min shards, but bump the capacity from 10 to 100. Those instances are using ~ 17GB in RSS and ~12GB cache. These are running in pods, we let them request 25GB and limit them to 30GB.

If you're interested you can graph this query: https://github.com/prometheus/prometheus/blob/master/documentation/prometheus-mixin/dashboards.libsonnet#L107 to see if you're remote write is falling behind. Debug logging will also tell you how many shards remote write wants to use.

**Comment by beorn7** [comment] 2019-08-01 15:29
Also note that https://github.com/prometheus/prometheus/pull/5787 adds metrics for the configured and desired shards.

Overall, the observed behavior seems expected with the configured number of max shards. Since this is more a configuration problem than an actual bug, I'm closing this issue.

**Comment by bboreham** [comment] 2019-08-01 21:01
Also see #5267 wherein I try to reduce the default max shards and #5763 which is trying to improve the desired shards calculation.

**Comment by csmarchbanks** [comment] 2019-08-05 18:41
I do not think that the observed behavior in this ticket is expected. I see at least two real issues that are being commented on:
1. The current shard calculation only takes how far behind the remote write component is into account, not the input rate of samples. #5763 fixes that.
   * This is likely the biggest issue causing the spikes of number of shards.
1. Potentially large amount of upsharding when a queue is started. Caused while we catch up on samples missed during WAL replay, and amplified by point 1. Technically all of that time is unnecessary (though nice from a separation of concerns) since the TSDB startup also reads the WAL on startup.

These are valid concerns with the current remote write behavior and it is incredibly frustrating to tune a remote writing Prometheus right now.

**Comment by Niksko** [comment] 2019-08-07 00:25
From my point of view, part of this is a documentation issue.

Documentation should indicate that memory usage of this scale is expected and intended, and you should provide rough estimates to help people determine legitimate usage from unexpected usage. There are many, many threads in various places that show that the high memory usage of Prometheus comes as a shock to people. Clearly it shouldn't be a shock.

**Comment by beorn7** [comment] 2019-08-12 17:32
Thanks for all your input. Since #5763 and #5267 are still being worked on, I'll re-open this. Mostly so that people running into memory issues and searching for open bugs will find this. To be closed once both PRs are merged.

Also note that I re-purposed #5803 to track better documentation of configuring remote-write queues.

**Comment by cstyan** [comment] 2019-12-31 23:08
Some documentation has been added: https://github.com/prometheus/docs/pull/1417/files

Not sure there's anything else actionable here, if there is we should add it to #6333

**Comment by beorn7** [comment] 2020-05-04 14:47
We are currently running a bug scrub with the team. Following @cstyan's line of argument, we close this now. Please follow up in #6333 if needed.

**Closed by beorn7** 2020-05-04 14:47 UTC
Labels: component/remote storage
