### ISSUE TITLE
Support Snapshots and Native Histograms at the same time

### ISSUE THREAD

**Issue by sylr** [prometheus/prometheus#11735] opened 2022-12-15 22:01 UTC
### Proposal

I would really like to not have to trade fast prometheus startup for native histograms.

It would be terrific if we could have both at the same time.

**Comment by codesome** [comment] 2023-01-05 07:46
Yup, we plan to support it. Do note that native histograms are experimental and not suggested to use native histograms in production yet since there can be breaking changes (and there is indeed one breaking change coming for native histograms in the next release).

Closing as a duplicate of https://github.com/prometheus/prometheus/issues/11262

**Closed by codesome** 2023-01-05 07:46 UTC
