### ISSUE TITLE
Probe_success value for non exisisting URL

### ISSUE THREAD

**Issue by lalithasoundarya** [prometheus/prometheus#2257] opened 2016-12-06 06:41 UTC
**What did you do?**
I installed prometheus on my pc and tried to scrape Google.com but the probe status is 0 .

**What did you expect to see?**
It should give an error message as non existing url 
**What did you see instead? Under which circumstances?**
Iam seeing probe success  = 0 message for google.com

**Environment**
windows

* System information:

	insert output of `uname -srm` here
       Microsoft Windows [Version 6.1.7601]

* Prometheus version: 

	insert output of `prometheus -1.3.1 windows amd64`

* Alertmanager version:

	insert output of `alertmanager -version` here (if relevant to the issue)

* Prometheus configuration file:
global:
    external_labels:
       monitor: 'hostname'

rule_files:
    - 'C:\Users\prasanta1.sahoo\go\bin\alert.rules'

scrape_configs:
  - job_name: 'bb'
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    URL: google.com
    
    
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: 10.50.89.143:9115  # Blackbox exporter.
  Please let us know for any changes in the above config file.

```
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
[my global config.docx](https://github.com/prometheus/prometheus/files/633020/my.global.config.docx)

**Comment by brian-brazil** [comment] 2016-12-06 08:10
Dupe of #2256

**Closed by brian-brazil** 2016-12-06 08:10 UTC
