### ISSUE TITLE
 sum_over_time should use semi-closed range interval 

### ISSUE THREAD

**Issue by liguozhong** [prometheus/prometheus#7933] opened 2020-09-13 16:59 UTC
To denote the subsequence of a time series, four conventions are open:
a) start_time <= t < end_time
b) start_time < t <= end_time
c) start_time <= t <= end_time
d) start_time < t < end_time

![image](https://user-images.githubusercontent.com/9583245/93023831-5e536280-f624-11ea-9064-0c8fbfaedc9e.png)
http://demo.robustperception.io:9090/graph?g0.range_input=1h&g0.moment_input=2019-12-06%2011%3A59%3A00&g0.expr=vector(1)%5B3m%3A1m%5D&g0.tab=1&g1.range_input=1h&g1.moment_input=2019-12-06%2011%3A59%3A00&g1.expr=vector(1)%5B179s%3A1m%5D&g1.tab=1
Related issues
https://github.com/prometheus/prometheus/issues/6438
https://github.com/prometheus/prometheus/issues/6414
https://github.com/prometheus/prometheus/pull/4831
https://github.com/prometheus/prometheus/issues/1227
https://github.com/grafana/grafana/issues/14209
https://github.com/prometheus/prometheus/pull/3760
https://github.com/prometheus/prometheus/issues/3746

![image](https://user-images.githubusercontent.com/9583245/93024447-331f4200-f629-11ea-83fa-ab6c97cb03a8.png)

**Comment by brian-brazil** [comment] 2020-09-13 20:55
This is duplicate of many of the issues you listed in particular #6414, so I'm going to close this. As you have already mention, this is working as designed and changing it would be breaking.

**Closed by brian-brazil** 2020-09-13 20:55 UTC
