### ISSUE TITLE
Rancher support?

### ISSUE THREAD

**Issue by jmreicha** [prometheus/prometheus#1203] opened 2015-11-07 17:12 UTC
Rancher has a nice API, would it be possible to add support for it, similar to the other SD configurations currently supported?

It would be cool to be able to configure Prometheus based on Rancher labels for example.

**Comment by fabxc** [comment] 2015-11-07 17:24
In general, absolutely.
It mostly needs someone who writes the implementation (with guidance of course) and agrees to maintain it in the future.

**Comment by Rucknar** [comment] 2016-03-08 21:39
@jmreicha basic support can be used through the following. It should expose host/service/stack and label metrics so far... it's quite basic at the moment but open to any pull-requests if you have the time.

https://github.com/Rucknar/prometheus-rancher-exporter

**Comment by brian-brazil** [comment] 2016-03-08 21:51
That's a rancher exporter (which isn't listed on http://prometheus.io/docs/instrumenting/exporters/ - could you send a PR?), this issue is about service discovery support.

**Comment by jmreicha** [comment] 2016-03-08 22:02
@Rucknar Cool, I will check it out.  Thanks for the update!

**Comment by Rucknar** [comment] 2016-03-08 22:09
@brian-brazil my mistake, will send a PR!

**Comment by jmreicha** [comment] 2016-03-18 23:08
@Rucknar Getting around to testing this I am running in to an issue getting the prometheus-rancher-exporter Docker image to play with the Prometheus Rancher stack but it looks like issues are closed for the project?  What's the best way report and get hlep issues?

**Comment by brutus333** [comment] 2016-05-31 06:26
@fabxc: I am willing to take this assignment since we are trying to go into production with Rancher & Prometheus and we need a better solution. 
I clearly need some guidance - I will try to use consul_sd code as a starting point but I'm not sure if it's enough.
For rancher metadata I am planning to use the go client: https://github.com/rancher/go-rancher-metadata. If additional feature would be needed, I will PR this code also.
Do you have any advice to start working on this feature?

**Comment by fabxc** [comment] 2016-06-01 09:41
The Go client unfortunately lacks documentation but AFAICS there is no polling for changes. In that case one would just refresh every x seconds. For that case the DNS SD is more suitable as an example than the Consul one. It's also easier.

The biggest challenge will be providing testing. 
After accepting SD integrations without tests in the past, due to recent regressions I decided to no longer accept such PRs.

I would say just start implementing as far as you get and open a pull request to walk through missing steps together.

**Comment by burdiyan** [comment] 2016-11-16 16:13
Does anyone have any new about that? I'm thinking about implementing Rancher SD for Prometheus but wonder if there is anybody who already started to do something.

**Comment by brutus333** [comment] 2016-11-17 05:09
Hello!
I took a different route, please see: https://github.com/brutus333/prom-rancher-sd
The idea was borrowed from https://github.com/DanielDent/prom-rancher-sd which used json file for Prometheus integration.
I have also a rancher catalog which uses this:
https://github.com/brutus333/rancher-extra-catalog
It is not the most elegant solution, but it was an easy workaround. 
A real rancher_sd implementation would be clearly better.

**Comment by Rucknar** [comment] 2017-10-25 13:26
@brian-brazil Given rancher 2.0 moving to a kubernetes base, suggest this one is closed off? 
DNS service discovery works as-is, kubernetes should be usable once 2.0 is released.

**Comment by brian-brazil** [comment] 2017-10-25 14:34
That sounds reasonable to me.

**Closed by brian-brazil** 2017-10-25 14:34 UTC
Labels: component/service discovery, kind/enhancement, priority/Pmaybe
