### ISSUE TITLE
Custom http headers inside scrape configs / target configs

### ISSUE THREAD

**Issue by llacroix** [prometheus/prometheus#6536] opened 2019-12-31 20:08 UTC
## Proposal

Add a way to define custom headers inside the scrape requests. This could be set through labels using such format `__header_%s__`

As an example, I have a service to scrape behind docker swarm, it works correctly using the external url as long as I have 1 replica. The moment I start using multiple replicas, I'm forced to scrape each individual replica by their ip as the load balancer will receive conflicting results as the /metrics would fall on one or the other replica. Each replica has different metric sets. 

The issue is that the http handlers have routes defined on the application level based on a selected database based on the host url. In other words, a.example.com and b.example.com points to the same webservice but may use different routes based on the database selected by a.example.com or b.example.com. So in one case, /metrics may exist and /metrics may not exist for the other.

When the database can't be chosen, it will simply return a 404 errors. As prometheus is bypassing the loadbalancer and getting the resource by ip instead of by host, the applications server doesn't receive a proper host header and simply reject the requests. 

Having custom http headers would enable other use case such as custom authentication methods using custom http header formats.

**Comment by brian-brazil** [comment] 2019-12-31 20:44
Dupe of #1724

In this case the issue sounds like your applications not being able to serve /metrics on IP Host headers, which you'd need anyway for debugging.

**Closed by brian-brazil** 2019-12-31 20:44 UTC
