### ISSUE TITLE
Prometheus stop timeout

### ISSUE THREAD

**Issue by wlay** [prometheus/prometheus#5397] opened 2019-03-22 11:16 UTC
## Proposal
**Use case. Why is this important?**
Prometheus process can't exit gracefully.

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**
sudo systemctl stop prometheus.service
**What did you expect to see?**
The process exit gracefully. And show "See you next time!"
**What did you see instead? Under which circumstances?**
The process didn't show the message "See you next time!" until it timeout.

**Environment**
centos
* System information:

	Linux 3.10.0-514.el7.x86_64 x86_64

* Prometheus version:

	2.7.1
* Alertmanager version:

	didn't deploy it.

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
prometheus log:
level=warn ts=2019-03-22T08:35:46.127409912Z caller=main.go:464 msg="Received SIGTERM, exiting gracefully..."
level=info ts=2019-03-22T08:35:46.127525054Z caller=main.go:489 msg="Stopping scrape discovery manager..."
level=info ts=2019-03-22T08:35:46.127559332Z caller=main.go:503 msg="Stopping notify discovery manager..."
level=info ts=2019-03-22T08:35:46.127573097Z caller=main.go:525 msg="Stopping scrape manager..."
level=info ts=2019-03-22T08:35:46.127571547Z caller=main.go:485 msg="Scrape discovery manager stopped"
level=info ts=2019-03-22T08:35:46.127623261Z caller=main.go:499 msg="Notify discovery manager stopped"
level=info ts=2019-03-22T08:35:50.821469229Z caller=manager.go:745 component="rule manager" msg="Stopping rule manager..."
level=info ts=2019-03-22T08:35:50.821504484Z caller=main.go:519 msg="Scrape manager stopped"
level=info ts=2019-03-22T08:35:50.821581696Z caller=manager.go:751 component="rule manager" msg="Rule manager stopped"
level=info ts=2019-03-22T08:35:50.834491455Z caller=queue_manager.go:259 component=remote queue="0:https://xxxx/write?
db=xxxxx&rp=autogen&precision=s" msg="Stopping remote storage..."
level=info ts=2019-03-22T08:35:50.834598573Z caller=queue_manager.go:267 component=remote queue="0:https://xxxx/write?
db=xxxxx&rp=autogen&precision=s" msg="Remote storage stopped."
level=info ts=2019-03-22T08:35:50.858201061Z caller=notifier.go:521 component=notifier msg="Stopping notification manager..."
level=info ts=2019-03-22T08:35:50.858226827Z caller=main.go:679 msg="Notifier manager stopped"

/var/log/message:
Mar 22 08:37:16 xxxx systemd: prometheus.service stop-final-sigterm timed out. Killing.
Mar 22 08:37:16 xxxx systemd: Unit prometheus.service entered failed state.
Mar 22 08:37:16 xxxx systemd: Triggering OnFailure= dependencies of prometheus.service.
```

**Comment by simonpasquier** [comment] 2019-03-22 16:22
Did you configure any specific [`TimeoutStopSec`](https://www.freedesktop.org/software/systemd/man/systemd.service.html#TimeoutStopSec=) value? Have you tried starting and stopping without systemd and confirm that the process never stops?

**Comment by wlay** [comment] 2019-03-25 01:46
Hi @simonpasquier 
I didn't configure the "TimeoutStopSec".
This problem is not repeated every time. Is there any good way to confirm this problem from your point of view?

**Comment by simonpasquier** [comment] 2019-03-25 11:35
> This problem is not repeated every time. 

In that case, I would recommend setting a `TimeoutStopSec` value large enough to accomodate your setup. You might want to start/stop the process a few times manually (eg without systemd), measure how long it takes to exit effectively and multiply this number by a few.

**Comment by wlay** [comment] 2019-03-28 10:18
Hi @simonpasquier 
We do some tests. When the process stop timeout, the "file discovery manager" will not stop.
Normal exit, there will be the below msg: 
 ```
level=debug ts=2019-03-28T10:02:00.301222758Z caller=file.go:282 component="discovery manager scrape" discovery=file msg="Stopping file discovery..." paths="[federation/xxx1.json federation/xxx2.json federation/xxx3.json federation/xxx4.json federation/xxx5.json federation/xxx6.json federation/xxx7.json federation/xxx8.json federation/xxx9.json federation/xxx10.json federation/xxx11.json federation/xxx12.json federation/xxx13.json federation/xxx14.json federation/xxx15.json federation/xxx16.json federation/xxx17.json federation/xxx18.json federation/af_prod_node_exporter_scheduler_host.json federation/xxx19.json]"
level=debug ts=2019-03-28T10:02:00.301215991Z caller=file.go:282 component="discovery manager scrape" discovery=file msg="Stopping file discovery..." paths="[federation/xxxx1.json federation/xxxx2.json federation/xxxx3.json federation/xxxx4.json federation/xxxx5.json federation/xxxx6.json federation/xxxx7.json federation/xxxx8.json]"
level=info ts=2019-03-28T10:02:00.301255751Z caller=main.go:499 msg="Notify discovery manager stopped"
level=debug ts=2019-03-28T10:02:00.30137289Z caller=file.go:305 component="discovery manager scrape" discovery=file msg="File discovery stopped"
level=debug ts=2019-03-28T10:02:00.302180229Z caller=file.go:305 component="discovery manager scrape" discovery=file msg="File discovery stopped"

**Comment by simonpasquier** [comment] 2019-03-29 09:56
@wlay I received a comment from you in my inbox which mentioned that the issue might be with the file SD not stopping properly. Is this correct?

**Comment by wlay** [comment] 2019-04-02 02:24
@simonpasquier I made a mistake about the file SD not stopping. Please ignore it. 
I will continue to focus on this problem. If there is any clue, i will update it here in time.
Very sorry for that.

**Comment by wlay** [comment] 2019-04-28 08:57
I got this logs, when the prometheus exit timeout.
```
level=warn ts=2019-04-28T08:42:15.025687889Z caller=main.go:464 msg="Received SIGTERM, exiting gracefully..."
level=info ts=2019-04-28T08:42:15.025816183Z caller=main.go:489 msg="Stopping scrape discovery manager..."
level=info ts=2019-04-28T08:42:15.025840383Z caller=main.go:503 msg="Stopping notify discovery manager..."
level=info ts=2019-04-28T08:42:15.025853057Z caller=main.go:525 msg="Stopping scrape manager..."
level=info ts=2019-04-28T08:42:15.025856401Z caller=main.go:485 msg="Scrape discovery manager stopped"
level=info ts=2019-04-28T08:42:15.025884453Z caller=main.go:499 msg="Notify discovery manager stopped"
level=debug ts=2019-04-28T08:42:15.032296939Z caller=scrape.go:825 component="scrape manager" scrape_pool=af_nyc_system target="http://xxx:9090/federate?match%5B%5D=%7Bjob%3D~%22.%2B%22%7D" msg="Scrape failed" err="Get http://xxx:9090/federate?match%5B%5D=%7Bjob%3D~%22.%2B%22%7D: context canceled"
level=info ts=2019-04-28T08:42:15.052681805Z caller=manager.go:745 component="rule manager" msg="Stopping rule manager..."
level=info ts=2019-04-28T08:42:15.052734756Z caller=manager.go:751 component="rule manager" msg="Rule manager stopped"
level=info ts=2019-04-28T08:42:15.052715149Z caller=main.go:519 msg="Scrape manager stopped"
level=info ts=2019-04-28T08:42:15.06105633Z caller=notifier.go:521 component=notifier msg="Stopping notification manager..."
level=info ts=2019-04-28T08:42:15.061096139Z caller=main.go:679 msg="Notifier manager stopped"

**Comment by gouthamve** [comment] 2020-04-27 14:13
We've gone through this issue in our bugscrub and decided to close it as it is a very old version and we couldn't reproduce it. It also looks like a duplicate of #6747

**Closed by gouthamve** 2020-04-27 14:13 UTC
Labels: kind/more-info-needed
