### ISSUE TITLE
Prometheus agent mode does not send the samples which were not sent when restarted

### ISSUE THREAD

**Issue by PoojaSapaliga** [prometheus/prometheus#13542] opened 2024-02-06 05:41 UTC
### What did you do?

Hi, I am deploying prometheus in agent mode where it is remote writing to AWS prometheus with persistance enabled. If there are connectivity issues to remote write, prometheus will send the data once connectivity is back. But if the prometheus restarts during this scenario(disconnected mode), prometheus backs up all the wal files under the /data-agent/wal folder but does not send this  data to remote write. Is there any offset for the wal files that prometheus maintains which is lost after the restart? 

### What did you expect to see?

Time  series data collected duing disconnected mode should be sent to remote write  when it is back to online even if prometheus restarts.

### What did you see instead? Under which circumstances?

Data collected during the disconnected time persiod is not sent to remote write endpoint by prometheus but it backs up all this wal files after the restart

### Prometheus version

```text
2.44.0
```

**Comment by cstyan** [comment] 2024-02-06 17:35
Closing as a duplicate, since we have an issue already to track the feature needed to solve this. What you're describing is unfortunately by design currently, and not prometheus agent mode specific, until https://github.com/prometheus/prometheus/issues/8809 is implemented.

**Closed by cstyan** 2024-02-06 17:35 UTC
