### ISSUE TITLE
Prometheus module dependency resolution

### ISSUE THREAD

**Issue by idefixcert** [prometheus/prometheus#6884] opened 2020-02-27 07:48 UTC
**What did you do?**
I am in a go module project and just said:
`go get github.com/prometheus/prometheus/pkg/rulefmt`

**What did you expect to see?**
I expect do get the pkg.

**What did you see instead? Under which circumstances?**
```
> go version
go version go1.13.1 darwin/amd64

> go get github.com/prometheus/prometheus/pkg/rulefmt
go: finding github.com/prometheus/prometheus/pkg latest
go: finding github.com/prometheus/prometheus/pkg/rulefmt latest
go: downloading golang.org/x/sys v0.0.0-20191220142924-d4481acd189f
go: finding github.com/prometheus/tsdb/labels latest
go: extracting golang.org/x/sys v0.0.0-20191220142924-d4481acd189f
# github.com/prometheus/prometheus/storage/tsdb
/Users/chris/go/pkg/mod/github.com/prometheus/prometheus@v2.5.0+incompatible/storage/tsdb/tsdb.go:144:3: unknown field 'WALFlushInterval' in struct literal of type tsdb.Options
```

**Environment**

```
> go version
go version go1.13.1 darwin/amd64
```

* My thoughts

I think the Problem seems to be that I only get version v2.5.0.
But even If I give a version nummer it does not work.
```go list -u -m github.com/prometheus/prometheus```
gives me as the latest version V2.5.0

I figured out, that I could use:
```
go get github.com/prometheus/prometheus/pkg/rulefmt@master
```

but I think that's not a good idea.

**Comment by roidelapluie** [comment] 2020-02-27 07:57
Thanks for the report. Duplicate of #6048. See the discussions there.

**Closed by roidelapluie** 2020-02-27 07:57 UTC
Labels: kind/bug
