### ISSUE TITLE
prometheus server do not work if remote_read server is stop responding

### ISSUE THREAD

**Issue by dmitriy-lukyanchikov** [prometheus/prometheus#3520] opened 2017-11-29 15:33 UTC
**What did you do?**

Install two Prometheus 2.0.0 servers
configure on one remote_read to another
stop server that configured remote_read from

**What did you expect to see?**

I expect to see local metrics that stored on Prometheus server instead of error

**What did you see instead? Under which circumstances?**

i see 

`Error executing query: error sending request: Post http://[remote_read server ip]:9090/api/v1/read: dial tcp 159.89.26.71:9090: getsockopt: connection refused`

**Environment**

2 Prometheus servers on one remote_read to another

* System information:

	Linux 4.4.0-101-generic x86_64 on both servers

* Prometheus version:

	insert output of `prometheus --version` here

* Prometheus configuration file:
```
remote_read:
- url: http://[remote_read server ip]:9090/api/v1/read

```

**Comment by brian-brazil** [comment] 2017-11-29 15:35
Dupe of #2573

**Closed by brian-brazil** 2017-11-29 15:35 UTC
