### ISSUE TITLE
prometheus fails to build on armhf due to test panic: mmap, size 134217728: cannot allocate memory

### ISSUE THREAD

**Issue by bdrung** [prometheus/prometheus#10869] opened 2022-06-15 09:00 UTC
### What did you do?

Building prometheus 2.33.5+ds1-2 on Ubuntu 22.10 (kinetic) fails to build on armhf due to test failure. See https://launchpad.net/ubuntu/+source/prometheus

### What did you expect to see?

Tests that need more memory than the system provides should be skipped.

### What did you see instead? Under which circumstances?

```
=== RUN   TestRulesUnitTest/Long_evaluation_interval
Unit Testing:  ./testdata/long-period.yml
panic: mmap, size 134217728: cannot allocate memory

goroutine 5344 [running]:
github.com/prometheus/prometheus/tsdb.handleChunkWriteError({0x18b4030, 0x4dac0b0})
	/<<PKGBUILDDIR>>/.build/src/github.com/prometheus/prometheus/tsdb/head_append.go:585 +0x88
github.com/prometheus/prometheus/tsdb/chunks.(*chunkWriteQueue).processJob(0x4e93320, {0x1, 0x1, 0x3d1aa49a000, 0x3d1aa49a000, {0x18baa9c, 0x4d42630}, 0x1900000008, 0x164feb4})
	/<<PKGBUILDDIR>>/.build/src/github.com/prometheus/prometheus/tsdb/chunks/chunk_write_queue.go:106 +0xb4
github.com/prometheus/prometheus/tsdb/chunks.(*chunkWriteQueue).start.func1()
	/<<PKGBUILDDIR>>/.build/src/github.com/prometheus/prometheus/tsdb/chunks/chunk_write_queue.go:94 +0xa8
created by github.com/prometheus/prometheus/tsdb/chunks.(*chunkWriteQueue).start
	/<<PKGBUILDDIR>>/.build/src/github.com/prometheus/prometheus/tsdb/chunks/chunk_write_queue.go:90 +0x74
FAIL	github.com/prometheus/prometheus/cmd/promtool	13.307s
```

Full log: https://launchpadlibrarian.net/606855675/buildlog_ubuntu-kinetic-armhf.prometheus_2.33.5+ds1-2_BUILDING.txt.gz

Bug-Ubuntu: https://launchpad.net/bugs/1978803

**Comment by codesome** [comment] 2022-06-24 06:27
Does it just need more memory? The error is exactly for 128MiB and I don't think m-map tries to allocate that much actual memory upfront but might be virtual memory. Does the test environment have any limits on the memory?

**Comment by roidelapluie** [comment] 2022-09-05 09:55
How could we check that? I feel like this is somehow not super easy to detect, and we still want all the TSDB tests to pass if you build Prometheus for a specific architecture anyway.

**Comment by dswarbrick** [comment] 2022-10-04 19:12
This sounds like basically the same issue as #8661, and is likely to occur on any 32-bit arch, i.e. if processes are limited to 4 GiB memory or less. IIRC, 32-bit Linux kernels limit userspace memory allocations to approximately 3 GiB, reserving the remainder for the kernel.

It may be possible to conveniently reproduce this on a 64-bit host (e.g. amd64) by building / testing with `GOARCH=386` (which would also catch a plethora of other 64-bit assumptions that have recently crept into the code). Bear in mind however that 32-bit processes running on a 64-bit kernel can in fact use a full 4 GiB address space, so it won't be a perfect reproduction of a true 32-bit environment.

**Comment by dswarbrick** [comment] 2022-10-08 14:19
FWIW, I'm not able to get the `TestRulesUnitTest/Long_evaluation_interval` test to fail in a resource-constrained systemd slice with `GOARCH=386`, e.g.:
```
$ systemd-run --scope -p MemoryMax=1G -p MemorySwapMax=0 -E GOARCH=386 go test -count=1 ./...
```
(_other_, non-32-bit-safe tests fail, but I don't see the mmap ENOMEM error arise).

@bdrung Do you think it's possible that the armhf test environment is hitting `vm.max_map_count` limits?

**Comment by bdrung** [comment] 2022-10-11 19:14
How can I check if the test hits `vm.max_map_count`? I could run the autopkgtests against a PPA upload.

**Comment by dswarbrick** [comment] 2022-11-20 10:30
FWIW, I have also had to disable the following tests / architectures for the same reason as mentioned by the OP:
- TestHead_WALMultiRef (arm)
- TestDeletedSamplesAndSeriesStillInWALAfterCheckpoint (arm)
- TestHeadReadWriterRepair (386, arm)
- TestQueryHistogramFromBlocksWithCompaction (mipsle)

Overall it seems that there is a growing trend of tests which fail on 32-bit archs.

**Comment by dswarbrick** [comment] 2023-01-09 03:54
For the record, `TestRulesUnitTest/Long_evaluation_interval` now consistently fails for i386 on https://tests.reproducible-builds.org/debian/rb-pkg/unstable/i386/prometheus.html, essentially for the reasons already mentioned in this ticket.
```
=== RUN   TestRulesUnitTest/Long_evaluation_interval
Unit Testing:  ./testdata/long-period.yml
--- FAIL: TestRulesUnitTest (5.01s)
    --- PASS: TestRulesUnitTest/Passing_Unit_Tests (3.13s)
    --- FAIL: TestRulesUnitTest/Long_evaluation_interval (1.88s)
panic: mmap, size 134217728: cannot allocate memory
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x865de1e]
```

**Comment by beorn7** [comment] 2024-09-03 12:17
Hello from the bug scrub.

This particular issue is quite old by now, so we will close it as it is just one symptom of a bigger trend of many tests that fail on all or some 32-bit architectures.

First of all, the project has to come to terms what level of support it is willing and able to provide for 32-bit architectures. Based on that, we have to act and (for example, under the assumption that we _do_ want to provide some level of support), we have to fix all the currently failing tests.

This has been added as a agenda item for the dev summit already (based on similar issues in the recent past).

**Closed by beorn7** 2024-09-03 12:17 UTC
