### ISSUE TITLE
Making joins simpler in PromQL

### ISSUE THREAD

**Issue by RichiH** [prometheus/prometheus#3094] opened 2017-08-20 09:58 UTC
At yesterday's dev summit, and as part of the discussion around https://github.com/prometheus/snmp_exporter/issues/180 , @brian-brazil also suggested making joins easier to write.

This issue is to document possible changes / enhancements to PromQL.

**Comment by brian-brazil** [comment] 2017-08-20 22:06
I've pondered this previously, and haven't been able to come up with anything. Tooling on the Grafana end is likely going to be a more fruitful approach.

**Comment by matthiasr** [comment] 2017-08-21 14:18
## Yes, we need this

That it is hard does not mean we don't need it. Solving this in Grafana is not enough, I am frequently missing this both during exploration and in alerting. Having to construct long instance match regexes is not a solution, it takes a long time to assemble, makes the queries completely unreadable, and for large lists plain fails.

## Mockup (proposal)

I'm imagining a `join on()` operator that would work on time series like

```
metric1{thing="name1",some_property="an_endpoint"} 123
thing_info{thing="name1", thang="name2", other_property="a_label"} 1
thang_info{thang="name2, third_property="a_role"} 1
```

by matching on the labels in the on clause, taking the remaining labels from _both_ sides (favouring left in case of conflict) and the value from the _left_ side:

* `metric1 join on(thing) thing_info` => `metric1{thing="name1", some_property="an_endpoint", thang="name2", other_property="a_label"}`
* `metric1 join on(thing) thing_info join on(thang)` => `metric1{thing="name1", some_property="an_endpoint", thang="name2", other_property="a_label", , third_property="a_role"}

## Open questions

What would the meaning of group_left / group_right be in this context? They could of course just be illegal.

How would I limit which labels get joined? Do I need this capability? It could be emulated with label_replace.

## Real-world use-case

The above is distilled from the following use case: Given the request latency of an instance in Kubernetes, `kube_pod_info` which links the pod to the node, and `kube_node_info` which tells me the kernel version of each node, what is the 99th percentile latency for different kernel versions? By path and method?

**Comment by brian-brazil** [comment] 2017-08-21 14:40
> Having to construct long instance match regexes is not a solution, it takes a long time to assemble, makes the queries completely unreadable, and for large lists plain fails.

I'm not seeing how this is relevant to this issue.

> taking the remaining labels from both sides (favouring left in case of conflict) and the value from the left side:

I'm not particularly in favour of such a joining, as the nature of info metrics is that they contain an unknown and changing set of label names over time. Thus taking all the labels from the left means you no longer know what the labels of the output are, and thus breaks `without`.

> How would I limit which labels get joined? Do I need this capability?

That's what group_left already does, and this capability is essential for semantic sanity.

> Given the request latency of an instance in Kubernetes, kube_pod_info which links the pod to the node, and kube_node_info which tells me the kernel version of each node, what is the 99th percentile latency for different kernel versions? By path and method?

I don't see how the proposed change makes this significantly easier than what we have already, in fact it's likely to cause problems due to also pulling in all the other labels.

**Comment by matthiasr** [comment] 2017-08-28 10:10
> I'm not seeing how this is relevant to this issue.

It's how we work around joins not being simple.

> you no longer know what the labels of the output are, and thus breaks without.

Curious, I use `without` exactly for the case where I don't know what the exact label set is.

> I don't see how the proposed change makes this significantly easier than what we have already

Ah, so this _is_ possible already? How?

**Comment by brian-brazil** [comment] 2017-08-28 10:19
> It's how we work around joins not being simple.

Can you explain exactly what you're doing right now? Selectors are orthogonal to joins.

> Curious, I use without exactly for the case where I don't know what the exact label set is.

Thus why we need to be careful about keeping the set of in-play labels sufficiently knowable. Pulling in all labels from both sides of an expression where one side is an _info doesn't allow for that.

> Ah, so this is possible already? How?

I'd need to see the exact metrics, but it'd be something like `a * on (pod) group_left(kernel_version) (pod_info * on (node) group_left(kernel_version) node_info)`

**Comment by matthiasr** [comment] 2017-08-29 09:14
> Can you explain exactly what you're doing right now? Selectors are orthogonal to joins.

Out of band, we collect lists of hostnames for whatever we're interested in, and concatenate them into `instance=~"(host1|host2|host3|…).*"`. It's what Grafana does, but it's really awkward for exploration.

**Comment by brian-brazil** [comment] 2017-08-29 09:28
That'd be pretty awkward alright.

**Comment by hanikesn** [comment] 2017-12-13 17:07
We're also having trouble with the current `group_left` behavior with regard to labels. E.g. we want to aggregate container cpu usage in our kubernetes cluster by labels placed on the pods. The problem is we don't know beforehand what labels our users will put on the pods. This works fine, when we can use `kube_pod_info` as the left hand and join with per pod metrics, but breaks when we want to get metric per service per container aggregation.

**Comment by brian-brazil** [comment] 2017-12-14 15:27
If you don't know the names of the labels you want to aggregate by, you're going to find it fairly difficult to do anything.

**Comment by discordianfish** [comment] 2021-01-29 09:34
I'd love to revisit this eventually. I think how hard it is to do joins is the most awkward thing about the prometheus experience. It takes a few hours to understand the basic query language but even I after years still can't come up with a simple join without referring to examples..

**Comment by roidelapluie** [comment] 2021-01-29 09:37
> I'd love to revisit this eventually. I think how hard it is to do joins is the most awkward thing about the prometheus experience. It takes a few hours to understand the basic query language but even I after years still can't come up with a simple join without referring to examples..

Have you read the design doc?

**Comment by roidelapluie** [comment] 2021-01-29 09:38
The design doc is actually https://docs.google.com/document/d/1KWh7TNt66zMqn6_yBytZ_n_KEXOhHX0Qmmv2JLssy0s/edit?usp=sharing and the issue is #2204

**Comment by discordianfish** [comment] 2021-01-29 09:40
@roidelapluie Ah! Wasn't aware of that. Will review it. Should we close this in favor of #2204? I think this here is a subset of what's being discussed, right?

**Comment by roidelapluie** [comment] 2021-01-29 15:02
I'll let @RichiH close it if this fits the original issue.

**Comment by discordianfish** [comment] 2021-02-01 09:40
Proposal looks great btw. Not sure if we can do even more but definitely a great direction!

**Comment by sirkubax** [comment] 2021-04-19 10:52
I'd comment here, as I feel like we are missing regex in many places
Any chance of adding a regex to label queries ?

example presented:
https://github.com/prometheus/prometheus/issues/2204#issuecomment-822374059

**Comment by beorn7** [comment] 2024-02-20 11:37
A relevant idea: https://docs.google.com/document/d/1ebhGNLs3uhdeprJCullM-ywA9iMRDg_mmnuFAQCloqY/edit

**Comment by krajorama** [comment] 2024-02-20 11:40
Welcome from the bug scrub: this issue seems too generic for completion, closing in favor of #2204, please continue there or open more specific requirement.

**Closed by krajorama** 2024-02-20 11:40 UTC
Labels: kind/enhancement, priority/Pmaybe, component/promql
