### ISSUE TITLE
Target Scraped Twice Race Condition - Possibly Due to Reload

### ISSUE THREAD

**Issue by vsliouniaev** [prometheus/prometheus#6894] opened 2020-02-28 12:52 UTC
**What did you do?**
- Reloaded the prometheus configuration file by using the http endpoint
- It is possible that there were some configuration changes related to scrape targets but I am not able to provide details as this is a derived file that is heavily automated and does not contain a log of changes made. I expect this to not be the case because the relevant configuration was not being modified at the time when this happened

**What did you expect to see?**
- Continued steady-state operation

**What did you see instead? Under which circumstances?**
1. Immediately after a reload, a target had two separate data samples with an almost identical timestamp with a tiny difference in some of the values
2. The data gathered first ends up with a later timestamp than the data gathered second
3. A `rate` calculated based on the data produces a massive spike because prometheus considers the second sample, which has lower counter values, to have undergone a reset

time | value | time change | value change
-- | -- | -- | --
1582378204.022 | 1183407.023 |   |  
1582378234.022 | 1183412.101 | 30.000 | 5.078
1582378264.022 | 1183412.767 | 30.000 | 0.666
1582378294.032 | 1183419.399 | 30.010 | 6.632
*1582378294.033(13:31:34.033)* | *1183419.398* | *0.001* | *-0.001*
1582378324.122 | 1183424.997 | 30.089 | 5.599
1582378354.032 | 1183430.620 | 29.910 | 5.623

**Environment**

* System information:
`Linux 5.0.0-1032-azure x86_64`

* Prometheus version:
```
prometheus, version 2.15.2 (branch: HEAD, revision: d9613e5c466c6e9de548c4dae1b9aabf9aaf7c57)
  build user:       root@688433cf4ff7
  build date:       20200106-14:50:51
  go version:       go1.13.5
```

* Prometheus configuration file:
I'd rather not include the entire configuration file since it is extremely large and does not seem relevant. There are 40 `jobs` and 565 `instances`

```
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
  external_labels:
    prometheus: infrastructure
    prometheus_replica: "0"
alerting:
  alert_relabel_configs:
  - separator: ;
    regex: prometheus_replica
    replacement: $1
    action: labeldrop
  alertmanagers:
  - kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - monitoring
    scheme: http
    path_prefix: /
    timeout: 10s
    api_version: v1
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      separator: ;
      regex: prom-op-prometheus-operato-alertmanager
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_endpoint_port_name]
      separator: ;
      regex: web
      replacement: $1
      action: keep
rule_files:
- /etc/prometheus/rules/prometheus-prom-op-prometheus-operato-prometheus-rulefiles-0/*.yaml
```

* Logs:
```
{"caller":"main.go:762","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Completed loading of configuration file","ts":"2020-02-22T13:28:27.884Z"}
{"caller":"manager.go:566","component":"rule manager","group":"infrastructure-remote-metrics-remote-write-metrics","level":"warn","msg":"Error on ingesting results from rule evaluation with different value but same timestamp","numDropped":2,"ts":"2020-02-22T13:28:37.523Z"}
{"caller":"manager.go:566","component":"rule manager","group":"infrastructure-remote-metrics-remote-write-metrics","level":"warn","msg":"Error on ingesting results from rule evaluation with different value but same timestamp","numDropped":2,"ts":"2020-02-22T13:28:37.653Z"}
{"caller":"manager.go:563","component":"rule manager","group":"kube-apiserver.rules","level":"warn","msg":"Error on ingesting out-of-order result from rule evaluation","numDropped":603,"ts":"2020-02-22T13:31:03.237Z"}
{"caller":"main.go:734","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Loading configuration file","ts":"2020-02-22T13:31:27.322Z"}
{"caller":"kubernetes.go:190","component":"discovery manager scrape","discovery":"k8s","level":"info","msg":"Using pod service account via in-cluster config","ts":"2020-02-22T13:31:27.614Z"}
{"caller":"kubernetes.go:190","component":"discovery manager scrape","discovery":"k8s","level":"info","msg":"Using pod service account via in-cluster config","ts":"2020-02-22T13:31:27.616Z"}
{"caller":"kubernetes.go:190","component":"discovery manager scrape","discovery":"k8s","level":"info","msg":"Using pod service account via in-cluster config","ts":"2020-02-22T13:31:27.617Z"}
{"caller":"kubernetes.go:190","component":"discovery manager scrape","discovery":"k8s","level":"info","msg":"Using pod service account via in-cluster config","ts":"2020-02-22T13:31:27.618Z"}
{"caller":"kubernetes.go:190","component":"discovery manager scrape","discovery":"k8s","level":"info","msg":"Using pod service account via in-cluster config","ts":"2020-02-22T13:31:27.619Z"}
{"caller":"kubernetes.go:190","component":"discovery manager scrape","discovery":"k8s","level":"info","msg":"Using pod service account via in-cluster config","ts":"2020-02-22T13:31:27.620Z"}
{"caller":"kubernetes.go:190","component":"discovery manager scrape","discovery":"k8s","level":"info","msg":"Using pod service account via in-cluster config","ts":"2020-02-22T13:31:27.621Z"}
{"caller":"kubernetes.go:190","component":"discovery manager scrape","discovery":"k8s","level":"info","msg":"Using pod service account via in-cluster config","ts":"2020-02-22T13:31:27.623Z"}
{"caller":"kubernetes.go:190","component":"discovery manager scrape","discovery":"k8s","level":"info","msg":"Using pod service account via in-cluster config","ts":"2020-02-22T13:31:27.624Z"}
{"caller":"kubernetes.go:190","component":"discovery manager scrape","discovery":"k8s","level":"info","msg":"Using pod service account via in-cluster config","ts":"2020-02-22T13:31:27.625Z"}
{"caller":"kubernetes.go:190","component":"discovery manager scrape","discovery":"k8s","level":"info","msg":"Using pod service account via in-cluster config","ts":"2020-02-22T13:31:27.626Z"}
{"caller":"kubernetes.go:190","component":"discovery manager scrape","discovery":"k8s","level":"info","msg":"Using pod service account via in-cluster config","ts":"2020-02-22T13:31:27.627Z"}
{"caller":"kubernetes.go:190","component":"discovery manager scrape","discovery":"k8s","level":"info","msg":"Using pod service account via in-cluster config","ts":"2020-02-22T13:31:27.629Z"}
{"caller":"kubernetes.go:190","component":"discovery manager scrape","discovery":"k8s","level":"info","msg":"Using pod service account via in-cluster config","ts":"2020-02-22T13:31:27.630Z"}
{"caller":"kubernetes.go:190","component":"discovery manager scrape","discovery":"k8s","level":"info","msg":"Using pod service account via in-cluster config","ts":"2020-02-22T13:31:27.632Z"}
{"caller":"kubernetes.go:190","component":"discovery manager notify","discovery":"k8s","level":"info","msg":"Using pod service account via in-cluster config","ts":"2020-02-22T13:31:27.633Z"}
{"caller":"main.go:762","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Completed loading of configuration file","ts":"2020-02-22T13:31:27.898Z"}
{"caller":"manager.go:563","component":"rule manager","group":"kube-apiserver.rules","level":"warn","msg":"Error on ingesting out-of-order result from rule evaluation","numDropped":603,"ts":"2020-02-22T13:34:03.863Z"}
{"caller":"main.go:734","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Loading configuration file","ts":"2020-02-22T13:34:27.322Z"}
{"caller":"kubernetes.go:190","component":"discovery manager scrape","discovery":"k8s","level":"info","msg":"Using pod service account via in-cluster config","ts":"2020-02-22T13:34:27.633Z"}
```

**Speculation**
I would expect this to be related to a configuration reload - otherwise we would be seeing this more frequently.

I do not know the prometheus internals to a sufficient degree to know, but I suspect that there is a channel for scrapes that need to be handled that is populated based on the configuration in memory. The same target ended up being added to this channel after a reload, which caused the double-scrape. I don't know what logic exists in Prometheus to handle not adding the same target twice, but whatever happened was either not caught by it due to a bug in the reload logic, or by design because the target configuration was modified.

**Comment by roidelapluie** [comment] 2020-02-28 13:18
What was changed during the reload?

**Comment by vsliouniaev** [comment] 2020-02-28 13:44
> What was changed during the reload?

It was most likely some targets. The block that I posted above was not modified. Unfortunately I'm not able to provide the full diff between the configurations because the config is derived through numerous automation components and I don't have a log of the changes made between those two times.

> Can we get the raw http requests/response you use to make the table with timestamp/value?

This was just the prometheus UI that I used and reformatted into a table:
```
query:
  node_disk_io_time_seconds_total{job="m3",m3_role="dbnode",m3_cluster="scus-prod", instance="10.12.42.175:9100", device="sdc"}[5m]

result: 
  node_disk_io_time_seconds_total{device="sdc",endpoint="node-exporter",instance="10.12.42.175:9100",isolation_group="2",job="m3",m3_cluster="scus-prod",m3_profile="prod-hosts",m3_role="dbnode",namespace="m3-monitor",node="10.12.42.175",service="prod-hosts-scus-prod-dbnode-2"}
  1183407.023 @1582378204.022
  1183412.101 @1582378234.022
  1183412.767 @1582378264.022
  1183419.399 @1582378294.032
  1183419.398 @1582378294.033
  1183424.997 @1582378324.122
  1183430.62 @1582378354.032
  1183431.365 @1582378384.032
  1183440.6670000001 @1582378414.032
  1183442.548 @1582378444.032
  1183448.746 @1582378474.223
```

**Comment by roidelapluie** [comment] 2020-02-28 15:42
What do the logs look like around that time?

**Comment by vsliouniaev** [comment] 2020-02-28 17:28
> What do the logs look like around that time?

Logs are included

**Comment by roidelapluie** [comment] 2020-05-15 22:37
https://github.com/prometheus/prometheus/blob/6e19c4697d8f37e739fd8278b3ec6909751019a7/scrape/scrape.go#L389-L453

In this function, we first start new scrapes before stopping old scrapes.

The hash might change because at reload we start and stop service discovery.

Then, we have started a new scrape with the old labels while a scrape with the new labels was already schedules.

Now that can explain why two scrapes.

We now have to understand why the scrape started later could have got metrics from before.

Mayve b := sl.buffers.Get(sl.lastScrapeSize).([]byte) in did take more time on the scrape started before?

https://github.com/prometheus/prometheus/blob/6e19c4697d8f37e739fd8278b3ec6909751019a7/scrape/scrape.go#L941-L948

**Comment by roidelapluie** [comment] 2020-05-15 22:40
My explanation would work if:

```
  1183419.399 @1582378294.032 => OLD SCRAPE, takes time to get buffer, set metric targetIntervallenght, then only start the request at e.g. 0.034
  1183419.398 @1582378294.033 => NEW SCRAPE, buffer = 0, no metric, targetIntervalLength, so faster
```

**Comment by roidelapluie** [comment] 2020-05-15 22:41
That is fairly nice race which will not be easy to solve as we probably don't want for old scrapes to end before starting new ones.

**Comment by roidelapluie** [comment] 2020-05-15 22:45
https://github.com/prometheus/prometheus/commit/5fba810452f1695843484642d2e384d8ef5e8b49 ?

**Comment by roidelapluie** [comment] 2020-05-15 22:55
Moving start seems a better fix. I will propose a PR in the coming days.

**Comment by roidelapluie** [comment] 2020-07-31 18:16
My investigation has ended.

I do believe that the only case where this is possible is when the "scrape job name" has changed but the "job" label is overriden in targets.

The fix would be, when we calculate the offset of the scrapes, to include the "scrape job name", regardless of the  "job" label.

**Comment by roidelapluie** [comment] 2020-07-31 18:20
> Moving start seems a better fix. I will propose a PR in the coming days.

Actually that would not have changed anything, I was wrong.

**Comment by brian-brazil** [comment] 2020-07-31 19:01
> The fix would be, when we calculate the offset of the scrapes, to include the "scrape job name", regardless of the "job" label.

That doesn't seem quite right, as that'd mean that if you were moving things between scrape configs due to a migration that it'd end up with a different offset.

**Comment by tianshuang** [comment] 2022-02-17 10:13
Is this problem solved? We had the same problem with version 2.27.0.

**Comment by beorn7** [comment] 2024-04-09 12:01
Hello from the bug scrub.

Four years later, this is still unresolved, sadly. We need more evidence and more detective work to even reproduce this reliably. We'll leave this open and would welcome more evidence.

**Comment by bwplotka** [comment] 2024-04-16 11:25
Hello from the bug scrub.

Let's close it then for now, we can always reopen. Thanks!

**Closed by bwplotka** 2024-04-16 11:25 UTC
Labels: kind/bug, priority/P2, kind/more-info-needed, component/scraping
