### ISSUE TITLE
/api/v1/series HTTP API does not have dedicated method in Querier interface

### ISSUE THREAD

**Issue by dmitsh** [prometheus/prometheus#5668] opened 2019-06-14 17:44 UTC
## Proposal
**Use case. Why is this important?**
There is no dedicated method for `/api/v1/series` API in the `Querier` interface. It is implemented via `Select` method, similar to `/api/v1/query_range`.
For TSDB it seems not to be a problem, as the `SeriesIterator` is not used by `/api/v1/series`, therefore the samples are not pulled.
However, for `remote_read` operation `Select` returns the entire time-series, including the samples, which are later discarded when serving `/api/v1/series`
This results in significant overhead in traffic and data processing from both Prometheus server and `remote_read` endpoint.

My proposal would be to add a new `Series` method to `Querier` interface.
I understand that this is a breaking change, and I suggest to make it in two steps.
First step is to add the `Series` method and temporarily implement it by calling `Select` under the hood. That will provide backward compatibility, and expose updated `Querier` interface to the community.
Second step would require support of `Series` method by exiting `remote_read` implementations, after which we can replace the temporary implementation.

**Comment by dmitsh** [comment] 2019-06-14 17:52
I have a working prototype, which I would gladly turn into a PR, if there are no objections to this proposal

**Comment by jacksontj** [comment] 2019-06-14 20:12
This seems like a dupe of #4057 (for more context).

**Comment by brian-brazil** [comment] 2019-06-14 20:54
Yip, that's a dupe. I don't believe anyone has worked on this yet, so a PR would be appreciated.

**Closed by brian-brazil** 2019-06-14 20:54 UTC

**Comment by dmitsh** [comment] 2019-06-14 20:57
Thanks @jacksontj , I agree, the idea is the same, although both issues are open, and #4057 has diverted a bit.
I'm totally OK with closing this issue in favor of #4057, but I'd like to continue the discussion.
I understand that there were two proposals:
1. add a flag in `SelectParams` to prevent sample from being sent
2. add a new method in `Querier` to query series metadata

My proposal aligns with the second approach.
I agree that the first approach is simpler but a bit "hacky".
Second approach is cleaner, but introduces a breaking change.

@brian-brazil, any preferences?
