### ISSUE TITLE
Custom graph resolution renders no datapoint

### ISSUE THREAD

**Issue by sebbonnet** [prometheus/prometheus#3028] opened 2017-08-07 11:09 UTC
[NOTICE]: <> (If your question is around usage and not a bug in Prometheus please use: https://groups.google.com/forum/#!forum/prometheus-users)

**What did you do?**

Created 2 graphs in prometheus:
- up{job="cassandra", environment="stage"} leaving the default resolution - the calculated resolution shows 43s
- same graph with a custom resolution of 43s

http://<prometheus-url>/graph?g0.range_input=3h&g0.end_input=2017-08-04+23%3A11&g0.expr=up%7Bjob%3D%22cassandra%22%2C+environment%3D%22stage%22%7D&g0.tab=0&g1.range_input=3h&g1.end_input=2017-08-04+23%3A11&g1.step_input=43&g1.expr=up%7Bjob%3D%22cassandra%22%2C+environment%3D%22stage%22%7D&g1.tab=0

**What did you expect to see?**

Both graphs should display the same data points

**What did you see instead? Under which circumstances?**

The first graph with no custom resolution correctly display the datapoints, while the second graph with the custom resolution (taken from the calculated resolution of first graph) doesn't show any datapoint.

![prometheus-resolution-issue](https://user-images.githubusercontent.com/16104857/29024171-b38b9568-7b68-11e7-8316-1b70fdbeebdf.png)

**Environment**

* System information:

- Client (browser): Linux 4.11.8-200.fc25.x86_64 x86_64, Firefox 54.0 (64-bit) or Google Chrome 61.0.3163.13 (Official Build) dev (64-bit)
-  Server (prometheus):  Linux 4.4.0-89-generic x86_64

* Prometheus version: 
```
gc 1 @0.012s 0%: 0.22+0.72+0.084 ms clock, 0.66+0.23/0.58/0.42+0.25 ms cpu, 4->4->1 MB, 5 MB goal, 16 P
gc 2 @0.021s 1%: 0.051+0.62+0.33 ms clock, 0.36+0.10/1.0/1.1+2.3 ms cpu, 4->4->1 MB, 5 MB goal, 16 P
gc 3 @0.032s 1%: 0.052+0.45+0.11 ms clock, 0.63+0.042/1.0/0.55+1.4 ms cpu, 4->4->1 MB, 5 MB goal, 16 P
gc 4 @0.040s 1%: 0.039+0.75+0.13 ms clock, 0.55+0.10/1.3/0.30+1.8 ms cpu, 4->4->2 MB, 5 MB goal, 16 P
gc 5 @0.049s 2%: 0.012+0.44+0.14 ms clock, 0.19+0.11/1.1/1.5+2.3 ms cpu, 4->4->2 MB, 5 MB goal, 16 P
gc 6 @0.054s 2%: 0.013+0.48+0.15 ms clock, 0.21+0.068/1.4/1.3+2.4 ms cpu, 4->4->2 MB, 5 MB goal, 16 P
gc 7 @0.064s 2%: 0.012+0.87+0.17 ms clock, 0.19+0.11/1.8/1.5+2.7 ms cpu, 5->5->3 MB, 6 MB goal, 16 P
prometheus, version 1.7.1 (branch: master, revision: 3afb3fffa3a29c3de865e1172fb740442e9d0133)
  build user:       root@0aa1b7fc430d
  build date:       20170612-11:44:05
  go version:       go1.8.3
```

**Comment by andrewhowdencom** [comment] 2017-08-07 11:12
Possible dupe of https://github.com/prometheus/prometheus/issues/2827

**Comment by brian-brazil** [comment] 2017-08-21 15:03
Yes, this should already be fixed in master.

**Closed by brian-brazil** 2017-08-21 15:03 UTC
