### ISSUE TITLE
Logical operation query return null when comes two empty vectors in prometheus 2.0

### ISSUE THREAD

**Issue by ZeeShen** [prometheus/prometheus#3603] opened 2017-12-20 03:59 UTC
**What did you do?**
query 
```
up{not_match="1"} or up{not_match="2"}
```

**What did you expect to see?**
return `{"status":"success","data":{"resultType":"vector","result":[]}}`

**What did you see instead? Under which circumstances?**
`{"status":"success","data":{"resultType":"vector","result":null}}`

prometheus graph js running into error `Uncaught TypeError: Cannot read property 'length' of null`

**Environment**

* Prometheus version:
```prometheus, version 2.0.0 (branch: HEAD, revision: 0a74f98628a0463dddc90528220c94de5032d1a0)
  build user:       root@615b82cb36b6
  build date:       20171108-07:11:59
  go version:       go1.9.2
```

Actually, my situation is: I had some old alerting rules that allow users to disable some alerts by setting a `NoAlert` label.
```
node_memory_usage{NoAlert!~".*mem.*",job="nodes"} > 0.95
node_cpu_usage{NoAlert!~".*cpu.*",job="nodes"} > 0.95
```
Because of #3575, prometheus 2.0 doesn't return metrics that `NoAlert` label is not set. So I tried and this `null` situation happened.
```
(node_memory_usage{NoAlert="",job="nodes"})
 or (node_memory_usage{NoAlert!~".*mem.*",job="nodes"})
```
I will put my NoAlert rules in alertmanager as it persists silences on disk now. But this `null` result maybe not a supposed return?

**Comment by brian-brazil** [comment] 2017-12-20 09:41
Dupe of #3515, fix will be in the next release.

**Closed by brian-brazil** 2017-12-20 09:41 UTC
