### ISSUE TITLE
ppc64le image on dockerhub

### ISSUE THREAD

**Issue by vaibhavsood** [prometheus/prometheus#3214] opened 2017-09-25 10:53 UTC
Hi, I'm looking to enable docker containers for packages like prometheus for multiple architectures on dockerhub, starting off with a focus on ppc64le. Wanted to check on the work that will be involved to do that

I have locally been able to successfully test ppc64le changes to the dockerfiles in this repo - changes for enabling additional arch would be minimum. 

Would like to know how a multi-arch image for this can be initiated? The official images have this method for enabling multi-arch : https://github.com/docker-library/official-images#multiple-architectures, however this repo isnt an official image yet. Would the first step be to make this an official image or are there any other ways the dockerhub prometheus image can be enabled for ppc64le?

**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus -version` here

* Alertmanager version:

	insert output of `alertmanager -version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by brian-brazil** [comment] 2017-09-28 08:16
Dupe of #3203

**Closed by brian-brazil** 2017-09-28 08:16 UTC
