### ISSUE TITLE
Prometheus Release 2.2.0  Memory Leak ?

### ISSUE THREAD

**Issue by piaoyu** [prometheus/prometheus#4164] opened 2018-05-15 14:00 UTC
## Proposal
**Use case. Why is this important?**

*Nice to have' is not a good use case :)*

## Bug Report
**What did you do?**
Not thing

**What did you expect to see?**
using memory and releasing it

**What did you see instead? Under which circumstances?**
using memory and not releasing it

**Environment**

* System information:
```
#uname -srm
Linux 3.10.0-327.ali2010.rc7.alios7.x86_64 x86_64
```

* Prometheus version:
```
/prometheus $ prometheus --version
prometheus, version 2.2.1 (branch: HEAD, revision: 94e4a4321761f83207ad11542ee971e7d5220e80)
  build user:       root@sz-bcs-a151
  build date:       20180508-12:56:09
  go version:       go1.9.4
```

* Alertmanager version:
```
/alertmanager $ alertmanager --version
alertmanager, version 0.14.0 (branch: HEAD, revision: 30af4d051b37ce817ea7e35b56c57a0e2ec9dbb0)
  build user:       root@37b6a49ebba9
  build date:       20180213-08:16:42
  go version:       go1.9.2
```

* Prometheus configuration file:
```
# Source: prometheus/templates/server-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-0
  namespace: monitoring
  labels:
    component: "server"
    addonmanager.kubernetes.io/mode: Reconcile
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      #scrape_timeout: 10s
      external_labels:
        zone: sz-uc

    #remote_write:
     #- url: http://remote-storage-adapter-service.monitoring.xxxx.local:9201/write

    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - prometheus-alertmanager-service.monitoring.xxxx.local:9093

    rule_files:
      - "/etc/rules/*.yml"
      - "/etc/rules/alerts"

    scrape_configs:

      - job_name: 'prometheus-server'
        static_configs:
        - targets:
          - xxxx:9090
          - xxxx:9090

      - job_name: 'kubernetes-apiservers'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        static_configs:
        - targets:
          - xxxx:6443
          - xxxx:6443
          - xxxx:6443
        metric_relabel_configs:
          - source_labels: ['__name__']
            regex: 'apiserver_request.*'
            action: keep

      - job_name: 'kubernetes-etcds'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        static_configs:
        - targets:
          - xxxx:2379
          - xxxx:2379
          - xxxx:2379

      - job_name: 'kubernetes-controller-manager'
        scheme: http
        static_configs:
        - targets:
          - xxxx:10252
          - xxxx:10252
          - xxxx:10252

      - job_name: 'kubernetes-kube-scheduler'
        scheme: http
        static_configs:
        - targets:
          - xxxx:10251
          - xxxx:10251
          - xxxx:10251

      - job_name: 'kubernetes-state-metrics'
        scheme: http
        static_configs:
        - targets:
          - prometheus-kube-state-metrics.monitoring.xxxx.local:8085
        metric_relabel_configs:
          - action: labeldrop
            regex: instance
          - action: labeldrop
            regex: container_id
          - action: labeldrop
            regex: image_id
          - source_labels: ['__name__']
            action: drop
            regex: '(kube_persistentvolume_status_phase|kube_pod_status_phase)'

      - job_name: 'kubernetes-nodes'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
        - api_server: xxxx.local:6443
          role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: xxxx.local:6443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}:4194/proxy/metrics
        metric_relabel_configs:
          - source_labels: ['__name__']
            action: keep
            regex: '(container_cpu_usage_seconds_total|container_memory.*|container_network_.*|container_fs.*|machine.*)'
          - source_labels: ['__name__']
            action: drop
            regex: container_memory_failures_total
          - source_labels: [pod_name]
            replacement: "$1"
            target_label: pod
          - action: labeldrop
            regex: id
          - action: labeldrop
            regex: name
          - action: labeldrop
            regex: beta_kubernetes_io_arch
          - action: labeldrop
            regex: beta_kubernetes_io_os

      - job_name: 'kubernetes-cadvisor'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
        - api_server: xxxx.local:6443
          role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: xxxx.local:6443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}:10255/proxy/metrics
        metric_relabel_configs:
          - source_labels: ['__name__']
            regex: kubelet_volume_stats_.*
            action: keep


      - job_name: 'kubernetes-service-endpoints'
        kubernetes_sd_configs:
        - api_server: xxxx.local:6443
          role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
            action: replace
            target_label: __scheme__
            regex: (https?)
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: (.+)(?::\d+);(\d+)
            replacement: ${1}:${2}
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_service_name]
            action: replace
            target_label: kubernetes_name
        metric_relabel_configs:
          - source_labels: ['__name__']
            regex: node_hwmon_.*
            action: drop
          - source_labels: ['__name__']
            regex: http_.*
            action: drop
          - source_labels: ['__name__']
            regex: node_vmstat_.*
            action: drop

      - job_name: 'kubernetes-services'
        metrics_path: /probe
        params:
          module: [http_2xx]
        kubernetes_sd_configs:
        - api_server: xxxx.local:6443
          role: service
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe]
            action: keep
            regex: true
          - source_labels: [__address__]
            target_label: __param_target
          - target_label: __address__
            replacement: blackbox
          - source_labels: [__param_target]
            target_label: instance
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_service_name]
            target_label: kubernetes_name

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - api_server: xxxx.local:6443
          role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: (.+):(?:\d+);(\d+)
            replacement: ${1}:${2}
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
  rules: ""

```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by piaoyu** [comment] 2018-05-15 14:04
```
(pprof) top 20
Showing nodes accounting for 8.79GB, 93.68% of 9.38GB total
Dropped 318 nodes (cum <= 0.05GB)
Showing top 20 nodes out of 86
      flat  flat%   sum%        cum   cum%
    2.45GB 26.14% 26.14%     2.52GB 26.85%  github.com/prometheus/prometheus/vendor/github.com/ugorji/go/codec.(*jsonDecDriver).DecodeString /root/gopath/src/github.com/prometheus/prometheus/vendor/github.com/ugorji/go/codec/json.go
    0.76GB  8.10% 34.23%     0.76GB  8.10%  github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/index.(*decbuf).uvarintStr /root/gopath/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/index/encoding_helpers.go
    0.69GB  7.40% 41.63%     0.69GB  7.40%  github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/index.newReader.func2 /root/gopath/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/index/index.go
    0.69GB  7.38% 49.00%     2.74GB 29.23%  github.com/prometheus/prometheus/vendor/github.com/ugorji/go/codec.fastpathT.DecSliceStringV /root/gopath/src/github.com/prometheus/prometheus/vendor/github.com/ugorji/go/codec/fast-path.generated.go
    0.57GB  6.06% 55.06%     0.85GB  9.02%  github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/api/v1.codecSelfer1234.decSliceNodeCondition /root/gopath/src/github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/api/v1/types.generated.go
    0.50GB  5.32% 60.39%     3.24GB 34.55%  github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/api/v1.codecSelfer1234.decSliceContainerImage /root/gopath/src/github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/api/v1/types.generated.go
    0.47GB  5.02% 65.40%     0.74GB  7.85%  github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/index.(*Reader).readSymbols /root/gopath/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/index/index.go
    0.43GB  4.61% 70.02%     0.45GB  4.84%  github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/api/v1.codecSelfer1234.decResourceList /root/gopath/src/github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/api/v1/types.generated.go
    0.37GB  3.92% 73.94%     0.37GB  3.92%  github.com/prometheus/prometheus/pkg/labels.(*Builder).Labels /root/gopath/src/github.com/prometheus/prometheus/pkg/labels/labels.go
    0.30GB  3.24% 77.18%     0.30GB  3.24%  github.com/prometheus/prometheus/pkg/textparse.(*Parser).Metric /root/gopath/src/github.com/prometheus/prometheus/pkg/textparse/parse.go
    0.23GB  2.46% 79.64%     0.23GB  2.46%  github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*decbuf).uvarintStr /root/gopath/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/encoding_helpers.go
    0.23GB  2.44% 82.08%     0.46GB  4.90%  github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*walReader).decodeSeries /root/gopath/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/wal.go
    0.21GB  2.29% 84.37%     0.21GB  2.29%  reflect.unsafe_New /root/working/go/src/runtime/malloc.go
    0.18GB  1.92% 86.29%     0.18GB  1.92%  github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/chunkenc.NewXORChunk /root/gopath/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/chunkenc/xor.go
    0.18GB  1.92% 88.21%     0.26GB  2.73%  github.com/prometheus/prometheus/vendor/github.com/ugorji/go/codec.fastpathT.DecMapStringStringV /root/gopath/src/github.com/prometheus/prometheus/vendor/github.com/ugorji/go/codec/fast-path.generated.go
    0.15GB  1.61% 89.82%     0.15GB  1.61%  github.com/prometheus/prometheus/retrieval.(*scrapeCache).trackStaleness /root/gopath/src/github.com/prometheus/prometheus/retrieval/scrape.go
    0.11GB  1.22% 91.05%     0.11GB  1.22%  github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.newMemSeries /root/gopath/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/head.go
    0.10GB  1.02% 92.07%     0.10GB  1.02%  github.com/prometheus/prometheus/retrieval.(*scrapeCache).addRef /root/gopath/src/github.com/prometheus/prometheus/retrieval/scrape.go
    0.08GB   0.9% 92.97%     0.08GB   0.9%  github.com/prometheus/prometheus/pkg/pool.(*BytesPool).Get /root/gopath/src/github.com/prometheus/prometheus/pkg/pool/pool.go
    0.07GB  0.71% 93.68%     0.07GB  0.71%  github.com/prometheus/prometheus/vendor/github.com/ugorji/go/codec.(*Decoder).string /root/gopath/src/github.com/prometheus/prometheus/vendor/github.com/ugorji/go/codec/decode.go (inline)
```

**Comment by piaoyu** [comment] 2018-05-15 14:06
![prom](https://user-images.githubusercontent.com/2255909/40061700-217b7344-588c-11e8-879d-13e39263e95b.png)

**Comment by piaoyu** [comment] 2018-05-15 14:07
[goroutine-stacks.txt](https://github.com/prometheus/prometheus/files/2005291/goroutine-stacks.txt)

**Comment by brancz** [comment] 2018-05-15 14:28
I think I’ve seen a memory profile like that before, can you just to try remove the scrape configs with “role: node” and see if it disappears? (I’ve seen leaks somehow related to node objects being deserialized, never found the reason for it though)

**Comment by piaoyu** [comment] 2018-05-15 16:56
@brancz just remove the role: node? (--config.file=/etc/config/prometheus.yml): parsing YAML file /etc/config/prometheus.yml: role missing (one of: pod, service, endpoints, node) .
I remove the kubernetes-service-endpoints  target which  has  about 150 node-exporter  and it's fine.
Is it the to many retrieval.(*scrapePool)   to cause OOM ?

**Comment by cofyc** [comment] 2018-05-16 03:05
@krasi-georgiev I've never encountered memory leak. 
@piaoyu Could you increase your prometheus memory limit to see if it grows unboundedly?

**Comment by piaoyu** [comment] 2018-05-17 10:07
@cofyc   Looks like it also memory  grows  always .
![image](https://user-images.githubusercontent.com/2255909/40171185-17e5b476-59fd-11e8-8b9e-9363e0b3a52e.png)

**Comment by piaoyu** [comment] 2018-05-17 10:17
[goroutine.txt](https://github.com/prometheus/prometheus/files/2012745/goroutine.txt)

**Comment by brancz** [comment] 2018-05-17 11:53
Can you confirm, that when you do `kubectl get pod <your-prometheus-pod> -oyaml`, that it actually says that your container has been OOMKilled?

In my case the graph of the container usage looks similar but I think we're just seeing mmap memory being freed.

Concretely I've been running a setup where the `container_memory_usage_bytes` looks similar to yours. My Prometheus container has a memory limit of 1Gi:

![screenshot from 2018-05-17 13-44-40](https://user-images.githubusercontent.com/4546722/40175719-5bcb647a-59d9-11e8-8366-e539068a4e1e.png)

However heap usage (reported by the go runtime) seems stable and not ever growing:

![screenshot from 2018-05-17 13-45-44](https://user-images.githubusercontent.com/4546722/40175747-6f636bae-59d9-11e8-878d-109c5da05338.png)

Also the process has been running for >24h, so besides Kubernetes not reporting an OOMKill to me, the process itself is also confirming that.

Could you try these queries and validate this against your setup?

**Comment by piaoyu** [comment] 2018-05-18 10:17
@brancz   
![image](https://user-images.githubusercontent.com/2255909/40229676-8917c128-5ac7-11e8-97ce-66e3f6aba052.png)
container_memory_usage_bytes  not the  real memory but container_memory_rss does

**Comment by grantstephens** [comment] 2018-05-25 15:24
I've also just found this bug: works fine without the k8 discovery, but as soon as I add that it, it OOM.

**Comment by grantstephens** [comment] 2018-05-25 15:50
I recently upgraded from 2.1 to 2.2.1 and am getting the same thing. I tried removing the k8 cluster from the config but the same thing ends up happening. It uses up all the memory, then starts going into swap before OOM.

**Comment by piaoyu** [comment] 2018-05-28 02:35
@krasi-georgiev  I check the logs it really gets OOM killed.

**Comment by grantstephens** [comment] 2018-05-28 05:26
I've also experienced the same problem and it has stopped when I removed the k8 cluster from the config.

**Comment by cofyc** [comment] 2018-05-28 06:20
I'm looking into this, and trying to reproduce this issue in my cluster.

```
/prometheus $ prometheus --version
 prometheus, version 2.2.1 (branch: HEAD, revision: 94e4a4321761f83207ad11542ee971e7d5220e80)
  build user:       root@sz-bcs-a151
  build date:       20180508-12:56:09
  go version:       go1.9.4
```

@piaoyu From output of `prometheus --version`, you are using a custom build, could you try to use `quay.io/prometheus/prometheus:v2.2.1` instead? If it still get OOM killed, let me know.

**Comment by cofyc** [comment] 2018-05-28 06:27
@grantstephens Could you provide output of `prometheus --version`?

**Comment by grantstephens** [comment] 2018-05-28 10:11
```
prometheus, version 2.2.1 (branch: HEAD, revision: bc6058c81272a8d938c05e75607371284236aadc)
  build user:       root@149e5b3f0829
  build date:       20180314-14:15:45
  go version:       go1.10
```
Let me know if you need any more information.

**Comment by simonpasquier** [comment] 2018-06-04 11:17
@djsly it would helpful if you could share:
- The exact Prometheus version.
- System logs about the OOM events.
- Prometheus logs.
- graphs of the following metrics
  -  `container_memory_usage_bytes` for the Prometheus pod(s).
  - `prometheus_tsdb_head_series`
  - `rate(prometheus_tsdb_head_series_created_total[1m])`

**Comment by krasi-georgiev** [comment] 2018-06-06 16:07
for everyone in this issue I just realised that if you are testing the binary from the release page this doesn't include the refactoring so make sure you build a new one from master or the 2.2 branch.

https://github.com/prometheus/prometheus/tree/release-2.2

I can build the binary for anyone willing to test it.

**Comment by krasi-georgiev** [comment] 2018-06-07 11:29
@piaoyu did you read my comment above?
`quay.io/prometheus/prometheus:v2.2.1` is before the refactoring which is suppose to fix the problem

**Comment by krasi-georgiev** [comment] 2018-06-07 11:33
v2.3.0 is out so try that.

`quay.io/prometheus/prometheus:v2.3.0`

**Comment by piaoyu** [comment] 2018-06-12 10:22
@krasi-georgiev  OK .  I will try quay.io/prometheus/prometheus:v2.3.0

**Comment by dfredell** [comment] 2018-06-18 13:52
My prometheus was sucking up a ton of memory and disk. More than I expected. I had storage.tsdb.retention set to 10 days, and gave the prometheus docker 50G disk and 4G of memory. It wasn't happy. I tried upgrading to 2.3.0 and I think that made things even worse. 
Doing more research I found https://www.robustperception.io/which-are-my-biggest-metrics/ which pointed out that I had a custom metric with `166070` entries. I think I will fix my metrics and see if that fixes my prometheus stability issue. Adding it here in case others have this issue too. 

`topk(10, count by (__name__, job)({__name__=~".+"}))`

Element | Value
-- | --
containerpilot_events{job="consul"} | 166070
consul_catalog_service_node_healthy{job="consul"} | 150
consul_health_service_status{job="consul"} | 141
go_gc_duration_seconds{job="consul"}|105

ex
`containerpilot_events{job="consul"}`


Element | Value
-- | --
containerpilot_events{code="Metric",instance="192.168.130.252:9090",job="consul",service="containerpilot",source="tb_process_load\|0.000024106811388486265"} | 1
containerpilot_events{code="Metric",instance="192.168.130.252:9090",job="consul",service="containerpilot",source="tb_process_load\|0.000024114556647921814"} | 1
containerpilot_events{code="Metric",instance="192.168.130.252:9090",job="consul",service="containerpilot",source="tb_process_load\|0.000024234685599017417"} | 1
containerpilot_events{code="Metric",instance="192.168.130.252:9090",job="consul",service="containerpilot",source="tb_process_load\|0.000024337671686951137"} | 1

**Comment by krasi-georgiev** [comment] 2018-06-18 15:15
@dfredell thanks for the report, but can you open a new issue as this is getting to long.

@piaoyu can you please confirm if 2.3 fixed the problem for you so we can close this one?

**Comment by piaoyu** [comment] 2018-06-22 03:11
@krasi-georgiev  seem like 2.3 fixed the problem for 12hours  memory watch.

![image](https://user-images.githubusercontent.com/2255909/41756076-089a2070-760d-11e8-817c-f526f7421b15.png)

**Comment by krasi-georgiev** [comment] 2018-06-22 10:18
Nice , closing this as resolved!
Feel free to reopen or file a new one if you notice any other problems.

Thanks for the team work :+1:

**Closed by krasi-georgiev** 2018-06-22 10:18 UTC
Labels: kind/more-info-needed
