### ISSUE TITLE
last page of the wal is torn, filling it with zeros

### ISSUE THREAD

**Issue by buggithubs** [prometheus/prometheus#8630] opened 2021-03-21 08:28 UTC
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

```
uname -srm
Linux 3.10.0-957.el7.x86_64 x86_64
```

```
48 cpu
256G RAM
4.9T intel NVME
```

* Prometheus version:

	insert output of `prometheus --version` here

```
prometheus --version
prometheus, version 2.8.1 (branch: HEAD, revision: 4d60eb36dcbed725fcac5b27018574118f12fffb)
  build user:       root@bfdd6a22a683
  build date:       20190328-18:04:08
  go version:       go1.11.6
```

```
exec bin/prometheus/prometheus \
    --config.file="/home/deploy/prometheus-9090/conf/prometheus.yml" \
    --web.listen-address=":9090" \
    --web.external-url="http://10.10.10.10:9090/" \
    --web.enable-admin-api \
    --log.level="info" \
    --storage.tsdb.path="/home/deploy/prometheus-9090/data" \
    --storage.tsdb.retention="30d"
```

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

```
level=info ts=2021-03-21T03:00:28.925941532Z caller=head.go:583 component=tsdb msg="WAL checkpoint complete" first=21682 last=21723 duration=17.464059027s
level=info ts=2021-03-21T03:00:40.607206218Z caller=compact.go:441 component=tsdb msg="compact blocks" count=3 mint=1616263200000 maxt=1616284800000 ulid=01F19BM4MYEPSPV7PTACK34VSF sources="[01F18Q024SWSVFZ4PKXYBGAM2K 01F18XVSCTTS0YM3WQKG9VQYWB 01F194QGM1PFB1KKPDT9ZW15S4]" duratio
n=11.136658075s
level=info ts=2021-03-21T05:00:09.034126044Z caller=compact.go:496 component=tsdb msg="write block" mint=1616292000000 maxt=1616299200000 ulid=01F19JEZ4TE4FHVWJB3ETSEN27 duration=9.008101059s
level=info ts=2021-03-21T05:00:10.577266909Z caller=head.go:536 component=tsdb msg="head GC completed" duration=882.46215ms
level=info ts=2021-03-21T05:00:27.958399632Z caller=head.go:583 component=tsdb msg="WAL checkpoint complete" first=21724 last=21765 duration=17.381084332s
level=info ts=2021-03-21T07:00:09.521360975Z caller=compact.go:496 component=tsdb msg="write block" mint=1616299200000 maxt=1616306400000 ulid=01F19SAPCS9D41VZHBF7KWCT30 duration=9.495585397s
level=info ts=2021-03-21T07:00:10.965295498Z caller=head.go:536 component=tsdb msg="head GC completed" duration=916.73346ms
level=info ts=2021-03-21T07:00:28.662212433Z caller=head.go:583 component=tsdb msg="WAL checkpoint complete" first=21766 last=21807 duration=17.6968441s
level=warn ts=2021-03-21T08:12:58.668958973Z caller=main.go:274 deprecation_notice="'storage.tsdb.retention' flag is deprecated use 'storage.tsdb.retention.time' instead."
level=info ts=2021-03-21T08:12:58.669045258Z caller=main.go:321 msg="Starting Prometheus" version="(version=2.8.1, branch=HEAD, revision=4d60eb36dcbed725fcac5b27018574118f12fffb)"
level=info ts=2021-03-21T08:12:58.669066588Z caller=main.go:322 build_context="(go=go1.11.6, user=root@bfdd6a22a683, date=20190328-18:04:08)"
level=info ts=2021-03-21T08:12:58.669093061Z caller=main.go:323 host_details="(Linux 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 IDC-172-16-6-6 (none))"
level=info ts=2021-03-21T08:12:58.669111135Z caller=main.go:324 fd_limits="(soft=1000000, hard=1000000)"
level=info ts=2021-03-21T08:12:58.669127614Z caller=main.go:325 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2021-03-21T08:12:58.669746902Z caller=main.go:640 msg="Starting TSDB ..."
level=info ts=2021-03-21T08:12:58.669800736Z caller=web.go:418 component=web msg="Start listening for connections" address=:9090
level=info ts=2021-03-21T08:12:58.689237884Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1613652347446 maxt=1613714400000 ulid=01EYWZ5TD8E4FETPRFQ840EJW3
level=info ts=2021-03-21T08:12:58.689334532Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1613714400000 maxt=1613908800000 ulid=01EZ2HRY0MHJ5Z7FR01KNDGADS
level=info ts=2021-03-21T08:12:58.689391726Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1613908800000 maxt=1614103200000 ulid=01EZ8B558HQWDQBBMCW2GQ1NN7
level=info ts=2021-03-21T08:12:58.689440381Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1614103200000 maxt=1614297600000 ulid=01EZE4HK4Z0QVASY10NTD93VZQ
level=info ts=2021-03-21T08:12:58.689491694Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1614297600000 maxt=1614492000000 ulid=01EZKXY9JM1QX9K59SVY7ES14T
level=info ts=2021-03-21T08:12:58.689538165Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1614492000000 maxt=1614686400000 ulid=01EZSQBCGPNVKCEE4N5EQ95W7Z
level=info ts=2021-03-21T08:12:58.689589727Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1614686400000 maxt=1614880800000 ulid=01EZZGRRR4V0VN0N3GA104SX8P
level=info ts=2021-03-21T08:12:58.689634903Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1614880800000 maxt=1615075200000 ulid=01F05A6KFA39DVQFGCQZZW4EZX
level=info ts=2021-03-21T08:12:58.689682657Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1615075200000 maxt=1615269600000 ulid=01F0B3GZM1SCXPDVVHVS5XBZPB
level=info ts=2021-03-21T08:12:58.689730695Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1615269600000 maxt=1615464000000 ulid=01F0GWXBFT476840NZCYXW9GPP
level=info ts=2021-03-21T08:12:58.689781497Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1615464000000 maxt=1615658400000 ulid=01F0PP9YYBVS8V97M6AV9VDQVW
level=info ts=2021-03-21T08:12:58.689830442Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1615658400000 maxt=1615852800000 ulid=01F0WFPQN72PTF066HX04YF64E
level=info ts=2021-03-21T08:12:58.68987993Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1615852800000 maxt=1616047200000 ulid=01F1293V6CQ60Z9WKYSTKQ0VNP
level=info ts=2021-03-21T08:12:58.689924965Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1616047200000 maxt=1616241600000 ulid=01F182FJV17JM4R8SYQPDWHFVW
level=info ts=2021-03-21T08:12:58.689963297Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1616241600000 maxt=1616263200000 ulid=01F18Q0Z650CRT09E0SXGXQKVX
level=info ts=2021-03-21T08:12:58.689989592Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1616284800000 maxt=1616292000000 ulid=01F19BK7WTERF7RMB4DNAHKP6F
level=info ts=2021-03-21T08:12:58.69002129Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1616263200000 maxt=1616284800000 ulid=01F19BM4MYEPSPV7PTACK34VSF
level=info ts=2021-03-21T08:12:58.690044349Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1616292000000 maxt=1616299200000 ulid=01F19JEZ4TE4FHVWJB3ETSEN27
level=info ts=2021-03-21T08:12:58.69006705Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1616299200000 maxt=1616306400000 ulid=01F19SAPCS9D41VZHBF7KWCT30
level=warn ts=2021-03-21T08:12:58.707653379Z caller=wal.go:116 component=tsdb msg="last page of the wal is torn, filling it with zeros" segment=/home/deploy/prometheus-9090/data/wal/00021915
```

**Comment by roidelapluie** [comment] 2021-03-21 09:00
Thank you for this report. 2.8 is very old and many bug fixes and improvements have happened over the last two years. Can you please upgrade to the latest release and let us know if you can reproduce this? Thanks!

**Comment by buggithubs** [comment] 2021-03-21 09:08
OK, I'll test the startup with the new version on the old data later

**Comment by roidelapluie** [comment] 2021-03-21 09:47
I don't remember seeing such an error message.

cc @codesome @bwplotka can you answer those questions maybe?

**Comment by roidelapluie** [comment] 2021-03-21 11:30
Be careful that if you might want to use --no-storage.tsdb.wal-compression if you want to be able to come back to a version pre-2.20

**Comment by buggithubs** [comment] 2021-03-22 01:53
**After I use the new version to start the service on the old data, the information is as follows**

```
./prometheus --web.listen-address="0.0.0.0:9099" --storage.tsdb.path="/home/deploy/prometheus-9090/data.bak2"
level=info ts=2021-03-22T01:48:31.662Z caller=main.go:366 msg="No time or size retention was set so using the default time retention" duration=15d
level=info ts=2021-03-22T01:48:31.662Z caller=main.go:404 msg="Starting Prometheus" version="(version=2.25.2, branch=HEAD, revision=bda05a23ada314a0b9806a362da39b7a1a4e04c3)"
level=info ts=2021-03-22T01:48:31.662Z caller=main.go:409 build_context="(go=go1.15.10, user=root@de38ec01ef10, date=20210316-18:07:52)"
level=info ts=2021-03-22T01:48:31.662Z caller=main.go:410 host_details="(Linux 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 IDC-172-16-6-6 (none))"
level=info ts=2021-03-22T01:48:31.662Z caller=main.go:411 fd_limits="(soft=1024, hard=4096)"
level=info ts=2021-03-22T01:48:31.662Z caller=main.go:412 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2021-03-22T01:48:31.664Z caller=web.go:532 component=web msg="Start listening for connections" address=0.0.0.0:9099
level=info ts=2021-03-22T01:48:31.664Z caller=main.go:779 msg="Starting TSDB ..."
level=info ts=2021-03-22T01:48:31.664Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1613652347446 maxt=1613714400000 ulid=01EYWZ5TD8E4FETPRFQ840EJW3
level=info ts=2021-03-22T01:48:31.665Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1613714400000 maxt=1613908800000 ulid=01EZ2HRY0MHJ5Z7FR01KNDGADS
level=info ts=2021-03-22T01:48:31.665Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1613908800000 maxt=1614103200000 ulid=01EZ8B558HQWDQBBMCW2GQ1NN7
level=info ts=2021-03-22T01:48:31.665Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1614103200000 maxt=1614297600000 ulid=01EZE4HK4Z0QVASY10NTD93VZQ
level=info ts=2021-03-22T01:48:31.665Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1614297600000 maxt=1614492000000 ulid=01EZKXY9JM1QX9K59SVY7ES14T
level=info ts=2021-03-22T01:48:31.665Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1614492000000 maxt=1614686400000 ulid=01EZSQBCGPNVKCEE4N5EQ95W7Z
level=info ts=2021-03-22T01:48:31.665Z caller=tls_config.go:191 component=web msg="TLS is disabled." http2=false
level=info ts=2021-03-22T01:48:31.665Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1614686400000 maxt=1614880800000 ulid=01EZZGRRR4V0VN0N3GA104SX8P
level=info ts=2021-03-22T01:48:31.665Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1614880800000 maxt=1615075200000 ulid=01F05A6KFA39DVQFGCQZZW4EZX
level=info ts=2021-03-22T01:48:31.665Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1615075200000 maxt=1615269600000 ulid=01F0B3GZM1SCXPDVVHVS5XBZPB
level=info ts=2021-03-22T01:48:31.665Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1615269600000 maxt=1615464000000 ulid=01F0GWXBFT476840NZCYXW9GPP
level=info ts=2021-03-22T01:48:31.665Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1615464000000 maxt=1615658400000 ulid=01F0PP9YYBVS8V97M6AV9VDQVW
level=info ts=2021-03-22T01:48:31.665Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1615658400000 maxt=1615852800000 ulid=01F0WFPQN72PTF066HX04YF64E
level=info ts=2021-03-22T01:48:31.665Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1615852800000 maxt=1616047200000 ulid=01F1293V6CQ60Z9WKYSTKQ0VNP
level=info ts=2021-03-22T01:48:31.665Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1616047200000 maxt=1616241600000 ulid=01F182FJV17JM4R8SYQPDWHFVW
level=info ts=2021-03-22T01:48:31.665Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1616241600000 maxt=1616263200000 ulid=01F18Q0Z650CRT09E0SXGXQKVX
level=info ts=2021-03-22T01:48:31.665Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1616284800000 maxt=1616292000000 ulid=01F19BK7WTERF7RMB4DNAHKP6F
level=info ts=2021-03-22T01:48:31.665Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1616263200000 maxt=1616284800000 ulid=01F19BM4MYEPSPV7PTACK34VSF
level=info ts=2021-03-22T01:48:31.665Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1616292000000 maxt=1616299200000 ulid=01F19JEZ4TE4FHVWJB3ETSEN27
level=info ts=2021-03-22T01:48:31.665Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1616299200000 maxt=1616306400000 ulid=01F19SAPCS9D41VZHBF7KWCT30
level=info ts=2021-03-22T01:48:32.074Z caller=db.go:1212 component=tsdb msg="Deleting obsolete block" block=01EZ8B558HQWDQBBMCW2GQ1NN7
level=info ts=2021-03-22T01:48:32.271Z caller=db.go:1212 component=tsdb msg="Deleting obsolete block" block=01EZSQBCGPNVKCEE4N5EQ95W7Z
level=info ts=2021-03-22T01:48:32.488Z caller=db.go:1212 component=tsdb msg="Deleting obsolete block" block=01EZZGRRR4V0VN0N3GA104SX8P
level=info ts=2021-03-22T01:48:32.669Z caller=db.go:1212 component=tsdb msg="Deleting obsolete block" block=01EZE4HK4Z0QVASY10NTD93VZQ
level=info ts=2021-03-22T01:48:32.732Z caller=db.go:1212 component=tsdb msg="Deleting obsolete block" block=01EYWZ5TD8E4FETPRFQ840EJW3
level=info ts=2021-03-22T01:48:32.935Z caller=db.go:1212 component=tsdb msg="Deleting obsolete block" block=01EZ2HRY0MHJ5Z7FR01KNDGADS
level=info ts=2021-03-22T01:48:33.128Z caller=db.go:1212 component=tsdb msg="Deleting obsolete block" block=01EZKXY9JM1QX9K59SVY7ES14T
level=info ts=2021-03-22T01:48:33.128Z caller=head.go:668 component=tsdb msg="Replaying on-disk memory mappable chunks if any"
level=info ts=2021-03-22T01:48:33.128Z caller=head.go:682 component=tsdb msg="On-disk memory mappable chunks replay completed" duration=9.176µs
level=info ts=2021-03-22T01:48:33.128Z caller=head.go:688 component=tsdb msg="Replaying WAL, this may take a while"
level=info ts=2021-03-22T01:48:36.186Z caller=head.go:714 component=tsdb msg="WAL checkpoint loaded"
level=info ts=2021-03-22T01:48:38.041Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=21808 maxSegment=21916
level=info ts=2021-03-22T01:48:39.711Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=21809 maxSegment=21916
```


`component=tsdb msg="WAL segment loaded"` Information is constantly printing

![image](https://user-images.githubusercontent.com/11624213/111930678-6e2c9180-8af4-11eb-80cf-dfd2e86ae57d.png)

**Comment by buggithubs** [comment] 2021-03-22 01:58
![image](https://user-images.githubusercontent.com/11624213/111930803-b51a8700-8af4-11eb-90af-2360441bd864.png)

Use the new version（2.25.2 / 2021-03-16 ） to start the damaged data。

again ：： how much monitoring will be lost ?

```
level=info ts=2021-03-22T01:53:37.027Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=21916 maxSegment=21916
level=info ts=2021-03-22T01:53:37.027Z caller=head.go:745 component=tsdb msg="WAL replay completed" checkpoint_replay_duration=3.057576724s wal_replay_duration=5m0.841543027s total_replay_duration=5m3.899152401s

level=info ts=2021-03-22T01:53:37.907Z caller=main.go:799 fs_type=XFS_SUPER_MAGIC
level=info ts=2021-03-22T01:53:37.907Z caller=main.go:802 msg="TSDB started"
level=info ts=2021-03-22T01:53:37.907Z caller=main.go:928 msg="Loading configuration file" filename=prometheus.yml
level=info ts=2021-03-22T01:53:38.149Z caller=main.go:959 msg="Completed loading of configuration file" filename=prometheus.yml totalDuration=241.254694ms remote_storage=10.212µs web_handler=569ns query_engine=5.409µs scrape=240.651349ms scrape_sd=70.252µs notify=52.292µs notify_sd=27.438µs rules=4.994µs
level=info ts=2021-03-22T01:53:38.149Z caller=main.go:751 msg="Server is ready to receive web requests."
level=info ts=2021-03-22T01:54:08.817Z caller=compact.go:507 component=tsdb msg="write block" mint=1616306400000 maxt=1616313600000 ulid=01F1BT6Y23SCT27W1KBT2FXJHR duration=14.574058865s
level=info ts=2021-03-22T01:54:09.656Z caller=head.go:847 component=tsdb msg="Head GC completed" duration=835.745762ms
level=info ts=2021-03-22T01:54:19.186Z caller=compact.go:507 component=tsdb msg="write block" mint=1616313600000 maxt=1616320800000 ulid=01F1BT7D65CB0QSQTJJQZJNC1G duration=9.452954151s
level=info ts=2021-03-22T01:54:20.977Z caller=head.go:847 component=tsdb msg="Head GC completed" duration=1.787234109s
level=info ts=2021-03-22T01:54:20.989Z caller=checkpoint.go:95 component=tsdb msg="Creating checkpoint" from_segment=21808 to_segment=21879 mint=1616320800000
level=info ts=2021-03-22T01:54:50.648Z caller=head.go:944 component=tsdb msg="WAL checkpoint complete" first=21808 last=21879 duration=29.660211676s
level=info ts=2021-03-22T01:55:17.451Z caller=compact.go:448 component=tsdb msg="compact blocks" count=3 mint=1616284800000 maxt=1616306400000 ulid=01F1BT8N4SJ068Q6HK9YVT0WGJ sources="[01F19BK7WTERF7RMB4DNAHKP6F 01F19JEZ4TE4FHVWJB3ETSEN27 01F19SAPCS9D41VZHBF7KWCT30]" duration=26.802137466s
level=info ts=2021-03-22T01:55:17.532Z caller=db.go:1212 component=tsdb msg="Deleting obsolete block" block=01F19BK7WTERF7RMB4DNAHKP6F
level=info ts=2021-03-22T01:55:17.663Z caller=db.go:1212 component=tsdb msg="Deleting obsolete block" block=01F19SAPCS9D41VZHBF7KWCT30
level=info ts=2021-03-22T01:55:17.789Z caller=db.go:1212 component=tsdb msg="Deleting obsolete block" block=01F19JEZ4TE4FHVWJB3ETSEN27
```

**Comment by buggithubs** [comment] 2021-03-22 02:02
**I got bad data; thanks for the new version** 


![image](https://user-images.githubusercontent.com/11624213/111931194-a84a6300-8af5-11eb-9e57-dd2c7825b62d.png)

**Comment by roidelapluie** [comment] 2021-03-22 16:15
The "last page of the wal is torn, filling it with zeros" message is probably because Prometheus is killed abruptly.

**Comment by roidelapluie** [comment] 2021-03-22 19:13
Considering that your issue is fixed, I will close this.

Note that you can ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Closed by roidelapluie** 2021-03-22 19:13 UTC
