### ISSUE TITLE
Fix go back button in graph

### ISSUE THREAD

**Issue by discordianfish** [prometheus/prometheus#813] opened 2015-06-16 17:13 UTC
Hi,

if you click the go back button in the graph view, nothing happens. Instead it should change the expression input field back to the last value and refresh the graph.

**Comment by varunpatro** [comment] 2015-10-05 08:23
@discordianfish Hi what's the status of this PR? Is this enhancement still missing?

**Comment by fabxc** [comment] 2015-10-05 08:24
Yes, that is still missing.

**Comment by nsauro** [comment] 2017-10-05 00:01
Is still legit?  I do not see a "go back" button on the graph view.

**Comment by grobie** [comment] 2017-10-05 07:18
The browser functionality to load the previous page is meant here.

**Comment by discordianfish** [comment] 2017-10-05 10:05
We should probably completely rewrite the graph ui. This could be made so much better. Maybe I'll find some time for that but maybe we find a more experience frontend person for that. I mean, I imaging this being The Great Thing to work on as a UX/frontend person who wants to contribute to some FOSS.

**Comment by beorn7** [comment] 2017-10-05 11:32
If I understood correctly, the big picture is to rewrite the Prometheus server web UI in the same way the Alertmanager UI was rewritten. Or, in other words, the Elm-based UI revamp is meant as a canary for a common way to build the web UI in the Prometheus ecosystem.

**Comment by discordianfish** [comment] 2017-10-05 11:40
@beorn7 I've heard similar rumors :) Is there a issue to track that though?

**Comment by nsauro** [comment] 2017-10-05 14:55
With regards to this particular issue, how would the back button work if there are multiple charts on the page?  Would it just cycle through some stack of chart edit events, and then update the last "current" chart?

With regards to the last few comments, does that mean this should not really be looked at, since there is a potential rewrite in the works(or roadmap?)

**Comment by beorn7** [comment] 2017-10-05 17:32
As far as I understand, we do already update the URL when changing any state on the page, but when going back and forward through the browser's history, the URL changes but the page is not refreshed. (Disclaimer: I'm not a front-end developer.)

About the rewrite: I think this is more in the "let's put in on the roadmap" stage than in the "let's file a tracking issue" stage. I don't feel empowered to make the call if it should happen in the first place.
@nsauro having said that, I wouldn't wait for the rewrite if you have an easy fix for the issue at hand.

**Comment by limscoder** [comment] 2017-11-20 18:09
@beorn7 I'd love to hear more about p8s plans with Elm. Is that just an idea at this point or is there planned work?

**Comment by grobie** [comment] 2017-11-20 23:36
@limscoder No planned work unfortunatey, I'd love if someone could dedicate some time and wants to kick of such rewrite. I believe separating the UI from the server and only using the existing APIs (a few information are still missing, but could be easily added) would help a lot to make for a better experience and remove a lot of old cruft. I've had many discussions with others and have a bunch of ideas around that.

Happy to discuss in a different forum (new issue, mailing list), let's keep this issue to the back button.

**Comment by beorn7** [comment] 2017-11-21 10:46
I recommend to loop in @w0rm and @mxinden as those have worked on the new Alertmanager UI, which is supposed to be a canary for the grand unified way how to do UIs in Prometheus land.

**Comment by juliusv** [comment] 2019-02-17 12:52
I'm currently rewriting the expression browser UI in React and this should be fixed by that.

**Comment by nwchandler** [comment] 2019-02-18 15:55
Sounds good, @juliusv .

**Comment by roidelapluie** [comment] 2019-11-10 20:19
@juliusv bug is still there in react ui :)

**Comment by juliusv** [comment] 2019-11-10 20:35
@roidelapluie Haha, brilliant :) Damn, in my initial integration PR, at least the expression input got updated correctly on forward/backward buttons (although the updated expression didn't get executed), but that got broken again along the way somewhere.

**Comment by juliusv** [comment] 2019-11-10 22:01
@boyskila According to `git bisect`, b5a16a8f861c29799f9a903f1e0859f513e862ed introduced this regression - would you be up for looking into it?

**Comment by boyskila** [comment] 2019-11-11 06:34
Will check, sure

**Comment by juliusv** [comment] 2019-11-12 09:23
@boyskila fixed this for the new React UI in https://github.com/prometheus/prometheus/pull/6300. I don't think we need to spend energy on fixing it in the old UI before it disappears, so treating this as closed.

**Closed by juliusv** 2019-11-12 09:23 UTC
Labels: component/ui, hacktoberfest, help wanted, kind/enhancement, low hanging fruit, priority/P3
