### ISSUE TITLE
Add "rules_discovery" to dynamically load alerts via HTTP, similar to "http_sd_configs"

### ISSUE THREAD

**Issue by a-belhadj** [prometheus/prometheus#15444] opened 2024-11-24 10:41 UTC
### Proposal

Hello team 👋,

I would like to propose a new feature: a `rules_discovery` mechanism that allows dynamically loading alerting rules from an HTTP endpoint, similar to how `http_sd_configs` works for service discovery.

Currently, alerting rules are static, requiring manual updates and reloads. A `rules_discovery` feature could simplify workflows in environments where rules frequently change or are managed centrally via APIs.

Thanks for all your work on this project

**Comment by beorn7** [comment] 2024-11-26 11:23
Hello from the bug scrub!

Closing as duplicate of #12343

**Closed as completed by beorn7** 2024-11-26 11:23 UTC
