### ISSUE TITLE
Add `/-/healthy` and `/-/ready` endpoints

### ISSUE THREAD

**Issue by discordianfish** [prometheus/prometheus#2831] opened 2017-06-10 10:27 UTC
Prometheus should provide an health endpoint which returns 200 if prometheus is ready to response to queries (recovery is done etc).

The officially recommendation on high availability is to run two instances behind a load balance. In such scenario we need a health endpoint to avoid hitting a prometheus server that got restarted and isn't ready to serve traffic.

**Comment by beorn7** [comment] 2017-06-12 11:57
From the discussion in https://github.com/prometheus/pushgateway/issues/105 , I'd say what you want here is a `/-/ready` endpoint. The other suggested endpoint is `/-/healthy`, which returns 200 for as long as Prometheus doesn't want to get restarted.

In other words:

Prometheus should bind to `/-/healthy` immediately after startup and keep responding 200 for as long as it doesn't wish to get killed.

Prometheus should start responding 200 to `/-/ready` once it is ready to accept queries.

**Comment by discordianfish** [comment] 2017-06-12 15:52
Ah nice, yes that totally makes sense :+1:

**Comment by yonkeltron** [comment] 2017-07-05 17:31
Just wanted to throw in my two cents for this one as it would be awesome to have this for Kubernetes to use as well.

**Comment by beorn7** [comment] 2017-07-23 18:11
@Gouthamve I just saw you pinged me on IRC about this. I think all my thoughts around this have already been dumped into my last comment above. Please let me know what you are missing, and I'll try to go into more details where needed.

**Comment by emluque** [comment] 2017-07-26 00:46
Hi, I have been working on this on my local. I have arrived at a simple working solution. I think I could send a PR before end of week. If nobody else is working on this I would like to claim the issue.

**Comment by Gouthamve** [comment] 2017-07-26 02:57
Sure @emluque, looking forward to the PR! I am assigning this issue to you. Incase you get stuck somewhere, feel free to hit us up on IRC or comment here.

Incase you no longer can work on this, please de-assign yourself.

**Comment by SimenB** [comment] 2017-08-15 11:53
#2997 is merged, should this be closed?

**Comment by grobie** [comment] 2017-08-15 12:30
Resolved with #2997.

**Closed by grobie** 2017-08-15 12:30 UTC
Labels: component/ui, help wanted, kind/enhancement, low hanging fruit

**Comment by julianvmodesto** [comment] 2017-10-05 16:06
Is it possible to backport this to 1.7.x? Related to https://github.com/coreos/prometheus-operator/issues/658

**Comment by beorn7** [comment] 2017-10-05 17:33
This is part of the 1.x line of Prometheus. It will in fact be released tomorrow (if nothing goes wrong). It will be 1.8.0, however, as this is a new feature and not a bug fix.
