### ISSUE TITLE
the prometheus how to scrape Prometheus Pushgateway data

### ISSUE THREAD

**Issue by zengzhihai110** [prometheus/prometheus#1008] opened 2015-08-19 07:17 UTC
i don't find to how to it

**Comment by juliusv** [comment] 2015-08-20 15:58
You'd just scrape the pushgateway like any other Prometheus target. Have you taken a look at:

* http://prometheus.io/docs/introduction/getting_started/
* http://prometheus.io/docs/instrumenting/pushing/
* https://github.com/prometheus/pushgateway

Closing this issue here since it's not a bug in the Prometheus server.

**Closed by juliusv** 2015-08-20 15:58 UTC

**Comment by KyleFromOhio** [comment] 2018-12-28 20:17
The following example worked for me...

EDIT: /opt/prometheus/prometheus.yml (must have correct indentation)

job_name: 'pushgateway'  
                 honor_labels: true  
                 static_configs:  
                    - targets: ['localhost:9091']

Restart prometheus service to load new scrape config.
Run/start the pushgateway service.
For testing i ran manually: $ /pathto/binary/file/pushgateway --web.listen-address=":9091" 

Then send a curl request from remote server to gateway (make sure firewall is correct first)...
$ echo 'test_metric 3.15' | curl --data-binary @- http://YOURGATEWAY:9091/metrics/job/pushgateway/instance/yourremoteserver01

Then check if scraping ok: http://YOURPROMETHEUS:9090/targets
Then look for your metric (should be the last one at bottom: http://YOURGATEWAY:9091/metrics
You could check locally like: $ curl -vs http://localhost:9091/metrics | tail
