### ISSUE TITLE
Add ability to set min step for queries in the UI

### ISSUE THREAD

**Issue by hitanshu-mehta** [prometheus/prometheus#8475] opened 2021-02-11 16:09 UTC
When scrape interval is common(eg. 15s), default step  does not make much sense.
Flag to set default step would be nice.

There was similar proposal for Thanos (Issue: [#3651](https://github.com/thanos-io/thanos/issues/3651), PR: [#3740](https://github.com/thanos-io/thanos/pull/3740)). It would be nice to have this flag in Prometheus as well.

**Comment by roidelapluie** [comment] 2021-02-11 16:48
Thank you for your issue.

It seems that in my experience with Prometheus, I have pretty much always been happy with the default behaviour of the Prometheus UI. I even think that it works quite well.
The fact that by default, we have an adaptive step is something really appreciated, because the UI can quickly make you request years of data, by pressing a few times the `+` button.
Once a step is set in the UI, it is not by changed anymore. Such a scenario would mean that you would put a very high load on a prometheus server while de-zooming. 

I would like to ask what is the problem that this would solve. Is it really needed to have a fixed default step, or should we adapt the graph panel to compute a step by default, which would be better than the current automatic step ?

**Comment by hitanshu-mehta** [comment] 2021-02-12 06:31
Sorry for being unclear in describing issue. 
This step should only be used when step is not explicitly set in UI. This way we can have both adaptive step and ability to set default step for all queries. 
This flag would be helpful when scrape interval is relatively big (eg. 1 hr). In such cases, if user query without specifying step then Prometheus will use 1s as default value which is too low for no good reason. WDYT ?

PS: @bwplotka Please correct me if my understanding is wrong regarding this. 🤗

**Comment by roidelapluie** [comment] 2021-02-12 20:49
I think that there is a misunderstanding between the default step and the loopback delta. In general, scraping less often than 2 minutes will lead to pretty bad results with Prometheus default settings. Users who have lower scrape intervals can find convenient to adjust the `--query.lookback-delta=` to be a multiple of their scrape interval, but that is not related to the step interval.

**Comment by bwplotka** [comment] 2021-02-21 19:50
> It seems that in my experience with Prometheus, I have pretty much always been happy with the default behavior of the Prometheus UI. I even think that it works quite well.

Great that it worked for you, but some customization is necessary for a smooth experience when scrape interval is customized. While it's more often seen in Cortex/Thanos use cases, I saw this in Prometheus too. Especially if you KNOW as Prometheus admin that you don't allow different scrape intervals than e.g 30s, having 1s is just not needed and inefficient.

> I think that there is a misunderstanding between the default step and the loopback delta. In general, scraping less often than 2 minutes will lead to pretty bad results with Prometheus default settings. Users who have lower scrape intervals can find it convenient to adjust the --query.lookback-delta= to be a multiple of their scrape interval, but that is not related to the step interval.

I think there is no misunderstanding. For such an example system, I have seen users were already adjusting lookback delta, so step is the only missing piece causing worse then needed UX. (: 

We already fixed this in Thanos, but would be nice to upstream this for vanilla Prometheus users too! 🤗

**Comment by roidelapluie** [comment] 2021-02-21 19:53
I tend to disagree, the problem is that with 30s, you can have samples that are up to 29s off.

**Comment by roidelapluie** [comment] 2021-02-21 19:55
The point is that if you have many targets, you need to have a higher step by default in the UI to see when each target is changing. Having a mower interval seems like mainly a workaround for thanos being slow  (as per https://github.com/thanos-io/thanos/issues/3651#issue-771357436 )

**Comment by roidelapluie** [comment] 2021-02-21 20:02
I would also like to know what problem is fixed with this by thanos:

default step is de facto "14s" for range queries. The code that was merged in thanos only matter when you zoom below 250 ms, which is strange?

**Comment by roidelapluie** [comment] 2021-02-21 20:16
We could have it but I don't think it is low hanging fruit.

- What is good: we currently already display the step in the reacti UI
- I would like to have this handled by the react ui only. I appreciate the fact that you *have* to pass a step to the API. It is not the API to decide which step to use.
- I would like to keep the default as is it now (I have not checked what default we have).


Thanks!

**Comment by roidelapluie** [comment] 2021-02-21 21:12
I have updated the title to reflect that the goal of the issue is to be able to pass something else than '1' in https://github.com/prometheus/prometheus/blob/8c8de46003d1800c9d40121b4a5e5de8582ef6e1/web/ui/react-app/src/pages/graph/Panel.tsx#L116 via a flag.

**Comment by bwplotka** [comment] 2021-03-01 21:03
Cool, no worries. 

Hm, let's maybe close this for now and bring this discussion back when we will work on importing Prometheus React UI directly on Thanos. Then it will be more important 🤗

**Closed by bwplotka** 2021-03-01 21:03 UTC
Labels: component/api, component/react-ui, help wanted, kind/enhancement, low hanging fruit
