### ISSUE TITLE
How do I change the time zone of prometheus, please

### ISSUE THREAD

**Issue by D-PENG** [prometheus/prometheus#4613] opened 2018-09-17 03:59 UTC
Is it configured in `prometheus.yml` ?

**Comment by AndorCS** [comment] 2018-09-17 09:39
Prometheus always keep data in UTC timezone.

However, you can use timezone-related settings in Grafana.

**Comment by D-PENG** [comment] 2018-09-17 10:32
@AndorCS The time zone of Grafana can be set, but it is inconvenient to view. It is more flexible and convenient to check on Prometheus.

**Comment by Andor** [comment] 2018-09-17 10:37
> It is more flexible and convenient to check on Prometheus.

Check what? What exactly are you trying to do when you need timezones?

**Comment by D-PENG** [comment] 2018-09-17 10:49
> > It is more flexible and convenient to check on Prometheus.
> 
> Check what? What exactly are you trying to do when you need timezones?

For example, I want to see the data of an index, (such as `((sum by(pod_name) (rate(container_network_receive_bytes_total{pod_name="alertmanager-wechat-5b665cdbc7-bbsqx"}[1m]))) / 1024) `.)
On the graph of Prometheus, I can quickly get the historical data of the index, which is very flexible.

**Comment by gouthamve** [comment] 2018-09-17 10:56
This is dupe of #500 See https://prometheus.io/docs/introduction/faq/#can-i-change-the-timezone?-why-is-everything-in-utc? for reasoning.

**Comment by D-PENG** [comment] 2018-09-18 10:18
> This is dupe of #500 See https://prometheus.io/docs/introduction/faq/#can-i-change-the-timezone?-why-is-everything-in-utc? for reasoning.

thx

**Closed** 2018-09-21 14:02 UTC
