### ISSUE TITLE
Did consul_sd_config support adding multi server?

### ISSUE THREAD

**Issue by WuLeeX** [prometheus/prometheus#3576] opened 2017-12-12 09:03 UTC
Here is my use case: I set up a consul cluster with serveral servers and clients, while in the Prometheus.yml, I can only set one server. I wanna add multi servers in the configs, in case the server I add in the Prometheus.yml go DOWN, the others can take over. just like:
- job_name: 'consul'
    consul_sd_configs:
      - server: 'ip1:8500'
      - server: 'ip2:8500'
      - server: 'ip3:8500'
      ......
      - server: 'ipN:8500'

Any suggestions? Thanks a lot.

**Comment by brian-brazil** [comment] 2017-12-12 09:20
Dupe of #1538

**Closed by brian-brazil** 2017-12-12 09:20 UTC

**Comment by WuLeeX** [comment] 2017-12-13 00:22
Sorry, I donnot think it's the same topic.
Here I am talking about how to add serveral servers in the Prometheus.yml as HA mode, not the same topic with [#1538](https://github.com/prometheus/prometheus/issues/1538).

Maybe using a DNS name, instead of a server ip seems to be a practical way.

**Comment by brian-brazil** [comment] 2017-12-13 09:06
It's the same issue, that's not how Consul is intended to be used.
