### ISSUE TITLE
Prometheus goes down with error "http: superfluous response.WriteHeader call from github.com/opentracing-contrib/go-stdlib/nethttp.(*statusCodeTracker).WriteHeader (status-code-tracker.go:19" msg=)

### ISSUE THREAD

**Issue by varun-krishna** [prometheus/prometheus#7221] opened 2020-05-07 07:45 UTC
What did you see ?

Prometheus is down with multiple errors as follows 

prometheus[21965]: level=error ts=2020-05-07T06:38:02.035Z caller=stdlib.go:89 component=web caller="http: superfluous response.WriteHeader call from github.com/opentracing-contrib/go-stdlib/nethttp.(*statusCodeTracker).WriteHeader (status-code-tracker.go:19" msg=)
prometheus[21965]: level=info ts=2020-05-07T06:38:03.369Z caller=head.go:662 component=tsdb msg="head GC completed" duration=27.061633556s
prometheus[21965]: level=info ts=2020-05-07T06:39:43.270Z caller=head.go:732 component=tsdb msg="WAL checkpoint complete" first=208 last=292 duration=1m39.900546944s
prometheus[21965]: level=info ts=2020-05-07T06:40:02.479Z caller=head.go:662 component=tsdb msg="head GC completed" duration=4.827104553s
prometheus[21965]: level=info ts=2020-05-07T06:41:22.298Z caller=head.go:732 component=tsdb msg="WAL checkpoint complete" first=293 last=350 duration=1m19.819063915s
prometheus[21965]: level=info ts=2020-05-07T06:41:39.862Z caller=head.go:662 component=tsdb msg="head GC completed" duration=4.489466475s
prometheus[21965]: level=info ts=2020-05-07T06:42:41.930Z caller=head.go:732 component=tsdb msg="WAL checkpoint complete" first=351 last=389 duration=1m2.067394704s
**prometheus[21965]: level=warn ts=2020-05-07T06:45:01.618Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:361: watch of *v1.Endpoints ended with: too old resource version: 516336955 (516337253)"**

**Environment**

* Prometheus version:

 prometheus --version 2.17.0  and   2.18.0

**Comment by dinesh4747** [comment] 2020-05-07 07:59
@brian-brazil  @bwplotka Your thoughts on this - we had the similar issue and upgraded to multiples version of prometheus from V2.13.0 to V2.18.0 but hard luck - any pointers on this 

I see one open issue already here - https://github.com/prometheus/prometheus/issues/6139

**Comment by brian-brazil** [comment] 2020-05-07 08:05
@beorn7 is the one looking at these. Should we mark as a dupe?

**Comment by beorn7** [comment] 2020-05-07 10:38
I'm not actively looking into these problems. It's not even clear where the bug is. Could be in opentracing.

In any case, Prometheus should not "go down" with this error. It should, in my understanding, be a pretty harmless thing.

**Comment by beorn7** [comment] 2020-05-07 10:39
In any case, bundling all the "superfluous response.WriteHeader" into one issue probably makes sense.

**Comment by brian-brazil** [comment] 2020-05-07 10:42
Yeah, this looks like a dupe of #6139 so closing this one. This does appear harmless overall.

**Closed by brian-brazil** 2020-05-07 10:42 UTC
Labels: kind/bug
