### ISSUE TITLE
Main menu appearance using Safari with 0.19.0

### ISSUE THREAD

**Issue by roman-vynar** [prometheus/prometheus#1662] opened 2016-05-25 12:49 UTC
The main menu appears broken into 2 rows using Safari web browser with Prometheus 0.19.0.
<img width="937" alt="screen shot 2016-05-25 at 15 41 48" src="https://cloud.githubusercontent.com/assets/2220941/15540390/b6b6407c-228f-11e6-8919-6c9b4c207bb3.png">

It is okay in Chrome and Firefox.

**Comment by brian-brazil** [comment] 2016-05-25 12:53
Dupe of #1659

**Closed by brian-brazil** 2016-05-25 12:53 UTC
