### ISSUE TITLE
exemplar storage doesn't work for v2.40.0-rc.0

### ISSUE THREAD

**Issue by songjiayang** [prometheus/prometheus#11540] opened 2022-11-06 05:04 UTC
### What did you do?

I test native histograms with [v2.40.0-rc.0](https://hub.docker.com/layers/prom/prometheus/v2.40.0-rc.0/images/sha256-3fe0d56a6707a36b44a2558c7ec59c36e0ac66fb49a33a65ae777a2b3df6c769?context=explore)  docker image,  scrape [client_golang random app](https://github.com/prometheus/client_golang/blob/main/examples/random/main.go) with `main` branch and `5f202eefdb5dcb9b5b26d4d7c3351d1e5a0d9bc7 `  hash.

I run two Prometheus instances, one start with native histograms enabled, another disabled. all of them scrape the random app's metrics.

The docker compose yaml like:

```
 prometheus:
    image: prom/prometheus:v2.40.0-rc.0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --log.level=error
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --enable-feature=native-histograms
      - --enable-feature=exemplar-storage
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-1-data:/prometheus
    ports:
      - 9090:9090
  prometheus2:
    image: prom/prometheus:v2.40.0-rc.0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --log.level=error
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --enable-feature=exemplar-storage
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-2-data:/prometheus
    ports:
      - 9091:9090
  native-demo:
    image: client_golang:v0.1
    ports:
      - 8080:8080
``` 

When run some times, check the two Prometheus's histograms  and exemplar data, I find only the native histograms enabled instance works well with exemplar.

### What did you expect to see?

Exemplar storage works well with prometheus:v2.40.0-rc.0 even if disabled native histograms, the Graph dashbord will show exempalr data when click `Show Exemplars` button.

### What did you see instead? Under which circumstances?

The Graph dashbord doesn't show  any exempalr data when click `Show Exemplars` button.

### System information

docker image prometheus:v2.40.0-rc.0

**Comment by beorn7** [comment] 2022-11-07 12:05
Thanks for the comprehensive report. This is interesting. I'll have a look ASAP.

**Comment by beorn7** [comment] 2022-11-07 14:04
The problem is that the content negotiation fails to negotiate OpenMetrics. That broke when the accept header was changed to `version=1.0.0`, i.e. it already failed before we merged the native histograms. The native histograms then "semi-fixed" the problem because exemplars also work with the protobuf format, which got reintroduced with native histograms.

Of course, exemplars should also work without the native histogram feature flag, see #11542 for the fix.

**Comment by beorn7** [comment] 2022-11-07 17:32
The fix will be in v2.40.0, and should be merged into the main branch soon.

**Closed by beorn7** 2022-11-07 17:32 UTC

**Comment by roidelapluie** [comment] 2022-11-08 00:04
> The problem is that the content negotiation fails to negotiate OpenMetrics. That broke when the accept header was changed to `version=1.0.0`, i.e. it already failed before we merged the native histograms. The native histograms then "semi-fixed" the problem because exemplars also work with the protobuf format, which got reintroduced with native histograms.
> 
> Of course, exemplars should also work without the native histogram feature flag, see #11542 for the fix.

df3b674f01f05ea846095ab7258191f33baadb25 broke it and it is only in the histogram branch. Prometheus 2.39 is using `application/openmetrics-text;version=1.0.0,application/openmetrics-text;version=0.0.1;q=0.75,text/plain;version=0.0.4;q=0.5,*/*;q=0.1`.

I would suggest we re use the same and keep the versions to not break anyone.

**Comment by beorn7** [comment] 2022-11-08 20:43
I see. Let's do it that way then. I'll create a PR ASAP.

**Comment by beorn7** [comment] 2022-11-08 22:22
See https://github.com/prometheus/prometheus/pull/11552
