### ISSUE TITLE
Read endpoint for grafana5 throws invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ximply** [prometheus/prometheus#4240] opened 2018-06-08 02:52 UTC
Prometheus 2.3 (and 2.2.1 is ok) use as a read endpoint for grafana5 will throw a error like this:

level=error ts=2018-06-08T02:39:50.80339667Z caller=stdlib.go:89 component=web caller="http: panic serving 192.168.10.176:31525" msg="runtime error: invalid memory address or nil pointer dereference"

192.168.10.176 is the grafana server

**Comment by brian-brazil** [comment] 2018-06-08 06:46
Can you clarify what you mean by "read endpoint"? Which URL is Grafana hitting?

**Comment by ximply** [comment] 2018-06-08 08:16
Sorroy, **read enpoint** is **remote read endpoint**.

The setting of grafana datasource for prometheus:
the **_HTTP URL_** is **http://192.168.10.248:8080**
the **_HTTP Access_** is **proxy**

**Comment by ximply** [comment] 2018-06-08 08:18
Here are the settings:
![default](https://user-images.githubusercontent.com/3693445/41146891-72938696-6b37-11e8-86b1-eb8e1d562206.png)

**Comment by brian-brazil** [comment] 2018-06-08 08:18
Grafana doesn't use the remote read endpoint. Can you capture the HTTP request in question?

**Comment by ximply** [comment] 2018-06-08 09:42
But I use Prometheus 2.2.1, it is ok.

**Comment by y2sarakawa** [comment] 2018-06-10 04:03
Grafana 5 accesses the Prometheus /series endpoint when referring to variables.

If more than one entry is in remote_read, nil is passed to "p * storage.SelectParams" in ToQuery () of storage/remote/codec.go.

After merging #4122, nil pointer dereference will occur to refer to "p" when creating ReadHints in ToQuery ().
https://github.com/prometheus/prometheus/blob/v2.3.0/storage/remote/codec.go#L96

Please also see #4205.

**Comment by brian-brazil** [comment] 2018-06-13 14:31
Looks like a dupe of #4205 alright.

**Closed by brian-brazil** 2018-06-13 14:31 UTC
