### ISSUE TITLE
humanizeDuration for floats/parsing floats to ints in templates

### ISSUE THREAD

**Issue by ties** [prometheus/prometheus#8565] opened 2021-03-05 15:42 UTC
## Proposal
As a user, I would like to either:
  * `humanizeDuration` a float
  * have a template method for getting the integer value from a float string.

Either would allow me to implement what I want.

#### Use case
I am alerting when newly encountered objects have a time to live that is too short (e.g. `increase(metric_expiration_seconds_bucket{le="54611.0"}[15m] > 0`). When alerting for this, it is useful that the alert contains a readable amount of time such as for `humanizeDuration`.

While the methods from `text/templating` and a [number of other functions](https://github.com/prometheus/prometheus/blob/main/template/template.go#L117) are available, I do not see a way to print the histogram bucket boundary as a string. If is already possible, a hint would also be very welcome!

**Comment by roidelapluie** [comment] 2021-03-05 16:40
Thank you! This has been proposed already.
I am closing this as a duplicate of  #8303.
Note that a pull request exists but would require more work (someone could pick this up again: #8339)

**Closed by roidelapluie** 2021-03-05 16:40 UTC

**Comment by ties** [comment] 2021-03-05 16:48
Oops. Thanks for cleaning up the duplicate (I did not find it somehow).
