### ISSUE TITLE
https://prometheus.io is down

### ISSUE THREAD

**Issue by mza97** [prometheus/prometheus#2987] opened 2017-07-25 08:30 UTC
https://prometheus.io is down, any solution to download it ?

**Comment by grobie** [comment] 2017-07-25 08:33
I can't confirm, it's up form 3 different locations I just checked. We use cloudflare as CDN, it's highly unlikely that CloudFlare is down.

http://downforeveryoneorjustme.com/prometheus.io

**Comment by mza97** [comment] 2017-07-25 08:54
Since friday it was not working, but now I check the downforeveryoneorjustme website it's working again lol I don't know why

**Comment by Gouthamve** [comment] 2017-07-25 08:59
Thanks for letting us know! But I think it could have been a very short hiccup in your or Cloudflare's network.

As this is not a bug anymore, I am closing it. Please feel free to reopen if anything changes.

**Closed by Gouthamve** 2017-07-25 08:59 UTC
