### ISSUE TITLE
Disable local storage

### ISSUE THREAD

**Issue by h7kanna** [prometheus/prometheus#2729] opened 2017-05-16 19:48 UTC
Provide an option to configure Prometheus in disk-less storage mode in 2.x series.

From the discussion
https://groups.google.com/forum/#!topic/prometheus-users/kJ1knCitxQs

I learnt this can be easily implemented in 1.x series which I am trying to do.
But the suggestion was to ask someone working on 2.x series to consider this as a feature request.

Thanks,
Harsha

**Comment by fabxc** [comment] 2017-05-16 20:10
This should be pretty straightforward but it has very low-priority for me right now. Happy provide guidance and review if someone wants to implement that feature for 2.x

I am curious about your use case though – do I assume correct that you still want to keep a certain amount of history in memory for querying or is it just about proxying data via remote-write?

The easy mode is to set a short retention and point the data dir to tmpfs. Truly disabling anything persistence related will probably not give notable performance gains in 2.x

**Comment by h7kanna** [comment] 2017-05-16 20:14
Yes, use case is metrics in memory for querying but completely ephemeral. Persistence to disk is only via remote write or optional.

Reason is not particularly performance but to deploy Prometheus as stateless container.

**Comment by fabxc** [comment] 2017-05-16 20:17
We basically do this all the time with Kubernetes. Prometheus writes its data to the file system as usual, but it is backed by tmpfs and if the container goes down, the data is simply dropped. Anything speaking against that solution?

**Comment by h7kanna** [comment] 2017-05-16 20:23
Currently trying to deploy on internal PAAS platform which only supports stateless containers.
We are not yet on Kubernetes (adoption is in works though). Will try to deploy as you suggested.
Thanks @fabxc

**Comment by fabxc** [comment] 2017-06-06 07:23
Closing here as this seems to be a viable solution.

**Closed by fabxc** 2017-06-06 07:23 UTC

**Comment by AndreaGiardini** [comment] 2017-12-18 13:28
I would like to add my findings and doubts to this issue:

 - I have prometheus with remote read/write (influxdb)
 - I set retention period for 2 days and mounted the /prometheus folder as tmpfs as suggested by @fabxc 

My doubts are:

 - It looks like this technique does not provide any in-memory caching (every request still goes to the influxdb backend). Am I missing something? I would expect every query that includes data less than 2d old to be processed locally... or maybe the metrics are deleted from local storage as soon as they are shipped to influxdb?

 - Kubernetes does not allow you to set a size for the tmpfs volume. This means that whoever implements this solution needs to pay particular attention to the retention policy since their pod might get OOM killed.

**Comment by sevagh** [comment] 2018-05-16 16:25
>It looks like this technique does not provide any in-memory caching (every request still goes to the influxdb backend). Am I missing something? I would expect every query that includes data less than 2d old to be processed locally... or maybe the metrics are deleted from local storage as soon as they are shipped to influxdb?

I think this is intended behavior. When doing some basic testing, I put a log statement in my remote storage adapter on the `/read` endpoint, and every query/graph was hitting remote storage. I believe the remote storage is always used when it's defined.

**Comment by juliusv** [comment] 2018-05-17 21:44
@AndreaGiardini 
> It looks like this technique does not provide any in-memory caching (every request still goes to the influxdb backend). Am I missing something? I would expect every query that includes data less than 2d old to be processed locally... or maybe the metrics are deleted from local storage as soon as they are shipped to influxdb?

For queries that don't touch data older than the start time of the local TSDB, remote reads should only occur when the `read_recent: true` flag is set in a [`remote_read`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_read) config.

Relevant code: https://github.com/prometheus/prometheus/blob/406233e937e00b0847b13316274be908a65c211a/storage/remote/read.go#L103-L123

**Comment by juliusv** [comment] 2018-05-17 21:45
(at least now, not sure if it was already true when your comment was written :))
