### ISSUE TITLE
prometheus returnd cannot validate certificate

### ISSUE THREAD

**Issue by liyehaha** [prometheus/prometheus#1882] opened 2016-08-10 11:12 UTC
Hi I had this problem when using prometheus in kubernetes. 

The error log is:
`ERRO[0000] Cannot initialize nodes collection: unable to list Kubernetes nodes: unable to query any API servers: Get https://172.60.0.1:443/api/v1/nodes: x509: cannot validate certificate for 172.60.0.1 because it doesn't contain any IP SANs  source=node.go:124`

The prometheus config file is:
`scrape_configs:
- job_name: 'kubernetes-cluster'
  scheme: https
  tls_config:
    ca_file: /var/run/kubernetes/cert/ca.crt
    key_file: /var/run/kubernetes/cert/kubelet.key
    cert_file: /var/run/kubernetes/cert/kubelet.crt
    insecure_skip_verify: true

  kubernetes_sd_configs:
  - api_servers:
    - 'https://172.60.0.1:443'
    role: apiserver

- job_name: 'kubernetes-node'
  scheme: https
  tls_config:
    insecure_skip_verify: true
    ca_file: /var/run/kubernetes/cert/ca.crt
    key_file: /var/run/kubernetes/cert/prom.key
    cert_file: /var/run/kubernetes/cert/prom.crt

  kubernetes_sd_configs:
  - api_servers:
    - 'https://172.60.0.1:443'
    role: node

  relabel_configs:
  - source_labels: [__meta_kubernetes_role]
    action: keep
    regex: (?:apiserver|node)`

The problem happend when I don't set to apiserver

**Comment by brian-brazil** [comment] 2016-08-10 13:46
Dupe of #1822

**Closed by brian-brazil** 2016-08-10 13:46 UTC
