### ISSUE TITLE
max aggregation always treats histograms as 0

### ISSUE THREAD

**Issue by jhesketh** [prometheus/prometheus#14711] opened 2024-08-22 03:47 UTC
### What did you do?

Query `max(series)` that groups together some series with floats and some series with histograms

### What did you expect to see?

I expect to see the maximum float when it is available, even if it is negative. For example, if I have a series with a float value of `-10` and a native histogram at the same timestamp, I expect to see the float value regardless of the histogram.

Maybe this is incorrect, but the point is that a histogram is always treated as a `0`. This is likely true for `min` aggregations (and maybe others) too.

### What did you see instead? Under which circumstances?

I saw a float value of `0`.

[promql.info demonstration](https://promql.info/?b64=IyBUZXN0IG1heCBhZ2dyZWdhdGlvbiB3aXRoIGhpc3RvZ3JhbXMgYW5kIGEgbWl4IG9mIGhpc3RvZ3JhbStmbG9hdCB2YWxldXMNCmxvYWQgMW0NCglzZXJpZXN7bGFiZWw9InZhbHVlIn0gICAtMTAgLTEwIC0xMCAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAxMCAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgLTEwICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHt7c2NoZW1hOjEgc3VtOjEwIGNvdW50OjUgYnVja2V0czpbMSAzIDFdfX0NCglzZXJpZXN7bGFiZWw9InZhbHVlMiJ9ICAwICAgLTkgIHt7c2NoZW1hOjEgc3VtOjUgY291bnQ6NSBidWNrZXRzOlsxIDMgMV19fSB7e3NjaGVtYToxIHN1bTo1IGNvdW50OjUgYnVja2V0czpbMSAzIDFdfX0ge3tzY2hlbWE6MSBzdW06NSBjb3VudDo1IGJ1Y2tldHM6WzEgMyAxXX19IHt7c2NoZW1hOjEgc3VtOjUgY291bnQ6NSBidWNrZXRzOlsxIDMgMV19fQ0KCXNlcmllc3tsYWJlbD0idmFsdWUzIn0gIC0yMCAtOSAgLTkgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHt7c2NoZW1hOjEgc3VtOjUgY291bnQ6NSBidWNrZXRzOlsxIDMgMV19fSB7e3NjaGVtYToxIHN1bTo1IGNvdW50OjUgYnVja2V0czpbMSAzIDFdfX0ge3tzY2hlbWE6MSBzdW06NSBjb3VudDo1IGJ1Y2tldHM6WzEgMyAxXX19DQoNCiMgUEFTU0VTOg0KZXZhbCByYW5nZSBmcm9tIDAgdG8gNW0gc3RlcCAxbSBtYXgoc2VyaWVzKQ0KCXt9IDAgLTkgMCAxMCAwIDANCg0KZXZhbCByYW5nZSBmcm9tIDAgdG8gNW0gc3RlcCAxbSBtaW4oc2VyaWVzKQ0KCXt9IC0yMCAtMTAgLTEwIDAgLTEwIDANCg0KDQojIFdIQVQgSSBXT1VMRCBFWFBFQ1QgVE8gUEFTUywgQlVUIEZBSUxTOg0KZXZhbCByYW5nZSBmcm9tIDAgdG8gNW0gc3RlcCAxbSBtYXgoc2VyaWVzKQ0KCXt9IDAgLTkgLTkgMTAgLTEwIF8NCg0KZXZhbCByYW5nZSBmcm9tIDAgdG8gNW0gc3RlcCAxbSBtaW4oc2VyaWVzKQ0KCXt9IC0yMCAtMTAgLTEwIDEwIC0xMCBfDQoNCmNsZWFy).

**Comment by NeerajGartia21** [comment] 2024-08-24 20:19
@jhesketh you are right. Currently promql treats histogram as 0 in case of min and max functions and there are other exceptions too, which are mentioned in #13934. I'm working on this and will fix this soon!

**Comment by beorn7** [comment] 2024-08-28 14:45
Closing as dupe of #13934 .

**Closed by beorn7** 2024-08-28 14:45 UTC
