### ISSUE TITLE
Prometheus 2.9.2: runtime: out of memory

### ISSUE THREAD

**Issue by bismarck** [prometheus/prometheus#5524] opened 2019-04-30 01:05 UTC
## Bug Report
**What did you do?**
Upgraded from 2.6.1 to 2.9.2.

**What did you expect to see?**
Before upgrade RSS was around 37 GiB.

![memory-2 6 1](https://user-images.githubusercontent.com/1072760/56935537-94d81e00-6abf-11e9-9739-d14e1470e040.png)

**What did you see instead? Under which circumstances?**
After upgrade RSS jumped to 112 GiB and eventually panic'd with a `runtime: out of memory` error.

![memory-2 9 2](https://user-images.githubusercontent.com/1072760/56935564-d4066f00-6abf-11e9-848f-6f91efa91440.png)

This is an Azure D32s v3 instance type with 32 vCPUs and 128 GiB RAM.  This Prometheus instance appends ~134 K samples/s.

I understand higher RSS is expected, but this is a dramatic increase.  I believe we might be seeing the effects golang/go#31616 and golang/go#31678

**Environment**

* System information:
```
Linux 4.15.0-1037-azure x86_64
```

* Prometheus version:
```
prometheus, version 2.9.2 (branch: HEAD, revision: d3245f15022551c6fc8281766ea62db4d71e2747)
  build user:       root@1d43b6951e8f
  build date:       20190424-15:32:31
  go version:       go1.12.4
```

* Prometheus configuration file:
```
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    datacenter: eastus2
    environment: qa
    prometheus: platform

rule_files:
- /etc/prometheus/rules/platform/*
scrape_configs:

... lots of scrape configs ...
```

* Logs:
```
Apr 26 05:56:52 my-host prometheus[29830]: fatal error: runtime: out of memory
Apr 26 05:56:52 my-host prometheus[29830]: runtime stack:
Apr 26 05:56:52 my-host prometheus[29830]: runtime.throw(0x20a6c3b, 0x16)
Apr 26 05:56:52 my-host prometheus[29830]:         /usr/local/go/src/runtime/panic.go:617 +0x72
Apr 26 05:56:52 my-host prometheus[29830]: runtime.sysMap(0xf2b8000000, 0x10000000, 0x39024d8)
Apr 26 05:56:52 my-host prometheus[29830]:         /usr/local/go/src/runtime/mem_linux.go:170 +0xc7
Apr 26 05:56:52 my-host prometheus[29830]: runtime.(*mheap).sysAlloc(0x38e9ae0, 0xcf04000, 0x38e9af0, 0x6782)
Apr 26 05:56:52 my-host prometheus[29830]:         /usr/local/go/src/runtime/malloc.go:633 +0x1cd
Apr 26 05:56:52 my-host prometheus[29830]: runtime.(*mheap).grow(0x38e9ae0, 0x6782, 0x0)
Apr 26 05:56:52 my-host prometheus[29830]:         /usr/local/go/src/runtime/mheap.go:1232 +0x42
Apr 26 05:56:52 my-host prometheus[29830]: runtime.(*mheap).allocSpanLocked(0x38e9ae0, 0x6782, 0x39024e8, 0x41d44d)
Apr 26 05:56:52 my-host prometheus[29830]:         /usr/local/go/src/runtime/mheap.go:1150 +0x3a7
Apr 26 05:56:52 my-host prometheus[29830]: runtime.(*mheap).alloc_m(0x38e9ae0, 0x6782, 0x7fbe4ad70101, 0x38e9af0)
Apr 26 05:56:52 my-host prometheus[29830]:         /usr/local/go/src/runtime/mheap.go:977 +0xc2
Apr 26 05:56:52 my-host prometheus[29830]: runtime.(*mheap).alloc.func1()
Apr 26 05:56:52 my-host prometheus[29830]:         /usr/local/go/src/runtime/mheap.go:1048 +0x4c
Apr 26 05:56:52 my-host prometheus[29830]: runtime.(*mheap).alloc(0x38e9ae0, 0x6782, 0xc1a2010101, 0xc26e40d500)
Apr 26 05:56:52 my-host prometheus[29830]:         /usr/local/go/src/runtime/mheap.go:1047 +0x8a
Apr 26 05:56:52 my-host prometheus[29830]: runtime.largeAlloc(0xcf032c4, 0x7fbe2e730101, 0x1)
Apr 26 05:56:52 my-host prometheus[29830]:         /usr/local/go/src/runtime/malloc.go:1055 +0x99
Apr 26 05:56:52 my-host prometheus[29830]: runtime.mallocgc.func1()
Apr 26 05:56:52 my-host prometheus[29830]:         /usr/local/go/src/runtime/malloc.go:950 +0x46
Apr 26 05:56:52 my-host prometheus[29830]: runtime.systemstack(0xc21bbc87e0)
Apr 26 05:56:52 my-host prometheus[29830]:         /usr/local/go/src/runtime/asm_amd64.s:351 +0x66
Apr 26 05:56:52 my-host prometheus[29830]: runtime.mstart()
Apr 26 05:56:52 my-host prometheus[29830]:         /usr/local/go/src/runtime/proc.go:1153
Apr 26 05:56:52 my-host prometheus[29830]: goroutine 32989 [running]:
Apr 26 05:56:52 my-host prometheus[29830]: runtime.systemstack_switch()
Apr 26 05:56:52 my-host prometheus[29830]:         /usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc4305b5868 sp=0xc4305b5860 pc=0x45ab40
Apr 26 05:56:52 my-host prometheus[29830]: runtime.mallocgc(0xcf032c4, 0x1c307c0, 0xc64ea56b01, 0xc4305b5940)
Apr 26 05:56:52 my-host prometheus[29830]:         /usr/local/go/src/runtime/malloc.go:949 +0x872 fp=0xc4305b5908 sp=0xc4305b5868 pc=0x40c062
Apr 26 05:56:52 my-host prometheus[29830]: runtime.makeslice(0x1c307c0, 0xcf032c4, 0xcf032c4, 0x0)
Apr 26 05:56:52 my-host prometheus[29830]:         /usr/local/go/src/runtime/slice.go:49 +0x6c fp=0xc4305b5938 sp=0xc4305b5908 pc=0x443d9c
Apr 26 05:56:52 my-host prometheus[29830]: bytes.makeSlice(0xcf032c4, 0x0, 0x0, 0x0)
Apr 26 05:56:52 my-host prometheus[29830]:         /usr/local/go/src/bytes/buffer.go:232 +0x6d fp=0xc4305b5968 sp=0xc4305b5938 pc=0x4eb2cd
Apr 26 05:56:52 my-host prometheus[29830]: bytes.(*Buffer).grow(0xc1e91fc720, 0x200, 0x1862)
Apr 26 05:56:52 my-host prometheus[29830]:         /usr/local/go/src/bytes/buffer.go:145 +0x16f fp=0xc4305b59b8 sp=0xc4305b5968 pc=0x4eac0f
Apr 26 05:56:52 my-host prometheus[29830]: bytes.(*Buffer).ReadFrom(0xc1e91fc720, 0x257c580, 0xc60be2ab00, 0x7fbe5f528798, 0xc1e91fc720, 0x1)
Apr 26 05:56:52 my-host prometheus[29830]:         /usr/local/go/src/bytes/buffer.go:205 +0x4b fp=0xc4305b5a28 sp=0xc4305b59b8 pc=0x4eb0bb
Apr 26 05:56:52 my-host prometheus[29830]: io.copyBuffer(0x257c500, 0xc1e91fc720, 0x257c580, 0xc60be2ab00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fbd8d492820)
```

**Comment by simonpasquier** [comment] 2019-04-30 08:24
Thanks for the detailed report! It looks like the regression should be fixed in Go 1.12.5 which is slated for May 1st (https://github.com/kubernetes/kubernetes/issues/75833#issuecomment-487830238). Once it is available, could you build a new binary from it and tell us if it fixes the problem? I can assist if you need.

**Comment by bismarck** [comment] 2019-04-30 14:02
Sure thing!  We will run a new build when Go 1.12.5 comes out.  We can currently work around the issue by setting the environment variable `GODEBUG=madvdontneed=1`, which forces [Go 1.11 memory behavior](https://golang.org/doc/go1.12#runtime).

**Comment by simonpasquier** [comment] 2019-05-07 07:51
@bismarck 1.12.5 is out if you want to try!

**Comment by bismarck** [comment] 2019-05-07 17:06
Just got Prometheus 2.9.2 built with Go 1.12.5 running.  It's looking much better (RSS flattened out much quicker and lower).  Will post results in a couple hours.

**Comment by bismarck** [comment] 2019-05-07 20:46
@simonpasquier Here's what it looks like after a couple hours:

![go-1 12 5](https://user-images.githubusercontent.com/1072760/57331691-362a2a00-70e7-11e9-8b55-deed9247e272.png)

I am guessing we're not getting an official Prometheus build with 1.12.5 until the v2.10 release?

**Comment by brian-brazil** [comment] 2019-05-07 20:55
We're two weeks away from 2.10, this doesn't seem to be hitting many people, there's a workaround, and there's nothing else that needs to to be released. As-is I don't plan on doing a 2.9.3.

**Comment by simonpasquier** [comment] 2019-05-09 08:17
Thanks for the follow-up @bismarck

**Comment by cstyan** [comment] 2019-09-20 23:57
Sounds like this can be closed?

**Comment by beorn7** [comment] 2019-09-21 12:23
Agreed.

**Closed by beorn7** 2019-09-21 12:23 UTC
