### ISSUE TITLE
WAL watcher replay in agent mode takes significantly more time since 2.45

### ISSUE THREAD

**Issue by jlevesy** [prometheus/prometheus#13111] opened 2023-11-08 17:39 UTC
### What did you do?

Hello 👋 

I'm not sure this is a use case you're willing to support, so feel free to reclassify // close this 😄. But I'm wondering if this issue does not impact all agents with existing data on disk, so here I go anyway 😁.

Let met give you a bit of context: 

- We're using a pair of Prometheus instances in agent mode in our Kubernetes clusters, and run a leader election between them using a sidecar I wrote called [prometheus-elector](https://github.com/jlevesy/prometheus-elector) so that we only have one replica sending samples.
- Both the replicas have persistent volumes attached, which means that they always retain some (likely stale) data on disk.
- This sidecar generates a Prometheus configuration based on the leader status of the pod
  - If the pod is follower, it generates a minimal configuration so that Prometheus actually starts and scraps itself
  - If the pod is leader, it generates a full configuration with all our `scrape_configs` and  a `remote_write` target so that the Prometheus container starts collecting and sending samples to our remote storage.
- When the pod is promoted leader, `prometheus-elector` regenerates an actual Prometheus configuration, writes it on disk then tells the `prometheus` container to reload its configuration with the API.
- This makes Prometheus create a WAL watcher which replays all the WAL from disk and starts sending samples . For any versions `<= 2.44.0`, the [WAL watcher replay](https://github.com/prometheus/prometheus/blob/v2.45.0/tsdb/wlog/watcher.go#L274) took `~10s`. This gave us decent fail-over time when the leading replica went down.
- But when we tried to upgrade to a version `>= 2.45.0`, we started to notice that WAL  watcher is now taking `~5m` to catch up when a replica is elected leader(for a similar amount of segments), which becomes problematic because it makes the agent stop sending samples during the replay then then creates a surge of samples sent after the WAL is fully replayed, causing the remote storage to reject some of the sent samples 😭.

I believe this change of behavior was introduced  https://github.com/prometheus/prometheus/pull/11949.

- In 2.44, the [watch method](https://github.com/prometheus/prometheus/blob/v2.44.0/tsdb/wlog/watcher.go#L336) was calling [readSegment](https://github.com/prometheus/prometheus/blob/v2.44.0/tsdb/wlog/watcher.go#L425) every [readPeriod (10ms)](https://github.com/prometheus/prometheus/blob/v2.44.0/tsdb/wlog/watcher.go#L37)... it was actively polling and eating CPU I suppose :D. 
- Now in 2.45+ this behavior was changed to actually rely on an external actor calling [Notify](https://github.com/prometheus/prometheus/blob/v2.45.0/tsdb/wlog/watcher.go#L194) when a new segment needs to be read. And [relies on a 15s timeout to call](https://github.com/prometheus/prometheus/blob/v2.45.0/tsdb/wlog/watcher.go#L480) `readSegment`.
- But as far as I understand this PR (I'm not 100% sure of this 😅),  in agent mode, nobody actually calls `Notify` anymore, so we end up reading one segment every 15s, causing the WAL to take a much longer time to be replayed in our case.  Running Prometheus in debug mode higlighted that by printing this [debug line every 15s](https://github.com/prometheus/prometheus/blob/v2.45.0/tsdb/wlog/watcher.go#L297)  (see the attached logs extract)
- EDIT: rolling out [a v2.47.2 with this stupid patch](https://github.com/jlevesy/prometheus/commit/a740b6b6b973536c14332f2542eedc6f2f5feab5) restores the previous behavior. 

I would be happy to know if you consider this as a bug and if you see any option for fixing this. With a bit of guidance I would be happy to contribute it 😁.

Thanks anyway for your work (and time reading this 😅)!

### What did you expect to see?

WAL replay  in agent mode happening within a """decent""" time, in the observed cases roughly 10s.

### What did you see instead? Under which circumstances?

WAL replay taking ~5minutes, and a surge of samples being sent after the replay for a similar amount of segments to replay.

(under the circumstances explained above)

### Prometheus version

```text
>= v2.45.0
```

### Logs

```text
With 2.44 WAL replay takes ~10s

ts=2023-11-08T13:40:30.295Z caller=dedupe.go:112 component=remote level=info remote_name=mimir_remote_write url=http://write.mimir.local/api/v1/push msg="Replaying WAL" queue=mimir_remote_write
ts=2023-11-08T13:40:30.295Z caller=dedupe.go:112 component=remote level=debug remote_name=mimir_remote_write url=http://write.mimir.local/api/v1/push msg="Reading checkpoint" dir=data-agent/wal/checkpoint.00016830
....
ts=2023-11-08T13:40:33.635Z caller=dedupe.go:112 component=remote level=debug remote_name=mimir_remote_write url=http://write.mimir.local/api/v1/push msg="Tailing WAL" lastCheckpoint=data-agent/wal/checkpoint.00016830 checkpointIndex=16830 currentSegment=16831 lastSegment=16845 
ts=2023-11-08T13:40:33.636Z caller=dedupe.go:112 component=remote level=debug remote_name=mimir_remote_write url=http://write.mimir.local/api/v1/push msg="Processing segment" currentSegment=16831
ts=2023-11-08T13:40:34.138Z caller=dedupe.go:112 component=remote level=debug remote_name=mimir_remote_write url=http://write.mimir.local/api/v1/push msg="Processing segment" currentSegment=16832
ts=2023-11-08T13:40:34.667Z caller=dedupe.go:112 component=remote level=debug remote_name=mimir_remote_write url=http://write.mimir.local/api/v1/push msg="Processing segment" currentSegment=16833
...
ts=2023-11-08T13:40:41.191Z caller=dedupe.go:112 component=remote level=info remote_name=mimir_remote_write url=http://write.mimir.local/api/v1/push msg="Done replaying WAL" duration=10.896565194s

With 2.45, WAL replay takes ~5m, please note the ~15s interval between two "Processing segment" log.

ts=2023-11-08T15:05:15.553Z caller=dedupe.go:112 component=remote level=info remote_name=mimir_remote_write url=http://write.mimir.local/api/v1/push msg="Replaying WAL" queue=mimir_remote_write
ts=2023-11-08T15:05:15.553Z caller=dedupe.go:112 component=remote level=debug remote_name=mimir_remote_write url=http://write.mimir.local/api/v1/push msg="Reading checkpoint" dir=data-agent/wal/checkpoint.00016830
...
ts=2023-11-08T15:05:18.849Z caller=dedupe.go:112 component=remote level=debug remote_name=mimir_remote_write url=http://write.mimir.local/api/v1/push msg="Tailing WAL" lastCheckpoint=data-agent/wal/checkpoint.00016830 checkpointIndex=16830 currentSegment=16831 lastSegment=16852
ts=2023-11-08T15:05:18.849Z caller=dedupe.go:112 component=remote level=debug remote_name=mimir_remote_write url=http://write.mimir.local/api/v1/push msg="Processing segment" currentSegment=16831
ts=2023-11-08T15:05:33.850Z caller=dedupe.go:112 component=remote level=debug remote_name=mimir_remote_write url=http://write.mimir.local/api/v1/push msg="Watcher is reading the WAL due to timeout, haven't received any write notifications recently" timeout=15s
ts=2023-11-08T15:05:34.352Z caller=dedupe.go:112 component=remote level=debug remote_name=mimir_remote_write url=http://write.mimir.local/api/v1/push msg="Processing segment" currentSegment=16832
ts=2023-11-08T15:05:49.838Z caller=dedupe.go:112 component=remote level=debug remote_name=mimir_remote_write url=http://write.mimir.local/api/v1/push msg="Processing segment" currentSegment=16833
ts=2023-11-08T15:06:05.358Z caller=dedupe.go:112 component=remote level=debug remote_name=mimir_remote_write url=http://write.mimir.local/api/v1/push msg="Processing segment" currentSegment=16834
ts=2023-11-08T15:06:20.851Z caller=dedupe.go:112 component=remote level=debug remote_name=mimir_remote_write url=http://write.mimir.local/api/v1/push msg="Processing segment" currentSegment=16835
ts=2023-11-08T15:06:35.852Z caller=dedupe.go:112 component=remote level=debug remote_name=mimir_remote_write url=http://write.mimir.local/api/v1/push msg="Watcher is reading the WAL due to timeout, haven't received any write notifications recently" timeout=15s
ts=2023-11-08T15:06:36.348Z caller=dedupe.go:112 component=remote level=debug remote_name=mimir_remote_write url=http://write.mimir.local/api/v1/push msg="Processing segment" currentSegment=16836
...
ts=2023-11-08T15:10:58.599Z caller=dedupe.go:112 component=remote level=info remote_name=mimir_remote_write url=http://write.mimir.local/api/v1/push msg="Done replaying WAL" duration=5m43.046537509s
```

**Comment by cstyan** [comment] 2023-11-24 06:59
> But as far as I understand this PR (I'm not 100% sure of this 😅), in agent mode, nobody actually calls Notify anymore, so we end up reading one segment every 15s, causing the WAL to take a much longer time to be replayed in our case. Running Prometheus in debug mode higlighted that by printing this [debug line every 15s](https://github.com/prometheus/prometheus/blob/v2.45.0/tsdb/wlog/watcher.go#L297) (see the attached logs extract)

If we did indeed miss the `Notify` call for the agent mode codepath that's a bug and a fix would be more than welcome. While your "hack" :)  works, I think the correct fix is just adding a `db.SetWriteNotified(remoteStorage)` call between [these two lines](https://github.com/prometheus/prometheus/blob/main/cmd/prometheus/main.go#L1129-L1130).

**Comment by jlevesy** [comment] 2023-11-24 08:34
Something like [this](https://github.com/prometheus/prometheus/compare/main...jlevesy:prometheus:jly/13111/actual-fix) ?

**Comment by cstyan** [comment] 2023-11-24 21:55
@jlevesy good catch, honestly I'm surprised this wasn't reported already, oops.
> What I did also here is making Watcher.watch call readSegment synchronously and early return if we're not tailing. My reasoning here mostly boils down to "hey, why waiting if the data is on disk?". This did the trick but I suspect this change is not without consequences. What do you think about this?

No you're correct, I think this is the right fix. The two timeout periods feels less correct to me. I'm happy to take your changes in via a PR. We should include a test like `BenchmarkStartup` but create a wal dir of some fixed amount of samples/WAL segment files, and then ensure that the time from start to end is less than the 15 timeout period. I don't think there are any consequences of making this change tbh.

> agent.DB doesn't support working with a Notifier, so when should we call Notify in agent.DB then? I went for appender.Commit here but it doesn't solve my issues as this will only be called based on the scrape interval (~15s) if I'm correct 😅

Again, good catch. You're right, `Commit` would only be called for data written to the tsdb after we startup, so your suggested fix above is what we need _in addition to_ including the notify call.

**Comment by jlevesy** [comment] 2023-11-25 10:01
PR is away 🎉  

Thanks for your help!

**Comment by jeespers** [comment] 2023-11-27 11:38
@jlevesy Great work finding the root cause and suggesting a proper solution.
I hope the [PR](https://github.com/prometheus/prometheus/pull/13188) gets a timely review from the code-owners once the fix is tested 🙏 
https://github.com/prometheus/prometheus/blob/965e603fa792bca0900ac76eb45ae84c81af1cdf/.github/CODEOWNERS#L6

**Comment by Leegin-darknight** [comment] 2023-12-06 07:06
@jlevesy Brilliant work. We are also facing the same issue after we moved to 2.45. It has been seriously impacting the availability when both the Prometheus pods go OOM killed and they try to replay wal for a very long time. In my setup, I can see it has taken 32 mins as well.
![image](https://github.com/prometheus/prometheus/assets/114397475/a2b92e4c-d93b-4b3e-b2c8-7d21e143fb65)

This fix is still unreleased. When can we expect the next release. This fix would help us a lot.

**Comment by cstyan** [comment] 2023-12-06 17:15
Our releases are roughly every 6 weeks: https://github.com/prometheus/prometheus/blob/main/RELEASE.md

The short answer is "soon". In the mean time you could roll back to 2.47.x or build from [this](https://github.com/prometheus/prometheus/pull/13251) PR.

**Comment by cstyan** [comment] 2024-02-06 17:28
closing since the relevant PRs are merged and we backported + have had additional release since then

**Closed by cstyan** 2024-02-06 17:28 UTC
