### ISSUE TITLE
Visualizing tarjets "not happy" if you have more than 20 jobs defined

### ISSUE THREAD

**Issue by pablolanchez** [prometheus/prometheus#14107] opened 2024-05-15 16:24 UTC
### What did you do?

I configured prometheus.yml with 21 different jobs

### What did you expect to see?

In Prometheus web UI, in status->target, up until 20 jobs I saw (by default) all scraping jobs.
So I hopped for the same behavior for more than 20 jobs.

### What did you see instead? Under which circumstances?

When I added the 21 st job, something "got broken" and the visualization started showing (by defalt) only the first scrap job. In my case `alertmanager`
![image](https://github.com/prometheus/prometheus/assets/136340428/a568cb6d-942e-4eaa-82e0-9e3ecf09f856)

Now (with more than 20 jobs), if I want to see all the scrap jobs, I have to `Clear selection` in the filter first.
![image](https://github.com/prometheus/prometheus/assets/136340428/85ab9b64-7129-4318-a67b-0d1c6ba77115)

### System information

RHEL 9.2

### Prometheus version

```text
prometheus, version 2.51.1 (branch: HEAD, revision: 855b5ac4b80956874eb1790a04c92327f2f99e38)
  build user:       root@d3785d7783f2
  build date:       20240328-09:27:30
  go version:       go1.22.1
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

**Comment by machine424** [comment] 2024-05-15 20:29
This seems to be a duplicate of https://github.com/prometheus/prometheus/issues/13413

**Closed** 2024-05-15 20:44 UTC
