### ISSUE TITLE
UI: Filter in service discovery page has a weird behaviour

### ISSUE THREAD

**Issue by Nexucis** [prometheus/prometheus#10458] opened 2022-03-16 17:22 UTC
**What did you do?**

We were trying to filter some targets in the service discovery page, when we found that using a pattern shouldn't match anything, is still returning/displaying the dropped target

<img width="565" alt="image" src="https://user-images.githubusercontent.com/4548045/158649646-1d1ac207-e4d9-4527-8736-eb8d6bdbeb7c.png">

**What did you expect to see?**

When the pattern doesn't match any target, then it shouldn't display anything

**Environment**

* Prometheus version:

	v2.33.5

/cc @AntoineThebaud

**Comment by juliusv** [comment] 2022-05-04 16:15
Hmmm, it's unclear what the expected behavior *should* be. I can well imagine that for some people it might be useful to search dropped ones as well, especially if they want to confirm whether they existed at all before dropping if they are unexpectedly missing.

**Comment by AntoineThebaud** [comment] 2022-05-04 16:31
That's actually the point of this proposal @juliusv, today you can not easily search among dropped targets because the filter is ignored, so when you have thousands of dropped targets like in the example above & pagination applying, it's really difficult to narrow down to a specific dropped target.

**Comment by juliusv** [comment] 2022-05-04 18:10
Ah I misunderstood. Sounds good!

**Comment by krajorama** [comment] 2024-08-27 11:45
Hello from the bug scrub,

is this still relevant for the new UI @juliusv  @Nexucis  ?

**Comment by juliusv** [comment] 2024-08-30 13:11
This all works a bit differently in the new UI, but as far as I can see it works as I would expect at least :) So closing this.

**Closed by juliusv** 2024-08-30 13:11 UTC
Labels: kind/bug, component/ui
