### ISSUE TITLE
Empty stretches in timeseries are displayed as if they had data

### ISSUE THREAD

**Issue by RichiH** [prometheus/prometheus#1276] opened 2015-12-28 08:34 UTC
Due to https://github.com/prometheus/prometheus/issues/1275 and the holidays, I have an extended gap in my load timeseries. When displaying this as a graph, it's not immediately obvious that I have a gap here:

![load_graph](https://cloud.githubusercontent.com/assets/754723/12015988/78f898b2-ad45-11e5-83d7-e546930a36a8.png)

Given Prometheus' design, I am not sure if it's reasonably possible to store the information that data is missing now, and that's fine. Detecting $long stretches of empty data should be possible during graphing, though.

**Comment by brian-brazil** [comment] 2015-12-28 11:10
Dupe of #345

**Closed by brian-brazil** 2015-12-28 11:10 UTC
