### ISSUE TITLE
Implement oauth2 using refresh_token

### ISSUE THREAD

**Issue by SindhuraGowri** [prometheus/prometheus#10339] opened 2022-02-22 17:45 UTC
## Proposal
**Use case. Why is this important?**

Current implementation of oauth2 uses client_credentials (client_id and client_secret) https://www.oauth.com/oauth2-servers/access-tokens/client-credentials/ but for oauth2 authentication using refresh_token requires (refresh_token secret) https://www.oauth.com/oauth2-servers/access-tokens/refreshing-access-tokens/. 
When the endpoint has oauth2 authentication using refresh_token grant type, then we need to fetch access_token from user provided refresh_token secret and then hit the endpoint url.
Hence we shall add the support for oauth2 authentication using refresh_token along with client_credentials.

**Comment by SindhuraGowri** [comment] 2022-02-22 17:48
I am working on this enhancement and the proposed design is to introduce **refresh_token** and **grant_type** attributes in the oauth2 - https://prometheus.io/docs/prometheus/latest/configuration/configuration/#oauth2 and fetch access_token from given refresh_token or client_credentials

**Comment by roidelapluie** [comment] 2022-02-22 20:13
What is your usecase? refresh_token is something that a client gets when it authenticates for the first time. This should not be used in a configuration file. Additionally, I'd like to keep the fact that our oauth implementation is only using golang.org/x/ and stdlib libraries.

**Comment by SindhuraGowri** [comment] 2022-02-23 09:41
Usecase -

We have an endpoint with oauth2 authentication which needs to be scraped by
prometheus serviceMonitor.  This oauth2 authentication is based on
refresh_token
https://www.oauth.com/oauth2-servers/access-tokens/refreshing-access-tokens/
This refresh_token(long lived) generation is one time effort but the
endpoint is only accessed using the access_token which is generated by
refresh_token and token_url.
Here we don't use client credentials for auth, hence we need oauth2 to
support refresh_token based authentication.

We have to first generate *access_token* from the token_url using above
described refresh_token, then use this access_token to access the
authenticated endpoint which needs to be scraped. Please let me know if
this is possible.

Thanks,
Sindhura

**Comment by SindhuraGowri** [comment] 2022-02-23 13:07
Process - We have an authenticated (oauth2 - refresh-token based - https://www.oauth.com/oauth2-servers/access-tokens/refreshing-access-tokens/ ) endpoint that needs to be scraped by prometheus-operator. We actually get the refresh_token for the first time from the client_credentials. Using this refresh_token alone we need to hit the token_url to get  the access_token using which we can access the authenticated endpoint. I was thinking if we can use below library for our usecase. Please correct me if I am wrong.
https://pkg.go.dev/golang.org/x/oauth2#Token

**Comment by SindhuraGowri** [comment] 2022-02-24 17:40
As suggested to use stdlib libraries, I looked at the oauth2 token library and I believe that we can use https://pkg.go.dev/golang.org/x/oauth2#Token for implementation of refreshing access_tokens for oauth2 auth in prometheus repo.

@roidelapluie could you please confirm if we can use above go oauth token library https://github.com/golang/oauth2/blob/2e8d9340160224d36fd555eaf8837240a7e239a7/internal/token.go for our usecase  (refreshing access_tokens).

Also please let me know if I can proceed with implementing this change in this repo.
Thanks.

**Comment by roidelapluie** [comment] 2022-02-24 18:37
This is not a roundtripper. It sounds like to me that you are not using oauth2 as intended. You could try using a proxy.

**Comment by SindhuraGowri** [comment] 2022-03-08 03:55
We believe that we are using OAuth2 as intended. We have used https://datatracker.ietf.org/doc/html/rfc6749#section-6 logic in our service.
After the service is deployed, we generate long-lived refresh_token (one time effort) using client_id. We use this refresh_token to regenerate access_token and this short lived access_token is used to hit the authenticated endpoint for metrics.

To clarify, we generate refresh_token as part of our deployment and store it in secret (one-time) - this transaction is done by our service. Only the generation of access_token using the provided refresh_token and hitting the endpoint needs to be taken care by the prometheus.

Please let me know if you have any queries/ need more information. Also can you please describe more on the proxy that you have mentioned in the previous comment.

**Comment by SindhuraGowri** [comment] 2022-03-08 04:00
We believe that we are using OAuth2 as intended. We have used https://datatracker.ietf.org/doc/html/rfc6749#section-6 logic in our service.
After the service is deployed, we generate long-lived refresh_token (one time effort) using client_id. We use this refresh_token to regenerate access_token and this short lived access_token is used to hit the authenticated endpoint for metrics.

To clarify, we generate refresh_token as part of our deployment and store it in secret (one-time) - this transaction is done by our service. Only the generation of access_token using the provided refresh_token and hitting the endpoint needs to be taken care by the prometheus.

@roidelapluie Please let me know if you have any queries/ need more information. Also can you please describe more on the proxy that you have mentioned in the previous comment.

**Comment by roidelapluie** [comment] 2022-03-08 13:24
I am afraid that it's not possible to follow only part of the RFC.
It sounds like you are ignoring the protocol flow section: https://datatracker.ietf.org/doc/html/rfc6749#section-1.2
Your usecase does not match what is in the RFC because you have multiple clients. Sadly, we can't support that in Prometheus.

**Comment by bboreham** [comment] 2024-08-20 11:57
Hello from the bug-scrub! No update in over two years, so closing.

**Closed by bboreham** 2024-08-20 11:57 UTC
Labels: kind/more-info-needed
