### ISSUE TITLE
Metrics created by rules should keep the timestamp

### ISSUE THREAD

**Issue by grobie** [prometheus/prometheus#386] opened 2014-03-28 20:55 UTC
When using a rule expression to create a metric, it shouldn't matter how long the server needs to create the new data, datapoints should be at added at same time. At the moment, rule created metrics lag behind.

These two graphs show the same data, one queries the times eries directly `sum(foo) by (bar)`, the other one uses the rule defined metric: `job:foo_by_bar:sum`.

![screenshot from 2014-03-28 16 52 26](https://cloud.githubusercontent.com/assets/3432/2555167/466412aa-b6bb-11e3-82d6-0e10dd6b09b1.png)

**Comment by juliusv** [comment] 2015-07-22 14:28
The asynchronous storage appends are fixed (except for the case of completely new time series appearing during a rule evaluation cycle and not being indexed yet), and the other timestamp issues here are basically working as intended for now (or tracked in other issues). Closing this one.

**Closed by juliusv** 2015-07-22 14:28 UTC
