### ISSUE TITLE
"Context deadline exceeded" for responsive target

### ISSUE THREAD

**Issue by AlexRudd** [prometheus/prometheus#2459] opened 2017-03-01 14:45 UTC
**What did you do?**

Tried to run Prometheus server in a docker container and scrape metrics from a node_exporter instance running in a separate but linked container (see environment section.)

Used a basic config which scrapes the linked container, via its container name dns address, every 10 seconds.

Noticed that this very basic target was showing as DOWN in the Prometheus dashboard targets view, with the error: "context deadline exceeded"

I attached to the running Prometheus container and timed a manual scrape of the target using `time` and `wget`, this worked as expected:

```sh
$ docker exec prometheus time wget -qO- http://node_exporter:9100/metrics
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0.000302033
go_gc_duration_seconds{quantile="0.25"} 0.0005395150000000001
... (other metrics) ...
real	0m 0.01s
user	0m 0.00s
sys	0m 0.00s
```

Created a separate target group with `scrape_interval` and `scrape_timeout` both increased to 30s but targeted still at the same node_exporter instance. Scrapes for this group are successful but appear to take a long time (Last Scrape reported as > 36s ago which I assume means the scrape took upwards of 6 seconds from Prometheus' perspective.)

![image](https://cloud.githubusercontent.com/assets/3588652/23464180/039ac3a8-fe8c-11e6-98f5-75dfca5bb1c1.png)

**What did you expect to see?**

Both target groups reporting as UP and scrapes completing quickly

**What did you see instead? Under which circumstances?**

DOWN "context deadline exceeded" for the 10s scrape group

**Environment**

Recreate my exact environment:

```sh
# Run monitoring (node_exporter + prometheus server)
docker run --name "node_exporter" -d prom/node-exporter

# Write config into file for mounting into prometheus container
mkdir -p /tmp/prometheus/
cat << EOF > /tmp/prometheus/prometheus.yml
---
global:
  scrape_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'defaults'
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          group: 'defaults'
          
  - job_name: 'increased_timeout'
    scrape_interval: 30s
    scrape_timeout: 30s
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          group: 'increased_timeout'
EOF

docker run --name "prometheus" \
  -d \
  -p 9090:9090 \
  --link node_exporter:node_exporter \
  -v /tmp/prometheus/prometheus.yml:/prometheus.yml \
  -v /tmp/prometheus/data:/data \
  prom/prometheus:v1.5.2 \
  -storage.local.path=/data \
  -config.file=/prometheus.yml

# Open http://localhost:9090 in your browser and look at the Targets section.

# Stop and remove containers:
docker stop node_exporter prometheus
docker rm node_exporter prometheus
```

* Prometheus version: 

```sh
$ docker run -ti prom/prometheus:v1.5.2 -version
prometheus, version 1.5.2 (branch: master, revision: bd1182d29f462c39544f94cc822830e1c64cf55b)
  build user:       root@1a01c5f68840
  build date:       20170210-16:23:28
  go version:       go1.7.5
```

* Prometheus configuration file:

```yml
---
global:
  scrape_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'defaults'
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          group: 'defaults'
          
  - job_name: 'increased_timeout'
    scrape_interval: 30s
    scrape_timeout: 30s
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          group: 'increased_timeout'
```

* Logs:
```
time="2017-03-01T11:53:25Z" level=info msg="Starting prometheus (version=1.5.2, branch=master, revision=bd1182d29f462c39544f94cc822830e1c64cf55b)" source="main.go:75" 
time="2017-03-01T11:53:25Z" level=info msg="Build context (go=go1.7.5, user=root@1a01c5f68840, date=20170210-16:23:28)" source="main.go:76" 
time="2017-03-01T11:53:25Z" level=info msg="Loading configuration file /prometheus.yml" source="main.go:248" 
time="2017-03-01T11:53:26Z" level=info msg="Loading series map and head chunks..." source="storage.go:373" 
time="2017-03-01T11:53:26Z" level=info msg="1434 series loaded." source="storage.go:378" 
time="2017-03-01T11:53:26Z" level=info msg="Listening on :9090" source="web.go:259" 
time="2017-03-01T11:53:26Z" level=info msg="Starting target manager..." source="targetmanager.go:61" 
time="2017-03-01T11:58:26Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:612" 
time="2017-03-01T11:58:26Z" level=info msg="Done checkpointing in-memory metrics and chunks in 107.457463ms." source="persistence.go:639" 
time="2017-03-01T12:03:26Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:612" 
time="2017-03-01T12:03:26Z" level=info msg="Done checkpointing in-memory metrics and chunks in 97.668263ms." source="persistence.go:639"
...
```

Nothing which seems to be relevant in the logs.

Hopefully I'm not doing anything obviously wrong!

Thanks

**Comment by juliusv** [comment] 2017-03-01 20:08
Hm, @alexellis mentioned that he had similar problems with Prometheus on Docker - he couldn't even scrape Prometheus itself at `localhost`. Alex, did you find a solution to that?

@AlexRudd I used your exact steps to reproduce your scenario and it works for me. I wonder if Docker broke something networking-related in recent versions. I'm still on Docker 1.12.1. This might be one of these cases where you want to pull out Wireshark or tcpdump and look at what's really happening on the network.

**Comment by alexellis** [comment] 2017-03-01 20:19
I was seeing the same error with the latest docker images for Prometheus. I thought it was because I was running it as a `docker stack` i.e. docker swarm service.

**Comment by juliusv** [comment] 2017-03-01 20:25
It does work for me with exactly the same Prometheus version mentioned here btw., so I suspect it's Docker-related. But since I can't reproduce, it would be cool if someone who sees the problem can dig into actual packet traces to see what's going on.

**Comment by AlexRudd** [comment] 2017-03-01 22:49
Ah, I didn't think to check my docker version!

I just tried my reproduction steps at home and it worked fine:

```
$ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

I'll check what version I'm on at work tomorrow and do some digging through Docker's issues.

**Comment by AlexRudd** [comment] 2017-03-02 17:55
So at work I'm running:

```
$ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:32:39 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:32:39 2017
 OS/Arch:      linux/amd64
```

I upgraded to the latest Docker (now Docker CE) and still get the same "context deadline exceeded" error in Prometheus:

```
$ docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:01:32 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:01:32 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by juliusv** [comment] 2017-03-02 22:48
Then I'll have to refer to "But since I can't reproduce, it would be cool if someone who sees the problem can dig into actual packet traces to see what's going on." :) It seems it's either a Docker problem, or some weird interaction between how Go resolves things and the way Docker does DNS.

**Comment by agaoglu** [comment] 2017-03-03 12:14
Any chance you might be hitting https://github.com/docker/docker/issues/19866? Seems a lot has changed regarding default bridge network and --link.

**Comment by gesellix** [comment] 2017-03-12 21:35
I get the same error message (context deadline exceeded) on Travis-CI and Docker 1.12.3. I don't use Prometheus, but run integration tests from a Java client against the Docker daemon. The error appears when creating a service and directly afterwards requesting the current tasks. Locally on Docker for Mac 17.03.0-ce-mac2 I cannot reproduce the error.

In other words: I would confirm @juliusv's assumption that this isn't a Prometheus issue - but maybe the Prometheus setup helps to reproduce the issue?

**Comment by juliusv** [comment] 2017-03-12 23:41
Yeah - I think it's safe to close this issue for now, as it's likely a Docker issue. I'd rather ask the Docker folks about it.

**Closed by juliusv** 2017-03-12 23:41 UTC

**Comment by devghai** [comment] 2017-03-27 07:07
Happening in Centos 7.3 in AWS without using docker. This is a very basic setup as the OP reported, with nothing fancy going on, except that i am running everything native. Would be happy to provide any details that might help resolution.

**Comment by prologic** [comment] 2017-07-18 08:51
Ran into a similar problem on Docker 17.03-17.05 ce

These versions of docker have a bug such that connecting the service/container to the host bridge network is harder than it should be.

Work-around:

```#!bash
$ docker network connect bridge <cid_of_prometheus>
```

**Comment by joshpollara** [comment] 2017-09-15 15:54
Ran into the same issue. Amazon Linux 2017.03 no docker. Basic setup.

**Comment by Vivian007** [comment] 2017-10-25 03:53
@juliusv 
   Happening in Ubuntu 16.04  in  CDS cloud without using docker. Noticed that "node_exporter" target was showing as DOWN , with the error: "context deadline exceeded".

Prometheus version:
`
prometheus, version 1.7.1 (branch: master, revision: 3afb3fffa3a29c3de865e1172fb740442e9d0133)
  build user:       root@0aa1b7fc430d
  build date:       20170612-11:44:05
  go version:       go1.8.3
`


Prometheus configuration file:

 `
global:
  scrape_interval:     30s
  evaluation_interval: 30s

  external_labels:
      monitor: 'Video-monitor'

rule_files:
   - "rules/alert.rules"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "10.8.0.12:9093"

scrape_configs:
##  prometheus_job
  - job_name: 'Video_prometheus'
    static_configs:
      - targets: ['192.168.1.13:9090']
        labels:
          alias: video-prometheus

##  node_exporter_job
  - job_name: 'Video_node_exporter'
    scrape_interval: 120s
    scrape_timeout: 120s
    static_configs:
      - targets: ['192.168.1.13:9100']
        labels:
          alias: video-prometheus
      - targets: ['192.168.1.2:9100']
        labels:
          alias: video-master
      - targets: ['192.168.1.3:9100']
        labels:
          alias: video-node01
      - targets: ['192.168.1.4:9100']
        labels:
          alias: video-node02
      - targets: ['192.168.1.5:9100']
        labels:
          alias: video-node03
      ……………………
`

![234](https://user-images.githubusercontent.com/29111297/31979743-ea7b4108-b90d-11e7-9bac-031a99fbbf0b.png)

**Comment by benitogf** [comment] 2017-11-14 08:58
@juliusv found this issue on ubuntu 16.04:

```
docker version
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:04:16 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:02:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
docker ps
4bbab0972d91        prom/node-exporter   "/bin/node_exporte..."   19 minutes ago      Up 19 minutes       0.0.0.0:9100->9100/tcp   prometheus_node-exporter_1
a38bf51d25c6        prom/prometheus      "/bin/prometheus -..."   20 minutes ago      Up 20 minutes       0.0.0.0:9090->9090/tcp   vibrant_brown
```

```
prometheus
State | Labels                     | Last Scrape  | Error
DOWN |  instance="128.199.213.45:9100" | 56.407s ago | context deadline exceeded
```

Scrape interval and timeout set to 30s but no change

**Comment by roberteventival** [comment] 2018-01-31 18:10
Hi, I've had the same problem, but noticed by docker environment is very slow and swapping quite a lot. After adding more RAM and restarting docker, the problem is gone for the moment.

**Comment by dcmspe** [comment] 2018-09-27 21:10
I am experiencing the same issue. 

`CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
c4120abe7244        prometheus          0.03%               21.57MiB / 15.58GiB   0.14%               44.7kB / 128kB      393kB / 0B          21
`

My docker has 15GB of limit, adding more memory could solve the issue?

**Comment by weskinner** [comment] 2018-12-18 22:20
The fix for me was editing the NetworkPolicy associated with the Pod prometheus was trying to scrape.

**Comment by rcsavage** [comment] 2019-02-27 19:55
@weskinner what exactly did you edit in the NetworkPolicy associated with the Pod?   I am seeing the same issue right now, so any advise would help.

**Comment by weskinner** [comment] 2019-02-27 21:11
@rcsavage sorry I'm not remember the specifics.  I just know the NetworkPolicy that applied to that pod was preventing prometheus from accessing it from the monitoring namespace.  Adjusting the labels on the monitoring namespace and/or the selectors in the NP should fix it if that is your problem as well.

**Comment by hemantthorat** [comment] 2019-08-07 11:26
Increasing value of `scrape_timeout` works for me in `prometheus.yml` file.

**Comment by hemantthorat** [comment] 2019-08-07 11:26
Increasing value of `scrape_timeout` works for me in `prometheus.yml` file `global` section.

**Comment by totogo** [comment] 2019-08-09 05:49
I was having this issue due to the firewall settings in AWS. The port in Security Group was not open.

**Comment by luigisainini** [comment] 2019-09-18 10:33
I'm trying to scrape kong metrics but the aws security group port is open and i used a scrape_interval: 30s. Any suggestion? Thanks

**Comment by Slutzky** [comment] 2019-11-26 17:34
In my case, the issue was caused by pod which was in error state due to OOM. I don't know why but after removing the failing pod from the node the Prometheus started to be able to scrape metrics.

**Comment by RdL87** [comment] 2020-01-29 12:57
I had the same problem and i solved it opening tcp ports 9100 and 9101 on AWS security groups.
I hope it can be helpful for you also.

**Comment by lvs071103** [comment] 2020-03-16 02:30
Hi, I've had the same problem
![image](https://user-images.githubusercontent.com/5029708/76718231-0751fb00-6771-11ea-8ec7-3f1a0b618156.png)

**Comment by nagaraju-n** [comment] 2020-12-29 11:05
> I had the same problem and i solved it opening tcp ports 9100 and 9101 on AWS security groups.
> I hope it can be helpful for you also.

Thanks a lot, it worked for me.

**Comment by ragsarang** [comment] 2021-07-16 06:14
I was facing this issue due to max connections reached. I increased the max_connections parameter in database and then released some connections. 
It was able to scrape again.

**Comment by lindenmj** [comment] 2021-11-04 22:30
For future users: I ran into this problem with Docker 20.10.7 on Ubuntu Server 20.04.3. The exporter instance/container was up and I could see the data by going to the /metrics URL. I tried every which way changing scrape times with no luck.

I finally opened up my local firewall ports with `sudo ufw allow <port>` for the exporter instances/containers, like @RdL87 did on AWS, and solved the issue.

**Comment by vetalslepak** [comment] 2021-11-16 14:49
> For future users: I ran into this problem with Docker 20.10.7 on Ubuntu Server 20.04.3. The exporter instance/container was up and I could see the data by going to the /metrics URL. I tried every which way changing scrape times with no luck.
> 
> I finally opened up my local firewall ports with `sudo ufw allow <port>` for the exporter instances/containers, like @RdL87 did on AWS, and solved the issue.

Hi. I have the same problem .. I can follow the link, but it is not transmitted in the grafan. Can you tell us in more detail what you did?

**Comment by lindenmj** [comment] 2021-11-24 22:02
> Hi. I have the same problem .. I can follow the link, but it is not transmitted in the grafan. Can you tell us in more detail what you did?

My problem was that my grafana container wasn't able to reach the container with the exporter, despite bridging them. The exporter was doing its job, I was able to verify that by going to the metrics URL manually. So after reading @RdL87's post, I tried opening up the port on Ubuntu's firewall with that command it did the trick.

**Comment by saran-kumaar** [comment] 2021-12-05 06:30
Is there is a way to monitor whenever the state goes to DOWN state.

**Comment by rthamrin** [comment] 2022-02-07 01:24
mine is a network problem, I installed my node on VirtualBox.  I deactivated the NAT,  I used NAT to supply my internet inside my master, I turn it off and I change to a bridge connection. and everything works smoothly. I hope it will never happen again.
