### ISSUE TITLE
Increased "Out of order" Rule Evaluation Result discards after upgrade

### ISSUE THREAD

**Issue by skolyszewski** [prometheus/prometheus#11484] opened 2022-10-24 11:58 UTC
### What did you do?

Upgraded Prometheus from 2.32.1 to 2.39.1. 

### What did you see instead? Under which circumstances?

We've noticed that warning log lines coming from `rule_manager` started appearing (in huge amounts), like:

```ts=2022-10-24T11:05:02.357Z caller=manager.go:683 level=warn component="rule manager" file=/etc/prometheus/rules/generic/recording/kubernetes/REDACTED.yml group=REDACTED_namespace_http_requests name=namespace:service_http_requests:quantile30s index=1 msg="Rule evaluation result discarded" err="out of order sample" sample="{__name__=\"namespace:service_http_requests:quantile30s\", kubernetes_cluster=\"REDACTED\", namespace=\"REDACTED\", quantile=\"0.10\", service=\"REDACTED\"} => 0.0010526315789473686 @[1666609501649]"```

We have not seen those warning messages before, neither have we observed any problems with evaluating rules. Our meta-monitoring doesn't provide any useful info. There's no elevated CPU/memory usage, no elevated latency. Just a lot of warnings.

### System information

Linux 4.14.276-211.499.amzn2.x86_64 x86_64, Docker version 20.10.13, build a224086 (ECS running on 64bit Amazon Linux 2/3.1.2)

### Prometheus version

```text
prometheus, version 2.39.1 (branch: HEAD, revision: dcd6af9e0d56165c6f5c64ebbc1fae798d24933a)
  build user:       root@273d60c69592
  build date:       20221007-15:57:09
  go version:       go1.19.2
  platform:         linux/amd64
```

### Logs

```text
=2022-10-24T11:05:02.357Z caller=manager.go:683 level=warn component="rule manager" file=/etc/prometheus/rules/generic/recording/kubernetes/REDACTED.yml group=REDACTED_namespace_http_requests name=namespace:service_http_requests:quantile30s index=1 msg="Rule evaluation result discarded" err="out of order sample" sample="{__name__=\"namespace:service_http_requests:quantile30s\", kubernetes_cluster=\"REDACTED\", namespace=\"REDACTED\", quantile=\"0.10\", service=\"REDACTED\"} => 0.0010526315789473686 @[1666609501649]"
```

**Comment by roidelapluie** [comment] 2022-11-08 00:06
Are you reloading the configuration when this happens?

**Comment by beorn7** [comment] 2024-10-15 11:44
Hello from the bug scrub!

Usually, out-of-order ingestion from rules happen if two rules feed into the same series. Not sure if that's the issue here. Since we haven't had any similar reports in almost two years, we assume this isn't a regression in Prometheus. Closing this, but happy to see more evidence in follow-ups.

**Closed by beorn7** 2024-10-15 11:44 UTC
Labels: component/rules
