### ISSUE TITLE
TSDB: Ever growing txRing in 2.27.1

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#9252] opened 2021-08-25 09:35 UTC
we also occur same problem at 2.27.1

{
  "status": "success",
  "data": {
    "version": "2.27.1",
    "revision": "db7f0bcec27bd8aeebad6b08ac849516efa9ae02",
    "branch": "HEAD",
    "buildUser": "root@fd804fbd4f25",
    "buildDate": "20210518-14:17:54",
    "goVersion": "go1.16.4"
  }
}

![image](https://user-images.githubusercontent.com/15689619/130762563-666deca3-b3d8-4719-9e19-a1e35b99c972.png)
![image](https://user-images.githubusercontent.com/15689619/130762671-f901f5b7-7ced-45f6-9203-4be9ba48c808.png)

_Originally posted by @ilixiaocui in https://github.com/prometheus/prometheus/issues/7120#issuecomment-905322514_

**Comment by beorn7** [comment] 2021-08-25 09:39
@ilixiaocui could you graph the low watermark and see if it is changing at all or if it got stuck for good? If the latter, is there anything that happened at that moment with your Prometheus? (Like a long running or failed query or anything interesting logged.)

If you restart your Prometheus, does the problem promptly recur, or does it take a while?

**Comment by roidelapluie** [comment] 2021-08-25 09:51
Closed as duplicate of #9253

**Closed by roidelapluie** 2021-08-25 09:51 UTC

**Comment by ilixiaocui** [comment] 2021-08-25 09:59
> @ilixiaocui could you graph the low watermark and see if it is changing at all or if it got stuck for good? If the latter, is there anything that happened at that moment with your Prometheus? (Like a long running or failed query or anything interesting logged.)
> 
> If you restart your Prometheus, does the problem promptly recur, or does it take a while?


1. It is changing.  
2. In order to keep the scene，I have not rebooting. No query operation was performed when the memory suddenly increased .
![image](https://user-images.githubusercontent.com/15689619/130770182-579d584d-88e5-4b9a-a888-9bdec0783ff9.png)
