### ISSUE TITLE
AWS Signature Version 4 support

### ISSUE THREAD

**Issue by mtanda** [prometheus/prometheus#3008] opened 2017-07-31 10:36 UTC
I want to scrape metrics from AWS API Gateway or S3.

To support this safely, I need to add auth layer in front of these service.
I want to use EC2 IAM role for auth request, so I want to add AWS sign v4 support.
http://docs.aws.amazon.com/general/latest/gr/signature-version-4.html

Using external proxy is one of the workaround, but I don't want to launch such proxy per scrape endpoint.
https://github.com/coreos/aws-auth-proxy

**Comment by brian-brazil** [comment] 2017-07-31 11:11
This is a non-standard authentication mechanism specific to one provider, I think a proxy is the way to go here.

**Comment by brian-brazil** [comment] 2020-03-16 15:07
Closing this off now, a proxy is the best approach here.

**Closed by brian-brazil** 2020-03-16 15:07 UTC
Labels: component/scraping, priority/Pmaybe

**Comment by rakyll** [comment] 2021-03-19 22:55
This is now available via https://github.com/prometheus/prometheus/pull/8509.

**Comment by roidelapluie** [comment] 2021-03-19 23:20
> This is contributed via #8509.

Not quite, we have added support for it in remote write only, not scrape. I don't know how common it is to use this with scrape, but as you are responsible for the endpoint to scrape, you can opt for an already supported auth scheme, like tls certificates. I don't think amazon offers natively sigv4 endpoints. We could reconsider this if/when this happens, e.g. if cloudwatch starts natively exporting prometheus metrics.

**Comment by rakyll** [comment] 2021-03-19 23:44
Right, people keep pointing me to this issue about the lack of SigV4 support but probably no one is reading the description that the issue is about scraping and not remote write -- neither I read the description.

**Comment by roidelapluie** [comment] 2021-03-19 23:48
The first version of Prometheus to support SIGv4 will be the release 2.26. The first release candidate is planned next week around Wednesday.
