### ISSUE TITLE
prometheus server cash

### ISSUE THREAD

**Issue by bizy01** [prometheus/prometheus#9596] opened 2021-10-26 12:54 UTC
prometheus server cash error

level=info ts=2021-10-26T12:47:53.092Z caller=main.go:794 msg="Server is ready to receive web requests."
panic: runtime error: slice bounds out of range [-7783:]

goroutine 740 [running]:
github.com/prometheus/prometheus/tsdb/encoding.(*Decbuf).Skip(...)
	/app/tsdb/encoding/encoding.go:196
github.com/prometheus/prometheus/tsdb/index.(*Writer).writePostingsToTmpFiles(0xc002bac6e0)
	/app/tsdb/index/index.go:891 +0x139c
github.com/prometheus/prometheus/tsdb/index.(*Writer).ensureStage(0xc002bac6e0, 0x3)
	/app/tsdb/index/index.go:378 +0xc5
github.com/prometheus/prometheus/tsdb/index.(*Writer).Close(0xc002bac6e0)
	/app/tsdb/index/index.go:1010 +0x27
github.com/prometheus/prometheus/tsdb.(*LeveledCompactor).write(0xc000dd4b40, {0x7ffeb3720a62, 0x10}, 0xc002ff90e0, {0xc0033de480, 0x3, 0x4})
	/app/tsdb/compact.go:612 +0xdfa
github.com/prometheus/prometheus/tsdb.(*LeveledCompactor).Compact(0xc000dd4b40, {0x7ffeb3720a62, 0x10}, {0xc0033de440, 0x3, 0x2ae4c80}, {0xc002bd8800, 0x4b, 0x58})
	/app/tsdb/compact.go:437 +0x22a
github.com/prometheus/prometheus/tsdb.(*DB).compactBlocks(0xc000de6000)
	/app/tsdb/db.go:1008 +0xdf
github.com/prometheus/prometheus/tsdb.(*DB).Compact(0xc000de6000)
	/app/tsdb/db.go:948 +0x5d2
github.com/prometheus/prometheus/tsdb.(*DB).run(0xc000de6000)
	/app/tsdb/db.go:829 +0x40f
created by github.com/prometheus/prometheus/tsdb.open
	/app/tsdb/db.go:762 +0xe16

**Comment by roidelapluie** [comment] 2021-11-05 16:36
Since you are probably not using a posix-compliant filesystem, I am going to close this issue.

If you can reproduce this issue with a Posix-Compliant file system, please reopen this issue or open a new one, thanks!

**Closed by roidelapluie** 2021-11-05 16:36 UTC

**Comment by bizy01** [comment] 2021-11-09 02:28
> Since you are probably not using a posix-compliant filesystem, I am going to close this issue.
> 
> If you can reproduce this issue with a Posix-Compliant file system, please reopen this issue or open a new one, thanks!

use seaweedfs， now use disk storage not error, thanks
