### ISSUE TITLE
2.4.0 on windows fails due to /\templates\_base.html: file does not exist

### ISSUE THREAD

**Issue by rgl** [prometheus/prometheus#4606] opened 2018-09-14 09:03 UTC
with prometheus 2.4.0 on windows, the default web page, http://localhost:9090/graph, fails with:

```
error reading base template: open /\templates\_base.html: file does not exist
```

any idea how to fix this?

to reproduce, just unpack the binaries, start prometheus, and access the [default web page](http://localhost:9090).

**Comment by gouthamve** [comment] 2018-09-14 09:06
Dupe of https://github.com/prometheus/prometheus/issues/4596 Fix will be out soon, sorry!

**Closed by gouthamve** 2018-09-14 09:06 UTC
