### ISSUE TITLE
Prometheus remote-write should use a DNS resolver that shuffles resulting IPs

### ISSUE THREAD

**Issue by duricanikolic** [prometheus/prometheus#15262] opened 2024-11-01 20:35 UTC
### Scenario
Suppose that we have a bunch of servers deployed in different regions, or availability zones (AZ). To distribute traffic between the servers, there is a load balancer, having a single node in each AZ. Each load balancer node has its own public IP address. When a DNS resolver gets the URL of the load balancer, it returns a list of IP addresses of all load balancer nodes.

We want to execute a certain number of concurrent remote-write requests to the URL of the load balancer.

### Expected behavior

After Prometheus performed the concurrent remote-wrirte requests, data have been spread through all healthy servers in all AZs.

### Actual behavior

In most of the cases, independently from the number of concurrent requests, data have been spread only between the servers of a single AZ.

### What happens?

Prometheus’ remote-write requests are HTTP requests that Prometheus executes by using Go’s [HTTP client](https://pkg.go.dev/net/http#Client). To perform HTTP requests, an HTTP client first chooses a connection from a pool of idle connections, if there is one, or otherwise creates a fresh one, executes the request, and finally gets a response. If the response is successful, and the connection is configured as “keep-alive”, the connection is then put into the idle connections pool, to be reused for another HTTP request. Creation of a fresh connection requires a DNS lookup that sometimes returns multiple IP addresses. When multiple IPs are returned, the HTTP client sequentially tries them in the order they are returned by the resolver. If it is not possible to connect to the first IP address, the HTTP client tries the second one, and so on.

But what happens if a DNS resolver always returns the IP addresses in the same order, and if the first one is always a good one? In that case, it might happen that if multiple concurrent HTTP requests are executed, new TCP connections will be created in a short period of time, all to the same IP address. 

This is exactly the behavior of net's [DefaultResolver](https://cs.opensource.google/go/go/+/refs/tags/go1.23.2:src/net/lookup.go;l=128), the default DNS resolver of the HTTP client, used by Prometheus as well: consecutive lookups for the domain names corresponding to multiple IPs often return the same IP addresses in the same order. 

### Proposed solution

In order to work around the problem explained above, Prometheus might use a custom DNS resolver that shuffles the IP addresses returned by the default DNS before returning them. 

This way, even if a DNS entry is cached, and therefore would give rise to a connection towards its first returned IP address, the shuffling would allow creation of a connection towards another IP address.

**Comment by bboreham** [comment] 2024-11-04 10:53
Unfortunately, your instinct that "this can't possibly be broken everywhere" is wrong.  I had the same reaction, but luckily the situation was explained here: https://daniel.haxx.se/blog/2012/01/03/getaddrinfo-with-round-robin-dns-and-happy-eyeballs/

It doesn't matter what the DNS server does; the client-side follows [RFC3484](https://www.ietf.org/rfc/rfc3484.txt), re-orders results, and picks the same first one every time. This is mentioned in your Wikipedia article.

Yes, the replacement can be in a library.  Maybe one exists already.

**Comment by beorn7** [comment] 2024-11-05 17:14
Thanks @bboreham for that blog post. It connects many dots and at least I understand now where the problem is coming from.

**Comment by bboreham** [comment] 2024-11-22 11:35
Closed by #15329.

**Closed by bboreham** 2024-11-22 11:35 UTC
