### ISSUE TITLE
Feature Request: Generate metrics from the past acording to new recording rules.

### ISSUE THREAD

**Issue by amadeuszkryze** [prometheus/prometheus#6440] opened 2019-12-10 15:27 UTC
## Proposal
It will be very helpful to have some sort of API call to prom server to generate metrics from the past, according to retention rules as a period (of course it there are valid 'raw' metrics) and recording rules as its content. 

**Use case. Why is this important?**
In very dynamic prometheus envs where most metric recording rules (according to [good practices](https://prometheus.io/docs/practices/rules/)) are often changed due to client expectations and needs. So in most cases old metrics are dropped due to its deprecation. And after updating dashboards with new recorded metrics there is no possibility to compare data from the past - like show last 7days of new metrics, even if PromQL query related to this data would return actual valid data.
*“Nice to have” is not a good use case. :)*

**Comment by brian-brazil** [comment] 2019-12-10 16:46
Dupe of #11

**Closed by brian-brazil** 2019-12-10 16:46 UTC
