### ISSUE TITLE
Too many web connections generates zombie tcp connectoins

### ISSUE THREAD

**Issue by ekinolik** [prometheus/prometheus#11610] opened 2022-11-21 22:28 UTC
### What did you do?

When running Prometheus with the default of 512 max web connections and receiving > 512 concurrent connections, Prometheus seems to drop tcp connections in various states.  Netstat shows that there are over 1,500 ESTABLISHED connections to the web port and thousands of connections in failed states.  All other functions of Prometheus (eg: scrapes and alerts) were working as expected.  No CPU or memory contention.

After setting `--web.max-connections` to 1024 the problem was resolved and there are roughly 800 connections with the majority in ESTABLISHED and 0 dropped connections (CLOSE_WAIT).

### What did you expect to see?

* Prometheus return an HTTP 503 or similar error that the server is busy. 
* A steady count of 512 ESTABLISHED connections.
* A metric to track the number of concurrent connections (ie: a gauge of how many used or available connections exist when the most recent connection was made)

### What did you see instead? Under which circumstances?

* Request timeouts
* Failed readiness probes due to connection timeouts and response timeouts
* Connections to the web port in various poor states (see below for a snapshot)
* No more than 512 ESTABLISHED connections
* No logs or metrics indicating the connection limit was hit

Snapshot of the number of connections to port 9090 and their various states with max conns of 512
```
   2680 CLOSE_WAIT
   1573 ESTABLISHED
      1 FIN_WAIT1
   5443 LAST_ACK
      1 LISTEN
    192 SYN_RECV
```

Snapshot of the number of connections to port 9090 and their various states with max conns of 1024
```
    634 ESTABLISHED
      1 LISTEN
    158 SYN_RECV
     13 TIME_WAIT
```

### System information

Linux 5.15.74

### Prometheus version

```text
Version	2.39.1
Revision	dcd6af9e0d56165c6f5c64ebbc1fae798d24933a
Branch	HEAD
BuildUser	root@273d60c69592
BuildDate	20221007-15:57:09
GoVersion	go1.19.2
```

### Prometheus configuration file

```yaml
global:                                        
  evaluation_interval: 30s      
  scrape_interval: 30s  
  external_labels:               
    environment: production                            
  query_log_file: /dev/stdout          
rule_files:          
- /etc/prometheus/rules/prometheus-prometheus-operator-prometheus-rulefiles-0/*.yaml
scrape_configs:                                        
  ...
alerting:
  alert_relabel_configs:
    ...
  alertmanagers:
    ...
```

**Comment by ekinolik** [comment] 2022-12-02 22:26
I've since found that the source of all these connections were ELB TCP health checks.  Using a Cluster ExternalTrafficPolicy for the Prometheus service caused ELB to send out hundreds of health checks per 10s interval, growing based on the number of nodes in the cluster.  Changing this to use a Local ExternalTrafficPolicy (and in turn HTTP health checks) reduced those health checks to 1 per interval and reduced the number of connections on the pod to ~20 total.

**Comment by roidelapluie** [comment] 2022-12-22 22:13
It looks like the issue was caused by excessive connections from the Elastic Load Balancer. Changing the ExternalTrafficPolicy to Local and using HTTP health checks instead of TCP health checks appears to have resolved the issue. Based on this information, I'm going to close this issue. Thank you for reporting it!

**Closed by roidelapluie** 2022-12-22 22:13 UTC
