### ISSUE TITLE
Degraded Query Performance 2.18.1

### ISSUE THREAD

**Issue by bueti** [prometheus/prometheus#7274] opened 2020-05-19 12:38 UTC
**What did you do?**
Upgrade from 2.17.2 to 2.18.1

**What did you expect to see?**
* no performance degradation

**What did you see instead? Under which circumstances?**
* much higher rule evaluation time, cpu usage & memory usage
* Queries didn't finish in time 

**Environment**

* System information:
  * Linux 4.19.104+ x86_64
  * GKE, 1.15.11-gke.1

* Prometheus version:
  * 2.18.1

However, I had to roll back to 2.17.2 since this happened on our production prometheus server.
The pod was deployed with the following helm chart: https://hub.helm.sh/charts/stable/prometheus/11.3.0

**Examples**

The following query finishes in <2 second with 2.17.2 but takes up to 45s to complete with 2.18.1:
```
sort((sum by(app) (rate(http_request_duration_seconds_bucket{le="1",tiers="frontend"}[1m])) + sum by(app) (rate(http_request_duration_seconds_bucket{le="5",tiers="frontend"}[1m]))) / 2 / sum by(app) (rate(http_request_duration_seconds_count{tiers="frontend"}[1m]))) < 0.8
```

![image](https://user-images.githubusercontent.com/383917/82325597-c75efc80-99db-11ea-9751-c265718d87c2.png)

Query times for queries that where `stats.timings.evalTotalTime` >1 over a window of 2hrs:

2.17.2:
![image](https://user-images.githubusercontent.com/383917/82326343-f164ee80-99dc-11ea-9bfb-15877919e2de.png)

2.18.1:
![image](https://user-images.githubusercontent.com/383917/82326356-f9bd2980-99dc-11ea-8db8-8dd9f8c5a8a0.png)

as you can see, all the queries take much longer than before.

**Comment by beorn7** [comment] 2020-05-19 12:42
That's unexpected, to say the least… assigning to @bwplotka as the shepherd of this release.

**Comment by brian-brazil** [comment] 2020-05-19 12:48
I don't see any obvious changes in the changelog that could have done this. Can you share the full query timings, and if you're using remote read?

**Comment by bueti** [comment] 2020-05-19 13:01
to be honest, I am a bit at a loss since I would expect such a degradation to show up not only on our deployment :)

We are not using remote read.

I noticed that there is a huge variance with the same queries:

60s evalTotalTime
```
{"timestamp":1589878998983,"log":{"error":"context deadline exceeded","params":{"end":"2020-05-19T09:02:06.360Z","query":"(sum by(app, handler, endpoint_severity) (rate(http_requests_total{code=~\"^5[0-9]{2}$\"}[30m])) / sum by(app, handler, endpoint_severity) (rate(http_requests_total[30m])) and (sum by(app, handler, endpoint_severity) (alert:http_requests_total:irate4h) >= (1 / 60)) and (sum by(app, handler, endpoint_severity) (alert:http_requests_total:irate4h) < 0.5) unless on(app) application_is_silenced) > 0.2","start":"2020-05-19T09:02:06.360Z","step":0},"ruleGroup":{"file":"/etc/config/alerts","name":"alerts"},"stats":{"timings":{"evalTotalTime":60.011896152,"resultSortTime":0,"queryPreparationTime":0.000643001,"innerEvalTime":0,"execQueueTime":0.000115763,"execTotalTime":60.012084354}},"ts":"2020-05-19T09:03:18.977Z"},"stream":"stdout","docker":{"container_id":"3f7236d89b5a2591c598def28799e57e0765951acd5a4b0945851a209511fceb"},"kubernetes":{"container_name":"prometheus-server","namespace_name":"platform","pod_name":"prometheus-server-85c7df5d5c-w2kmc","pod_id":"64ab6cbb-daf0-4788-9551-258e7b9bb396","labels":{"app":"prometheus","chart":"prometheus-11.3.0","component":"server","heritage":"Tiller","pod-template-hash":"85c7df5d5c","release":"prometheus"},"host":"gke-prod-cherry-prometheus-node-pool-1671fb74-d0xa","master_url":"https://10.34.0.1:443/api","namespace_id":"55ca4bd2-3509-11e9-b219-4201ac10000b"}}
```

24s innerEvalTime
```
{"timestamp":1589882559410,"log":{"params":{"end":"2020-05-19T10:02:06.360Z","query":"(sum by(app, handler, endpoint_severity) (rate(http_requests_total{code=~\"^5[0-9]{2}$\"}[30m])) / sum by(app, handler, endpoint_severity) (rate(http_requests_total[30m])) and (sum by(app, handler, endpoint_severity) (alert:http_requests_total:irate4h) >= (1 / 60)) and (sum by(app, handler, endpoint_severity) (alert:http_requests_total:irate4h) < 0.5) unless on(app) application_is_silenced) > 0.2","start":"2020-05-19T10:02:06.360Z","step":0},"ruleGroup":{"file":"/etc/config/alerts","name":"alerts"},"stats":{"timings":{"evalTotalTime":23.997719799,"resultSortTime":0,"queryPreparationTime":0.000932812,"innerEvalTime":23.99670201,"execQueueTime":0.000143319,"execTotalTime":23.997941177}},"ts":"2020-05-19T10:02:39.409Z"},"stream":"stdout","docker":{"container_id":"3f7236d89b5a2591c598def28799e57e0765951acd5a4b0945851a209511fceb"},"kubernetes":{"container_name":"prometheus-server","namespace_name":"platform","pod_name":"prometheus-server-85c7df5d5c-w2kmc","pod_id":"64ab6cbb-daf0-4788-9551-258e7b9bb396","labels":{"app":"prometheus","chart":"prometheus-11.3.0","component":"server","heritage":"Tiller","pod-template-hash":"85c7df5d5c","release":"prometheus"},"host":"gke-prod-cherry-prometheus-node-pool-1671fb74-d0xa","master_url":"https://10.34.0.1:443/api","namespace_id":"55ca4bd2-3509-11e9-b219-4201ac10000b"}}
```

8s innerEvalTime
```
{"timestamp":1589881704216,"log":{"params":{"end":"2020-05-19T09:48:06.360Z","query":"(sum by(app, handler, endpoint_severity) (rate(http_requests_total{code=~\"^5[0-9]{2}$\"}[30m])) / sum by(app, handler, endpoint_severity) (rate(http_requests_total[30m])) and (sum by(app, handler, endpoint_severity) (alert:http_requests_total:irate4h) >= (1 / 60)) and (sum by(app, handler, endpoint_severity) (alert:http_requests_total:irate4h) < 0.5) unless on(app) application_is_silenced) > 0.2","start":"2020-05-19T09:48:06.360Z","step":0},"ruleGroup":{"file":"/etc/config/alerts","name":"alerts"},"stats":{"timings":{"evalTotalTime":8.965060593,"resultSortTime":0,"queryPreparationTime":0.000752362,"innerEvalTime":8.964214092,"execQueueTime":0.000082374,"execTotalTime":8.965263241}},"ts":"2020-05-19T09:48:24.215Z"},"stream":"stdout","docker":{"container_id":"3f7236d89b5a2591c598def28799e57e0765951acd5a4b0945851a209511fceb"},"kubernetes":{"container_name":"prometheus-server","namespace_name":"platform","pod_name":"prometheus-server-85c7df5d5c-w2kmc","pod_id":"64ab6cbb-daf0-4788-9551-258e7b9bb396","labels":{"app":"prometheus","chart":"prometheus-11.3.0","component":"server","heritage":"Tiller","pod-template-hash":"85c7df5d5c","release":"prometheus"},"host":"gke-prod-cherry-prometheus-node-pool-1671fb74-d0xa","master_url":"https://10.34.0.1:443/api","namespace_id":"55ca4bd2-3509-11e9-b219-4201ac10000b"}}
```

**Comment by brian-brazil** [comment] 2020-05-19 13:18
Hmm, that shouldn't vary like that. How do CPU usage, memory, and disk i/o utilisation look for the machine overall?

**Comment by bueti** [comment] 2020-05-19 13:47
CPU usage increased considerably: 
![image](https://user-images.githubusercontent.com/383917/82332753-16aa2a80-99e6-11ea-9e1f-5eff18768823.png)

Memory a bit (server has 120GB(!)) for 2-4million series:
![image](https://user-images.githubusercontent.com/383917/82332779-1e69cf00-99e6-11ea-8a9c-5d01005a93bc.png)

Disk Operations:
![image](https://user-images.githubusercontent.com/383917/82333615-40178600-99e7-11ea-9525-0a1c54e5d657.png)

Networking:
![image](https://user-images.githubusercontent.com/383917/82333722-63423580-99e7-11ea-8c00-536b7eebdb8f.png)

The pod is on its own node, there shouldn't be CPU starvation caused by another pod.

**Comment by brian-brazil** [comment] 2020-05-19 14:08
How many cores does that machine have? That looks like hitting a ~9 core limit, though that doesn't explain the increase in cpu usage. Has the query rate increased? Can you share a snapshot with https://grafana.com/grafana/dashboards/12054 ?

**Comment by bueti** [comment] 2020-05-19 14:39
The node has 10 CPUs, unfortunately I cannot share a snapshot, Grafana isn't reachable from the internet.

However, I was thinking about the issue a bit and the initial deployment failed because of a wrong `JAEGER_HOST_PORT` environment variable (it was an ip+port combination instead of just a port). Since we don't even have a jaeger agent daemonset deployed on this node I redeployed Prometheus with `JAEGER_DISABLED=true` and now it runs nicely since ~15min on 2.18.1.
I guess having (partial) jaeger environment variables available confused the jaeger client in prometheus and that lead to the performance degradation we saw.

**Comment by brian-brazil** [comment] 2020-05-19 15:56
That sounds plausible, and it is a change in this version. So sounds like there isn't actually a regression in Prometheus.

**Comment by bueti** [comment] 2020-05-19 16:42
feel free to close this issue. from my point of view though, jaeger should be configurable via either a config param or a command line parameter.

**Comment by roidelapluie** [comment] 2020-05-19 16:45
We did not introduce options by purpose as Jaeger is a temporary solution.

**Comment by brian-brazil** [comment] 2020-05-19 17:07
It is configurable in a single way, which happens to be the usual way Jaeger does things. This could have happened to any other binary that happened to have Jaeger linked in.

This isn't an issue in Prometheus anyway.

**Closed by brian-brazil** 2020-05-19 17:07 UTC
Labels: kind/bug
