### ISSUE TITLE
Prometheus 2.0.0-beta.1 container exited unexpectedly

### ISSUE THREAD

**Issue by thirstycrow** [prometheus/prometheus#3078] opened 2017-08-15 09:17 UTC
With the following stderr output：
```
panic: runtime error: integer divide by zero

goroutine 129 [running]:
github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*LeveledCompactor).Plan(0xc4205cad80, 0x1c2b859, 0x5, 0x0, 0xa, 0x10, 0x0, 0x0)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/compact.go:173 +0x621
github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*DB).compact(0xc42014a380, 0xc420021201, 0x0, 0x0)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/db.go:406 +0x2c5
github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*DB).run(0xc42014a380)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/db.go:281 +0x3c6
created by github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.Open
	/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/db.go:250 +0x488
```

**Comment by klausenbusk** [comment] 2017-08-15 20:59
This seems like a duplicate of https://github.com/prometheus/prometheus/issues/3064 , as PR with the fix is already opened: https://github.com/prometheus/tsdb/pull/120

**Comment by brian-brazil** [comment] 2017-08-17 05:06
Closing as dupe.

**Closed by brian-brazil** 2017-08-17 05:06 UTC
