### ISSUE TITLE
PromQL: add `limit` keyword to reduce too much datapoint return 

### ISSUE THREAD

**Issue by Betula-L** [prometheus/prometheus#7485] opened 2020-06-30 09:33 UTC
## Proposal
I'm curious why no `limit` keyword for PromQL. It's a general grammar for other SQL-like language, i.e. `select * from users limit 5`. 
Keyword `limit` is a very useful feature for graph or preview data, an alternative is `topk` or `bottomk` now.

**Use case: preview data structure**

Consider that, user got metric `go_gc_duration_seconds` and do not know `labels` which metrics had, then it need query `go_gc_duration_seconds` to preview some data as follow.
![image](https://user-images.githubusercontent.com/6059935/86107921-14fb7880-baf5-11ea-8b98-e24dcb401f30.png)

Unfortunately,  prometheus fetch over 20000+ series which over 10000+ series is useless and dropped (due to UI limit).

It could reduce query load time and series by add `limit` keyword.

**Use case: avoid too much graph datapoint**

For grafana dashboard, it's no explicit way to keep graph datapoint in a reasonable boundary.

## Possible Solution
Similarly to `topk`, add keyword `limitk(10000, up)` which is without sort option.

**Comment by codesome** [comment] 2020-06-30 09:43
I would see this more as a feature in the query API and not the PromQL itself.

**Comment by brian-brazil** [comment] 2020-06-30 09:45
Things like this have come up before, and returning an arbitrary subset of a results doesn't make sense semantically. There are already topk/bottomk for this.

> It could reduce query load time

It should have very little impact.

**Comment by brian-brazil** [comment] 2020-06-30 09:46
Found it, dupe of #5656.

**Closed by brian-brazil** 2020-06-30 09:46 UTC
Labels: kind/feature, priority/Pmaybe

**Comment by bboreham** [comment] 2020-10-30 09:48
Being discussed again: https://github.com/prometheus/prometheus/issues/7903
