### ISSUE TITLE
reevaluate #2357

### ISSUE THREAD

**Issue by logemann** [prometheus/prometheus#4820] opened 2018-11-05 09:28 UTC
Given all the feedback after the close, mostly arguing in one direction, how about re-evaluating #2357 ? Given the fact that a lot of mainstream open source frameworks have no problems with env var substitution, it still puzzles me why this should be a problem at all. There are most likely 1000 use cases for a feature like that. Especially in the docker context. Spring Boot wouldnt be so popular without that for sure because everyone uses it. They have even more in that regard, they also provide a way of definiting profiles and set them during start as another way of defining several environments.

**Comment by brian-brazil** [comment] 2018-11-05 09:37
We've discussed this many times, and there are no plans to change this. This is a configuration management issue, which is out of scope for Prometheus.

Dupe of #2357

**Closed by brian-brazil** 2018-11-05 09:37 UTC

**Comment by zakkg3** [comment] 2018-11-14 12:03
workaround using confd, feel free to fork / use as inspiration :D
https://github.com/zakkg3/Prometheus-confd
