### ISSUE TITLE
Kubernetes service discovery: support discovering node meta labels when using endpoints as role

### ISSUE THREAD

**Issue by jiachengxu** [prometheus/prometheus#10021] opened 2021-12-15 11:09 UTC
**Use case**
Currently, the node meta labels can only be discovered when you have `node` as role in [`kubernetes_sd_config`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config). It would be helpful if those labels can also be discovered when using `endpoints` as role.
The use case can be for node exporter, which is used for providing node-level metrics, it would be helpful to have node meta labels (nodegroup, etc) set on those metrics. 
This is not really possible for now because the scrape config of node exporter is always using `endpoints` as role. Also when using ServiceMonitor from Prometheus operator,  the generated scrape config is also using `endpoints` as role, so the node meta labels can not be discovered.

Please let me know if this is a valid use case, or there are any approaches that can already support this. I would be more than happy to implement this feature and contribute to the community.

Thanks

**Comment by brancz** [comment] 2021-12-16 08:14
I believe this is a duplicate of https://github.com/prometheus/prometheus/issues/9510, would you agree @jiachengxu?

**Comment by jiachengxu** [comment] 2021-12-16 10:08
@brancz Oh, thanks for pointing this out. Yeah, I agree this is a duplicate one.
/close

**Closed** 2021-12-16 10:08 UTC
Labels: kind/enhancement, priority/Pmaybe, component/service discovery
