### ISSUE TITLE
rate and increase does not work with small changes

### ISSUE THREAD

**Issue by Jgfrausing** [prometheus/prometheus#11144] opened 2022-08-11 12:53 UTC
### What did you do?

I have created a `counterVec` that gets sometimes get incremented. Issue is that `rate`and `increase` returns 0 when the change is really low. 

I have the following Golang code for creating and updating the counter:
```
func NewStateCounter(registerer prometheus.Registerer, country constants.CountryCode, flowType constants.FlowType) (*StateCounterMetrics, error) {
	labels := make(prometheus.Labels, 1)
	labels["country"] = string(country)
	labels["flow_type"] = string(flowType)
	stateCount := prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Namespace:   namespace,
			Subsystem:   "",
			Name:        "state_total",
			Help:        "Count of state transitions",
			ConstLabels: labels,
		}, []string{"from", "to", "userId"})

	err := register(registerer, stateCount)
	if err != nil {
		return nil, errors.WithMessage(err, "failed to create state counter metrics")
	}

	return &StateCounterMetrics{
		stateCount: stateCount,
		country:    country,
	}, nil
}

func (m *StateCounterMetrics) AddStateTransition(from, to constants.FlowState, userId string) {
	m.stateCount.WithLabelValues(string(from), string(to), userId).Inc()
}
```

context: https://cloud-native.slack.com/archives/C167KFM6C/p1660209239010809

### What did you expect to see?

The correct value. I suspect that there could be a rounding error as the rate is very low

### What did you see instead? Under which circumstances?

In the screenshot (Grafana), there are two graphs of the same time period. The first shows the counter for `onboarding_state_total` with `to="started"`. In this time period, the counter goes from 581 to 585, which is an increase of 4. The second graph, I, therefore, expect to say 4. Instead, it lies flat at 0 for this time period. 

![image](https://user-images.githubusercontent.com/14124682/184133706-1df67998-c468-4d61-9467-58bcd52f9e57.png)

### System information

Linux 5.15.48-flatcar x86_64

### Prometheus version

```text
Runtime Information
Start time	Thu, 11 Aug 2022 08:12:04 GMT
Working directory	/prometheus
Configuration reload	Successful
Last successful configuration reload	2022-08-11T08:12:55Z
WAL corruptions	0
Goroutines	2999
GOMAXPROCS	4
GOGC	
GODEBUG	
Storage retention	31d
Build Information
Version	2.37.0
Revision	b41e0750abf5cc18d8233161560731de05199330
Branch	HEAD
BuildUser	root@0ebb6827e27f
BuildDate	20220714-15:13:18
GoVersion	go1.18.4
Alertmanagers
Endpoint
http://alertmanager:9093/api/v2/alerts
```

**Comment by Cosrider** [comment] 2022-08-12 10:08
it will compare with data one hour ago; maybe you can change the time range  10m,30m
try sum(increase(onboarding_state_total{to="stared"}[30m]))

**Comment by Jgfrausing** [comment] 2022-08-29 13:25
No avail. :( 
I found the issue, however. One of the labels is "userID". There are rarely more than 1 or 2 entries with the same user ID, in my data. There must be something iffy with the implementation of the aggregation, as removing that, solved my issue.

**Comment by roidelapluie** [comment] 2022-09-05 12:06
Since the issue is solved, I will close this issue.

**Closed by roidelapluie** 2022-09-05 12:06 UTC
