### ISSUE TITLE
Old Dockerfile shown on docker hub

### ISSUE THREAD

**Issue by steffkes** [prometheus/prometheus#4708] opened 2018-10-08 12:48 UTC
https://github.com/prometheus/prometheus/commit/377a549fe6e262286bea5b9ce933d5cae6504031 fixed the command line flags over a year ago - i've realized that the ["Dockerfile" Tab on docker hub](https://hub.docker.com/r/prom/prometheus/~/dockerfile/) still shows the old/previous version.

I'm not sure this repository is the right entrypoint for hints like this? if not, please let me know where else to go

**Comment by simonpasquier** [comment] 2018-10-08 12:53
Dupe of #3778

**Closed by simonpasquier** 2018-10-08 12:53 UTC

**Comment by steffkes** [comment] 2018-10-08 13:09
Ouch, thanks for the heads up Simon - i didn't see any open issues about it.

**Comment by simonpasquier** [comment] 2018-10-08 13:11
No problem, thanks for taking the time to open an issue!
