### ISSUE TITLE
prometheus-server error panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by nandeeshb09** [prometheus/prometheus#7275] opened 2020-05-19 13:47 UTC
Hi Team,

Need a help on this, as we are getting this error in prometheus and due to this container is restarting.

prometheus server version -- 2.1.0
eks cluster -- 1.13.12

18 19:03:36 prometheus-prod-prometheus-server-77bfbf6c7b-vc75t prometheus-server error panic: runtime error: invalid memory address or nil pointer dereference
May 18 19:03:36 prometheus-prod-prometheus-server-77bfbf6c7b-vc75t prometheus-server [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xaa8152]
May 18 19:03:36 prometheus-prod-prometheus-server-77bfbf6c7b-vc75t prometheus-server goroutine 34089759 [running]:
May 18 19:03:36 prometheus-prod-prometheus-server-77bfbf6c7b-vc75t prometheus-server github.com/prometheus/prometheus/discovery/ec2.(*Discovery).refresh.func2(0xc498e07660, 0x1, 0x0)
	/go/src/github.com/prometheus/prometheus/discovery/ec2/ec2.go:258 +0x7f2
May 18 19:03:36 prometheus-prod-prometheus-server-77bfbf6c7b-vc75t prometheus-server github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/service/ec2.(*EC2).DescribeInstancesPages.func1(0x19d0480, 0xc498e07660, 0x1, 0xc4fab0c240)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/service/ec2/api.go:6785 +0x49
May 18 19:03:36 prometheus-prod-prometheus-server-77bfbf6c7b-vc75t prometheus-server github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/aws/request.(*Request).EachPage(0xc568c44000, 0xc4d63b5b20, 0x2, 0x2)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/aws/request/request_pagination.go:98 +0xa1
May 18 19:03:36 prometheus-prod-prometheus-server-77bfbf6c7b-vc75t prometheus-server github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/service/ec2.(*EC2).DescribeInstancesPages(0xc4b5f981a0, 0x0, 0xc4d63b5c70, 0x1, 0x1)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/service/ec2/api.go:6784 +0x11a
May 18 19:03:36 prometheus-prod-prometheus-server-77bfbf6c7b-vc75t prometheus-server github.com/prometheus/prometheus/discovery/ec2.(*Discovery).refresh(0xc49e4eeff0, 0xc4a3810d80, 0x0, 0x0)
	/go/src/github.com/prometheus/prometheus/discovery/ec2/ec2.go:231 +0x32e
May 18 19:03:36 prometheus-prod-prometheus-server-77bfbf6c7b-vc75t prometheus-server github.com/prometheus/prometheus/discovery/ec2.(*Discovery).Run(0xc49e4eeff0, 0x290a240, 0xc4bd6818c0, 0xc4495100c0)
	/go/src/github.com/prometheus/prometheus/discovery/ec2/ec2.go:172 +0x2dc
May 18 19:03:36 prometheus-prod-prometheus-server-77bfbf6c7b-vc75t prometheus-server created by github.com/prometheus/prometheus/discovery.(*Manager).startProvider
	/go/src/github.com/prometheus/prometheus/discovery/manager.go:124 +0x11c
May 18 19:03:37 prometheus-prod-prometheus-server-77bfbf6c7b-vc75t prometheus-server info level=info ts=2020-05-18T13:33:37.769728529Z caller=main.go:225 msg="Starting Prometheus" version="(version=2.1.0, branch=HEAD, revision=85f23d82a045d103ea7f3c89a91fba4a93e6367a)"
May 18 19:03:37 prometheus-prod-prometheus-server-77bfbf6c7b-vc75t prometheus-server info level=info ts=2020-05-18T13:33:37.769772783Z caller=main.go:226 build_context="(go=go1.9.2, user=root@6e784304d3ff, date=20180119-12:01:23)"
May 18 19:03:37 prometheus-prod-prometheus-server-77bfbf6c7b-vc75t prometheus-server info level=info ts=2020-05-18T13:33:37.769788854Z caller=main.go:227 host_details="(Linux 4.14.173-137.229.amzn2.x86_64 #1 SMP Wed Apr 1 18:06:08 UTC 2020 x86_64 prometheus-prod-prometheus-server-77bfbf6c7b-vc75t (none))"

**Comment by roidelapluie** [comment] 2020-05-19 16:46
Can you please try with a more recent prometheus version?

2.1.0 is more than 2 years old.

**Comment by nandeeshb09** [comment] 2020-05-20 12:41
Ya.. we will upgrade, for now is there any solution and at-least when this error will get.?Any clue?

**Comment by roidelapluie** [comment] 2020-05-20 12:52
This is a known bug that was fixed in prometheus v2.4.0: #4469.

I recommend you to upgrade to the latest prometheus version, currently v2.18.0.

I am closing this bug as it is resolved in recent prometheus versions.

**Comment by roidelapluie** [comment] 2020-05-20 12:52
Dupe of https://github.com/prometheus/prometheus/issues/4441

**Closed by roidelapluie** 2020-05-20 12:52 UTC
Labels: kind/bug, kind/more-info-needed
