### ISSUE TITLE
PromConsole area renderer elevates a time series unexpectedly

### ISSUE THREAD

**Issue by staschuk-bungalow** [prometheus/prometheus#7711] opened 2020-07-31 22:02 UTC
**What did you do?**

I used PromConsole.Graph with `renderer: "area"`, and often see time series elevated more than they should be, as if they were stacked on other time series which are not actually under them.  I attach a screenshot.

See https://github.com/livebungalow/promconsole-rendering-example for a small working example (well, non-working, which is the point).  For the purposes of that example, I monkey-patch `PromConsole.Graph.prototype.buildQueryUrl` to inject data which provokes the issue -- I copied this data from an actual `query_range` response, formatted it, and reduced it to a manageable size.

**What did you expect to see?**

Time series resting on the x-axis.

**What did you see instead? Under which circumstances?**

Time series elevated off the x-axis.  The linked example repo has sample data that provokes the problem.

**Environment**

The linked example uses the docker image `prom/prometheus:v2.19.3` with its standard configuration file.

**Comment by staschuk-bungalow** [comment] 2020-07-31 22:03
<img width="495" alt="screenshot" src="https://user-images.githubusercontent.com/57634948/89080891-1fa96780-d358-11ea-914d-fbff3092d967.png">
the promised screenshot

**Comment by staschuk-bungalow** [comment] 2020-07-31 22:06
Oh, and my browser is Chrome Version 84.0.4147.89 (Official Build) (64-bit) on macOS 10.15.6 (19G73).

**Comment by staschuk-bungalow** [comment] 2020-07-31 22:15
Oh, and: I do _not_ see this behaviour in the expression browser, even for the same queries.  That is, if I click on the little plus sign of a console graph that has the wrong elevations, the resulting expression browser graph does not have wrong elevations.

**Comment by brian-brazil** [comment] 2020-08-04 13:58
What is the query that's using? Based on the timestamps that looks like a range vector from query, rather than from query range - which Rickshaw may not like.

**Comment by staschuk-bungalow** [comment] 2020-08-04 14:44
@brian-brazil The query that produced that data is `sum by (code_version) (info)`

**Comment by brian-brazil** [comment] 2020-08-04 16:12
Can you share the full query_range URL? The sample data you have didn't come from a Prometheus query_range - the timestamps are all wrong.

**Comment by staschuk-bungalow** [comment] 2020-08-04 22:46
@brian-brazil : verbatim from chrome developer tools, on a console where I'm seeing this issue in production:
```
:path: /api/v1/query_range?query=sum%20by%20(ecs_service)%20(up%7Bjob%3D%22ecs-task%22%2Cservice%3D%22metrics-web%22%7D)&step=5.3097345132743365&start=1596576860.673&end=1596580460.673
```
The first thousand characters of the response:
```
{"status":"success","data":{"resultType":"matrix","result":[{"metric":{},"values":[[1596576860.673,"0"],[1596576865.982,"0"],[1596576871.291,"0"],[1596576876.600,"0"],[1596576881.909,"0"],[1596576887.218,"0"],[1596576892.527,"0"],[1596576897.836,"0"],[1596576903.145,"0"],[1596576908.454,"0"],[1596576913.763,"0"],[1596576919.072,"0"],[1596576924.381,"0"],[1596576929.690,"0"],[1596576934.999,"0"],[1596576940.308,"0"],[1596576945.617,"0"],[1596576950.926,"0"],[1596576956.235,"0"],[1596576961.544,"0"],[1596576966.853,"0"],[1596576972.162,"0"],[1596576977.471,"0"],[1596576982.780,"0"],[1596576988.089,"0"],[1596576993.398,"0"],[1596576998.707,"0"],[1596577004.016,"0"],[1596577009.325,"0"],[1596577014.634,"0"],[1596577019.943,"0"],[1596577025.252,"0"],[1596577030.561,"0"],[1596577035.870,"0"],[1596577041.179,"0"],[1596577046.488,"0"],[1596577051.797,"0"],[1596577057.106,"0"],[1596577062.415,"0"],[1596577067.724,"0"],[1596577073.033,"0"],[1596577078.342,"0"],[1596577083.651,"0"],[1596577088.96
```
(lmk if you want more).

Since we seem to suspect that the data is wrong, here's details about the server that produced it.  (I omitted this information before because I believed it was a front-end issue.)

System information:

```
$ uname -srm
Linux 4.14.181-140.257.amzn2.x86_64 x86_64
```

Prometheus version:

```
$ prometheus --version
prometheus, version 2.15.1 (branch: HEAD, revision: 8744510c6391d3ef46d8294a7e1f46e57407ab13)
  build user:       root@4b1e33c71b9d
  build date:       20191225-01:04:15
  go version:       go1.13.5
```

Prometheus configuration file:

```
global:
  external_labels:
    export_prefix: productionfieldstone
scrape_configs:
  - job_name: ecs-task
    scrape_interval: 10s
    scheme: http
    file_sd_configs:
    - files:
      - /etc/prometheus/ecs-list.json
  - job_name: recent-commits
    scrape_interval: 60s
    scheme: https
    metrics_path: /github-recent-commits/recent-commits
    params:
      repo:
      - fieldstone
    bearer_token: [redacted]
    static_configs:
    - targets:
      - botler.bungalow.com
  - job_name: pushgateway
    scrape_interval: 1m
    scheme: http
    honor_labels: true
    static_configs:
      - targets:
          - 'localhost:9091'
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'localhost:9093'
rule_files:
  - rules/*.yaml
```

I omit the rules files; they specify alerts (no recording rules).  Let me know if you think they might be relevant.

**Comment by staschuk-bungalow** [comment] 2020-08-04 22:50
@brian-brazil , here's an example that more closely matches the prepared minimal example:

```
:path: /api/v1/query_range?query=sum%20by%20(code_version)%20(info)&step=5.3097345132743365&start=1596577699.264&end=1596581299.264
```

The first thousand characters of the response:

```
{"status":"success","data":{"resultType":"matrix","result":[{"metric":{"code_version":"50ba7bbcead1843108c88eaf1ea6a7cbe7131752"},"values":[[1596577699.264,"16"],[1596577704.573,"16"],[1596577709.882,"16"],[1596577715.191,"16"],[1596577720.500,"16"],[1596577725.809,"16"],[1596577731.118,"16"],[1596577736.427,"16"],[1596577741.736,"16"],[1596577747.045,"16"],[1596577752.354,"16"],[1596577757.663,"16"],[1596577762.972,"16"],[1596577768.281,"16"],[1596577773.590,"16"],[1596577778.899,"16"],[1596577784.208,"16"],[1596577789.517,"16"],[1596577794.826,"16"],[1596577800.135,"16"],[1596577805.444,"16"],[1596577810.753,"16"],[1596577816.062,"16"],[1596577821.371,"16"],[1596577826.680,"16"],[1596577831.989,"16"],[1596577837.298,"16"],[1596577842.607,"16"],[1596577847.916,"16"],[1596577853.225,"16"],[1596577858.534,"16"],[1596577863.843,"16"],[1596577869.152,"16"],[1596577874.461,"16"],[1596577879.770,"16"],[1596577885.079,"16"],[1596577890.388,"16"],[1596577895.697,"16"],[1596577901.006,"16"],[1
```
(Again, let me know if you want more.)

**Comment by brian-brazil** [comment] 2020-08-06 13:09
Your example doesn't render for me, and adding an appropriate endtime and duration then works fine. Do you have a more complete example?

**Comment by staschuk-bungalow** [comment] 2020-08-06 15:05
@brian-brazil Here's a complete `query_range` response: https://gist.github.com/staschuk-bungalow/cd41d228c4322209639a4ad946700552 .  This came from a request
```
:path: /api/v1/query_range?query=sum%20by%20(code_version)%20(info)&step=5.3097345132743365&start=1596722472.141&end=1596726072.141
```
Here's how it renders for me:
<img width="326" alt="Screen Shot 2020-08-06 at 11 03 02 AM" src="https://user-images.githubusercontent.com/57634948/89548152-a9cc5280-d7d4-11ea-819b-ef09840f465d.png">

Do these examples address your remark that the previous examples "didn't come from a Prometheus query_range - the timestamps are all wrong"?

**Comment by brian-brazil** [comment] 2020-08-06 15:11
> Here's a complete query_range response

What's the width parameter there?

**Comment by staschuk-bungalow** [comment] 2020-08-06 15:58
> What's the width parameter there?

I don't know what you're referring to.  I copied the response and the requested url from the Chrome developer console; they are verbatim, and neither mentions width.

**Comment by brian-brazil** [comment] 2020-08-06 16:30
Width is a parameter of the graphing code, I need it to figure out what the math is doing under the covers.

**Comment by staschuk-bungalow** [comment] 2020-08-06 19:31
The code creating the graph:
```
<script>
new PromConsole.Graph({
  node: document.querySelector("#codeVersions"),
  expr: "sum by (code_version) (info)",
  renderer: "area",
  name: "[[ code_version ]]",
  yAxisFormatter: PromConsole.NumberFormatter.humanizeNoSmallPrefix,
  yHoverFormatter: PromConsole.NumberFormatter.humanizeNoSmallPrefix,
  min: 0,
  yTitle: "Number of containers"
})
</script>
```

**Comment by brian-brazil** [comment] 2020-08-10 14:16
I had to reverse engineer a bit and still can't reproduce that exact graph, but I think I've found the issue. #7773

**Comment by staschuk-bungalow** [comment] 2020-08-12 14:26
I'm still seeing the problem, using prometheus built from source at ce838ad6fcbd14b0cf9971a4d093ad672e1469fe .

<img width="440" alt="Screen Shot 2020-08-12 at 10 26 08 AM" src="https://user-images.githubusercontent.com/57634948/90027214-4a63bc00-dc86-11ea-9e09-9e5272503415.png">

@brian-brazil , you mentioned that you weren't able to reproduce exactly the same graphs that I'm seeing.  I'd be happy to prepare a reproduction in docker, like the one in my original report here.  Would that be useful to you?

**Comment by roidelapluie** [comment] 2020-08-12 14:34
Yes that would help

**Comment by staschuk-bungalow** [comment] 2020-08-12 14:38
Ok, I'll prepare that -- but fyi I probably won't get to it until tomorrow.

**Comment by staschuk-bungalow** [comment] 2020-08-13 14:00
I've revised https://github.com/livebungalow/promconsole-rendering-example to use prometheus ce838ad6fcbd14b0cf9971a4d093ad672e1469fe .  See the README there for exact reproduction instructions, and a screenshot to help verify that we're seeing the same thing.

**Comment by brian-brazil** [comment] 2020-08-13 14:37
That's not a perfect reproduction, as indicated above the width of the graph also matters. This depends on your monitor and browser dimensions. Can you put in an explcit width?

**Comment by roidelapluie** [comment] 2020-08-13 14:39
I can reproduce that with my 1920x1080 screen,
it seems that the issue is that rickshaw calculates the stack per position in the vector instead of per timestamp.

**Comment by brian-brazil** [comment] 2020-08-13 14:42
So an upstream bug then?

**Comment by roidelapluie** [comment] 2020-08-13 14:44
I did not dig, that's what it looks like at first sight. Still present with latest rickshaw version.

**Comment by brian-brazil** [comment] 2020-08-13 14:48
It looks like Rickshaw is once again being maintained, so we might be able to get it fixed up there.

**Comment by staschuk-bungalow** [comment] 2020-08-13 15:14
> Can you put in an explicit width?

Sure.  I specified the width of the div in https://github.com/livebungalow/promconsole-rendering-example/commit/82fa2d0fb0e5ce9e3766b01b68b841e12465dbce

> Still present with latest rickshaw version.

I've never seen this behaviour in the Expression Browser.  Is there something different about how the Expression Browser uses rickshaw?

**Comment by beorn7** [comment] 2024-05-07 12:03
Hello from the bug scrub.

No update here in almost 4y. The issue only happens in the console templates, which is a bit of a niche feature. We still want to keep it, see https://github.com/prometheus/prometheus/issues/13443 , bet we _do_ want to get rid of the legacy css and js in it, which also includes Rickshaw.

We are closing this now, essentially because the problem is in deprecated code, and there doesn't seem to be an easy fix.

**Closed by beorn7** 2024-05-07 12:03 UTC
Labels: kind/bug, component/ui, priority/P3
