### ISSUE TITLE
Alert Unit Test integration for certain Query Functions

### ISSUE THREAD

**Issue by ahantke1** [prometheus/prometheus#11125] opened 2022-08-05 17:13 UTC
I know certain query functions, ie. time() can be easily mocked in unit testing the alert rules within promtool. Others are not supported though. In my specific case, I am using predict_linear in an expression and would like to be able to write a unit test within the promtool suite. Now, this can be extended to some of the other query functions as well but I am not familiar with which ones have support or not. 

So really asking for 2 big things:
- Can the alerting unit test docs provide more info on unit tests for expressions utilizing query functions
- Can the team look into adding support for unit testing all of the query functions (and if not explicitly state which ones can and cant be tested in the unit testing docs)

Here is the specific expression I am using if that provides any value:
node_filesystem_avail_bytes{fstype="nfs"} / node_filesystem_size_bytes{fstype="nfs"} - (predict_linear(node_filesystem_avail_bytes{fstype="nfs"}[12h], 604800) < 0) * 604800

**Comment by beorn7** [comment] 2024-10-01 11:26
Hello from the bug scrub!

The unit test framework allows you to inject any kind of time series with timestamps of your choice. You should be able to unittest your expressions without problems.

If you run into trouble doing it, use the [community channels](https://prometheus.io/community/) to find help.

Of course, PRs to improve the documentation are always welcome.

As this is not a bug in Prometheus, we are closing the issue.

**Closed by beorn7** 2024-10-01 11:26 UTC
