### ISSUE TITLE
Race condition starting HEAD prometheus with static scrape configs

### ISSUE THREAD

**Issue by csmarchbanks** [prometheus/prometheus#4551] opened 2018-08-28 03:48 UTC
## Bug Report
**What did you do?**
Ran prometheus locally, with some basic static configs

**What did you expect to see?**
Prometheus comes up and my targets are scraped. 

**What did you see instead? Under which circumstances?**
Most of the time none of my static targets are scraped. Approximately 5-10% of the time my targets are scraped properly.

**Environment**

* System information:

	Darwin 17.7.0 x86_64

* Prometheus version:

	latest master (87f1dad16da760aa48f8a41089c0d1a20b56689c)

* Prometheus configuration file:
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
```

* Logs:
```
$ go run cmd/prometheus/main.go --config.file=prometheus.yml --log.level=debug
level=info ts=2018-08-28T03:39:41.803111877Z caller=main.go:235 msg="Starting Prometheus" version="(version=, branch=, revision=)"
level=info ts=2018-08-28T03:39:41.803208011Z caller=main.go:236 build_context="(go=go1.10, user=, date=)"
level=info ts=2018-08-28T03:39:41.803227773Z caller=main.go:237 host_details=(darwin)
level=info ts=2018-08-28T03:39:41.803248042Z caller=main.go:238 fd_limits="(soft=4864, hard=unlimited)"
level=info ts=2018-08-28T03:39:41.803265702Z caller=main.go:239 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2018-08-28T03:39:41.803878491Z caller=main.go:551 msg="Starting TSDB ..."
level=info ts=2018-08-28T03:39:41.80393762Z caller=web.go:395 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2018-08-28T03:39:41.831430515Z caller=main.go:561 msg="TSDB started"
level=info ts=2018-08-28T03:39:41.831492958Z caller=main.go:621 msg="Loading configuration file" filename=prometheus.yml
level=info ts=2018-08-28T03:39:41.832040894Z caller=main.go:647 msg="Completed loading of configuration file" filename=prometheus.yml
level=info ts=2018-08-28T03:39:41.83207218Z caller=main.go:520 msg="Server is ready to receive web requests."
level=debug ts=2018-08-28T03:39:41.832084248Z caller=manager.go:151 component="discovery manager scrape" msg="discovery receiver's channel was full"
level=debug ts=2018-08-28T03:39:41.83209375Z caller=manager.go:151 component="discovery manager scrape" msg="discovery receiver's channel was full"
```

Appears to be related to https://github.com/prometheus/prometheus/pull/4523, if I revert that commit everything starts working. The "discovery receiver's channel was full" log only shows up in the failure case.

**Comment by brancz** [comment] 2018-08-28 03:53
cc @krasi-georgiev

**Comment by krasi-georgiev** [comment] 2018-08-28 08:27
at the moment this is to be expected. The main issue is that  the Scrape manager blocks the Discovery manager's channel. Reverting the commit only removes the logging, otherwise the problem is still there.
Will be fixed in https://github.com/prometheus/prometheus/pull/4526

@csmarchbanks btw why do you think this is a Race condition?

**Comment by krasi-georgiev** [comment] 2018-08-28 15:11
yeah this change shouldn't change the old behaviour just add this additional debug logging.



> sometimes the scrape configuration would load, and sometimes it would not. 

how do you know that the config didn't load? 

In general until #4526 is tested and merged any scaling down of targets would be slow as it goes in serial instead of parallel as in #4526

**Comment by csmarchbanks** [comment] 2018-08-28 16:01
I am pretty sure that by adding the default cases, behavior is changed:
Old way: Block until it is possible to write to the syncCh so the update is done eventually.
New way: Log a message and drop the update.

I know the scrape config didn't load properly because my /targets page is completely empty even though there should be two targets (prometheus and node-exporter). Since these are static targets, there shouldn't be any scaling down should there?

**Comment by krasi-georgiev** [comment] 2018-08-28 19:42
yes, I see what you mean.

Here is a PR https://github.com/prometheus/prometheus/pull/4556 that improves the behaviour.

I will look at it again tomorrow with fresh eyes, but will free to comment if you see anything suspicious :+1:

**Comment by csmarchbanks** [comment] 2018-08-29 02:55
👍 Thanks!

**Comment by Bplotka** [comment] 2018-09-03 11:12
I can repro same thing, from current master. (sha 674c76adb8a0842de6358ee3c701434332a5e1f5)

```
level=debug ts=2018-09-03T11:10:26.961711081Z caller=manager.go:186 component="discovery manager scrape" msg="discovery receiver's channel was full"
```

And no "Target" for my static, local scrape target. Any progress on this?

**Comment by Bplotka** [comment] 2018-09-03 11:13
Ah, we need this potentially? https://github.com/prometheus/prometheus/pull/4526 Will help with review

**Closed** 2018-09-05 11:32 UTC
Labels: component/service discovery, kind/bug

**Comment by Bplotka** [comment] 2018-09-05 15:41
Can anyone confirm this is not happening on master?

**Comment by csmarchbanks** [comment] 2018-09-05 16:07
@Bplotka master is working great for me now.
