### ISSUE TITLE
PromQL: Improve space complexity by streaming more; avoid series pre-lookup.

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#7326] opened 2020-06-02 16:28 UTC
Hi :wave: 

While changing [SeriesSet interfaces](https://github.com/prometheus/prometheus/pull/7251/), we found with @brian-brazil that our usage of SerieSet in PromQL might cause extra unnecessary allocations for certain implementations and cases. Let me describe the problem in two diagrams:

## Current PromQL logic for Range Query with Metric Selection:

![Prometheus PromQL v2 19 Flow](https://user-images.githubusercontent.com/6950331/83543350-2c464680-a4f4-11ea-9d90-8d6efc457f81.png)
_[Google Draw Link](https://docs.google.com/drawings/d/1NfV8Gp53afJY3CfGwn3L1_-dFImA6f2QvsUMDg4x0Bs/edit)_

All function names should match the current master: https://github.com/prometheus/prometheus/tree/18d9ebf0ffc26b8bd0e136f552c8e9886d29ade4

## Issues:

![Prometheus PromQL v2 19 Flow_ Unnecessary PreLookup of Series (1)](https://user-images.githubusercontent.com/6950331/83545333-f787be80-a4f6-11ea-8d4e-cc4aa99038e0.png)
_[Google Draw Link](https://docs.google.com/drawings/d/1Ice50aJRN7xgRIQKe-T3OM4uDLjw3dGeshVjzHT22X8/edit)_

**Problem**: We are accumulating all series first, to gather all iterators.

With the current interfaces (StoreSet, Remote Read, Thanos StoreAPI) “Series by Series” means that we stream Series labels together with labels. 

**Current Flow Issues:**

1. To finish this `eval` PromQL stage, we have to buffer & receive all data. Especially for remote data & Thanos, this means literally all. (: **Realistic space complexity is now O(2 * series * chunks), for the biggest result, so ~ O(2 series * chunks) B**
2. Current space complexity is also not great further with multi arg functions, as we build a hash map. For large cardinality queries, we end up hashing millions of Series potentially.

## Solution: Stream more!

The idea would be to follow really exactly the same algorithm as everywhere else (vertical dedup, merge series etc): Implement Heap / MergeSort that will iterate over "sorted" series from two SeriesSets. 

* Open Question: Good point that @brian-brazil mentioned, was that we don't know then how big matrix we should allocate. I wonder if we can workaround this somehow. To me it sounds we don't really want to operate on matrixes at all, rather on top two series from each SeriesSets... :thinking: 

This sounds like a big task but really needed, especially for Thanos community. Even with the work we are doing to make PromQL more concurrent for Prometheus Ecosystem (https://github.com/prometheus/prometheus/issues/6878), this issue might be impacting resource (memory) consumption significantly, especially for concurrent runs. I am happy to do this at some point, but I won't have time in near ~2weeks for this. so.. help wanted (: 

Any feedback on this to make it easier to improve this? (:  cc @slrtbtfs @brian-brazil @brancz @kakkoyun @cstyan  @tomwilkie @gouthamve @cstyan

**Comment by brian-brazil** [comment] 2020-06-02 16:36
This is actually quite a small change in removing the Expand from CheckAndExpand. It's really just cleanup from the big reworking of promql I did a few years back.

> Current space complexity is also not great further with multi arg functions, as we build a hash map. For large cardinality queries, we end up hashing millions of Series potentially.

I don't see how this is related to what's being discussed here. Hashing is cheap, and we'll need to do it anyway.


I'm not sure why you've marked this as a P1 feature. It's a small performance thing that's not really something user visible, and it's not urgent. It's a P3 cleanup or enhancement.

**Comment by bwplotka** [comment] 2020-06-02 16:46
Happy to hear it's easy =D let's try it out then.

**Comment by allenmqcymp** [comment] 2020-07-06 20:17
Hi there, first time contributor looking to help with low hanging-fruit issues. Could someone point me to the relevant code files so I can better understand the issue?

**Comment by brian-brazil** [comment] 2020-07-06 21:01
Basically in https://github.com/prometheus/prometheus/blob/933aa367b431e248524371dbab240c06ef8915da/promql/engine.go#L728 we should not be expanding the whole series in advance - that should happen during evaluation one series at a time.

**Comment by allenmqcymp** [comment] 2020-07-15 22:33
Hi, sorry for the inactivity. I would still like to pick this issue up. Currently looking through how engine.go works, is there any good documentation about the internals of the PromQL engine?

My current understanding of the issue is that it is inefficient to gather all the series data before rangeEval. I am still unsure of what the proposed fix might involve. Could someone please enlighten?

Thanks!

**Comment by brian-brazil** [comment] 2020-07-16 11:52
I'm not sure there's much in general docs.

> Could someone please enlighten?

In essence eliminate ExpandSeriesSet, and then fix up anything that breaks due to that. The only place things will happen to be fully expanded is subqueries, as that's what the output is.

**Comment by aryan9600** [comment] 2020-09-18 22:48
Hey everyone, a first time contributor here. I would like to work on this issue if no one else is already working on it.

Having gone through this issue and _some_ of the related code, I have a few doubts I was hoping to get cleared.

As far as I understand, we want to avoid using `checkAndExpandSeriesSet` and consequently `expandSeriesSet` in `eval()`.
If we don't expand the `SeriesSet`, how do we get access to the iterator of each `Series` in order to use the buffer? Also how do we determine the length of our output matrix?

Unfortunately, @bwplotka's solution regarding Heap/MergeSort and _streaming more_ made little sense to me, so it would be great if someone could elaborate on that.

Thanks!

**Comment by brian-brazil** [comment] 2020-09-19 09:58
> how do we get access to the iterator of each Series in order to use the buffer?

We do it as needed one by one, rather than in one big batch.

**Comment by aryan9600** [comment] 2020-09-22 22:52
> We do it as needed one by one.

I think I understand the issue, but can't really seem to get a grasp on the solution. Where exactly do we determine that we need to move to the next Series?

**Comment by brian-brazil** [comment] 2020-09-23 08:35
Anywhere we iterate over the slice today, instead we call next.

**Comment by aryan9600** [comment] 2020-10-04 07:08
Sorry for the inactivity, I have been trying to work on a patch, but can't get a few tests to pass (almost all of them pass), specifically some in `functions.test` and `subquery.test`. I replaced all for loops iterating over the slice, with a for loop which would expand the SeriesSet during eval time, but due to this a few Matrices (and consequently Vectors) are coming up empty, due to this change, and I can't really seem to figure out why exactly. Would you have any idea as to why this change would result in this error? Thanks :)

**Comment by brian-brazil** [comment] 2020-10-04 09:00
That's a bit weird, can you make a PR so we can have a look?

**Comment by sthaha** [comment] 2021-06-14 06:15
@bwplotka @brian-brazil , assuming the issue still exists, I would love to take a crack at this if  @aryan9600 isn't keen on progressing with #8009

**Comment by bwplotka** [comment] 2021-06-14 18:58
Totally, go for it. It's still available, but benchmarks might be necessary to assess results

**Comment by bwplotka** [comment] 2021-10-14 16:38
Just to give status on it.

It's still needed for Thanos and (and potentially Cortex purposes). See: https://github.com/thanos-io/thanos/issues/4780
 
Looks like @darshanime did a good job on this with https://github.com/prometheus/prometheus/pull/9071, so we can close https://github.com/prometheus/prometheus/pull/8009 (thanks for your hard initial work @aryan9600 !).

**Comment by keremgocen** [comment] 2022-06-14 22:06
happy to take a look or collab if no one else is on it

**Comment by beorn7** [comment] 2024-04-30 11:29
Hello from the bug scrub.

@bwplotka , our impression is that this is not required anymore (since #9071 was closed as "not required anymore"). Could you confirm? Please close if that's the case.

**Comment by bwplotka** [comment] 2024-04-30 12:16
Correct, not needed anymore, we can reopen if there will be a need!

**Closed** 2024-04-30 12:16 UTC
Labels: help wanted, low hanging fruit, component/promql, priority/P3, kind/feature
