### ISSUE TITLE
increase should handle no data to has data scenario

### ISSUE THREAD

**Issue by susanhuhu** [prometheus/prometheus#7270] opened 2020-05-19 01:48 UTC
If a counter starts to have data at (now - 1minute),  and I query increase[5m],  I get 0.   I expect to have a value > 0,   no data to with data is actually an increase.  Here is my query in real usage: increase(sum(requests_total{serviceidentity="$service",source="client",tag!="health"}) by (pod)[7d: 1m])

If a pod starts within last 7 days, I will get 0 for that pod even that pod had requests.  I tried to work it around by adding vector(0) to fill the no data period, but it doesn't have the same label 'pod' so it won't work.

**Comment by brian-brazil** [comment] 2020-05-19 08:23
Dupe of #1673

**Closed by brian-brazil** 2020-05-19 08:23 UTC

**Comment by susanhuhu** [comment] 2020-05-19 16:09
Would you or anybody suggest a workaround for my specific case?   #1673 just says there is no solution for this.   If there is a choice to allow people to fill 0 to any 'no data' gap in a vector, it will cover most of such scenarios.
