### ISSUE TITLE
api/v1/label/__name__/values does not return return values from remote read

### ISSUE THREAD

**Issue by robbruce** [prometheus/prometheus#6124] opened 2019-10-10 14:14 UTC
## Proposal
**Use case. Why is this important?**

If samples have been written to a remote and not via prometheus, then the labels are not returned in the api. This causes an issue for autocompletion in the prometheus UI and other tools such as Grafana.

## Bug Report
**What did you do?**

* Inserted samples directly into a Postgres + TimescaleDB remote database (to get around the data too old issue).
* Used prometheus UI to search the data
* Data can be queried, if the sample name is keyed in full

**What did you expect to see?**

* Autocomplete to include the same name in the list

**What did you see instead? Under which circumstances?**

* Sample name wasn't included

**Environment**

* System information:

Linux 4.14.133-88.112.amzn1.x86_64 x86_64
Running prom/prometheus docker image

* Prometheus version:

prometheus, version 2.13.0 (branch: HEAD, revision: 6ea4252299f542669aca11860abc2192bdc7bede)
  build user:       root@f30bdad2c3fd
  build date:       20191004-11:25:34
  go version:       go1.13.1

* Alertmanager version:
N/A

* Prometheus configuration file:
N/A

* Alertmanager configuration file:
N/A

* Logs:
N/A

**Comment by liguozhong** [comment] 2019-10-13 03:38
![image](https://user-images.githubusercontent.com/9583245/66710521-ed208500-edac-11e9-81fd-ab1245a4061d.png)
auto complete
The autocompletion feature relies on the labelValues interface. By default, this interface of remote storage is empty, and it can be implemented.

Our team maintains its own code branch, and in this branch we implement the autocompletion feature by implementing the labelValues interface.

![image](https://user-images.githubusercontent.com/9583245/66710530-1f31e700-edad-11e9-875b-1414b429e02e.png)

When we implement the labelValues interface, we need to complete the query based on the specific syntax in the specific TSDB selected by remote storage.
![image](https://user-images.githubusercontent.com/9583245/66710572-fd852f80-edad-11e9-9d92-9effbf112f90.png)

**Comment by liguozhong** [comment] 2020-03-04 07:23
@brian-brazil @roidelapluie  
labelvalues endpoint

**Comment by Harkishen-Singh** [comment] 2021-04-08 12:13
I think this is a duplicate of #3351

**Comment by beorn7** [comment] 2024-03-26 11:58
Hello from the bug scrub.

We close this as a duplicate #3351.

**Closed by beorn7** 2024-03-26 11:58 UTC
Labels: kind/enhancement, component/remote storage, priority/P3
