### ISSUE TITLE
prometheus-2.39.1.linux-386 segfaults on start

### ISSUE THREAD

**Issue by inflatador** [prometheus/prometheus#11439] opened 2022-10-09 14:38 UTC
### What did you do?

1. Download prometheus-2.39.1.linux-386 from github

2. Attempt to run the binary: 
```
/usr/local/bin/prometheus --help
Segmentation fault
```
If I revert to 2.39.0 , the binary loads with no issues.

### What did you expect to see?

prometheus binary starting as normal

### What did you see instead? Under which circumstances?

Segmentation fault

### System information

Linux 5.10.0-12-686-pae i686 , Debian Bullseye 11.5

### Prometheus version

I can't run `prometheus --version` as it segfaults, but I'm using the latest version from github as of this writing, prometheus-2.39.1

### Prometheus configuration file

```yaml
stock configuration
```

### Logs

```text
Oct 09 09:26:48 server.example.com systemd[1]: prometheus.service: Consumed 2h 27min 253ms CPU time.
Oct 09 09:26:48 server.example.com systemd[1]: Started Monitoring system and time series database.
Oct 09 09:26:48 server.example.com systemd[1]: prometheus.service: Main process exited, code=killed, status=11/SEGV
Oct 09 09:26:48 server.example.com systemd[1]: prometheus.service: Failed with result 'signal'.
Oct 09 09:26:48 server.example.com systemd[1]: prometheus.service: Scheduled restart job, restart counter is at 1.
Oct 09 09:26:48 server.example.com systemd[1]: Stopped Monitoring system and time series database.
Oct 09 09:26:48 server.example.com systemd[1]: Started Monitoring system and time series database.
Oct 09 09:26:48 server.example.com systemd[1]: prometheus.service: Main process exited, code=killed, status=11/SEGV
Oct 09 09:26:48 server.example.com systemd[1]: prometheus.service: Failed with result 'signal'.
Oct 09 09:26:48 server.example.com systemd[1]: prometheus.service: Scheduled restart job, restart counter is at 2.
```

**Comment by 94rain** [comment] 2022-10-21 20:53
I am unable to reproduce the segfault error via either `--version` or `--help`

```bash
@94rain ➜ /workspaces/prometheus-2.39.1.linux-386 $ ./prometheus --version
prometheus, version 2.39.1 (branch: HEAD, revision: dcd6af9e0d56165c6f5c64ebbc1fae798d24933a)
  build user:       root@ceece275ef05
  build date:       20221007-16:10:11
  go version:       go1.19.2
  platform:         linux/386
```

**Comment by roidelapluie** [comment] 2022-12-16 12:49
This was fixed in 2.39.2. Thanks!

**Closed by roidelapluie** 2022-12-16 12:49 UTC

**Comment by yesemenglong** [comment] 2023-01-05 07:49
Hello, Segmentation fault reappeared in 2.41.0, my centos version is CentOS Linux release 7.7.1908 (Core)

**Comment by yesemenglong** [comment] 2023-01-05 07:50
![image](https://user-images.githubusercontent.com/42922106/210728688-2699c9a9-6694-425d-bf48-0b8e60123df2.png)
