### ISSUE TITLE
file_sd_config: Support custom scrape_timeout

### ISSUE THREAD

**Issue by JasonZhang1991** [prometheus/prometheus#4662] opened 2018-09-26 16:10 UTC
how to config the targets.json  to custom scrape_timeout for  every  taget json?
 and  why  the label_name in targets.json is different from prometheus.yml,eg. methric_name in prometheus.yml but _ _metric_name_ _ in targets.json? why? why ? why?

**Comment by simonpasquier** [comment] 2018-09-27 07:52
Thanks for the report, this is a duplicate of #4561 so I'm closing it. See also https://www.robustperception.io/keep-it-simple-scrape_interval-id

**Closed by simonpasquier** 2018-09-27 07:52 UTC
