### ISSUE TITLE
fatal error: mSpanList.insertruntime

### ISSUE THREAD

**Issue by SarthakSahu** [prometheus/prometheus#12416] opened 2023-06-01 09:25 UTC
### What did you do?

No action taken.

### What did you expect to see?

No Panic and restart.

### What did you see instead? Under which circumstances?

Bellow panic has been seen in Prometheus server.

```
ts=2023-05-25T23:04:31.935Z caller=head.go:972 level=info component=tsdb msg="WAL checkpoint complete" first=562 last=574 duration=22.790495137s
ts=2023-05-25T23:08:35.308Z caller=compact.go:459 level=info component=tsdb msg="compact blocks" count=3 mint=1685016000003 maxt=1685037600000 ulid=01H1AJG6Y0TYHBP7102HXQDKW7 sources="[01H19PS0DDYG7JEE7CSER9PQDY 01H19XMQNDGJEWMS83NP2R59NY 01H1A4GEYRSEH1QEZJT4AH4K9R]" duration=4m3.372621194s
ts=2023-05-25T23:08:35.626Z caller=db.go:1293 level=info component=tsdb msg="Deleting obsolete block" block=01H1A4GEYRSEH1QEZJT4AH4K9R
ts=2023-05-25T23:08:36.303Z caller=db.go:1293 level=info component=tsdb msg="Deleting obsolete block" block=01H19XMQNDGJEWMS83NP2R59NY
ts=2023-05-25T23:08:36.538Z caller=db.go:1293 level=info component=tsdb msg="Deleting obsolete block" block=01H19PS0DDYG7JEE7CSER9PQDY
runtime: failed mSpanList.insert 0x7f24db941328 0x5dd3f3b80 0x0 0x0
fatal error: mSpanList.insertruntime stack:
runtime.throw({0x2bc50b4?, 0x0?})
    /usr/local/go/src/runtime/panic.go:992 +0x71
runtime.(*mSpanList).insert(0x40cc310?, 0x7f24db941328)
    /usr/local/go/src/runtime/mheap.go:1612 +0xe5
runtime.stackfree({0x0?, 0xc0000c0f00?})
    /usr/local/go/src/runtime/stack.go:513 +0x148
runtime.copystack(0xc32d33c820, 0x800000002?)
    /usr/local/go/src/runtime/stack.go:936 +0x307
runtime.newstack()
    /usr/local/go/src/runtime/stack.go:1110 +0x497
runtime.morestack()
```

### Prometheus version

```text
2.31.1
```

### Logs

```text
ts=2023-05-25T23:08:35.626Z caller=db.go:1293 level=info component=tsdb msg="Deleting obsolete block" block=01H1A4GEYRSEH1QEZJT4AH4K9R
ts=2023-05-25T23:08:36.303Z caller=db.go:1293 level=info component=tsdb msg="Deleting obsolete block" block=01H19XMQNDGJEWMS83NP2R59NY
ts=2023-05-25T23:08:36.538Z caller=db.go:1293 level=info component=tsdb msg="Deleting obsolete block" block=01H19PS0DDYG7JEE7CSER9PQDY
runtime: failed mSpanList.insert 0x7f24db941328 0x5dd3f3b80 0x0 0x0
fatal error: mSpanList.insertruntime stack:
runtime.throw({0x2bc50b4?, 0x0?})
    /usr/local/go/src/runtime/panic.go:992 +0x71
runtime.(*mSpanList).insert(0x40cc310?, 0x7f24db941328)
    /usr/local/go/src/runtime/mheap.go:1612 +0xe5
runtime.stackfree({0x0?, 0xc0000c0f00?})
    /usr/local/go/src/runtime/stack.go:513 +0x148
runtime.copystack(0xc32d33c820, 0x800000002?)
    /usr/local/go/src/runtime/stack.go:936 +0x307
runtime.newstack()
    /usr/local/go/src/runtime/stack.go:1110 +0x497
runtime.morestack()
    /usr/local/go/src/runtime/asm_amd64.s:547 +0x8bgoroutine 9502 [copystack]:
github.com/golang/snappy.encodeBlock({0xc5d6eca003, 0x23fcb2, 0x23fcb2}, {0xc4e9c6a000, 0x60a3, 0x18000})
    /root/go/pkg/mod/github.com/golang/snappy@v0.0.4/encode_amd64.s:265 +0x380 fp=0xc077fd52a0 sp=0xc077fd5298 pc=0x209f460
github.com/golang/snappy.Encode({0xc5d6eca000?, 0xc1c07d50d8?, 0x4?}, {0xc4e9c6a000?, 0x39?, 0xc1c07d50dc?})
    /root/go/pkg/mod/github.com/golang/snappy@v0.0.4/encode.go:39 +0x245 fp=0xc077fd5328 sp=0xc077fd52a0 pc=0x209eac5
github.com/prometheus/prometheus/tsdb/wal.(*WAL).log(0xc000438240, {0xc4e9c6a000, 0x60a3, 0x18000}, 0x1)
    /home/jenkins/workspace/CTO/CSF/FaultAndPerformanceManagement/CSF-PROMETHEUS/CSF-PROMETHEUS-PATCHES/21.11FP1PP/CSF-PROMETHEUS-PROMETHEUS-MIRROR/LX/src/github.com/prometheus/prometheus/tsdb/wal/wal.go:627 +0x136 fp=0xc077fd53f0 sp=0xc077fd5328 pc=0x20a66b6
github.com/prometheus/prometheus/tsdb/wal.(*WAL).Log(0xc000438240, {0xc077fd5548, 0x1, 0x46a21b?})
```

**Comment by bboreham** [comment] 2023-06-15 17:59
Please supply system information.
Note that version 2.31.1 is quite old.

**Comment by AVESH-RAI** [comment] 2023-07-13 10:13
I am also seeing the issue in the customer premises. Initially Prometheus gave OOM errors and also runtime panic issues (GC errors) occassionally. Further, we reduced the jobs being scrapped by prometheus to one-third. The OOM error is not seen anymore but runtime panic error is still seen. We are giving 2VCPU and 48 GB memory to prometheus. Disk is 50% full out of 104GB. 

Prometheus-2.31.1 is compiled with go version 1.18.1. K8s version is "v1.19.5" on centos 7.9. 

Attached file contains the backtrace. 
[prometheus panic issues files](https://drive.google.com/drive/u/0/folders/13yuaDNTGqEM1U3h-eXMeIPnNPxciZjOZ)

**Comment by AVESH-RAI** [comment] 2023-07-27 11:32
After adding this environment in prometheus container. The error is not seen in last 13 days after this change. Prior to this change it used to restart once in a day or two.
        - name: GODEBUG
          value: "gctrace=2"

**Comment by bboreham** [comment] 2023-07-27 11:46
Thanks for the update.  Can you please clarify are you working together with SarthakSahu or yours is a separate report?

I think if you are sometimes OOM-killed it is plausible that these errors from inside the Go runtime are also caused by running out of memory.

Many people report that Prometheus 2.44 and newer use much less memory; I recommend you upgrade.

**Comment by beorn7** [comment] 2024-12-03 11:24
Hello from the bug scrub!

This is now over a year old. We'll close it. If you have similar issues with current versions of Prometheus, please open a new issue.

**Closed by beorn7** 2024-12-03 11:24 UTC
Labels: kind/more-info-needed
