### ISSUE TITLE
prometheus take uncertainty recovery time after system time backward

### ISSUE THREAD

**Issue by liuliqiang** [prometheus/prometheus#8312] opened 2020-12-23 10:16 UTC
**What did you do?**

I change me system time backward 6 hours，command history is following：

```
#1608545032
date -s "Mon Dec 21 12:03:42 CST 2020"
```

- which `1608545032` is `Mon Dec 21 18:03:42 CST 2020` in this machine.

**What did you expect to see?**

When system time come from `Mon Dec 21 12:03:42 CST 2020` back to `Mon Dec 21 18:03:42 CST 2020`，prometheus should work fine as normal。

**What did you see instead? Under which circumstances?**

When system time come from `Mon Dec 21 12:03:42 CST 2020` back to `Mon Dec 21 18:03:42 CST 2020`，Prometheus still in innormal status，tail the log，it show：

```
...
level=warn ts=2020-12-21T19:15:08.968Z caller=scrape.go:1378 component="scrape manager" scrape_pool=prometheus target=http://127.0.0.1:9090/metrics msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=3572
level=warn ts=2020-12-21T19:15:08.969Z caller=scrape.go:1145 component="scrape manager" scrape_pool=prometheus target=http://127.0.0.1:9090/metrics msg="Append failed" err="out of bounds"
level=warn ts=2020-12-21T19:15:08.969Z caller=scrape.go:1094 component="scrape manager" scrape_pool=prometheus target=http://127.0.0.1:9090/metrics msg="Appending scrape report failed" err="out of bounds"
level=warn ts=2020-12-21T19:15:10.228Z caller=scrape.go:1378 component="scrape manager" scrape_pool=timemachine-exporter.timemachine target=http://10.77.89.172:9912/api/v3/prometheus/timemachine msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=48
level=warn ts=2020-12-21T19:15:10.228Z caller=scrape.go:1145 component="scrape manager" scrape_pool=timemachine-exporter.timemachine target=http://10.77.89.172:9912/api/v3/prometheus/timemachine msg="Append failed" err="out of bounds"
level=warn ts=2020-12-21T19:15:10.228Z caller=scrape.go:1094 component="scrape manager" scrape_pool=timemachine-exporter.timemachine target=http://10.77.89.172:9912/api/v3/prometheus/timemachine msg="Appending scrape report failed" err="out of bounds"
level=warn ts=2020-12-21T19:15:11.390Z caller=scrape.go:1094 component="scrape manager" scrape_pool=tuna-exporter.event target=http://10.77.89.172:10404/api/v2/exporter/tuna/event msg="Appending scrape report failed" err="out of bounds"
level=warn ts=2020-12-21T19:15:12.598Z caller=scrape.go:1378 component="scrape manager" scrape_pool=meta-exporter.basic target=http://10.77.89.172:10104/api/v1/prometheus/basic msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=183
level=warn ts=2020-12-21T19:15:12.598Z caller=scrape.go:1145 component="scrape manager" scrape_pool=meta-exporter.basic target=http://10.77.89.172:10104/api/v1/prometheus/basic msg="Append failed" err="out of bounds"
level=warn ts=2020-12-21T19:15:12.598Z caller=scrape.go:1094 component="scrape manager" scrape_pool=meta-exporter.basic target=http://10.77.89.172:10104/api/v1/prometheus/basic msg="Appending scrape report failed" err="out of bounds"
...
```

Until it recovery at `Dec 22 10:45:39 CST 2020` after i restart the prometheus

```
level=warn ts=2020-12-22T02:45:35.798Z caller=scrape.go:1094 component="scrape manager" scrape_pool=tuna-exporter.cpu target=http://10.77.89.172:10404/api/v2/exporter/tuna/cpu msg="Appending scrape report failed" err="out of bounds"
level=warn ts=2020-12-22T02:45:36.078Z caller=scrape.go:1378 component="scrape manager" scrape_pool=elf-exporter.host_scheduler target=http://10.77.89.172:10405/api/v2/exporter/elf/host_scheduler msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=1
level=warn ts=2020-12-22T02:45:36.078Z caller=scrape.go:1094 component="scrape manager" scrape_pool=elf-exporter.host_scheduler target=http://10.77.89.172:10405/api/v2/exporter/elf/host_scheduler msg="Appending scrape report failed" err="out of bounds"
level=warn ts=2020-12-22T02:45:38.593Z caller=scrape.go:1378 component="scrape manager" scrape_pool=tuna-exporter.misc target=http://10.77.89.172:10404/api/v2/exporter/tuna/misc msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=9
level=warn ts=2020-12-22T02:45:38.594Z caller=scrape.go:1094 component="scrape manager" scrape_pool=tuna-exporter.misc target=http://10.77.89.172:10404/api/v2/exporter/tuna/misc msg="Appending scrape report failed" err="out of bounds"
level=warn ts=2020-12-22T02:45:39.212Z caller=scrape.go:1378 component="scrape manager" scrape_pool=octopus-exporter.endpoint target=http://10.77.89.172:9900/metrics msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=1
level=warn ts=2020-12-22T02:45:39.212Z caller=scrape.go:1094 component="scrape manager" scrape_pool=octopus-exporter.endpoint target=http://10.77.89.172:9900/metrics msg="Appending scrape report failed" err="out of bounds"
level=warn ts=2020-12-22T02:45:39.886Z caller=main.go:572 msg="Received SIGTERM, exiting gracefully..."
level=info ts=2020-12-22T02:45:39.886Z caller=main.go:595 msg="Stopping scrape discovery manager..."
level=info ts=2020-12-22T02:45:39.886Z caller=main.go:609 msg="Stopping notify discovery manager..."
level=info ts=2020-12-22T02:45:39.886Z caller=main.go:631 msg="Stopping scrape manager..."
level=info ts=2020-12-22T02:45:39.886Z caller=main.go:591 msg="Scrape discovery manager stopped"
level=info ts=2020-12-22T02:45:39.891Z caller=main.go:605 msg="Notify discovery manager stopped"
level=info ts=2020-12-22T02:45:39.894Z caller=manager.go:924 component="rule manager" msg="Stopping rule manager..."
level=info ts=2020-12-22T02:45:39.907Z caller=manager.go:934 component="rule manager" msg="Rule manager stopped"
level=info ts=2020-12-22T02:45:39.907Z caller=main.go:625 msg="Scrape manager stopped"
level=info ts=2020-12-22T02:45:39.932Z caller=notifier.go:601 component=notifier msg="Stopping notification manager..."
```

and i can only get the metric in web console after this time:

![image](https://user-images.githubusercontent.com/9395418/102985696-908d2e00-454a-11eb-9ed6-b0476666b8de.png)

**Environment**

* System information:

	```
	# uname -srm
	Linux 3.10.0-1062.1.2.el7.smartx.1.x86_64 x86_64
	```

* Prometheus version:

        ```
        # prometheus --version
        prometheus, version 2.23.0 (branch: HEAD, revision: 26d89b4b0776fe4cd5a3656dfa520f119a375273)
          build user:       root@37609b3a0a21
          build date:       20201126-10:56:17
          go version:       go1.15.5
          platform:         linux/amd64
        ```

* Alertmanager version:

	no relation

* Prometheus configuration file:
```
no relation
```

* Alertmanager configuration file:
```
no relation
```

* Logs:
```
show up.
```

**Comment by roidelapluie** [comment] 2020-12-23 14:23
I would expect that in this case Prometheus would indeed skip 6 hours of data.

One the time on the server is moved by multiple hours, our TSDB behaviour can be erratic, in which case your best bet is to remove the WAL and restart prometheus.

cc @codesome do you see any reasonable improvement we could do here?

**Comment by liuliqiang** [comment] 2020-12-23 14:31
@roidelapluie  I think a simple solution is keep a max_time timestamp in tsdb head，and if find out older data to append，ignore them。

I don't know whether is it some problem for other case.

**Comment by roidelapluie** [comment] 2020-12-23 14:36
It is more complicated, the tsdb must ingest samples in the correct order. If you have ingested data at 6pm, you can't ingest the same samples at 1pm.

**Comment by liuliqiang** [comment] 2020-12-24 08:56
@roidelapluie  it seems acceptable？

If I backward datetime from 6pm to 1pm，prometheus had already ingest "old" 1pm samples，in this time，prometheus should not ingest "new" 1pm samples until time goforward after 6pm, and prometheus come back to normal sample ingest.

**Comment by codesome** [comment] 2020-12-24 12:30
@liuliqiang did you restart after every time change or only at the end to fix it? Either way, sounds weird either way since it should work, and I don't think WAL has anything to do with this weirdness.

**Comment by codesome** [comment] 2020-12-24 12:36
I think it has to do something with the scraping logic. I see `alignedScrapeTime` which remains uneffected by time change and always goes up. @roidelapluie since you worked on this part, do you think you could investigate this? I don't think this is related to TSDB since it does not play with the wall clock.

**Comment by roidelapluie** [comment] 2020-12-24 21:58
> I think it has to do something with the scraping logic. I see `alignedScrapeTime` which remains uneffected by time change and always goes up. @roidelapluie since you worked on this part, do you think you could investigate this? I don't think this is related to TSDB since it does not play with the wall clock.

If we are more that 2ms above or below alignedScrapeTime we ignore it and take the actual time. But I will have another look.

**Comment by liuliqiang** [comment] 2020-12-24 22:14
> @liuliqiang did you restart after every time change or only at the end to fix it? Either way, sounds weird either way since it should work, and I don't think WAL has anything to do with this weirdness.

I restart several times. 

First time I restart after the system time back to the time when i reset system lcok, but it not recovery.
Second and more time is the random try.
And the last time for my restart, it recovery show in the issue description.

**Comment by liuliqiang** [comment] 2020-12-30 10:02
hi, @roidelapluie @codesome  how is this issue going?

**Comment by Harkishen-Singh** [comment] 2021-04-12 18:09
> First time I restart after the system time back to the time when i reset system lcok, but it not recovery.

I wonder when you restarted after decreasing the system time (and prometheus was running by then), there were blocks in the tsdb dir such that the minvalidTime of head is still higher than 1pm. Maybe that is why it was saying out of order. Might be, deleting few recent blocks (along with wal) would have brought the minValidTime below 1pm and that should have been fine.

**Comment by roidelapluie** [comment] 2021-04-12 23:06
This is probably a duplicate of #8243 fixed by #8601. @liuliqiang can you update to 2.25.2 or 2.26.0 to test the fix? Thanks!

**Comment by Harkishen-Singh** [comment] 2021-04-13 09:54
I hope it's fixed. However, does anyone think 

https://github.com/prometheus/prometheus/blob/d1ced85d7a259250a36eaf0c47266e2c3c9ea00c/scrape/scrape.go#L592

can be a reason?

**Comment by dpkirchner** [comment] 2022-05-23 18:23
IMO it'd be helpful if Prometheus included more information with the "Error on ingesting samples that are too old or are too far into the future" error message. It's ambiguous -- are they too old or too far in the future? It's a big difference with potentially wildly different causes. Ideally, the log message would include the two compared timestamps. Without the timestamps, the messages are essentially noise.

(In my case the scrape target and prometheus-server are on servers with times that are essentially zero seconds apart, so I have to guess what the cause is.)

**Comment by jasper-zhang** [comment] 2022-09-19 08:30
I met the same issue, and I added some log before the err:
![image](https://user-images.githubusercontent.com/6657098/190976372-fb36a4bd-644b-47b7-959d-3456bd157645.png)

The log is:
![image](https://user-images.githubusercontent.com/6657098/190976607-c195b465-9480-4e01-bdba-81a4fdfb6e8a.png)

And I read the code, found the `maxt` may change when compact. 
![image](https://user-images.githubusercontent.com/6657098/190977056-f268d490-b216-4718-afc0-771db35a15f5.png)

The last block meta.json is:
![image](https://user-images.githubusercontent.com/6657098/190977194-f5be3ddb-9b2d-42ff-afad-bd1c5978f17f.png)

The duration of  MaxTime(from meta.json) and MaxTime(from head)  is  1800,  it is just half of chunk range (my chunk range is 3600). 

I wonder why this happened, and how to fix it?

(And I restart server many times, but it  happened after some hours again)

**Comment by bboreham** [comment] 2024-05-28 11:24
Hello from the bug-scrub!  

We believe this behaviour still exists, but we question whether this is something that Prometheus should deal with.  Production systems should have clocks that are synchronized with a global time source.

It should now be possible to recover more cleanly by turning on Out-Of-Order handling with a sufficient window.

If someone wants to work on a better way to handle this, please comment here and we can re-open.

**Closed by bboreham** 2024-05-28 11:24 UTC
Labels: kind/bug, priority/P3, component/scraping
