### ISSUE TITLE
volume bind not happening between local volume and /data (running in the container)

### ISSUE THREAD

**Issue by sundeepk1** [prometheus/prometheus#3503] opened 2017-11-22 09:53 UTC
sudo docker run -d -p 9090:9090 --name Prometheus-Monitoring -v ${PWD}/PROMETHEUS:/etc/prometheus/ -v ${PWD}/PROMETHEUS/PROMETHEUS_DATA:/data prom/prometheus:v2.0.0 --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/data -- --log.level=debug

**docker logs Prometheus-Monitoring**

level=info ts=2017-11-22T09:41:37.973165405Z caller=main.go:215 msg="Starting Prometheus" version="(version=2.0.0, branch=HEAD, revision=0a74f98628a0463dddc90528220c94de5032d1a0)"
level=info ts=2017-11-22T09:41:37.973218201Z caller=main.go:216 build_context="(go=go1.9.2, user=root@615b82cb36b6, date=20171108-07:11:59)"
level=info ts=2017-11-22T09:41:37.973236133Z caller=main.go:217 host_details="(Linux 4.4.0-1038-aws #47-Ubuntu SMP Thu Sep 28 20:05:35 UTC 2017 x86_64 2b1e1a313ee6 (none))"
level=info ts=2017-11-22T09:41:37.975595301Z caller=web.go:380 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2017-11-22T09:41:37.975564318Z caller=main.go:314 msg="Starting TSDB"
level=error ts=2017-11-22T09:41:37.975793217Z caller=main.go:323 **msg="Opening storage failed" err="open DB in /data: open /data/093999223: permission denied"**
ubuntu@ip-10-0-0-32:~/CM/Docker-StandAlone$

**Comment by brian-brazil** [comment] 2017-11-22 10:00
Dupe of #3480

**Closed by brian-brazil** 2017-11-22 10:00 UTC

**Comment by krasi-georgiev** [comment] 2017-12-04 14:50
this is  is dupe of #2939 and not #3480 right @brian-brazil ?

**Comment by brian-brazil** [comment] 2017-12-04 14:55
Right you are. Must have had that bug open at the same time and gotten confused.

**Comment by jcomeaux** [comment] 2017-12-18 05:59
I don't know about this being a dupe of #3480?  I was having the exact same issue, and it was because I was missing the "REXRAY_PREEMPT=true" option on the rexray/ebs driver.

Posted my solution here: https://groups.google.com/forum/#!topic/prometheus-users/khALXM9NhYQ

...in case anybody else turns up with the cryptic error from main.go:323 😄 

The root of the problem could have been more general though, as that "preempt" option on the rexray/ebs driver basically instructs to take the volume away from another node (and in my case, it was seeing the volume as in use?)
