### ISSUE TITLE
promtool rule test flaky (not deterministic) when eval_times are far apart

### ISSUE THREAD

**Issue by rudo-thomas** [prometheus/prometheus#7699] opened 2020-07-30 12:25 UTC
# promtool is flaky when eval_times are far apart in a rule test

## What did you do?

Ran `promtool test rules bug.testall.flaky.yaml` and got different results:
```
$ promtool-2.20.0 test rules bug.testall.flaky.yaml 
Unit Testing:  bug.testall.flaky.yaml
  FAILED:
    expr: "some_metric", time: 1h,
        exp:"{__name__=\"some_metric\"} 0E+00"
        got:"nil"

$ promtool-2.20.0 test rules bug.testall.flaky.yaml 
Unit Testing:  bug.testall.flaky.yaml
  SUCCESS
```
I used a script tun run promtool many times in succession to observe the flakiness.

The test has a single `promql_expr_test` against a trivial metric, but the `eval_time` of the two `<promql_test_case>`s are many `evaluation_interval`s apart. See the full file below.

## What did you expect to see?

It appears that under some circumstances, the test tool drops old data (see the failure above).

I expect the test tool not to drop any old data under any circumstances and, in this case, the test should consistently succeed.

* versions that exhibit the correct behaviour: `2.15.2`, `2.16.0`
* versions that exhibit the bug: `2.17.0`, ..., `2.20.0`

## What did you see instead? Under which circumstances?

I was unable to pinpoint to a particular reason for a failed vs successful run.

If you are getting consistent results, try running the tool 100 times and/or tweaking the later `eval_time`.
The value posted below (`30000h`) worked reasonably fine to trigger the flakiness on my system.

## Workaround

In my case the easiest workaround was to place the tests with different `eval_time` into separate files (see `bug.test1.ok.yaml` and `bug.test2.ok.yaml` in the attached archive).

Note that making these a separate `<test_group>` in a single file didn't help.

## Files for reproducing the bug
[promtool_flakiness.tar.gz](https://github.com/prometheus/prometheus/files/5001148/promtool_flakiness.tar.gz)

### `bug.rules.yaml`
```
groups:
- name: group
  interval: 1m  # irrelevant
  rules:
  - record: some_metric
    expr: 0
```
### bug.testall.flaky.yaml
```
rule_files:
- bug.rules.yaml
evaluation_interval: 30m
tests:
- promql_expr_test:
  - expr: some_metric
    eval_time: 1h
    exp_samples:
    - labels: some_metric{}
      value: 0
  - expr: some_metric
    # Tweak the following eval_time to get flaky behaviour.
    # Value too low => test always succeeds; too high => test always fails.
    eval_time: 30000h
    exp_samples:
    - labels: some_metric{}
      value: 0
```
Since `2.17.0` `promtool test rules bug.testall.flaky.yaml` is flaky.

## System information:

```
$ uname -srmpi
Linux 5.4.0-42-generic x86_64 x86_64 x86_64
```

## promtool version:

Downloaded for `linux-amd64` from the official github releases.

```
promtool, version 2.16.0 (branch: HEAD, revision: b90be6f32a33c03163d700e1452b54454ddce0ec)
  build user:       root@7ea0ae865f12
  build date:       20200213-23:50:02
  go version:       go1.13.8
promtool, version 2.17.0 (branch: HEAD, revision: 39e01b369dbd78278ca63e54f4976dff3b41df98)
  build user:       root@604d4517e800
  build date:       20200324-17:04:11
  go version:       go1.13.9
promtool, version 2.20.0 (branch: HEAD, revision: e5a06b483527d4fe0704b8fa3a2b475b661c526f)
  build user:       root@ac954b6d5c6e
  build date:       20200722-18:51:45
  go version:       go1.14.6
```

**Comment by johncming** [comment] 2020-07-31 03:44
The cause is the change from `time.Duration` to `model.Duration`.  Related PR is https://github.com/prometheus/prometheus/pull/6297.

The bug of this pr is that `time.ParseDuration` checks bigger integer but `model.ParseDuration` not.

Another bug is that `time.Duration` is not equal to `model.Duration`,  the unit of `time.Duration`  is `ns`, the unit of `model.Duration` is `ms`.

**Comment by brian-brazil** [comment] 2020-07-31 09:30
That doesn't seem right as an explanation, as that would have broken all the tests.

**Comment by johncming** [comment] 2020-07-31 10:25
> That doesn't seem right as an explanation, as that would have broken all the tests.

Only impact this case `promql_expr_test ` which has no test covered.

**Comment by rudo-thomas** [comment] 2020-07-31 12:23
@johncming

I agree with brian-brazil: The PR you mentioned (#6297) has been merged in June, but I was able to reproduce this as early as in 2.17.0 released in March.

Re: the error being "more deterministic" when you tweak the `eval_time` -- it's the `promtool` that has a bug and is not deterministic; there is no error in the test itself.

**Comment by Harkishen-Singh** [comment] 2020-09-09 10:40
Taking up this.

**Comment by Harkishen-Singh** [comment] 2020-09-18 13:25
So, I was working on this and seems (since I didn't encounter a failure) that the tsdb.DefaultOptions is the culprit. The retention policy for teststorage is too short for that range. As I increased the retention policy, it worked and haven't faced failures till now. I tested with `1h` and `300000h` because what @johncming  said is out of range.

If this is the reason, then I don't think there is a fix.

What do you think @brian-brazil ?

**Comment by brian-brazil** [comment] 2020-09-18 13:33
I'm confused, is there an issue here or not? It sounds to me like we need to adjust the tsdb options for promtool tests.

**Comment by Harkishen-Singh** [comment] 2020-09-18 13:35
I don't think there's a bug. Its just related to tsdb options. Do you want a PR for this?

**Comment by brian-brazil** [comment] 2020-09-18 14:24
If there's no bug, then there's no need for a PR.

**Comment by Harkishen-Singh** [comment] 2020-09-20 10:13
Should we close this?

**Comment by rudo-thomas** [comment] 2020-09-20 10:20
> Should we close this?

This is definitely a bug: If a well-written test sometimes fails and sometimes succeeds, the test tool is buggy.

If there is an option to tweak, it should be documented in the promtool help.

I will re-test with 2.21.0 next week.

**Comment by rudo-thomas** [comment] 2020-09-23 14:46
2.21.0 still has this bug.

After experimenting with the tsdb options, I agree with @brian-brazil when he said "sounds to me like we need to adjust the tsdb options for promtool tests". With the following patch, the 30000h test from the original report *always* succeeded:
```
diff --git a/util/teststorage/storage.go b/util/teststorage/storage.go
index 6fa90781e..88f4dd5cc 100644
--- a/util/teststorage/storage.go
+++ b/util/teststorage/storage.go
@@ -33,6 +33,7 @@ func New(t testutil.T) *TestStorage {
        // Tests just load data for a series sequentially. Thus we
        // need a long appendable window.
        opts := tsdb.DefaultOptions()
+       opts.RetentionDuration = int64(40000 * time.Hour / time.Millisecond)
        opts.MinBlockDuration = int64(24 * time.Hour / time.Millisecond)
        opts.MaxBlockDuration = int64(24 * time.Hour / time.Millisecond)
        db, err := tsdb.Open(dir, nil, nil, opts)
```

I'm not partcularly familiar with the code, but could the RetentionDuration be just set to `math.MaxInt64`? :)
Maybe that's the PR that @Harkishen-Singh was suggesting?

**Comment by brian-brazil** [comment] 2020-09-23 16:18
If setting that really low breaks everything, then MaxInt would make sense.

**Comment by Harkishen-Singh** [comment] 2020-09-23 16:49
Yes, and that should solve all range concerns that promtool has with respect to rule tests. Sounds good @brian-brazil ? (PR?)

**Comment by dgl** [comment] 2021-05-12 12:23
There's now tests for the unit testing and some other fixes that mean this won't manifest in quite the same way (the non-determinism may have come from the fact other tests in the file influenced the eval time), but the fix is still correct even if it is much less likely, so opened a PR.

**Closed** 2022-01-02 22:46 UTC
Labels: kind/bug, component/promtool, priority/P3
