### ISSUE TITLE
Unary Negation operation drops metric name

### ISSUE THREAD

**Issue by yeya24** [prometheus/prometheus#11390] opened 2022-10-02 07:09 UTC
### What did you do?

Tried to run some promql queries using unary operators, like `+up` and `-up`.

### What did you expect to see?

The two queries should give me the same series and I expect only the values should be different. 

### What did you see instead? Under which circumstances?

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/25150124/193442366-820a6f6c-6cb8-4226-a91d-cb36f2fff50d.png">

When `-` is specifed the metric name label is also dropped. I think the bahavior should be consistent for `+` and `-`.

In the code, only `-` op is handled and metric name gets dropped https://github.com/prometheus/prometheus/blob/main/promql/engine.go#L1503. I am not sure about the history why we want to drop the metric name in this case, but if we want to drop the name, we should do the same for `+` op as well. 

### Prometheus version

```text
I used the Prometheus demo site https://prometheus.demo.do.prometheus.io/.
```

**Comment by roidelapluie** [comment] 2022-12-22 22:01
I think the difference in behavior between the + and - operators is related to the fact that + is a no-op and does not change the metric value, while - inverts the value. As a result, the + operator keeps the metric name label as it is not changing anything, while the - operator drops the metric name label because it is modifying the metric value.

It's worth noting that the behavior you are seeing is the intended behavior for these operators. However, I don't have the full context or the history behind this design decision. It might be worth reaching out to @juliusv to see if he has any additional insights on this.

*note: generated with the help of chatgpt*

**Comment by juliusv** [comment] 2022-12-23 07:10
Yes, that's the reason. `+` is a no-op, while `-` changes the meaning of the metric, so the name is dropped, which is the general rule in PromQL.

**Comment by roidelapluie** [comment] 2023-02-20 23:40
I will close this as I think there is no bug

**Closed by roidelapluie** 2023-02-20 23:40 UTC
