### ISSUE TITLE
Crash during shutdown - SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by benz-netapp** [prometheus/prometheus#15401] opened 2024-11-14 19:43 UTC
### What did you do?

After updating to v2.55.0, we've observed occassional crashes when stopping Prometheus.

We were previously on v2.43.0 and did not observe crashes on that version.

### What did you see instead? Under which circumstances?

No crash on shutdown.

### System information

Linux 6.1.106-3 x86_64

### Prometheus version

```text
prometheus, version 2.55.0 (branch: HEAD, revision: 91d80252c3e528728b0f88d254dd720f6be07cb8)
  build user:       root@9fad779131cc
  build date:       20241022-13:47:22
  go version:       go1.23.2
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Logs

```text
ts=2024-11-13T08:45:36.391Z caller=main.go:1029 level=warn msg="Received an OS signal, exiting gracefully..." signal=terminated
ts=2024-11-13T08:45:36.392Z caller=main.go:1056 level=info msg="Stopping scrape discovery manager..."
unexpected fault address 0x7f311ec86aa0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f311ec86aa0 pc=0x47f26e]

goroutine 4021 gp=0xc002317dc0 m=13 mp=0xc000603108 [running]:
runtime.throw({0x3dc689a?, 0x3e8?})
#011/usr/local/go/src/runtime/panic.go:1067 +0x48 fp=0xc00618a808 sp=0xc00618a7d8 pc=0x475a68
runtime.sigpanic()
#011/usr/local/go/src/runtime/signal_unix.go:914 +0x26c fp=0xc00618a868 sp=0xc00618a808 pc=0x477a8c
runtime.memmove()
#011/usr/local/go/src/runtime/memmove_amd64.s:372 +0x42e fp=0xc00618a870 sp=0xc00618a868 pc=0x47f26e
github.com/prometheus/prometheus/promql.ActiveQueryTracker.Delete(...)
#011/app/promql/query_logger.go:209
github.com/prometheus/prometheus/promql.(*ActiveQueryTracker).Delete(0xc002317dc0?, 0x3a99)
#011<autogenerated>:1 +0xe6 fp=0xc00618a900 sp=0xc00618a870 pc=0x2c48c86
github.com/prometheus/prometheus/promql.(*Engine).queueActive.func2()
#011/app/promql/engine.go:695 +0x24 fp=0xc00618a920 sp=0xc00618a900 pc=0x2c0c5e4
runtime.deferreturn()
#011/usr/local/go/src/runtime/panic.go:605 +0x5e fp=0xc00618a9b0 sp=0xc00618a920 pc=0x43b2fe
github.com/prometheus/prometheus/promql.(*Engine).exec(0xc0008bef00, {0x466b3d0, 0xc0079f39e0}, 0xc000703c70)
#011/app/promql/engine.go:678 +0x3d7 fp=0xc00618abb0 sp=0xc00618a9b0 pc=0x2c0b557
github.com/prometheus/prometheus/promql.(*query).Exec(0xc000703c70, {0x466b3d0, 0xc0079f3770})
#011/app/promql/engine.go:245 +0x1c5 fp=0xc00618aca0 sp=0xc00618abb0 pc=0x2c08de5
main.main.EngineQueryFunc.func45({0x466b3d0, 0xc0079f3770}, {0xc00794c840?, 0x0?}, {0x3aa8540?, 0xc0078735e0?, 0x0?})
#011/app/rules/manager.go:52 +0x95 fp=0xc00618ad20 sp=0xc00618aca0 pc=0x2f29e95
github.com/prometheus/prometheus/rules.(*AlertingRule).Eval(0xc001367440, {0x466b3d0, 0xc0079f3770}, 0x0?, {0xc00428f8c0?, 0x0?, 0x0?}, 0xc0009a53b0, 0xc000692240, 0x0)
#011/app/rules/alerting.go:343 +0x23e fp=0xc00618b320 sp=0xc00618ad20 pc=0x2c543be
github.com/prometheus/prometheus/rules.(*Group).Eval.func1(0x19, {0x4695460, 0xc001367440}, 0x0)
#011/app/rules/group.go:516 +0x7b2 fp=0xc00618bbc0 sp=0xc00618b320 pc=0x2c5b692
github.com/prometheus/prometheus/rules.(*Group).Eval(0xc002836a20, {0x466b3d0, 0xc0048042d0}, {0x4614930?, 0x37e23e741?, 0x0?})
#011/app/rules/group.go:632 +0x36f fp=0xc00618bc90 sp=0xc00618bbc0 pc=0x2c5accf
github.com/prometheus/prometheus/rules.DefaultEvalIterationFunc({0x466b3d0, 0xc0048042d0}, 0xc002836a20, {0x37e11d600?, 0x350e040?, 0x0?})
#011/app/rules/manager.go:81 +0xf7 fp=0xc00618bd20 sp=0xc00618bc90 pc=0x2c60ff7
github.com/prometheus/prometheus/rules.(*Group).run(0xc002836a20, {0x466b398, 0x67f7ac0})
#011/app/rules/group.go:295 +0x9da fp=0xc00618bf88 sp=0xc00618bd20 pc=0x2c5879a
github.com/prometheus/prometheus/rules.(*Manager).Update.func1(0xc002836a20)
#011/app/rules/manager.go:241 +0xa6 fp=0xc00618bfc8 sp=0xc00618bf88 pc=0x2c624e6
github.com/prometheus/prometheus/rules.(*Manager).Update.gowrap2()
#011/app/rules/manager.go:242 +0x24 fp=0xc00618bfe0 sp=0xc00618bfc8 pc=0x2c62404
runtime.goexit({})
#011/usr/local/go/src/runtime/asm_amd64.s:1700 +0x1 fp=0xc00618bfe8 sp=0xc00618bfe0 pc=0x47e061
created by github.com/prometheus/prometheus/rules.(*Manager).Update in goroutine 289
#011/app/rules/manager.go:231 +0x3b8

goroutine 1 gp=0xc0000061c0 m=nil [runnable]:
runtime.pcvalue({0x66be328?, 0x66df500?}, 0x6bfaac?, 0x2f28b65?, 0x0?)
#011/usr/local/go/src/runtime/symtab.go:958 +0x6a9 fp=0xc000d62938 sp=0xc000d62930 pc=0x45c169
runtime.funcline1({0x5295ba1?, 0x5295ba1?}, 0x2f28b65, 0x0)
#011/usr/local/go/src/runtime/symtab.go:1139 +0x65 fp=0xc000d62988 sp=0xc000d62938 pc=0x4799c5
runtime.(*Frames).Next(0xc00807c2d0)
#011/usr/local/go/src/runtime/symtab.go:191 +0x729 fp=0xc000d62ab0 sp=0xc000d62988 pc=0x45b149
runtime.Caller(0x5)
#011/usr/local/go/src/runtime/extern.go:307 +0xf8 fp=0xc000d62bd8 sp=0xc000d62ab0 pc=0x40d578
github.com/prometheus/common/promlog.NewWithLogger.Caller.func1()
#011/go/pkg/mod/github.com/go-kit/log@v0.2.1/value.go:86 +0x1b fp=0xc000d62c48 sp=0xc000d62bd8 pc=0xa011fb
github.com/go-kit/log.bindValues({0xc008928c80, 0x4, 0xc000680708?})
#011/go/pkg/mod/github.com/go-kit/log@v0.2.1/value.go:20 +0x6c fp=0xc000d62c78 sp=0xc000d62c48 pc=0x990a6c
github.com/go-kit/log.(*context).Log(0xc00088c1e0, {0xc006af9f00?, 0x4, 0x2?})
#011/go/pkg/mod/github.com/go-kit/log@v0.2.1/log.go:162 +0x245 fp=0xc000d62d00 sp=0xc000d62c78 pc=0x98f7c5
github.com/go-kit/log/level.(*logger).Log(0xc00aea9900?, {0xc006af9f00?, 0x20?, 0x0?})
#011/go/pkg/mod/github.com/go-kit/log@v0.2.1/level/level.go:71 +0x9b fp=0xc000d62d30 sp=0xc000d62d00 pc=0x991d5b
github.com/go-kit/log.(*context).Log(0xc00711e9b0, {0xc00aea9920?, 0x2, 0x2?})
#011/go/pkg/mod/github.com/go-kit/log@v0.2.1/log.go:168 +0x34f fp=0xc000d62db8 sp=0xc000d62d30 pc=0x98f8cf
main.main.func15({0x10?, 0xb?})
#011/app/cmd/prometheus/main.go:1070 +0xc6 fp=0xc000d62e28 sp=0xc000d62db8 pc=0x2f28b66
github.com/oklog/run.(*Group).Run(0xc000d63470)
#011/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:47 +0x17d fp=0xc000d62ea0 sp=0xc000d62e28 pc=0x9ff47d
main.main()
#011/app/cmd/prometheus/main.go:1338 +0xbede fp=0xc000d63f50 sp=0xc000d62ea0 pc=0x2f260fe
runtime.main()
#011/usr/local/go/src/runtime/proc.go:272 +0x28b fp=0xc000d63fe0 sp=0xc000d63f50 pc=0x43f4eb
runtime.goexit({})
#011/usr/local/go/src/runtime/asm_amd64.s:1700 +0x1 fp=0xc000d63fe8 sp=0xc000d63fe0 pc=0x47e061
```

**Comment by machine424** [comment] 2024-11-15 07:45
This looks like a duplicate of https://github.com/prometheus/prometheus/issues/15232, I suggest we link them and continue discussion there.

**Comment by jan--f** [comment] 2024-11-18 15:35
Closing this on in favor of #15232.

**Closed as completed by jan--f** 2024-11-18 15:35 UTC
Labels: duplicate
