### ISSUE TITLE
Make alerts stateless

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#1117] opened 2015-09-26 12:39 UTC
Alerting rules should always be evaluated as a range query over the entire hold duration so pending alerts are not lost on restart.

**Comment by matthiasr** [comment] 2015-09-26 12:40
:+1:

**Comment by brian-brazil** [comment] 2015-09-26 15:31
This is a dupe of #422 .

I think we'll need something more nuanced to cover both the time when the prometheus server is down (we don't want an alert before 2 scrapes have been done so we have our bearings), and that doing the query historically may not have exactly the same results as doing it at each point in time.

**Closed by brian-brazil** 2015-09-26 15:31 UTC

**Comment by juliusv** [comment] 2015-09-28 10:54
Also, doing the query always over the entire `FOR` range gets prohibitively expensive for some alert expressions, so the state needs to be kept separately for alerting rules.

**Comment by fabxc** [comment] 2015-09-28 11:06
That's something I strongly doubt without measurements indicating otherwise.
Our evaluation interval typically is 60s, alerts are on average `FOR 10m`.
This increases my computation by 10x. Chunk preloading is not affected in
most cases as a single sample of samples over 10m are in the same chunk.

As alerting rule evaluation has never been anything but white noise so far,
the increase is most likely completely negligible.

If on the other hand, it would be an issue. This would be a clear sign to
me that we have to work on our completely naiive query evaluation, which
can most likely be an order of magnitude more efficient.

**Comment by juliusv** [comment] 2015-09-28 11:14
As `FOR` durations are not technically limited, some people will have `FOR` durations of multiple hours, or in pathological cases even days (although the latter would usually be a bad idea in any case). This will definitely have a big impact on rule evaluations. Of course optimizing general expression evaluation is always a good idea, but I don't see that legitimizing making alert evaluations potentially 100x or more expensive than they are now.

**Comment by brian-brazil** [comment] 2015-09-28 11:14
I'm expecting to see for expressions up to a month in length in common usage, so I agree with Julius that I don't see this approach working out.

**Comment by fabxc** [comment] 2015-09-28 11:18
At which evaluating at 1m intervals would be a highly questionable approach.

**Comment by juliusv** [comment] 2015-09-28 11:25
Even if you increase the interval by a bit, that'll be very confusing to a user, why suddenly `FOR` doesn't work at their defined rule evaluation interval anymore, and also it would still kill the storage because it'd load a huge amount of history. We should keep the `FOR` state separately.

**Comment by juliusv** [comment] 2015-09-28 11:27
Also, most rules should be able to be answered from memory alone. Once we need to go to disk, we are already dead for many of them (you can already see that after some beefy servers start up - they take a while to function properly after restart because the rules load so much from disk).

**Comment by matthiasr** [comment] 2015-09-28 11:28
So, the original reason we thought about doing it this way was to get sensible evaluation of FOR over restarts / reloads, without having to introduce yet another bit of storage that needs to be updated and cared for.

We don't need to make the evaluation "really" stateless – but what about using the timeseries data if the rule hasn't been evaluated since a restart / reload, but cache the result of that (the time when it started firing) in memory?

**Comment by brian-brazil** [comment] 2015-09-28 11:33
> We don't need to make the evaluation "really" stateless – what about using the timeseries data if the rule hasn't been evaluated since a restart / reload, but cache the result of that (the time when it started firing) in memory?

Such as via `ALERTS`? It needs a little bit more than that (we need the time it started firing and to add a bit more time for 'for' expressions on the lower end), but the general approach sounds good.

**Comment by barkerd427** [comment] 2015-09-28 12:09
We run batch jobs weekly or monthly, so my for time goes back that far.
Without some sort of method for determining the date or day of the week, I
have to go back a week to ensure we get results each week. This may just be
a poor architecture, but it is working well currently.

**Comment by jinhang** [comment] 2016-11-07 13:10
@brian-brazil why I write `for 1s` but the pending to firing use time more than 1s ?

**Comment by juliusv** [comment] 2016-11-08 17:19
@jinhang Because alerts need at least one rule evaluation cycle to go from pending to firing. I would guess that your rule evaluation cycle is much longer. You can just omit `FOR` to go directly into firing mode. This question is not related to this issue though.
