### ISSUE TITLE
add ability to set max resolution

### ISSUE THREAD

**Issue by Andor** [prometheus/prometheus#2253] opened 2016-12-05 13:21 UTC
Currently, we have hardcoded limit for 11000 data points per query.
I think we should make it configurable. For some cases, we need to limit it to less than 4096, sometimes we need higher resolution more than 11000.

https://github.com/prometheus/prometheus/blob/30af47535d4d7c0a7566df78e63e77515ba26863/web/api/v1/api.go#L202
```
	// For safety, limit the number of returned points per timeseries.
	// This is sufficient for 60s resolution for a week or 1h resolution for a year.
	if end.Sub(start)/step > 11000 {
		err := errors.New("exceeded maximum resolution of 11,000 points per timeseries. Try decreasing the query resolution (?step=XX)")
		return nil, &apiError{errorBadData, err}
	}
```

**Comment by brian-brazil** [comment] 2017-03-27 13:04
Can you explain in what cases you need more than 11k points, and why you can't handle it in multiple requests?

**Comment by olivernadj** [comment] 2017-03-30 02:20
Hi Brian,
We use Prometheus for system, application and business metrics and provide access for system engineers, developers, QA and even non IT guys.
Since many associate can build dashboards in Grafana it follows that some of them are performing slowly and one of the reason is the non optimal resolution.
In the office I did not find any person who has wider screen than 4096 pixel, but I find many dashboards try to represent few thousands data points in a small graph, what causes unintended overload.   
To keep Prometheus responsive we decreased max response time, but we would also like to decreased max resolution as I prefer a die quick approach.

**Comment by Daemon-Knoppix** [comment] 2017-11-22 06:58
Hi Brian,

I am new to machine learning and monitoring servers and using Prometheus 2.0.0 on `ubuntu 16.04` and monitoring stats over a period of time.

My scraping cycle is 1s that means for getting stats overtime for `1 day` i need to process **`86400 datapoints`** `(24 × 60 × 60)` (which is pretty reasonable) i have to call query range api about 8 times as per current limit 11000.

When i start monitoring datapoints for a month (assuming 31 days) value of datapoints jumps to **`2678400 datapoints`** `( (24 × 60 × 60) * 31 )`, which as per current limit of 11000 becomes query range api call of about 243 times.

It would be great if this setting could be introduced for user to decide how much datapoints they need at a time.

> *Assuming this setting will be added in future, doing this might take time ... Can you please guide me on how and where can i change this on my Ubuntu source code ? As it only shows me binary code which is not human readable.

**Comment by brian-brazil** [comment] 2017-11-22 09:13
You probably want the query endpoint there to get raw data, not query range which is evaluating promql.

That sort of massive query is why we have this limit :)

**Comment by Daemon-Knoppix** [comment] 2017-11-22 09:26
Thanks for a quick reply!!

True, datapoints for a month will result in a very big data set ... How can i achieve query endpoint for raw data ? Can you share a tutorial or a guide ?

**Comment by Daemon-Knoppix** [comment] 2017-11-22 10:48
Brian, [this query](https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries, "Instant Queries") provides data for a single instance in time (current or at a single point), not a solution to what i am looking for, i am **evaluating data for a month** ... Let me explain -

Lets say i want to check how many times my server was **down over a month** (i.e up == 0). Now if i use instant queries it will give me record of a single instance in time that means for a month i will end up fetching data from `2678400 api calls`. Query range however provides data for `11000 datapoints` at once only.

I have build a code in NodeJS (which at my end is very much optimized) that divides 2 dates ranges into intervals as per maximum limit (which in this case is `11000`) and make api calls to fetch data.

When i process data for a month i hit api call `243 times` (asynchronous parallel calls using async module) which is taking overall time `70 - 80 seconds` to fetch data for a month (for a single instance i am monitoring 24*7).

Now if the query was to status code of my application `200, 400 etc.`. This single api time increases to 3 to 5 seconds which makes overall process exceed limit.

So i can now see 2 ways to get faster results for getting data for a month -

1. Limit of 11000 datapoints is increased at Prometheus end.
2. I create my own data parser on location Prometheus is storing its datapoints.

Considering option 2 : As i have not looked at source code of Prometheus it will be a little tricky for me to perform this in a short time frame. If i can get a guide on how your query engine works / stores datapoints i might end up creating / enhancing my own logic in it or externally.

Considering option 1 : If increasing datapoint limit at Prometheus end is not that of a big deal in terms of performance, as it's query engine must be very much optimized by you guys ... I would like to know how can i do that in Ubuntu 16.04 setup of Prometheus or change in source code and build a new setup from current updated source.

Please let me know which option would you suggest. Thanks in advance!!!

**Comment by Gouthamve** [comment] 2017-11-22 10:55
@Daemon-Knoppix Append the time range to the end of the query string. Ex: `http://localhost:9090/api/v1/query?query=up[10h]&time=1511347941.586`

Also, please ask further queries like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by RedheatWei** [comment] 2019-08-06 09:31
I don't think limit 11k is a good idea especially that I'm trying to get all data points for machine learning by http api, so can you tell me how can I do this? Like this issue's title, I think that's necessary. That's unecessary for UI but not http api.

**Comment by astrieanna** [comment] 2019-12-03 17:42
I'm also running into this problem. While I can split the queries up and then recombine the data, it seems like pointless extra work. I'm getting data on each node of a 60 node cluster with start/step/end set to give 1000 time steps. Each node with have its own line on the graph, so I don't want to lower the resolution based on the number of nodes to sample. I also plan to run the same queries on larger clusters in the future, so the downsampling required to achieve only 11k samples would increase.

Why is the 11k limit needed? Considering I have a script gathering the data, I don't mind waiting a significant period of time for the query to complete. Making this configurable (with the existing 11k limit as the default) would make my work easier without harming the default use-case.

**Comment by brian-brazil** [comment] 2020-03-16 15:38
After 4 years noone has presented a use case for graphing with more than this many steps. On the other hand we have more protections for PromQL memory these days - but part of their implementation tradeoffs includes that this limit is in here. Given all that this limit seems appropriate. If people start getting wider monitors that require a higher limit we can bump this, but there doesn't seem to be a need to make it configurable so I'm going to close this off.

**Closed by brian-brazil** 2020-03-16 15:38 UTC
Labels: component/ui, kind/enhancement, priority/Pmaybe

**Comment by mhellmeier-ISST** [comment] 2021-07-14 13:10
I am also looking for an option to configure and change the maximum resolution limit.

Let me just comment some of your points, @brian-brazil :

> Can you explain in what cases you need more than 11k points, and why you can't handle it in multiple requests?

One example: You want to make an experiment with a long execution time and a short resolution. At the end, all collected data points should be exported. There are still cases where it isn't possible to time and export every X days. Even if it's possible, it yields to much more work to connect the results of the multiple requests.
Another example: If you have got one machine and you want to make scientific experiments on it, you don't want to start and query an export in the middle of the experiment. This could lead to some adulterations of the results caused by the request in the middle of the experiment.



> Given all that this limit seems appropriate. If people start getting wider monitors that require a higher limit we can bump this, but there doesn't seem to be a need to make it configurable so I'm going to close this off.

Currently, there are 10 thumps up for this issue. This means that there is already interest in the implementation and that use cases exists.

Just remember: No one wants to increase the default limit for all prometheus projects to an extremely high value. People want to have an option to increase or decrease the value without building the whole project from source. The default value of `11000` might be okay for 99 % of the users. But to give the other small amount of users the ability to satisfy their use cases, a config option would be great.

**Comment by roidelapluie** [comment] 2021-07-14 22:36
This is a very advanced move that is in almost every case a mistake and the default limit of 11000 on query_range should not be configurable.

Advanced users can use `[]` selectors in the query endpoint (not query_range) if they want to extract more data. You can do: `metric[1w]` (to get raw data) or `rate(foo[5m])[1w:1h]` (to get eval every 1h for 1 week) using the instant query endpoint. This is not something we want to document or advertise, but if you really want to use this workaround, it might work for you.
