### ISSUE TITLE
Edit page button flashing

### ISSUE THREAD

**Issue by lujinghai** [prometheus/prometheus#11985] opened 2023-02-17 07:21 UTC
### What did you do?

i deploy  my prometheus

### What did you see instead? Under which circumstances?

When I deploy my Prometheus monitoring to my server and enter the service monitoring page, I check a specific data, such as CPU monitoring, there is a flashing in the upper right corner, and when I use F11 to check, I find that a button has been called, and the apply button has been flashing between hidden and visible, resulting in uninterrupted flashing in the upper right corner.
The bug location appears on the discard, save, apply page, I think there is a problem with the logic of the button, the class of this button is css-s11uau-toolbar-button.

### System information

CentOS7.4

### Prometheus version

```text
prometheus --2.42.0
```

**Comment by roidelapluie** [comment] 2023-02-20 23:14
Can you share a screenshot and your browser version?

**Comment by lujinghai** [comment] 2023-02-21 09:22
> 您可以分享屏幕截图和浏览器版本吗？
The browser version is Google Chrome 86.0.4240.75 (official version) (64-bit), could it be the reason for the timer?
Screenshots are not very convenient to upload, sorry

**Comment by lujinghai** [comment] 2023-02-21 09:39
Find the cause of the problem, browser version

**Comment by roidelapluie** [comment] 2023-03-05 23:56
Thank you for letting me know. Since you have identified the cause of the issue, I will close this ticket. If you encounter any other problems, please don't hesitate to open a new issue. Thank you for using Prometheus!

**Closed by roidelapluie** 2023-03-05 23:56 UTC
