### ISSUE TITLE
Prometheus Agent Stops Scraping all its Targets after sometime without any error logs.

### ISSUE THREAD

**Issue by Rahuly360** [prometheus/prometheus#10151] opened 2022-01-11 06:52 UTC
Prometheus with --enable-feature=agent Stops Scraping all its Targets after sometime and when we check in terminal logs there is no such logs related scraping stop. 
Is anyone has any idea about this ???
Image : prometheus:v2.32.0
Stop Targets 
<img width="445" alt="image" src="https://user-images.githubusercontent.com/87700693/148894045-4e70b62e-7ed5-4b71-9f71-303bff725748.png">

**Comment by codesome** [comment] 2022-01-11 12:44
cc @rfratto

**Comment by roidelapluie** [comment] 2022-01-11 13:16
Can you tell us if all your targets are affected? Is your browser and Prometheus Agent at the correct/same time?

**Comment by rfratto** [comment] 2022-01-11 14:06
We ran into a similar issue with Grafana Agent, where the root cause was a deadlock in the series tracker. That bug should've been fixed by the time we moved the code, but maybe I missed something. A goroutine dump would be really useful here.

**Comment by Rahuly360** [comment] 2022-01-11 14:11
Is anyone here who is using Prometheus Agent currently with the successful scraping targets ???

**Comment by rfratto** [comment] 2022-01-14 13:47
For reference, this was the Grafana Agent issue we fixed that seemed similar to this: grafana/agent#185. Those changes seem to have been brought over in the initial move, so either something else is wrong or moving the code re-introduced a deadlock somewhere else.

**Comment by rfratto** [comment] 2022-01-14 13:55
I suspect something may be wrong with [stripeSeries.Set](https://github.com/prometheus/prometheus/blob/a5d57c926903677e0e16c29bce46de69dfca153f/tsdb/agent/series.go#L177-L192) being run in parallel to [stripeSeries.gc](https://github.com/grafana/agent/blob/e1df94f5751b8b27b475adaca5e653739f455407/pkg/metrics/wal/series.go#L132).

The equivalent [Grafana Agent code](https://github.com/grafana/agent/blob/e1df94f5751b8b27b475adaca5e653739f455407/pkg/metrics/wal/series.go#L207-L217) doesn't try to grab both locks at once. I'm trying to think through if that would cause any problems here.

**Comment by rfratto** [comment] 2022-01-14 14:03
> The equivalent Grafana Agent code doesn't try to grab both locks at once. I'm trying to think through if that would cause any problems here.

OK, it's definitely likely this is the problem, and I can follow how it would cause a deadlock. I'll open a PR.

**Comment by rhowe-trp** [comment] 2022-01-18 15:10
I have also witnessed this behaviour although I don't have a goroutine dump.  If I see it happen again I'll try and grab one.

**Comment by rhowe-trp** [comment] 2022-01-21 13:51
OK, I think we have an example of this

prom 2.32.1 build 41f1a8125e664985dd30674e5bdf6b683eff5d32

The goroutine dump is at https://gist.github.com/rhowe-trp/c84591d0d14872dfd9679c5e2f065bac

**Comment by roidelapluie** [comment] 2022-02-25 16:11
Can you confirm that this was fixed in latest prometheus release? (latest is 2.33.4 at time of writing) ?

**Comment by Rahuly360** [comment] 2022-03-04 08:49
@roidelapluie  Thank you 
The latest Prometheus release( 2.33.4 a) working fine for the same.

**Closed** 2022-03-08 17:04 UTC
