### ISSUE TITLE
Fix notation of `storage.tsdb.retention.size` to match kubernetes notation

### ISSUE THREAD

**Issue by sed-i** [prometheus/prometheus#10768] opened 2022-05-28 05:26 UTC
## Proposal
Let `storage.tsdb.retention.size` take values in the same format as k8s does, specifically:
- support both binary and decimal formats
- interpret unitless values as decimal bytes

Currently, the `storage.tsdb.retention.size` flag is expected to be specified in decimal notation (e.g. 500MB), but is interpreted as binary notation (i.e. 500MiB):

> supported units: B, KB, MB, GB, TB, PB, EB. Ex: \"512MB\". Based on powers-of-2, so 1KB is 1024B.

https://github.com/prometheus/prometheus/blob/57f4aab27d53872b109c8513846765df6b51eb57/cmd/prometheus/main.go#L304-L307

Compare to [k8s spec](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-memory):

> You can express memory as a plain integer or as a fixed-point number using one of these [quantity](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/quantity/) suffixes: E, P, T, G, M, k. You can also use the power-of-two equivalents: Ei, Pi, Ti, Gi, Mi, Ki. For example, the following represent roughly the same value:
>
> 128974848, 129e6, 129M,  128974848000m, 123Mi

This is actually a standard ([ref](https://en.wikipedia.org/wiki/Byte#History_of_the_conflicting_definitions)):

> In December 1998, the IEC addressed such multiple usages and definitions by adopting the IUPAC's proposed prefixes (kibi, mebi, gibi, etc.) to unambiguously denote powers of 1024. Thus one kibibyte (1 KiB) is 1024^1 bytes = 1024 bytes, one mebibyte (1 MiB) is 1024^2 bytes = 1,048,576 bytes, and so on.

**Comment by roidelapluie** [comment] 2022-05-30 15:45
I do not think we should support unitless values. For decimal notation (e.g. 500MB), 500MB is not the decimal notation, which should be `500mB`, and is rejected by Prometheus. We could have it, if it is accepted upstream: https://github.com/alecthomas/units

**Comment by sed-i** [comment] 2022-05-30 17:01
My bad, seems like `storage.tsdb.retention.size` is currently using **legacy binary** notation. Is that correct?
![image](https://user-images.githubusercontent.com/82407168/171034717-5625b570-2ed6-490f-a23a-127e1eb39611.png)

but seems like `alecthomas/units` supports all three to some extent.

Other than "kB" and "KB", all the others (MB, GB, TB) are identical, so for backwards compatibility would probably have to have a new flag and "Overrides _ if this flag is set to anything other than default."..?

**Comment by frittentheke** [comment] 2022-07-15 11:39
BTW, this issue seems to be a duplicate of https://github.com/prometheus/prometheus/issues/9406.

**Comment by bboreham** [comment] 2024-07-16 11:45
Closing as duplicate of #9406.

**Closed by bboreham** 2024-07-16 11:45 UTC
Labels: kind/enhancement, not-as-easy-as-it-looks, priority/P3
