### ISSUE TITLE
Alertmanager stops sending data  

### ISSUE THREAD

**Issue by rjhaylor** [prometheus/prometheus#7171] opened 2020-04-26 18:17 UTC
**What did you do?**

Increased uwsgi processes to 40 that helped but still an issue over time 

**What did you expect to see?**
Data in alerta but goes blank and alertmanager sometimes just stops but in this state if it shows up it does not send data to alerta 
**What did you see instead? Under which circumstances?**

We feel this may be an issue related to the amount of alerts being sent. Says 1000 critical  alerts 

**Environment**

VM 

* System information:

Linux 3.10.0-862.14.4.el7.x86_64 x86_64

* Prometheus version:

prometheus, version 2.15.2 (branch: HEAD, revision: d9613e5c466c6e9de548c4dae1b9aabf9aaf7c57)
  build user:       root@688433cf4ff7
  build date:       20200106-14:50:51
  go version:       go1.13.5
* Alertmanager version:

alertmanager, version 0.15.3 (branch: HEAD, revision: d4a7697cc90f8bce62efe7c44b63b542578ec0a1)
  build user:       root@4ecc17c53d26
  build date:       20181109-15:40:48
  go version:       go1.11.2
* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
Apr 26 16:20:19 linux-infrastructure-prometheus-1.openstacklocal alertad[774]: 2020-04-26 16:20:19,597 alerta.app[1604]: [ERROR] 'NoneType' object has no attribute 'is_blackout' request_id=48304f3f-e84e-453a-8027-a688c084ee32 ip=127.0.0.1
                                                                               TypeError: post_receive() got an unexpected keyword argument 'config'
                                                                               AttributeError: 'NoneType' object has no attribute 'is_blackout'
                                                                                   raise ApiError(str(e), 500)
                                                                               alerta.exceptions.ApiError: 'NoneType' object has no attribute 'is_blackout'
Apr 26 16:20:19 linux-infrastructure-prometheus-1.openstacklocal alertad[774]: OSError: write error
Apr 26 16:20:21 linux-infrastructure-prometheus-1.openstacklocal alertad[774]: --- Logging error ---
Apr 26 16:20:21 linux-infrastructure-prometheus-1.openstacklocal alertad[774]: OSError: [Errno 90] Message too long
Apr 26 16:20:21 linux-infrastructure-prometheus-1.openstacklocal alertad[774]: Unable to print the message and arguments - possible formatting error.
                                                                               Use the traceback above to help find the error.
Apr 26 16:20:22 linux-infrastructure-prometheus-1.openstacklocal alertad[774]: OSError: write error

Redirecting to /bin/systemctl status alertmanager.service
● alertmanager.service - Prometheus Alertmanager
   Loaded: loaded (/etc/systemd/system/alertmanager.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2020-04-26 16:18:26 UTC; 1h 35min ago
 Main PID: 29646 (alertmanager)
   CGroup: /system.slice/alertmanager.service
           └─29646 /opt/prometheus/alertmanager-0.15.3.linux-amd64/alertmanager --storage.path=/app/alertmanager --config.file=/etc/prometheus/alertmanager.yml --web.listen-addres...

Apr 26 17:48:31 linux-infrastructure-prometheus-1.openstacklocal prometheus-alertmanager[29646]: level=error ts=2020-04-26T17:48:31.681331505Z caller=notify.go:332 component...eeded"
Apr 26 17:48:31 linux-infrastructure-prometheus-1.openstacklocal prometheus-alertmanager[29646]: level=error ts=2020-04-26T17:48:31.681418074Z caller=dispatch.go:280 compone...eeded"
Apr 26 17:50:21 linux-infrastructure-prometheus-1.openstacklocal prometheus-alertmanager[29646]: level=error ts=2020-04-26T17:50:21.686186055Z caller=notify.go:332 component...eeded"
Apr 26 17:50:21 linux-infrastructure-prometheus-1.openstacklocal prometheus-alertmanager[29646]: level=error ts=2020-04-26T17:50:21.686311885Z caller=dispatch.go:280 compone...eeded"
Apr 26 17:53:31 linux-infrastructure-prometheus-1.openstacklocal prometheus-alertmanager[29646]: level=error ts=2020-04-26T17:53:31.654879189Z caller=notify.go:332 component...eeded"
Apr 26 17:53:31 linux-infrastructure-prometheus-1.openstacklocal prometheus-alertmanager[29646]: level=error ts=2020-04-26T17:53:31.654982346Z caller=dispatch.go:280 compone...eeded"
Apr 26 17:53:31 linux-infrastructure-prometheus-1.openstacklocal prometheus-alertmanager[29646]: level=error ts=2020-04-26T17:53:31.666836307Z caller=notify.go:332 component...eeded"
Apr 26 17:53:31 linux-infrastructure-prometheus-1.openstacklocal prometheus-alertmanager[29646]: level=error ts=2020-04-26T17:53:31.66690383Z caller=dispatch.go:280 componen...eeded"
Apr 26 17:53:31 linux-infrastructure-prometheus-1.openstacklocal prometheus-alertmanager[29646]: level=error ts=2020-04-26T17:53:31.681698197Z caller=notify.go:332 component...eeded"
Apr 26 17:53:31 linux-infrastructure-prometheus-1.openstacklocal prometheus-alertmanager[29646]: level=error ts=2020-04-26T17:53:31.681766117Z caller=dispatch.go:280 compone...eeded"



nginx     1566   774  0 Apr24 ?        00:18:19 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1567   774  0 Apr24 ?        00:18:08 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1568   774  0 Apr24 ?        00:17:29 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1569   774  0 Apr24 ?        00:18:43 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1570   774  0 Apr24 ?        00:17:49 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1571   774  0 Apr24 ?        00:18:25 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1572   774  0 Apr24 ?        00:17:25 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1573   774  0 Apr24 ?        00:17:54 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1574   774  0 Apr24 ?        00:16:50 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1575   774  0 Apr24 ?        00:16:51 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1576   774  0 Apr24 ?        00:18:43 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1577   774  0 Apr24 ?        00:18:11 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1578   774  0 Apr24 ?        00:16:48 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1579   774  0 Apr24 ?        00:19:28 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1580   774  0 Apr24 ?        00:18:51 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1581   774  0 Apr24 ?        00:20:22 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1582   774  0 Apr24 ?        00:18:28 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1583   774  0 Apr24 ?        00:18:37 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1584   774  0 Apr24 ?        00:19:51 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1585   774  0 Apr24 ?        00:20:20 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1586   774  0 Apr24 ?        00:19:21 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1587   774  0 Apr24 ?        00:20:20 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1589   774  0 Apr24 ?        00:20:31 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1590   774  0 Apr24 ?        00:25:43 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1592   774  0 Apr24 ?        00:22:04 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1593   774  0 Apr24 ?        00:22:46 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1594   774  0 Apr24 ?        00:26:44 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1596   774  0 Apr24 ?        00:28:43 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1598   774  0 Apr24 ?        00:27:26 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1599   774  1 Apr24 ?        00:46:03 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1600   774  1 Apr24 ?        00:33:33 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1601   774  1 Apr24 ?        00:32:54 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1602   774  1 Apr24 ?        00:37:01 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1603   774  1 Apr24 ?        00:42:57 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1604   774  1 Apr24 ?        00:51:14 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1605   774  2 Apr24 ?        01:04:42 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1606   774  2 Apr24 ?        01:17:06 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1607   774  4 Apr24 ?        02:01:23 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1608   774  3 Apr24 ?        01:40:03 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini
nginx     1609   774  4 Apr24 ?        02:04:30 /opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini


nginx     4604  4603  0 Apr24 ?        00:00:03 nginx: worker process
nginx     4605  4603  0 Apr24 ?        00:00:03 nginx: worker process
nginx     4606  4603  0 Apr24 ?        00:00:04 nginx: worker process
nginx     4607  4603  0 Apr24 ?        00:00:05 nginx: worker process
nginx     4608  4603  0 Apr24 ?        00:00:07 nginx: worker process
nginx     4609  4603  0 Apr24 ?        00:00:09 nginx: worker process
nginx     4610  4603  0 Apr24 ?        00:00:12 nginx: worker process
nginx     4611  4603  0 Apr24 ?        00:00:15 nginx: worker process
nginx     4612  4603  0 Apr24 ?        00:00:23 nginx: worker process
nginx     4613  4603  0 Apr24 ?        00:00:34 nginx: worker process
nginx     4614  4603  0 Apr24 ?        00:00:38 nginx: worker process
nginx     4615  4603  0 Apr24 ?        00:00:48 nginx: worker process
nginx     4616  4603  0 Apr24 ?        00:01:04 nginx: worker process
nginx     4617  4603  0 Apr24 ?        00:01:12 nginx: worker process
nginx     4618  4603  0 Apr24 ?        00:01:26 nginx: worker process
nginx     4619  4603  0 Apr24 ?        00:01:45 nginx: worker process



```

**Comment by xkilian** [comment] 2020-05-22 01:39
You might want to look at using inhibitions to reduce the number of alerts firing if the alerts are hierarchical in nature. There are usually few root causes for current running alerts. Critical alerts should really be related to service level(business) events or leading to service level events.

Humor bit: If you really have that many real alerts, you should fire the dev/product teams and start over ;-)

**Comment by roidelapluie** [comment] 2020-06-22 14:56
We have looked into this into our bug scrub and decided to close this issue as it seems to be an Alerta issue instead of a prometheus one. Can you please escalate that to the alerta project?

Thanks.

**Closed by roidelapluie** 2020-06-22 14:56 UTC
Labels: kind/bug
