### ISSUE TITLE
A lot of ".tmp" folders appear in Prometheus storage

### ISSUE THREAD

**Issue by zhanglijingisme** [prometheus/prometheus#5725] opened 2019-07-02 01:54 UTC
## Bug Report
**What did you do?**
Ran Prometheus and keep it running for several days
**What did you expect to see?**
In storage folder, all chunks are well-compacted, disk usage increasing steadily
**What did you see instead? Under which circumstances?**
A lot of ".tmp" folders appear in storage folder, which means compaction failure
`# ls -ltr | tail -15`
`drwxr-xr-x. 3 ddeadmin dde 4096 Apr 16 12:25 01D8JY9NTMZHWVS7JY391T8Y86.tmp`
`drwxr-xr-x. 3 ddeadmin dde 4096 Apr 16 12:26 01D8JYBGGDNBY5B3RWY8KWS7K0.tmp`
`drwxr-xr-x. 3 ddeadmin dde 4096 Apr 16 12:27 01D8JYDB3GP8RM74Q3GGKHYJAK.tmp`
`drwxr-xr-x. 3 ddeadmin dde 4096 Apr 16 12:28 01D8JYF5PMJS0N8VX5ZDF2SAMX.tmp`
`drwxr-xr-x. 3 ddeadmin dde 4096 Apr 16 12:29 01D8JYH09R4PMN2DGA5W2V083X.tmp`
`drwxr-xr-x. 3 ddeadmin dde 4096 Apr 16 12:30 01D8JYJTWWJZJ1K37J3QHP2GTA.tmp`
`drwxr-xr-x. 3 ddeadmin dde 4096 Apr 16 12:31 01D8JYMNHB7EZ187RWWTCMW6CX.tmp`
`drwxr-xr-x. 3 ddeadmin dde 4096 Apr 16 12:32 01D8JYPG4KZ8DW1QA83X1ZF4T3.tmp`
**Environment**
Non-container environment
* System information:
Linux 3.10.0-862.14.4.el7.x86_64 x86_64
* Prometheus version:
v2.3.1
* Alertmanager version:
N/A
* Prometheus configuration file:
N/A
* Alertmanager configuration file:
N/A
* Logs:
N/A

**Comment by zhanglijingisme** [comment] 2019-07-02 01:59
I've noticed similar issues has been reported like
- https://github.com/prometheus/prometheus/issues/5683
- https://github.com/prometheus/prometheus/issues/4108
- https://github.com/prometheus/prometheus/issues/3190

Those .tmp folders will soon eat up disk space. I checked some web pages and know these folders are there because of Prometheus compaction failure.

Could you please let me know,
- Is this a known issue of Prometheus? If so, is there already a fix in latest Prometheus versions, or is there a plan to fix this?
- If there is no fix currently, how can we avoid such case? 

I've searched some ways, but don't know what the silver bullet is.
- Avoid Prometheus from being killed during a compaction
- Increase memory / storage disk space
- Give short compaction intervals like "storage.tsdb.min-block-duration=30m" and "storage.tsdb.max-block-duration=1d"

Thanks in advance for your kindly suggestions.

**Comment by codesome** [comment] 2019-07-02 06:21
@zhanglijingisme I would suggest having at least 2x the disk space of what Prometheus is using while compaction is not happening. Also, the .tmp directories should have been removed if the Prometheus was still running after the compaction failure, was it killed instead?

I am closing this as this is a dupe of #5683, can you post your logs in #5683 when the compaction faliure happened?

**Closed by codesome** 2019-07-02 06:21 UTC

**Comment by zhanglijingisme** [comment] 2019-07-02 06:46
> @zhanglijingisme I would suggest having at least 2x the disk space of what Prometheus is using while compaction is not happening. Also, the .tmp directories should have been removed if the Prometheus was still running after the compaction failure, was it killed instead?
> 
> I am closing this as this is a dupe of #5683, can you post your logs in #5683 when the compaction faliure happened?

Unfortunately .tmp is not removed and it's filling whole storage folder. There are hundreds of ".tmp" folders in storage folder and keep generating per minute. Prometheus is not killed - though I think it's not working well.

So can I get this conclusion - that currently no code fix has been done to avoid such case?

**Comment by codesome** [comment] 2019-07-02 06:53
I am not sure what is causing it, because on compaction error we delete the `.tmp` directories. Can you share the logs?

**Comment by zhanglijingisme** [comment] 2019-07-02 06:57
@codesome Unfortunately I cannot provide log at this time. It used to happen on our labs for several times, but not now. We are searching a way to solve (at least, avoid) this annoying issue.

1) Will compaction failure in v2.3.1 delete ".tmp" folders?
2) Do you have any suggestion about how to avoid this? Following is my conclusion,
- Avoid Prometheus from being killed during a compaction
- Increase memory / storage disk space
- Give short compaction intervals like "storage.tsdb.min-block-duration=30m" and "storage.tsdb.max-block-duration=1d"

**Comment by codesome** [comment] 2019-07-02 07:04
`2.3.1` is very old, I would suggest you to upgrade to the latest version as there have been changes/improvements in compactions. And without the logs, I can only suggest having more disk space and avoid getting Prometheus killed during compaction (if it does get killed, it is safe to delete the `.tmp` directories and restart Prometheus).
