### ISSUE TITLE
hope to support environment variable for prometheus config

### ISSUE THREAD

**Issue by mojo-zd** [prometheus/prometheus#6376] opened 2019-11-26 06:34 UTC
## Proposal
*i'd like to use environment fill prometheus config, but current not support.*
*Use Case*
use `pod-name` to fill the external_label

**Comment by brian-brazil** [comment] 2019-11-26 06:36
Dupe of #2357.

**Closed by brian-brazil** 2019-11-26 06:36 UTC

**Comment by roidelapluie** [comment] 2021-03-31 08:17
@mojo-zd   Starting Prometheus 2.27, we will be able to substitute env variables in external labels if you use `--enable-feature=expand-external-labels`

This can be tested  with the `main` docker image.
