### ISSUE TITLE
Use `module github.com/prometheus/prometheus/v2` in go.mod

### ISSUE THREAD

**Issue by bogdandrutu** [prometheus/prometheus#7663] opened 2020-07-24 16:58 UTC
In order to follow golang conventions for versions you need to update the module in go.mod to be `v2`.

Try:
```
go get github.com/prometheus/prometheus@v2.19.3

go: finding github.com/prometheus/prometheus v2.19.3
go: finding github.com/prometheus/prometheus v2.19.3
go get github.com/prometheus/prometheus@v2.19.3: github.com/prometheus/prometheus@v2.19.3: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

**Comment by roidelapluie** [comment] 2020-07-24 18:24
Prometheus is NOT following golang convention.

Adding v2 would mistake people into believing that we follow Go conventions. This is not the case.

You can go get specific commit id's or tag ids:

git rev-list -n 1 v2.19.3
657ba532e42f1db8d7c77bf802378643da0d3118

go get github.com/prometheus/prometheus@657ba532e42f1db8d7c77bf802378643da0d3118

**Comment by roidelapluie** [comment] 2020-07-24 18:28
Duplicate of #6048

**Closed** 2020-07-24 18:28 UTC
Labels: kind/question

**Comment by Benjamintf1** [comment] 2020-08-19 20:04
@roidelapluie `mistake people into believing that we follow Go conventions` If you are using go mod, you should be following go conventions. This makes it impossible for anyone else to use go mod to pull in prometheus. We followed the workaround, and it just does not work.

**Comment by roidelapluie** [comment] 2020-08-19 20:10
Hi Benjamin,

We are happy to help you on the prometheus-developers mailing list about this matter, if you can provide us with more details there about what does not work.

**Comment by Benjamintf1** [comment] 2020-08-19 20:15
Use go (I believe) 1.14.x. Try and import promethues. See that it gives the following error `github.com/prometheus/prometheus@v2.19.3: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2`, even when imported using the former method.

**Comment by roidelapluie** [comment] 2020-08-19 20:18
Yes, you need to

`go get github.com/prometheus/prometheus@657ba532e42f1db8d7c77bf802378643da0d3118`

**Comment by Benjamintf1** [comment] 2020-08-19 20:21
yeah, that doesn't work

**Comment by roidelapluie** [comment] 2020-08-19 20:27
I am on go 1.15. It works for me:

```
~/testgoprom $ go mod init github.com/roidelapluie/testgoprom
go: creating new go.mod: module github.com/roidelapluie/testgoprom
~/testgoprom $ go get github.com/prometheus/prometheus@657ba532e42f1db8d7c77bf802378643da0d3118
go: downloading github.com/prometheus/prometheus v1.8.2-0.20200724121523-657ba532e42f
go: github.com/prometheus/prometheus 657ba532e42f1db8d7c77bf802378643da0d3118 => v1.8.2-0.20200724121523-657ba532e42f
~/testgoprom $ go version
go version go1.15 linux/amd64
```

**Comment by roidelapluie** [comment] 2020-08-19 20:28
Note that you can ignore the v1.8.2, that does not reflect the reality.

**Comment by Benjamintf1** [comment] 2020-08-19 20:43
Hmm, I'm majorly confused. I was in a state where I was getting the error, now I'm suddenly not? I still have some major concerns about the workaround required to be functional with go mod(especially as it's been the very strong stance of go mod that users of go mod should use major versioning in their modules, and as they've reduced workarounds to do so, like removing +incompatible to do so. https://blog.golang.org/v2-go-modules. We'll keep investigating.

**Comment by Benjamintf1** [comment] 2020-08-19 20:48
go mod can be a frustrating mystery sometimes :/
