### ISSUE TITLE
remote writer configuration: drop metrics whose timestamp is out of acceptance range

### ISSUE THREAD

**Issue by Anhui-tqhuang** [prometheus/prometheus#7938] opened 2020-09-14 05:44 UTC
## Proposal
**Use case. Why is this important?**

I configure remote writer to send metrics to sysdig, some metrics will be rejected by sysdig if the timestamp of the metrics is out of acceptance range like 10 minutes, we shouldn't retry to submit them and drop them.

So i want a option in remote-writer configurations like `acceptance time window`, if a metric's timestamp reaches the `acceptance time window`, we drop it and never retry to submit it.

*“Nice to have” is not a good use case. :)*

**Comment by roidelapluie** [comment] 2020-09-14 07:13
Thanks! This is a duplicate of #7912 .

cc @csmarchbanks for awareness.

**Closed by roidelapluie** 2020-09-14 07:13 UTC

**Comment by Anhui-tqhuang** [comment] 2020-09-14 08:09
@roidelapluie thx!
