### ISSUE TITLE
Kubernetes service discovery: too old resource version

### ISSUE THREAD

**Issue by caarlos0** [prometheus/prometheus#5853] opened 2019-08-10 19:57 UTC
## Bug Report

**What did you do?**

I'm not sure this is a problem, but I see a lot of the warnings bellow on prometheus logs.
Prometheus was deployed with prometheus operator and its default configs.

**What did you expect to see?**
Hopefully no warnings, maybe the reason why this happens?

**What did you see instead? Under which circumstances?**

```
level=warn ts=2019-08-10T19:26:04.441Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:265: watch of *v1.Pod ended with: too old resource version: 1105886308 (1105894298)"
level=warn ts=2019-08-10T19:27:15.066Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:265: watch of *v1.Pod ended with: too old resource version: 1105886218 (1105895173)"
level=warn ts=2019-08-10T19:34:07.078Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:265: watch of *v1.Pod ended with: too old resource version: 1105902608 (1105904325)"
level=warn ts=2019-08-10T19:34:31.767Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 1105889741 (1105892423)"
level=warn ts=2019-08-10T19:34:46.349Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 1105887774 (1105892656)"
level=warn ts=2019-08-10T19:34:48.120Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:265: watch of *v1.Pod ended with: too old resource version: 1105901051 (1105907855)"
level=warn ts=2019-08-10T19:35:21.231Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:265: watch of *v1.Pod ended with: too old resource version: 1105897621 (1105909037)"
level=warn ts=2019-08-10T19:36:18.508Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 1105889478 (1105894322)"
level=warn ts=2019-08-10T19:38:10.522Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:265: watch of *v1.Pod ended with: too old resource version: 1105901381 (1105913174)"
level=warn ts=2019-08-10T19:39:19.152Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 1105894237 (1105897870)"
level=warn ts=2019-08-10T19:42:42.090Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:265: watch of *v1.Pod ended with: too old resource version: 1105910336 (1105915092)"
level=warn ts=2019-08-10T19:44:29.154Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:265: watch of *v1.Pod ended with: too old resource version: 1105911449 (1105915389)"
level=warn ts=2019-08-10T19:44:54.266Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:265: watch of *v1.Pod ended with: too old resource version: 1105912381 (1105915469)"
level=warn ts=2019-08-10T19:52:10.604Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:265: watch of *v1.Pod ended with: too old resource version: 1105916616 (1105921924)"
```

**Environment**

- Kubernetes: v1.9.8
- Prometheus 2.11.1
- Prometheus Operator 0.31.1

**Comment by brancz** [comment] 2019-08-12 08:50
My understanding is that this is not a problem. What's happening here is that a watch against the Kubernetes API is timing out, and it is being restarted, which is intended behavior. Watches by default timeout after 15min I believe.

**Comment by simonpasquier** [comment] 2019-08-20 13:28
If anything, it looks like the problem is with `k8s.io/client-go`. I'm closing it for now.

**Closed by simonpasquier** 2019-08-20 13:28 UTC
