### ISSUE TITLE
Feat: recording rules linked to targets

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#3908] opened 2018-03-04 07:00 UTC
Hi,

I would like to see the ability to add recording rules to jobs. Those recording rules would be run after each target of the job is scraped and would only be run on the metrics related to that target.

# Use Case

We poll network switches every 5 minutes. It would be handy to be able to run irate() on each of the switches interfaces throughput.

# Why not plain recording rules?

Plain recording rules would be run anywhere between scrapes and for all switches, thus taking a lot of time and getting "incorrect" timestamps.

# Implications

It is not clear if we can easily know which metrics come from a specific target at the moment.

**Comment by brian-brazil** [comment] 2018-03-04 08:55
Dupe of #394

**Closed by brian-brazil** 2018-03-04 08:55 UTC
