### ISSUE TITLE
Corruption in head chunk file on OpenBSD

### ISSUE THREAD

**Issue by huhndev** [prometheus/prometheus#12963] opened 2023-10-11 08:26 UTC
### What did you do?

Run Prometheus on OpenBSD via [rcctl(8)](https://man.openbsd.org/rcctl.8).

### What did you expect to see?

I expect Prometheus not to panic and to crash.

### What did you see instead? Under which circumstances?

Prometheus panics without any interaction after some hours.

### System information

OpenBSD 7.3 -release

### Prometheus version

```text
prometheus-2.37.6

prometheus, version  (branch: , revision: )
  build user:       
  build date:       
  go version:       go1.20.1
  platform:         openbsd/amd64
```

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "openbsd"
    file_sd_configs:
    - files:
      - "/etc/prometheus/targets-openbsd.json" 

  - job_name: "shelly"
    scrape_interval: 5m
    metrics_path: /probe
    file_sd_configs:
    - files:
      - "/etc/prometheus/targets-shelly.json"
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: localhost:9101

  - job_name: "synapse"
    scrape_interval: 30s
    metrics_path: "/_synapse/metrics"
    static_configs:
      - targets: ["$SYNAPSE_URL:9000"]

  - job_name: "restic"
    scheme: https
    scrape_interval: 5m
    metrics_path: "/metrics"
    static_configs:
      - targets: ["$RESTIC_URL:8000"]
```

### Alertmanager version

```text
Alertmanager not used.
```

### Alertmanager configuration file

```yaml
Alertmanager not used.
```

### Logs

```text
Oct 10 23:00:00 monitoring01 prometheus[45642]: panic: corruption in head chunk file /var/prometheus/chunks_head/000001: checksum mismatch expected:00000000, actual:d096d996
Oct 10 23:00:00 monitoring01 prometheus[45642]: 
Oct 10 23:00:00 monitoring01 prometheus[45642]: goroutine 389 [running]:
Oct 10 23:00:00 monitoring01 prometheus[45642]: github.com/prometheus/prometheus/tsdb.(*memSeries).chunk(0xc001000380, 0x0?, 0xc00283b238?)
Oct 10 23:00:00 monitoring01 prometheus[45642]:         /usr/obj/ports/prometheus-2.37.6/go/src/github.com/prometheus/prometheus/tsdb/head_read.go:322 +0x1f4
Oct 10 23:00:00 monitoring01 prometheus[45642]: github.com/prometheus/prometheus/tsdb.(*headChunkReader).Chunk(0xc00213dda0, 0x81c000003)
Oct 10 23:00:00 monitoring01 prometheus[45642]:         /usr/obj/ports/prometheus-2.37.6/go/src/github.com/prometheus/prometheus/tsdb/head_read.go:272 +0xb7
Oct 10 23:00:00 monitoring01 prometheus[45642]: github.com/prometheus/prometheus/tsdb.(*populateWithDelGenericSeriesIterator).next(0xc002b49860)
Oct 10 23:00:00 monitoring01 prometheus[45642]:         /usr/obj/ports/prometheus-2.37.6/go/src/github.com/prometheus/prometheus/tsdb/querier.go:572 +0xc2
Oct 10 23:00:00 monitoring01 prometheus[45642]: github.com/prometheus/prometheus/tsdb.(*populateWithDelChunkSeriesIterator).Next(0xc0019cf920)
Oct 10 23:00:00 monitoring01 prometheus[45642]:         /usr/obj/ports/prometheus-2.37.6/go/src/github.com/prometheus/prometheus/tsdb/querier.go:670 +0x28
Oct 10 23:00:00 monitoring01 prometheus[45642]: github.com/prometheus/prometheus/tsdb.(*LeveledCompactor).populateBlock(0xc000480960, {0xc00283bb38, 0x1, 0x41?}, 0xc001c717a0, {0x3a1f150, 0xc002b9cb00}, {0x3a17ad8, 0xc0034aa840})
Oct 10 23:00:00 monitoring01 prometheus[45642]:         /usr/obj/ports/prometheus-2.37.6/go/src/github.com/prometheus/prometheus/tsdb/compact.go:770 +0x1422
Oct 10 23:00:00 monitoring01 prometheus[45642]: github.com/prometheus/prometheus/tsdb.(*LeveledCompactor).write(0xc000480960, {0x72151e3d7313, 0xf}, 0xc001c717a0, {0xc00283bb38, 0x1, 0x1})
Oct 10 23:00:00 monitoring01 prometheus[45642]:         /usr/obj/ports/prometheus-2.37.6/go/src/github.com/prometheus/prometheus/tsdb/compact.go:597 +0x64c
Oct 10 23:00:00 monitoring01 prometheus[45642]: github.com/prometheus/prometheus/tsdb.(*LeveledCompactor).Write(0xc000480960, {0x72151e3d7313, 0xf}, {0x3a2f680, 0xc00213dd20}, 0x18b1abee5cd, 0x18b1b2cc200, 0x0)
Oct 10 23:00:00 monitoring01 prometheus[45642]:         /usr/obj/ports/prometheus-2.37.6/go/src/github.com/prometheus/prometheus/tsdb/compact.go:504 +0x213
Oct 10 23:00:00 monitoring01 prometheus[45642]: github.com/prometheus/prometheus/tsdb.(*DB).compactHead(0xc00041da00, 0xc00213dd20)
Oct 10 23:00:00 monitoring01 prometheus[45642]:         /usr/obj/ports/prometheus-2.37.6/go/src/github.com/prometheus/prometheus/tsdb/db.go:978 +0x6c
Oct 10 23:00:00 monitoring01 prometheus[45642]: github.com/prometheus/prometheus/tsdb.(*DB).Compact(0xc00041da00)
Oct 10 23:00:00 monitoring01 prometheus[45642]:         /usr/obj/ports/prometheus-2.37.6/go/src/github.com/prometheus/prometheus/tsdb/db.go:936 +0x2df
Oct 10 23:00:00 monitoring01 prometheus[45642]: github.com/prometheus/prometheus/tsdb.(*DB).run(0xc00041da00)
Oct 10 23:00:00 monitoring01 prometheus[45642]:         /usr/obj/ports/prometheus-2.37.6/go/src/github.com/prometheus/prometheus/tsdb/db.go:828 +0x3e6
Oct 10 23:00:00 monitoring01 prometheus[45642]: created by github.com/prometheus/prometheus/tsdb.open
Oct 10 23:00:00 monitoring01 prometheus[45642]:         /usr/obj/ports/prometheus-2.37.6/go/src/github.com/prometheus/prometheus/tsdb/db.go:758 +0xdf1
[...]
Oct 11 05:00:00 monitoring01 prometheus[30362]: panic: corruption in head chunk file /var/prometheus/chunks_head/000006: checksum mismatch expected:00000000, actual:d096d996
Oct 11 05:00:00 monitoring01 prometheus[30362]: 
Oct 11 05:00:00 monitoring01 prometheus[30362]: goroutine 395 [running]:
Oct 11 05:00:00 monitoring01 prometheus[30362]: github.com/prometheus/prometheus/tsdb.(*memSeries).chunk(0xc0010d2460, 0x0?, 0xc00099f238?)
Oct 11 05:00:00 monitoring01 prometheus[30362]:         /usr/obj/ports/prometheus-2.37.6/go/src/github.com/prometheus/prometheus/tsdb/head_read.go:322 +0x1f4
Oct 11 05:00:00 monitoring01 prometheus[30362]: github.com/prometheus/prometheus/tsdb.(*headChunkReader).Chunk(0xc001cdf060, 0x40900000d)
Oct 11 05:00:00 monitoring01 prometheus[30362]:         /usr/obj/ports/prometheus-2.37.6/go/src/github.com/prometheus/prometheus/tsdb/head_read.go:272 +0xb7
Oct 11 05:00:00 monitoring01 prometheus[30362]: github.com/prometheus/prometheus/tsdb.(*populateWithDelGenericSeriesIterator).next(0xc000f3b180)
Oct 11 05:00:00 monitoring01 prometheus[30362]:         /usr/obj/ports/prometheus-2.37.6/go/src/github.com/prometheus/prometheus/tsdb/querier.go:572 +0xc2
Oct 11 05:00:00 monitoring01 prometheus[30362]: github.com/prometheus/prometheus/tsdb.(*populateWithDelChunkSeriesIterator).Next(0xc003166ed0)
Oct 11 05:00:00 monitoring01 prometheus[30362]:         /usr/obj/ports/prometheus-2.37.6/go/src/github.com/prometheus/prometheus/tsdb/querier.go:670 +0x28
Oct 11 05:00:00 monitoring01 prometheus[30362]: github.com/prometheus/prometheus/tsdb.(*LeveledCompactor).populateBlock(0xc000492ae0, {0xc00099fb38, 0x1, 0x41?}, 0xc004967ef0, {0x3a1f150, 0xc001bb2c60}, {0x3a17ad8, 0xc002d9db40})
Oct 11 05:00:00 monitoring01 prometheus[30362]:         /usr/obj/ports/prometheus-2.37.6/go/src/github.com/prometheus/prometheus/tsdb/compact.go:770 +0x1422
Oct 11 05:00:00 monitoring01 prometheus[30362]: github.com/prometheus/prometheus/tsdb.(*LeveledCompactor).write(0xc000492ae0, {0x7310867f77f3, 0xf}, 0xc004967ef0, {0xc00099fb38, 0x1, 0x1})
Oct 11 05:00:00 monitoring01 prometheus[30362]:         /usr/obj/ports/prometheus-2.37.6/go/src/github.com/prometheus/prometheus/tsdb/compact.go:597 +0x64c
Oct 11 05:00:00 monitoring01 prometheus[30362]: github.com/prometheus/prometheus/tsdb.(*LeveledCompactor).Write(0xc000492ae0, {0x7310867f77f3, 0xf}, {0x3a2f680, 0xc001cdefe0}, 0x18b1c087cce, 0x18b1c765900, 0x0)
Oct 11 05:00:00 monitoring01 prometheus[30362]:         /usr/obj/ports/prometheus-2.37.6/go/src/github.com/prometheus/prometheus/tsdb/compact.go:504 +0x213
Oct 11 05:00:00 monitoring01 prometheus[30362]: github.com/prometheus/prometheus/tsdb.(*DB).compactHead(0xc0004f0340, 0xc001cdefe0)
Oct 11 05:00:00 monitoring01 prometheus[30362]:         /usr/obj/ports/prometheus-2.37.6/go/src/github.com/prometheus/prometheus/tsdb/db.go:978 +0x6c
Oct 11 05:00:00 monitoring01 prometheus[30362]: github.com/prometheus/prometheus/tsdb.(*DB).Compact(0xc0004f0340)
Oct 11 05:00:00 monitoring01 prometheus[30362]:         /usr/obj/ports/prometheus-2.37.6/go/src/github.com/prometheus/prometheus/tsdb/db.go:936 +0x2df
Oct 11 05:00:00 monitoring01 prometheus[30362]: github.com/prometheus/prometheus/tsdb.(*DB).run(0xc0004f0340)
Oct 11 05:00:00 monitoring01 prometheus[30362]:         /usr/obj/ports/prometheus-2.37.6/go/src/github.com/prometheus/prometheus/tsdb/db.go:828 +0x3e6
Oct 11 05:00:00 monitoring01 prometheus[30362]: created by github.com/prometheus/prometheus/tsdb.open
Oct 11 05:00:00 monitoring01 prometheus[30362]:         /usr/obj/ports/prometheus-2.37.6/go/src/github.com/prometheus/prometheus/tsdb/db.go:758 +0xdf1
```
```

**Comment by roidelapluie** [comment] 2023-10-14 09:40
Unfortunately we do not support OpenBSD at the moment due to the behaviour of mmap. Please see #8799 indeed. Per such, I will close this ticket as duplicate of that one .

**Closed by roidelapluie** 2023-10-14 09:40 UTC
