### ISSUE TITLE
HTTP 307 from alertmanager is not respected

### ISSUE THREAD

**Issue by lae** [prometheus/prometheus#1368] opened 2016-02-04 01:09 UTC
This occurs with alertmanager 1.0.0.beta1 and 2, and with alertmanager.url set to a url with a trailing slash (e.g. `/usr/bin/prometheus -alertmanager.url=http://localhost:9093/`) in Prometheus:

```
T 127.0.0.1:34951 -> 127.0.1.1:9093 [AP]
POST //api/v1/alerts HTTP/1.1.
Host: <host>:9093.
.
<payload>

T 127.0.1.1:9093 -> 127.0.0.1:34951 [AP]
HTTP/1.1 307 Temporary Redirect.
Location: /api/v1/alerts.
Date: Thu, 04 Feb 2016 01:03:39 GMT.
```

Prometheus doesn't attempt to POST the data again, so Alertmanager never sees the alerts. Prometheus should respect that response code and POST the data again (for this particular problem stripping out trailing slashes from alertmanager.url would be fine, but that's ugly).

**Comment by brian-brazil** [comment] 2016-02-04 07:52
Dupe of #668

**Closed by brian-brazil** 2016-02-04 07:52 UTC
Labels: bug

**Comment by fabxc** [comment] 2016-02-04 10:57
That said, this particular case can be fixed by sanitizing the appending of the API endpoint #1370.
