### ISSUE TITLE
Prometheus crash when boot with a empty checkpoint dir

### ISSUE THREAD

**Issue by AllenzhLi** [prometheus/prometheus#8035] opened 2020-10-09 11:34 UTC
**What did you do?**
bootstrap cortex 1.4

**What did you expect to see?**
running

**What did you see instead? Under which circumstances?**
```
level=info ts=2020-10-09T11:20:56.594262Z caller=wal.go:570 msg="recovering from /tmp/cortex/wal/checkpoint.000003"
panic: runtime error: index out of range [0] with length 0

goroutine 498 [running]:
github.com/prometheus/prometheus/tsdb/wal.NewSegmentBufReader(0x0, 0x0, 0x0, 0x0)
        /Users/allenzhli/Workspace/infrastore-metric/vendor/github.com/prometheus/prometheus/tsdb/wal/wal.go:845 +0x13f
github.com/prometheus/prometheus/tsdb/wal.NewSegmentsRangeReader(0xc000ee5768, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        /Users/allenzhli/Workspace/infrastore-metric/vendor/github.com/prometheus/prometheus/tsdb/wal/wal.go:827 +0x4e8
github.com/prometheus/prometheus/tsdb/wal.NewSegmentsReader(0xc000d6c180, 0x21, 0x0, 0x0, 0x0, 0x0)
        /Users/allenzhli/Workspace/infrastore-metric/vendor/github.com/prometheus/prometheus/tsdb/wal/wal.go:799 +0xfa
github.com/cortexproject/cortex/pkg/ingester.newWalReader(0xc000d6c180, 0x21, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/allenzhli/Workspace/infrastore-metric/pkg/ingester/wal.go:1002 +0xa8
github.com/cortexproject/cortex/pkg/ingester.processCheckpoint(0xc000d6c180, 0x21, 0xc00015c600, 0xc000528b90, 0xf, 0xc000ae8000, 0xc, 0xc0009d2300, 0xc, 0xc, ...)
        /Users/allenzhli/Workspace/infrastore-metric/pkg/ingester/wal.go:633 +0x86
github.com/cortexproject/cortex/pkg/ingester.processCheckpointWithRepair(0xc000528b90, 0xf, 0xc000ae8000, 0xc, 0xc0009d2300, 0xc, 0xc, 0xc0009d2360, 0xc, 0xc, ...)
        /Users/allenzhli/Workspace/infrastore-metric/pkg/ingester/wal.go:572 +0x618
github.com/cortexproject/cortex/pkg/ingester.recoverFromWAL(0xc000ae8000, 0x0, 0x0)
        /Users/allenzhli/Workspace/infrastore-metric/pkg/ingester/wal.go:525 +0x3f8
github.com/cortexproject/cortex/pkg/ingester.(*Ingester).starting(0xc000ae8000, 0x3f57120, 0xc0002dc600, 0x0, 0x0)
        /Users/allenzhli/Workspace/infrastore-metric/pkg/ingester/ingester.go:231 +0x1a9
github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main(0xc000872b40)
        /Users/allenzhli/Workspace/infrastore-metric/pkg/util/services/basic_service.go:134 +0xc2
created by github.com/cortexproject/cortex/pkg/util/services.(*BasicService).StartAsync.func1
        /Users/allenzhli/Workspace/infrastore-metric/pkg/util/services/basic_service.go:96 +0x118
Exiting.
```

**Environment**

	cortex 1.4

* System information:

	Darwin 19.6.0 x86_64

* Prometheus version:

	prometheus 2.20

**Comment by roidelapluie** [comment] 2020-10-09 11:41
This should no longer happen with Prometheus 2.22. You will need to remove that empty dir manually.

Duplicate of https://github.com/prometheus/prometheus/issues/6976

**Closed by roidelapluie** 2020-10-09 11:41 UTC
