### ISSUE TITLE
remote_write: Headers are not sent

### ISSUE THREAD

**Issue by zalintyre** [prometheus/prometheus#13030] opened 2023-10-24 22:26 UTC
### What did you do?

I started prometheus with --enable-feature=agent. I configured custom headers with the remote_write configuration, but they are not sent with the request.

### What did you expect to see?

The custom headers being sent.

### What did you see instead? Under which circumstances?

```
POST / HTTP/1.1
Host: localhost:8888
User-Agent: Prometheus/2.42.0+ds
Content-Length: 4889
Authorization: Basic XXXXXXXXXXXXXXXXXXXXXXXXXXX
Content-Encoding: snappy
Content-Type: application/x-protobuf
X-Prometheus-Remote-Write-Version: 0.1.0
```

### System information

Linux 6.1.0-rpi4-rpi-v6 armv6l

### Prometheus version

```text
prometheus/stable,now 2.42.0+ds-5 armhf
```

### Prometheus configuration file

```yaml
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    instance: 'hallway'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    static_configs:
      - targets: ['localhost:9100']

remote_write:
  - url: http://localhost:8888
    basic_auth:
      username: "XXXX"
      password: "XXXX"
    headers:
      "X-Scope-OrgID": "1"
      "A": "B"
```
```


### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

_No response_

**Comment by machine424** [comment] 2023-11-09 15:02
It doesn't seem to be an issue with prometheus, I added a test for that https://github.com/prometheus/prometheus/pull/13117 (ran successfully on `2.42.0` as well), if you think the test doesn't reflect your config, please let me know.

If not, maybe you have a proxy in between that rewrite/alter the headers. You can also make sure that the config you shared is really taken into account by prometheus.

**Comment by zalintyre** [comment] 2023-11-11 23:03
I have now solved the issue by not installing Prometheus from the Raspbian package manager apt, but the binary from GitHub. Could this be some sort of back-port where the version did not contain the announced feature?

**Comment by machine424** [comment] 2023-11-13 12:04
Yep, maybe there is a problem with versions, I don't know who manages those packages...

> Could this be some sort of back-port where the version did not contain the announced feature?

I expect prometheus to fail (re)loading the config if it contains something it doesn't know about.

**Comment by jkroepke** [comment] 2023-11-17 14:21
@machine424 I from what I know, I'm not able to define/overwrite the Host header.

In my case, i have the URL `https://20.0.0.1/api/v1/write`, but I have to sent the request to an specific Virtual Host. With `tls_config.server_name` I'm able to define the TLS SNI value, but Host header seems ignore. See #13157

**Comment by philcerf** [comment] 2023-11-18 02:10
I have the same problem (though I don't use `--enable-feature=agent`) with version 2.42.0, using the Debian package.

Listening with `nc`, there are none of my custom headers set.

**Comment by kot0dama** [comment] 2024-03-13 14:09
I can confirm this issue with both Debian stable and testing/unstable versions:

```
$ prometheus --version                                                                                                                                                           
prometheus, version 2.42.0+ds (branch: debian/sid, revision: 2.42.0+ds-5+b5)                                                                                                                 
  build user:       team+pkg-go@tracker.debian.org                                                                                                                                           
  build date:       20230518-08:49:35                                                                                                                                                        
  go version:       go1.19.8                                                                                                                                                                 
  platform:         linux/amd64     

$ prometheus --version
prometheus, version 2.45.3+ds (branch: debian/sid, revision: 2.45.3+ds-1)
  build user:       team+pkg-go@tracker.debian.org
  build date:       20240205-11:58:47
  go version:       go1.21.6
  platform:         linux/amd64
  tags:             unknown
```

Headers are not set, resulting in "no org id" error in Grafana Mimir with multi-tenancy enabled (the default).

**Comment by kot0dama** [comment] 2024-03-13 14:14
I can confirm this issue with both Debian stable and testing/unstable versions.
I am also not using `--enable-feature=agent` option.

```
$ prometheus --version                                                                                                                                                           
prometheus, version 2.42.0+ds (branch: debian/sid, revision: 2.42.0+ds-5+b5)                                                                                                                 
  build user:       team+pkg-go@tracker.debian.org                                                                                                                                           
  build date:       20230518-08:49:35                                                                                                                                                        
  go version:       go1.19.8                                                                                                                                                                 
  platform:         linux/amd64     

$ prometheus --version
prometheus, version 2.45.3+ds (branch: debian/sid, revision: 2.45.3+ds-1)
  build user:       team+pkg-go@tracker.debian.org
  build date:       20240205-11:58:47
  go version:       go1.21.6
  platform:         linux/amd64
  tags:             unknown
```

Headers are not set, resulting in "no org id" error in Grafana Mimir with multi-tenancy enabled (the default).
Thanks

**Comment by vladimir259** [comment] 2024-06-13 12:24
I can also confirm this with the current prometheus version 2.42.0+ds-5+b5 in debian 12.5.

I do NOT have prometheus running as agent, but simply added the "remote_write" and writing the data additionaly to a remote location.

The metrics are transmitted corrently, but the headers - and the "X-Scope-OrgID" among them - is ignored.
As a result, on the "remote" side where i do have a Multi-tenant Mimir-setup, the data lands in the "anonymous" tenant :-\

**Comment by vladimir259** [comment] 2024-06-13 12:49
had to replace the debian binaries(prometheus, promtool) by the latest 2.52.0 binary from https://prometheus.io/download/  to solve the issue :-\

**Comment by NightTsarina** [comment] 2024-09-16 15:48
@roidelapluie Thanks for the heads-up! I am surprised at this issue, I cannot imagine what could cause this behaviour, but I will investigate it.

**Comment by KarstenSiemer** [comment] 2024-11-21 15:19
For anyone tumbling over this:
1. Currently, as of prometheus version 2.54.1, there is no way to remote write to an IP and set the host header
2. There was a PR made for this, but it had a mistake and it was reverted
3. There is another PR made for this, but not yet merged. Dangling since July

To still get around this, I cheated using the service from nip.io.
E.g. DNS querying prometheus.X.X.X.X.nip.io will return the record of X.X.X.X
so querying prometheus.20.0.0.1.nip.ip will return 20.0.0.1.

But then you still need that vhost in your target ingress. But thats easier than having no host header or just the IP as the host

**Comment by bwplotka** [comment] 2024-11-25 09:56
Thanks for reporting! 

I just checked latest 3.0 and 2.55.x versions and I cannot reproduce this:

1) programmatically (e.g. there is a [unit test](https://github.com/prometheus/prometheus/blob/main/storage/remote/client_test.go#L178)).
2) e2e with the following config: https://github.com/bwplotka/sink/blob/repro/test/prom_test.go#L188

I also don't see how agent mode impacts with Remote Write client here, those are the same.

Note that particularly ["host" header is not allowed](https://github.com/prometheus/prometheus/blob/main/config/config.go#L45) and should fail configuration parsing with a clear message.

It feels either past versions might have been broken or you run through some proxy environment that strips some headers. If you want to remove `host` from NOT allowed list, let us know in a separate dedicated issue/PR. 

I will close this issue, we can reopen if you can still reproduce this problem on the latest Prometheus WITHOUT extra proxies (e.g. ideally there is a simple reproduction setup we could run).

**Closed by bwplotka** 2024-11-25 09:56 UTC
