### ISSUE TITLE
How to enable HTTP/2 to scrape metrics from the target(s)

### ISSUE THREAD

**Issue by yucelalbar** [prometheus/prometheus#6893] opened 2020-02-28 06:34 UTC
**What did you do?**
Executed Prometheus to scrape metrics from my application over HTTP/2

**What did you expect to see?**

**What did you see instead? Under which circumstances?**
HTTP query that's version is HTTP/1.1 from Prometheus

**Environment**
Ubuntu 16.04.6 LTS

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	2.16.0

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: My Service
    scrape_interval: 10s
    #scheme: https
    static_configs:
      - targets: ['localhost:7002']

* Alertmanager configuration file:
* Logs:

**Comment by roidelapluie** [comment] 2020-02-28 06:52
Duplicate of #5938 .

Thanks for your report. Prometheus is using the standard golang http client which enables http2 only over https.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Closed by roidelapluie** 2020-02-28 06:52 UTC
Labels: kind/bug
