### ISSUE TITLE
[Feature request] zero_increase to easily compute increase in new counters

### ISSUE THREAD

**Issue by fungiboletus** [prometheus/prometheus#7249] opened 2020-05-12 09:10 UTC
## Proposal

`increase` does report 0 for counters that are created during the time window, whatever their first value is. It's how it's designed and it's not a bug. However, it would be nice to have an alternative to `increase`, like `zero_increase`, that uses zero when the counter doesn't exist yet, so you could compute an increase from zero when a new counter is created.

An example is a metric with an error code as a label. For a given error code, it doesn't exist until the first error occurs. *Unless you initialize all your metrics with all possible labels of course.*

`increase` will return 0 even if the first value of the counter is higher than zero. If errors with the same label do not occur again in following time windows, you could notice that a new error code label is there, but the line chart would only show zero errors for it. If you want to see a spike in the chart when the error happens, you cannot use `increase` and have to rely on complex queries. `zero_increase` would easily offer this feature.

It's related to #1673, which has been locked by a bot.

**Comment by brian-brazil** [comment] 2020-05-12 09:32
This is a dupe of #1673, your proposal has the exact same issues as discussed there.

**Closed by brian-brazil** 2020-05-12 09:32 UTC

**Comment by fungiboletus** [comment] 2020-05-12 09:34
#1673 is a bug, closed, and locked. Mine is feature request.

**Comment by brian-brazil** [comment] 2020-05-12 09:38
What you're requesting is essentially identical to #1673.

**Comment by fungiboletus** [comment] 2020-05-12 09:43
Yes, that's why I link the feature request to the issue #1673. I understand now that you don't want to have this feature request and prefer to keep the conversation on #1673. But it's closed and locked.
Usually I put a 👍 on issues and move on, but since it's locked and you closed the issue after you got interesting suggestions, I thought I could help by making a feature request with a summary. I was wrong, that's fine.
