### ISSUE TITLE
Prometheus service metrics are not consistent with memory issues

### ISSUE THREAD

**Issue by dhbarman** [prometheus/prometheus#5700] opened 2019-06-21 13:59 UTC
## Bug Report
**What did you do?**

Three instances of Prometheus were running in production and all of them crashed on different occasions due to memory issues.

**What did you expect to see?**

No memory issues

**What did you see instead? Under which circumstances?**

Errors in logs. But in prometheus console we don't see any gradual growth in memory consumption (process_resident_memory_bytes).

**Environment**

* System information:

	Linux 4.1.12-124.27.1.el7uek.x86_64 x86_64

* Prometheus version:

```
prometheus, version 2.9.1 (branch: release-2.9, revision: 9b00faa5ccd46413ab733a4740b7b3b5a6bffde5)
  build user:       teamcity@tca-hv05-agent005-default
  build date:       20190611-21:22:14
  go version:       go1.12.4
```

* Logs:
```
level=info ts=2019-06-20T03:02:29.133Z caller=compact.go:499 component=tsdb msg="write block" mint=1560988800000 maxt=156099600000
0 ulid=01DDSD784PKD89XGWNC645GE47 duration=2m28.854925279s
level=error ts=2019-06-20T03:02:39.181Z caller=db.go:363 component=tsdb msg="compaction failed" err="reload blocks: unexpected cor
rupted block:map[01DDSD784PKD89XGWNC645GE47:mmap files: mmap: cannot allocate memory]"
level=info ts=2019-06-20T03:05:06.595Z caller=compact.go:499 component=tsdb msg="write block" mint=1560988800000 maxt=156099600000
0 ulid=01DDSDC49NDYVH35TCYM3FJZM4 duration=2m26.413867455s
level=info ts=2019-06-20T03:05:29.168Z caller=head.go:540 component=tsdb msg="head GC completed" duration=14.153918585s
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x213ea8e, 0x16)
        /data/buildAgent/work/go-compiler/go/src/runtime/panic.go:617 +0x72
runtime.sysMap(0x13158000000, 0x20000000, 0x3a23f18)
        /data/buildAgent/work/go-compiler/go/src/runtime/mem_linux.go:170 +0xc7
runtime.(*mheap).sysAlloc(0x3a0b0a0, 0x1cff4000, 0x3a0b0b0, 0xe7fa)
        /data/buildAgent/work/go-compiler/go/src/runtime/malloc.go:633 +0x1cd
runtime.(*mheap).grow(0x3a0b0a0, 0xe7fa, 0x0)

```

**Comment by cstyan** [comment] 2019-09-20 23:53
Can you share your config file? Are you running in a container or k8s? What values are `go_memstats...` metrics reporting?

**Comment by csmarchbanks** [comment] 2019-09-24 02:25
Prometheus v2.12.0 included many memory improvements for tsdb, do you still have issues when using that version?

It looks like the OOM occurred during compaction which could have been a quick spike in memory rather than a gradual increase.

**Comment by beorn7** [comment] 2020-05-04 14:43
We are currently running a bug scrub with the team. We close this assuming the lack of follow-up means the issue is fixed with recent Prometheus versions. Please follow up if you still have issues.

**Closed by beorn7** 2020-05-04 14:43 UTC
Labels: kind/more-info-needed
