### ISSUE TITLE
`kubernetes_sd_config` doesn't discover Kubernetes endpoints correctly after some time

### ISSUE THREAD

**Issue by multani** [prometheus/prometheus#11444] opened 2022-10-11 14:28 UTC
### What did you do?

* Prometheus is configured to discover Alertmanagers using the `kubernetes_sd_configs` discovery mechanism (using Kubernetes "endpoints"):
  ```yaml
  alerting:
    alertmanagers:
    - follow_redirects: true
      enable_http2: true
      scheme: http
      path_prefix: /
      timeout: 10s
      api_version: v2
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: prometheus-operator-alertmanager
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        separator: ;
        regex: http-web
        replacement: $1
        action: keep
      kubernetes_sd_configs:
      - role: endpoints
        kubeconfig_file: ""
        follow_redirects: true
        enable_http2: true
        namespaces:
          own_namespace: false
          names:
          - prometheus-operator
  ```

* Alertmanager runs as a Kubernetes statefulset

Everything runs using the [Prometheus Kubernetes Operator](https://github.com/prometheus-operator/prometheus-operator/) and the [kube-prom-stack Helm Chart](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack).

### What did you expect to see?

Every time Alertmanager restarts and gets a new IP addresses, Prometheus should automatically discover that new IP addresses  without having to restart the Prometheus process.

### What did you see instead? Under which circumstances?

Using the configuration posted above, we can see the following.

Alertmanager runs and exposes its endpoint to Prometheus:

```
$ kubectl get endpoints prometheus-operator-alertmanager
NAME                               ENDPOINTS                                            AGE
prometheus-operator-alertmanager   10.96.12.31:9093,10.96.21.48:9093,10.96.22.74:9093   96d
```

There are 3 Alertmanager pods running here, and their endpoints are correctly configured in Prometheus:

```
$ curl -s http://localhost:9090/api/v1/alertmanagers | jq .data.activeAlertmanagers
[
  {
    "url": "http://10.96.12.31:9093/api/v2/alerts"
  },
  {
    "url": "http://10.96.21.48:9093/api/v2/alerts"
  },
  {
    "url": "http://10.96.22.74:9093/api/v2/alerts"
  }
]
```

Prometheus doesn't log any special information about Alertmanager at this stage (see "Prometheus starting logs" below)

After waiting enough time and having Alertmanagers restarted several times (using `kubectl rollout  restart statefulset alertmanager-prometheus-operator-alertmanager`), we eventually reach out a stage where the Alertmanagers configured in Prometheus differ from the one exposed by Kubernetes:

Alertmanager endpoints now, as they should be discovered by Prometheus's configuration, return:

```
$ kubectl get endpoints prometheus-operator-alertmanager
NAME                               ENDPOINTS                                            AGE
prometheus-operator-alertmanager   10.96.12.35:9093,10.96.21.52:9093,10.96.22.81:9093   96d
```

But Prometheus still returns (only the 2nd Alertmanager is correctly configured here):

```
$ curl -s http://localhost:9090/api/v1/alertmanagers | jq .data.activeAlertmanagers
[
  {
    "url": "http://10.96.12.33:9093/api/v2/alerts"
  },
  {
    "url": "http://10.96.21.52:9093/api/v2/alerts"
  },
  {
  "url": "http://10.96.22.80:9093/api/v2/alerts"
  }
]
```

Note that this is difficult to reproduce reliably: it seems it happens more easily if Prometheus is running for several hours, but so far, we haven't found what starts to desynchronize both systems (Prometheus vs Kubernetes endpoints).

After that desynchronization, Prometheus starts to log:

```json
{"alertmanager":"http://10.96.22.80:9093/api/v2/alerts","caller":"notifier.go:534","component":"notifier","count":15,"err":"Post \"http://10.96.22.80:9093/api/v2/alerts\": context deadline exceeded","level":"error","msg":"Error sending alert","ts":"2022-10-11T14:12:03.897Z"}
```

Eventually, all the Alertmanagers URLs known by Prometheus don't exist anymore and Prometheus is unable to send any alerts. The only way we have to get out of this situation is to restart the Prometheus process.

### System information

Linux 5.10.133+ #1 SMP Thu Aug 18 08:46:00 UTC 2022 x86_64

### Prometheus version

```text
2.39.1 (running Docker image `quay.io/prometheus/prometheus:v2.39.1`)
```

### Prometheus configuration file

```yaml
alerting:
    alertmanagers:
    - follow_redirects: true
      enable_http2: true
      scheme: http
      path_prefix: /
      timeout: 10s
      api_version: v2
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: prometheus-operator-alertmanager
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        separator: ;
        regex: http-web
        replacement: $1
        action: keep
      kubernetes_sd_configs:
      - role: endpoints
        kubeconfig_file: ""
        follow_redirects: true
        enable_http2: true
        namespaces:
          own_namespace: false
          names:
          - prometheus-operator
```

### Alertmanager version

```text
0.24.0 (runing Docker image `quay.io/prometheus/alertmanager:v0.24.0`)
```

### Logs

```text
{"caller":"main.go:543","level":"info","mode":"server","msg":"Starting Prometheus Server","ts":"2022-10-11T14:03:22.273Z","version":"(version=2.39.1, branch=HEAD, revision=dcd6af9e0d56165c6f5c64ebbc1fae798d24933a)"}
{"build_context":"(go=go1.19.2, user=root@273d60c69592, date=20221007-15:57:09)","caller":"main.go:548","level":"info","ts":"2022-10-11T14:03:22.273Z"}
{"caller":"main.go:549","host_details":"(Linux 5.10.133+ #1 SMP Thu Aug 18 08:46:00 UTC 2022 x86_64 prometheus-prometheus-operator-prometheus-0 (none))","level":"info","ts":"2022-10-11T14:03:22.273Z"}
{"caller":"main.go:550","fd_limits":"(soft=1048576, hard=1048576)","level":"info","ts":"2022-10-11T14:03:22.273Z"}
{"caller":"main.go:551","level":"info","ts":"2022-10-11T14:03:22.273Z","vm_limits":"(soft=unlimited, hard=unlimited)"}
{"address":"0.0.0.0:9090","caller":"web.go:559","component":"web","level":"info","msg":"Start listening for connections","ts":"2022-10-11T14:03:22.278Z"}
{"caller":"main.go:980","level":"info","msg":"Starting TSDB ...","ts":"2022-10-11T14:03:22.279Z"}
{"caller":"tls_config.go:231","component":"web","http2":false,"level":"info","msg":"TLS is disabled.","ts":"2022-10-11T14:03:22.281Z"}
{"caller":"repair.go:56","component":"tsdb","level":"info","maxt":1664064000000,"mint":1663939683056,"msg":"Found healthy block","ts":"2022-10-11T14:03:22.294Z","ulid":"01GEEVK5RQVYXWPEZEWGA77NR8"}
{"caller":"repair.go:56","component":"tsdb","level":"info","maxt":1664258400000,"mint":1664064000008,"msg":"Found healthy block","ts":"2022-10-11T14:03:22.295Z","ulid":"01GEEVQF0VRX9XBM0783DYRS32"}
{"caller":"repair.go:56","component":"tsdb","level":"info","maxt":1664452800000,"mint":1664258400029,"msg":"Found healthy block","ts":"2022-10-11T14:03:22.295Z","ulid":"01GEEVYY20QCKH0NGGVPQ2Q9QE"}
{"caller":"repair.go:56","component":"tsdb","level":"info","maxt":1664647200000,"mint":1664452800000,"msg":"Found healthy block","ts":"2022-10-11T14:03:22.296Z","ulid":"01GEEW8D1C6RB641ANS443QD4C"}
{"caller":"repair.go:56","component":"tsdb","level":"info","maxt":1664841600000,"mint":1664647200012,"msg":"Found healthy block","ts":"2022-10-11T14:03:22.296Z","ulid":"01GEGP1CJ6MSWRYHYPPMQS1C47"}
{"caller":"repair.go:56","component":"tsdb","level":"info","maxt":1665036000000,"mint":1664841600002,"msg":"Found healthy block","ts":"2022-10-11T14:03:22.297Z","ulid":"01GEPF8ZYV45R6GKPP1C4CJ309"}
{"caller":"repair.go:56","component":"tsdb","level":"info","maxt":1665230400000,"mint":1665036000006,"msg":"Found healthy block","ts":"2022-10-11T14:03:22.298Z","ulid":"01GEW8NE2W9V7CMKCJDC53PVGE"}
{"caller":"repair.go:56","component":"tsdb","level":"info","maxt":1665424800000,"mint":1665230400001,"msg":"Found healthy block","ts":"2022-10-11T14:03:22.307Z","ulid":"01GF225F6GPSB4YZR1EPX66NR7"}
{"caller":"repair.go:56","component":"tsdb","level":"info","maxt":1665446400000,"mint":1665424800010,"msg":"Found healthy block","ts":"2022-10-11T14:03:22.324Z","ulid":"01GF2PMWMNSCNEPN6NVMV4EEGY"}
{"caller":"repair.go:56","component":"tsdb","level":"info","maxt":1665475200000,"mint":1665468000001,"msg":"Found healthy block","ts":"2022-10-11T14:03:22.325Z","ulid":"01GF34BCMN94GD446JFMBJQNH9"}
{"caller":"repair.go:56","component":"tsdb","level":"info","maxt":1665482400000,"mint":1665475200001,"msg":"Found healthy block","ts":"2022-10-11T14:03:22.326Z","ulid":"01GF3B73WN7DS3GHXWGZ5F2FXE"}
{"caller":"repair.go:56","component":"tsdb","level":"info","maxt":1665468000000,"mint":1665446400009,"msg":"Found healthy block","ts":"2022-10-11T14:03:22.326Z","ulid":"01GF3B8B5024XB960EJY3ZXASM"}
{"caller":"repair.go:56","component":"tsdb","level":"info","maxt":1665489600000,"mint":1665482400001,"msg":"Found healthy block","ts":"2022-10-11T14:03:22.327Z","ulid":"01GF3J2V4PC0G10NRTHPGRW6VM"}
{"caller":"head.go:551","component":"tsdb","level":"info","msg":"Replaying on-disk memory mappable chunks if any","ts":"2022-10-11T14:03:30.316Z"}
{"caller":"head.go:595","component":"tsdb","duration":"4.279002983s","level":"info","msg":"On-disk memory mappable chunks replay completed","ts":"2022-10-11T14:03:34.595Z"}
{"caller":"head.go:601","component":"tsdb","level":"info","msg":"Replaying WAL, this may take a while","ts":"2022-10-11T14:03:34.595Z"}
{"caller":"head.go:637","component":"tsdb","level":"info","msg":"WAL checkpoint loaded","ts":"2022-10-11T14:03:43.044Z"}
{"caller":"head.go:672","component":"tsdb","level":"info","maxSegment":2350,"msg":"WAL segment loaded","segment":2338,"ts":"2022-10-11T14:03:44.931Z"}
{"caller":"head.go:672","component":"tsdb","level":"info","maxSegment":2350,"msg":"WAL segment loaded","segment":2339,"ts":"2022-10-11T14:03:47.314Z"}
{"caller":"head.go:672","component":"tsdb","level":"info","maxSegment":2350,"msg":"WAL segment loaded","segment":2340,"ts":"2022-10-11T14:03:49.420Z"}
{"caller":"head.go:672","component":"tsdb","level":"info","maxSegment":2350,"msg":"WAL segment loaded","segment":2341,"ts":"2022-10-11T14:03:51.736Z"}
{"caller":"head.go:672","component":"tsdb","level":"info","maxSegment":2350,"msg":"WAL segment loaded","segment":2342,"ts":"2022-10-11T14:03:53.673Z"}
{"caller":"head.go:672","component":"tsdb","level":"info","maxSegment":2350,"msg":"WAL segment loaded","segment":2343,"ts":"2022-10-11T14:03:55.920Z"}
{"caller":"head.go:672","component":"tsdb","level":"info","maxSegment":2350,"msg":"WAL segment loaded","segment":2344,"ts":"2022-10-11T14:03:57.838Z"}
{"caller":"head.go:672","component":"tsdb","level":"info","maxSegment":2350,"msg":"WAL segment loaded","segment":2345,"ts":"2022-10-11T14:03:59.693Z"}
{"caller":"head.go:672","component":"tsdb","level":"info","maxSegment":2350,"msg":"WAL segment loaded","segment":2346,"ts":"2022-10-11T14:04:01.774Z"}
{"caller":"head.go:672","component":"tsdb","level":"info","maxSegment":2350,"msg":"WAL segment loaded","segment":2347,"ts":"2022-10-11T14:04:03.669Z"}
{"caller":"head.go:672","component":"tsdb","level":"info","maxSegment":2350,"msg":"WAL segment loaded","segment":2348,"ts":"2022-10-11T14:04:05.827Z"}
{"caller":"head.go:672","component":"tsdb","level":"info","maxSegment":2350,"msg":"WAL segment loaded","segment":2349,"ts":"2022-10-11T14:04:06.427Z"}
{"caller":"head.go:672","component":"tsdb","level":"info","maxSegment":2350,"msg":"WAL segment loaded","segment":2350,"ts":"2022-10-11T14:04:06.428Z"}
{"caller":"head.go:709","checkpoint_replay_duration":"8.449074515s","component":"tsdb","level":"info","msg":"WAL replay completed","total_replay_duration":"36.112144645s","ts":"2022-10-11T14:04:06.428Z","wal_replay_duration":"23.38393787s","wbl_replay_duration":"164ns"}
{"caller":"main.go:1001","fs_type":"EXT4_SUPER_MAGIC","level":"info","ts":"2022-10-11T14:04:10.041Z"}
{"caller":"main.go:1004","level":"info","msg":"TSDB started","ts":"2022-10-11T14:04:10.041Z"}
{"caller":"main.go:1184","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Loading configuration file","ts":"2022-10-11T14:04:10.041Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.052Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.052Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.053Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.053Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.054Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.054Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.054Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.055Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.055Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.056Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.056Z"}
{"caller":"kubernetes.go:326","component":"discovery manager notify","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.057Z"}
{"caller":"main.go:1221","db_storage":"2.338µs","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Completed loading of configuration file","notify":"32.674µs","notify_sd":"448.929µs","query_engine":"1.952µs","remote_storage":"2.185µs","rules":"105.863522ms","scrape":"505.828µs","scrape_sd":"5.431873ms","totalDuration":"121.861347ms","tracing":"11.449µs","ts":"2022-10-11T14:04:10.163Z","web_handler":"659ns"}
{"caller":"main.go:965","level":"info","msg":"Server is ready to receive web requests.","ts":"2022-10-11T14:04:10.163Z"}
{"caller":"manager.go:943","component":"rule manager","level":"info","msg":"Starting rule manager...","ts":"2022-10-11T14:04:10.163Z"}
{"caller":"main.go:1184","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Loading configuration file","ts":"2022-10-11T14:04:10.163Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.174Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.175Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.175Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.175Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.176Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.176Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.177Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.177Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.177Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.178Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.178Z"}
{"caller":"kubernetes.go:326","component":"discovery manager notify","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.179Z"}
{"caller":"main.go:1221","db_storage":"2.478µs","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Completed loading of configuration file","notify":"28.613µs","notify_sd":"612.06µs","query_engine":"1.356µs","remote_storage":"2.476µs","rules":"109.399766ms","scrape":"95.831µs","scrape_sd":"4.532069ms","totalDuration":"124.953568ms","tracing":"6.729µs","ts":"2022-10-11T14:04:10.288Z","web_handler":"620ns"}
{"caller":"main.go:1184","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Loading configuration file","ts":"2022-10-11T14:04:10.288Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.298Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.298Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.298Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.299Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.299Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.299Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.300Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.300Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.300Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.301Z"}
{"caller":"kubernetes.go:326","component":"discovery manager scrape","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.301Z"}
{"caller":"kubernetes.go:326","component":"discovery manager notify","discovery":"kubernetes","level":"info","msg":"Using pod service account via in-cluster config","ts":"2022-10-11T14:04:10.302Z"}
{"caller":"main.go:1221","db_storage":"2.164µs","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Completed loading of configuration file","notify":"19.335µs","notify_sd":"363.836µs","query_engine":"1.257µs","remote_storage":"2.807µs","rules":"118.927463ms","scrape":"77.471µs","scrape_sd":"4.150944ms","totalDuration":"132.278018ms","tracing":"9.259µs","ts":"2022-10-11T14:04:10.421Z","web_handler":"646ns"}
```

**Comment by multani** [comment] 2022-10-11 14:32
Note that there was a similar issue reported in https://github.com/prometheus/prometheus/issues/8768 and released in 2.38.0 but it still happens for us as of Prometheus 2.39.1.

We don't really have much more detailed information at this stage, but this happens almost several times a month, on multiple Kubernetes clusters (so different deployments of Prometheus/Alertmanagers) since multiple releases (our earliest report in our team is from beginning of 2021).

We deploy a set of Prometheus and Alertmanager per Kubernetes cluster, they communicate only between them in the same cluster (not cross Kubernetes communications).

**Comment by roidelapluie** [comment] 2022-10-13 10:39
Duplicate of https://github.com/prometheus/prometheus/issues/11305

**Closed by roidelapluie** 2022-10-13 10:39 UTC

**Comment by Sijoma** [comment] 2022-10-13 22:26
We (same group as @multani) experience the very same issue with `dns_sd_config` . Prometheus is not able to update the IPs even though it should do it every 30s. 

We tested the following configuration:
```yaml
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    dns_sd_configs:
    - names:
      - alertmanager-operated
      refresh_interval: 30s
      type: A
      port: 9093
```

Is that still a duplciate of #11305 ?
