### ISSUE TITLE
Remote writing only Prometheus consumes more than 10Gb of RAM

### ISSUE THREAD

**Issue by weeco** [prometheus/prometheus#5666] opened 2019-06-14 14:31 UTC
## Bug Report
**What did you do?**

I am running Prometheus v2.10.0 which is configured to remote write all metrics to my Cortex cluster. This prometheus instance is not used for any reads. However this instance consumes more than 10GB of RAM.

**What did you expect to see?**

I expected the remote writing prometheus only takes like 1-2 GB RAM max as I don't see why it would need to keep so much data in memory.

**What did you see instead? Under which circumstances?**

Prometheus takes 10.5GB RAM and is pretty stable around this.

Prometheus metrics: 

![Bildschirmfoto 2019-06-14 um 14 25 01](https://user-images.githubusercontent.com/23424570/59509231-bc891700-8eb0-11e9-809b-65f8acd17b6f.png)

**Environment**

Kubernetes / Docker + Persistent Volume for the prometheus data directory

* Prometheus version:

v2.10.0

**Prometheus Flags**

```
          args = [
            "--config.file=/etc/prometheus/prometheus.yml",
            "--storage.tsdb.path=/data",
            "--storage.tsdb.no-lockfile",
            "--storage.tsdb.min-block-duration=2h",
            "--storage.tsdb.max-block-duration=2h",
            "--storage.tsdb.retention.time=1d",
            "--web.enable-lifecycle",
            "--web.console.libraries=/etc/prometheus/console_libraries",
            "--web.console.templates=/etc/prometheus/consoles",
          ]
```

Why does it take so much RAM? Is it supposed to be like this or is this a bug / configuration issue?

**Comment by cstyan** [comment] 2019-06-14 16:58
Can you show us your config file? Specifically the remote write/queue config?

**Comment by weeco** [comment] 2019-06-14 17:09
Sure:

```
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  scrape_timeout: 15s
  evaluation_interval: 15s
remote_write:
  - url: ${remote_write_url}
    bearer_token_file: "/etc/secrets/bearer_token.txt"
    queue_config:
      max_shards: 250
      max_samples_per_send: 500
```

I omitted the scrape configs which are just some kubernetes entities (pods, services, endpoints)

**Comment by cstyan** [comment] 2019-06-14 17:23
Looks reasonable to me. We saw something like a 20% increase in memory usage from 2.7 to 2.8 with the new remote write implementation.

What metric are you looking at for the memory usage?

**Comment by weeco** [comment] 2019-06-14 17:27
I looked at the CAdvisor metrics + node exporter metrics. `kubectl top pods` also returns that Prometheus consumed 10.5G RAM. 

When I start prometheus without any persisted data it starts with pretty much 100MB ram and slowly increases in memory usage up to the point where it keeps 10.5G memory in RAM. So when I would recreate a prometheus instance like every 2h I'd achieve what I want (prometheus sending metrics to Cortex) and it would just consume 2G instead of 10G RAM or so. This doesn't sound right to me.

**Comment by cstyan** [comment] 2019-06-14 17:34
I think the resharding issue might be the cause of some extra memory usage, at least from the OS's point of view, since GC takes a little bit to kick in. As of 2.8 remote write is now caching labels for all active series though, that has an affect on memory usage.

Do you might grabbing me the heap profile from the pprof endpoint so we can rule out some things?

**Comment by weeco** [comment] 2019-06-14 17:40
Hmm what is considered an active series, is there something which I could tweak to reduce the amount of active serieses? I sure have lots of metric series, but I could imagine I do not want my prometheus keeping all these labels in memory?

Here's the heap: https://we.tl/t-TqxYP7Behm

**Comment by cstyan** [comment] 2019-06-14 20:14
> Hmm what is considered an active series, is there something which I could tweak to reduce the amount of active serieses?

Any series that has samples in the in memory Head would be considered active, have a look at the metric `prometheus_tsdb_head_series`. So anything that has at least one scraped sample in the last couple of hours. So for example, a k8s pod that died a day ago should no longer have active series (assuming it's pod name was a label on some series). 

You could reduce the amount of active series with relabelling rules, or reduce the amount of series you're sending over remote write again with relabelling. It depends on whether you care about all the series you're scraping or not.

> I sure have lots of metric series, but I could imagine I do not want my prometheus keeping all these labels in memory?

If the series is active, and you haven't used relabelling to drop it for remote write, it's labels have to be cached. There are some possible optimizations we can make going forward, but the series record (which tells us which labels are part of that series) is only written to the WAL once. From then on, we would only see samples records, which just tell us which series reference to use to get those labels.

**Comment by weeco** [comment] 2019-06-14 21:52
> have a look at the metric `prometheus_tsdb_head_series`

I've got 650k-750k series in memory according to that metric.

So as far as I understood as of now I can't do anything to reduce the memory usage except dropping more metrics which are not important to me?

**Comment by cstyan** [comment] 2019-06-14 22:33
Not much else, no. 

You could try comparing your current instance's memory usage with either another instance running remote write but use v2.7.x (pre-remote write via WAL changes) or with the same version but with remote write turned off. That would show us how much impact remote write was having in your case.

As a data point, we have an instance with ~1.2mil active series and it's using ~18.5G of memory.

**Comment by weeco** [comment] 2019-06-19 15:01
@cstyan I tested v2.7.2 and it consumed pretty much the same amount of RAM (+/- 1-2GB). We also use the prometheus operator for running a normal prometheus cluster (with Thanos remote read/write) and it consumes pretty much the same amount of RAM compared to the instance which does nothing but remote writing.

In my opinion prometheus is currently lacking a mode where it would just scrape data and pushes that to a remote cluster (like Cortex) without keeping all the metrics in RAM (which it apparently does, no matter whether you use it only for writing metrics or reading as well).

**Comment by csmarchbanks** [comment] 2019-06-19 21:38
Moving a bit of conversation here to be more open: 

One option to reduce memory is to reduce the amount of data kept in the head via the `storage.tsdb.min-block-duration` flag so that data is flushed to disk more often. @weeco tried this and saw memory improvements on the order of 50-70%.

A Prometheus like scraper that sends straight to remote write would be more efficient, but as has been discussed before does not belong as part of Prometheus.

**Comment by daxwang** [comment] 2019-06-24 03:58
i have this problem also,  prometheus with version v2.8.1 consumes 40G of memory, one remote write,  so i change prometheus to version v2.7.2,   comsumes 10G memory.  that's ok for me.

**Comment by cstyan** [comment] 2019-06-24 04:05
@daxwang the conclusion here was that @weeco's 2.10 instance was not consuming significantly more ram than his 2.7.2 instance with the same configuration. If you're seeing that much of a memory usage difference between 2.7.2 and 2.8.1, please try again with 2.7.2 and 2.10. 2.8.1 doesn't have a couple of memory usage improvements we made in the remote write path. 

If you still see the same issue with 2.10 please open a new issue and I'll be happy to dig into it with you.

**Comment by beorn7** [comment] 2019-08-01 15:25
There seems to be nothing left to do WRT this issue. Following @cstyan's recommendation, I'm closing this.

**Closed by beorn7** 2019-08-01 15:25 UTC
Labels: component/remote storage

**Comment by bpownow** [comment] 2019-12-19 19:07
This appears to still be a huge issue @cstyan @beorn7. Started using remote_write on 2.14 and we're seeing memory jump 50-70% in the best case.

**Comment by cstyan** [comment] 2019-12-19 22:08
Can you provide more info; what version were you using before and were you using remote write with it, active series/series churn, etc. Unless a bug has been introduced in 2.14 I was under the impression the previous issues were fixed. I can provide some metrics to look at if you'd like.

Remote write is always going to add to memory usage since we cache label data.

**Comment by bpownow** [comment] 2019-12-19 23:07
I'm using remote_write with v2.14.0.

**Comment by cstyan** [comment] 2019-12-23 17:55
Sorry, but again I'd need more information to tell you whether or not what you're seeing is expected. For example, the number of active series, how much memory your instance is already using, etc.

FWIW upgraded one of our Prometheus instances from 2.13.x to 2.14.0 and over the last 3+ days the memory usage has been the same as it was with 2.13.x.
