### ISSUE TITLE
Implement ValueStream?

### ISSUE THREAD

**Issue by sunyc** [prometheus/prometheus#638] opened 2015-04-15 14:51 UTC
Hi,

I'm surprised to see that prometheus (or should I say, borgmon2) doesn't implement a valuestream function yet (allow transferring timeseries between prometheus instances). Which I thought was crucial to implement a multi-tier aggregation hierarchy,   

Any thoughts?

BTW: you guys are awsome creating prometheus!

**Comment by matthiasr** [comment] 2015-04-15 15:05
I've been playing around with multi-tier aggregation by exposing handcrafted "metrics" endpoints as console templates, building on [this example](https://github.com/prometheus/prometheus/blob/master/consoles/federation_template_example.txt). You can, instead of matching the name, specify any query (but need to then give it a new name). The effect is that one Prometheus can publish arbitrary (raw, aggregated or otherwise computed) timeseries that are then available to be scraped (albeit not at the standard endpoint) by any other prometheus.

**Comment by beorn7** [comment] 2015-04-15 15:16
@sunyc Could you explain what you mean by "valuestream"?

**Comment by sunyc** [comment] 2015-04-15 15:20
@matthiasr  which is obviously not very efficient...  And there is timestamping issue.

@beorn7  ValueStream is a RPC service that allows an prometheus instance scrape timeseries  from another prometheus . Which also retains original timestamp etc.

It has a number of usefulness, namely,  one could have a prometheus  that valuestream from several peers for aggregation etc etc etc.

**Comment by matthiasr** [comment] 2015-04-15 15:24
I'm not too worried about timestamps … when aggregating for example request counts from many individual instances as one timeseries, there is no one timestamp anyway. And if the samples are just passed through 1:1 then why aggregate in the first place?

**Comment by beorn7** [comment] 2015-04-15 15:24
The Prometheus scrape protocol already contains a timestamp for that purpose. However, it is currently not possible to scrape multiple samples for one time series in one scrape.

**Comment by sunyc** [comment] 2015-04-15 15:27
@matthiasr  because scrape is not synchronized between  targets,  If there were no timestamp in the output the aggregation would produce wrong values..

**Comment by juliusv** [comment] 2015-04-15 15:49
Heya Yucong,

valuestreaming aka hierarchical federation is on our roadmap:
http://prometheus.io/docs/introduction/roadmap/#hierarchical-federation

Right now we only have the "hack" that Matthias mentioned, but soon[tm]
we'll have the real thing. I agree, it should be possible to transfer raw
samples with their original timestamps and uninterpolated values.

Cheers,
Julius

**Comment by sunyc** [comment] 2015-04-15 15:55
I would be happy to help (maybe we can also use go-grpc now), believe it or not, i spent quite a bit of of time on it in the past life . 

LoL

**Comment by beorn7** [comment] 2015-04-15 16:00
I'll close this as a duplicate of https://github.com/prometheus/prometheus/issues/9 (updated that issue with the notion of "streaming").

**Closed by beorn7** 2015-04-15 16:00 UTC

**Comment by juliusv** [comment] 2015-04-15 16:07
@sunyc That'd be great in general. As a smaller starter project it'd probably be good to start with something small to get acquainted with the whole code and contributing business, and then go from there. We're all also hanging out on `#prometheus` on Freenode for discussions and inspiration :)
