### ISSUE TITLE
feature request: extend agent to write/read to/from filesystem instead of in-memory with retention

### ISSUE THREAD

**Issue by ydayagi** [prometheus/prometheus#10304] opened 2022-02-16 14:08 UTC
## Background of the problem
Hi.
We are working on managing edge devices from a central management application. Management application executes in k8s.

At the moment, we collect/scrape metrics ourselves in the device. Metrics are saved in TSDB format.
We need to send these metrics to the k8s cluster.
In the cluster, metrics should be available for querying. Either by user or Grafana.
We also need to be able to forward the metrics from the cluster to a multi-cluster management application like Stolostron.

We were made aware of Prometheus Agent Mode and thought of using that as the collector and forwarder in the devices (replace our implementation). It will write to a Prometheus/Thanos server in the cluster.
## Request/Proposal
The agent is missing a few features:
- write from TSDB files and not from memory
- disable in-memory metrics (default 2 hours) for lowering the memory usage
- delete/forget whatever was sent from TSDB files
- apply retention rules. delete metrics older than the configured threshold.

Existing features that might need verification or enhancements:
- Agent should retry endlessly to send the data. Our use case is 10000s of devices and not all can write at once.
## Links
[feature request: Add agent support for beyond WAL persistent storage and metric export](https://github.com/prometheus/prometheus/issues/9607)

**Comment by ydayagi** [comment] 2022-02-16 14:09
@bwplotka here's a new issue following our discussion. Thanks for all your help. appreciate it.

**Comment by roidelapluie** [comment] 2022-02-25 16:35
Prometheus agent is read/writing metrics from filesystem already, I am not sure what you mean with this issue. The agent is using a Write-Ahead-Log on disk.

**Comment by roidelapluie** [comment] 2022-02-25 16:35
cc @rfratto

**Comment by rfratto** [comment] 2022-02-25 18:28
It sounds like the proposal is for Prometheus Agent to write scraped metrics directly to the WAL and hold absolutely nothing in memory long-term (including from remote_write which also holds series in memory). Am I following correctly?

**Comment by ydayagi** [comment] 2022-02-27 09:40
@rfratto @roidelapluie 
Perhaps I am not aware of how agent works. I thought that it saves up to 2 hours of metrics. All of it as part of WAL and may be persisted to filesystem.
What I need is to save more than 2 hours. Days. Write the metrics to remote server. Delete sent metrics.

**Comment by bwplotka** [comment] 2022-03-11 14:31
Hm let's clarify this issue @ydayagi 

> write from TSDB files and not from memory

Do you mean remote write from TSBD blocks? I believe this ask is covered by https://github.com/prometheus/prometheus/issues/9607

> disable in-memory metrics (default 2 hours) for lowering the memory usage

I guess this is the core of this issue and it means what @rfratto tried to rephrase?

> It sounds like the proposal is for Prometheus Agent to write scraped metrics directly to the WAL and hold absolutely nothing in memory long-term (including from remote_write which also holds series in memory). Am I following correctly?

Is this what we are discussing here?

> Perhaps I am not aware of how agent works. I thought that it saves up to 2 hours of metrics. All of it as part of WAL and may be persisted to filesystem.
What I need is to save more than 2 hours. Days. 

I don't think that is physically possible because some code has to operate that WAL and that needs memory. Plus, I don't think we can have days of data in WAL format as it much less consistent 

> How heavy is the Prometheus server? If configuration includes only a few targets and no alerts are required , can it be considered a small server?

Yes, it can be considered "small". But there are things we can optimize further for your case:

* Removal of any memory structures required for efficient querying capabilities, since you probably don't want that
* Removal of data right after a remote write was successful for such batch of data.

Yet, there is nothing wrong in using it first and trying how it goes. Still, I don't think it matches your other point: the ability to remote write older data like "days", since we can only remote write data from first 2h. And even if we could remote write older data in the event of this binary being out of network for days, most of the backends/remote write receivers does not accept writes older than 2h.

We choose to instead of trimming Prometheus from those features, we will implement an agent mode that starts from the above points. Then we can slowly add things like persistent storage with blocks and ability to forward that data (and remove after forward). This is what https://github.com/prometheus/prometheus/issues/9607 asks for.

> delete/forget whatever was sent from TSDB files

I think this is also covered by https://github.com/prometheus/prometheus/issues/9607, please join discussion there.

**Comment by bboreham** [comment] 2024-07-23 11:23
Closing as duplicate of #9607

**Closed by bboreham** 2024-07-23 11:23 UTC
Labels: kind/more-info-needed
