### ISSUE TITLE
targets defined by consul_sd_config listed multiple times

### ISSUE THREAD

**Issue by guoshimin** [prometheus/prometheus#1083] opened 2015-09-14 17:41 UTC
I built a version from master on 20150909. The commit hash is 9a70ee7. I use consul service discovery to define targets. Over time, the same targets would be added again and again. Over the weekend, some targets were added half a dozen times on the status page.

**Comment by fabxc** [comment] 2015-09-14 17:53
If you hover over the "Base Labels" column in the status page, you are shown some labels.
Can you verify whether those are also the same for all those targets?

Also your configuration would be helpful, especially any relabeling.

**Comment by robbiet480** [comment] 2015-09-19 01:24
I'm also having the same problem now, but on 0.16.0rc1. Base Labels are the same for duplicated targets. My config is below:

```
global:
  scrape_interval:     15s  # default = every 15 seconds.
  evaluation_interval: 15s  # default = every 15 seconds.
  # scrape_timeout is set to the global default (10s).

rule_files:
  - "/etc/prometheus/rules/prometheus.rules"

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    scrape_timeout: 10s
    target_groups:
      - targets: ['localhost:9090']

  - job_name: 'consul'
    target_groups:
      - targets: ['localhost:9107']

  - job_name: "overwritten-default"
    consul_sd_configs:
    - server:   '127.0.0.1:8500'
      datacenter: 'aws-us-east-1'
      services: ['api', 'data-processor', 'data-importer', 'app-proxy', 'memcached_exporter', 'node_exporter', 'jmx_exporter', 'cloudwatch']

    relabel_configs:
    - source_labels: ['__meta_consul_service']
      regex:         '(.*)'
      target_label:  'job'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,jobname=(.*?),.*'
      target_label:  'job'
      replacement:   '$1'
    - source_labels: ['__meta_consul_node']
      regex:         '(.*)'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,Type=(.*?),.*'
      target_label:  'purpose'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,Environment=(.*?),.*'
      target_label:  'environment'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,instancetype=(.*?),.*'
      target_label:  'instancetype'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,jmx_type=(.*?),.*'
      target_label:  'jmx_monitored_application'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,jmx_type=(.*?),.*'
      target_label:  'job'
      replacement:   '$1'
    - source_labels: ['__meta_consul_dc']
      regex:         '(.*?)-(.*)'
      target_label:  'vendor'
      replacement:   '$1'
    - source_labels: ['__meta_consul_dc']
      regex:         '(.*?)-(.*)'
      target_label:  'region'
      replacement:   '$2'

    # metric_relabel_configs:
    # - source_labels: ['exported_job']
    #   regex:         '(.*?)'
    #   target_label:  'job'
    #   replacement:   '$1'
```

**Comment by robbiet480** [comment] 2015-09-19 01:43
FYI Reverting to Prometheus 0.15.1 fixes this problem and doesn't leave the duplicated targets in my status page

**Comment by guoshimin** [comment] 2015-09-19 03:05
Base labels completely identical.

Config:

    consul_sd_configs:
      - server: 'consul1.test.databricks.com:8500'
        services:
          - 'jenkins-slave'
    relabel_configs:
      - source_labels: ['__meta_consul_address']
        target_label: '__address__'
        regex: '(.*)'
        replacement: '${1}:8080'
      - source_labels: ['__meta_consul_tags']
        target_label: 'slave_name'
        regex: '.*slave_name=([^,]*).*'
        replacement: '${1}'
      - source_labels: ['__meta_consul_tags']
        target_label: 'public_hostname'
        regex: '.*public_hostname=([^,]*).*'
        replacement: '${1}'

**Comment by fabxc** [comment] 2015-09-19 10:17
Sorry, I should have been clearer. If you move your mouse over the base labels you see in general, a tooltip pops up that shows the label set before digestion to the base labels. The question is whether the labels in this those tooltips are also identical.

**Comment by robbiet480** [comment] 2015-09-19 12:13
@fabxc Yup, those are the labels I checked. Base labels are the same across duplicated targets. I checked multiple tags and targets to make sure.

**Comment by guoshimin** [comment] 2015-09-19 13:33
Yep, same here. And it would be nice if the base labels can be displayed in
a copy-and-pastable way.

**Comment by brian-brazil** [comment] 2015-09-19 14:06
The current way they're displayed was a quick hack to aid debugging, ultimately there should be a page showing a breakdown of all the labels.

**Comment by robbiet480** [comment] 2015-09-21 20:19
I'm assuming that this was caused by one of these commits: https://github.com/prometheus/prometheus/commit/4e84b86510e3adf2b1ae2e184aba593afb9e5ad9#diff-49cc5c249318707068b4168c27ab0260, https://github.com/prometheus/prometheus/commit/0138d37458567f63b20436d6bf3ac13e9ce4f8b7#diff-49cc5c249318707068b4168c27ab0260

Will look into it more in the next few days and will report back with what I find out.

**Comment by fabxc** [comment] 2015-09-21 20:22
Yes, those are the most likely candidates. Thanks.

**Comment by juliusv** [comment] 2015-09-28 10:32
@robbiet480 @guoshimin there's a slight chance that this was coincidentally fixed by https://github.com/prometheus/prometheus/pull/1116, which has just been merged. Could you give master another try?

**Comment by guoshimin** [comment] 2015-09-29 20:14
Built a binary at bf4e4a8, still having the same problem.

**Comment by juliusv** [comment] 2015-09-30 10:33
Ok, thanks! We'll need to dig deeper into that then.

**Comment by juliusv** [comment] 2015-10-06 13:37
@robbiet480 Any news on figuring out which of the two commits you mentioned creates this bug?

**Comment by robbiet480** [comment] 2015-10-06 19:32
@juliusv Haven't gotten to it yet, wrote a note to test again later today and will report back.

**Comment by juliusv** [comment] 2015-10-06 20:31
@robbiet480 Awesome - that's the last critical bug before we can release 0.16.0 :)

**Comment by juliusv** [comment] 2015-10-08 15:19
I now managed to reproduce this locally against our own Consul setup (we don't usually use Consul's interface directly for SD). Digging deeper now.

**Comment by juliusv** [comment] 2015-10-08 15:42
Can confirm that this regression was introduced by https://github.com/prometheus/prometheus/pull/970. Looking deeper...

**Comment by juliusv** [comment] 2015-10-08 16:09
Found the bug, PR incoming.

**Comment by juliusv** [comment] 2015-10-08 16:55
Fix PR is out here: https://github.com/prometheus/prometheus/pull/1151

**Comment by fabxc** [comment] 2015-10-08 17:00
Thanks a lot!

**Comment by juliusv** [comment] 2015-10-08 19:00
@fabxc It's the only thing blocking a 0.16.0 release :) Go go go :P

**Closed** 2015-10-09 16:21 UTC
Labels: bug, Critical
