### ISSUE TITLE
Allow scrape cache to be disabled per scrape job

### ISSUE THREAD

**Issue by rfratto** [prometheus/prometheus#12443] opened 2023-06-08 12:23 UTC
### Proposal

`metric_relabel_rules` is commonly used to drop unwanted metrics. This is especially useful in Kubernetes environments where there are often targets that expose a significant amount of metrics where not all of them are needed for monitoring. 

However, metrics dropped via `metric_relabel_rules` are still cached, meaning they still have an impact on memory usage; scraping a target that exposes 1,000,000 series but dropping most show a meaningful increase of memory usage, even though those aren't series stored in the TSDB (Prometheus) or WAL (Prometheus Agent). 

I propose extending the scrape_config block to allow disabling the caching for dropped metrics, allowing users to trade off memory consumption for CPU usage (as relabeling will need to be performed every scrape):

```yaml
scrape_configs:
  - job_name: example 
    cache_dropped: false  
    ...
```

**Comment by roidelapluie** [comment] 2023-06-12 21:32
This would be at the expense of CPU usage I guess? Did you run some benchmarks to understand the impact?

**Comment by bboreham** [comment] 2023-06-15 14:35
IMO the problem is not just that the cache includes dropped metrics, but that they include all labels pre-relabeling.
In Kubernetes this can be enormous.

I say we should not store all those labels.  I think they exist to facilitate troubleshooting, but in that case tens of thousands of dropped metrics are not useful; your browser will crash before you can see what happened.  Suggest only storing 100.

I experimented with a version that didn't store the dropped metrics, but re-ran the relabeling if you brought up the UI.

**Comment by roidelapluie** [comment] 2023-06-17 07:48
We can try this. I winder if we should refactor a bit the code to make passing options like this easier, think about it when implementing :-)

Thanks

**Comment by marcelobonin** [comment] 2023-07-18 14:59
There is any progress on this proposal? We are really interested on having this feature implemented.

**Comment by rfratto** [comment] 2023-07-21 15:31
> There is any progress on this proposal? We are really interested on having this feature implemented.

Sorry, I haven't personally been able to put any time into this yet.

**Comment by marcelobonin** [comment] 2023-08-16 23:52
Any progress so far?

**Comment by bboreham** [comment] 2023-10-16 17:30
I had a cunning idea: compress the keys to `scrapeCache.series` and `scrapeCache.droppedSeries`.
However this turns out to be unreasonably expensive in CPU.
@rfratto suggested computing the SHA of each series, which does appear to be workable.
I'll push a PR soon.

**Comment by maokitty** [comment] 2023-12-10 14:34
How about still providing the close cache config? there is situation where all metrics are useful without relabel operation. for example opentelemtry collector scrape the metric

**Comment by beorn7** [comment] 2024-12-03 11:33
Hello from the bug scrub!

#12993 was closed, and so was the PR it was replaced by, #13050, with the message "I guess we're not going to go ahead with this". @bboreham does this apply to this whole idea? Should we close this issue or is it interesting enough to keep it open although no activity has been happening here in a while?

**Comment by bboreham** [comment] 2024-12-03 12:13
I expect what would happen if you try disabling the dropped-metrics cache at scale is the CPU usage will go up so much that you turn it back on again.  So yes, I would close this.

In Prometheus Operator, a popular source of drop relabel rules, there is work under way to use Kubernetes selectors instead - https://github.com/prometheus-operator/prometheus-operator/issues/5345, https://github.com/prometheus-operator/prometheus-operator/pull/7086

> there is situation where all metrics are useful without relabel operation

This proposal is all about the cache for metrics dropped by relabeling. If there is no relabeling, this proposal does not do anything.

I still like https://github.com/prometheus/prometheus/pull/13050, which would shrink all the scrape caches, but nobody else seemed to like it.

**Comment by beorn7** [comment] 2024-12-03 14:22
OK, let's close this then. We can still revisit if somebody has concrete plans to push things with some well reasoned implementation plans.

**Closed by beorn7** 2024-12-03 14:22 UTC

**Comment by ringerc** [comment] 2025-04-22 04:54
People hitting this issue are likely to see large allocations in `scrape (*scrapeCache) addDropped` in `go tool pprof` memory profiles of a Prometheus in which `action: drop` rules are used to drop large numbers of metrics in a `metric_relabel_configs` section.

In my case for example, over 1GiB just for keeping track of the label drop cache.

**Comment by bboreham** [comment] 2025-04-28 17:18
You can monitor `sum(scrape_samples_scraped) - sum(scrape_samples_post_metric_relabeling)` to see how many entries are in the dropped series cache. 

(Not quite as good as the size in bytes, but significantly less work)
