### ISSUE TITLE
Prometheus service discovery taking 2x memory and CPU resulting OOMKilled

### ISSUE THREAD

**Issue by infa-kparida** [prometheus/prometheus#12301] opened 2023-04-28 04:38 UTC
### What did you do?

Upgraded to Prometheus to v2.43.0-stringlabels from 2.37.0.
While navigating to Service Discovery the prometheus POD takes all memory and CPU and resulted in OOMKilled.

In regular situation prometheus POD is taking max 24G memory but when I click on Service Discovery it goes till 56GB of memory(Max Limit set for the POD) and gets OOMKilled.

Tried downgrading to 2.43.0.In this version although POD is not getting OOMKilled service discovery takes lot of time to load making the browser to crash

### What did you expect to see?

I expect service discovery should happen and show on the browser

### What did you see instead? Under which circumstances?

Browser crash in 2.43.0 version and POD getting OOMKilled for v2.43.0-stringlabels version

### Prometheus version

v2.43.0-stringlabels

**Comment by infa-kparida** [comment] 2023-05-01 17:38
Hi @bboreham 
Please find the heap usage details
![profile001](https://user-images.githubusercontent.com/27209740/235498634-225231fc-46f6-4797-8816-57dd630cd4ec.svg)

**Comment by bboreham** [comment] 2023-05-01 18:58
Hi, can you upload the pprof file please; there is a lot of detail that is nearly impossible to derive from the image. 

If you like, use a site like flamegraph.com

**Comment by infa-kparida** [comment] 2023-05-01 19:10
Hi @bboreham  
Please find the flame graph 
https://flamegraph.com/share/87c9e457-e853-11ed-bb01-4a9f46d3c4af

**Comment by infa-kparida** [comment] 2023-05-08 23:18
Can we please look into the above flame graph and see the reason for high resource usage with the latest version

**Comment by bboreham** [comment] 2023-05-10 08:58
Sorry it turns out that flamegraph.com has a bug where it doesn't show the in-use memory, and I went off to see if I could get that fixed and forgot to come back here.

Some points are visible from the image:
* The heap is 14GB so the process would be running at about 28GB at the time; this is closer to the "regular situation [...]
 24G" than the 56GB you reported the OOM at, so the bulk of the problem is probably not in that profile.
* 9% of the heap is in maps being constructed to send data to the browser.  This matches what I said at https://github.com/prometheus/prometheus/issues/12301#issuecomment-1527527289

Suspect the quickest way for your situation to improve is for you to change your service discovery config to filter out targets via label and namespace matchers rather than relabel rules.

In the code, I think we should put a limit on the number of dropped targets that we try to send to the browser.

**Comment by bboreham** [comment] 2023-09-03 09:10
@infa-kparida would you be able to try out v2.47-rc.0 with `keep_dropped_targets` set to something modest, e.g. 20?

**Comment by beorn7** [comment] 2024-11-26 11:07
Hello from the bug scrub!

After 1y without follow-up, we'll close this. Please follow up or file a new issue based on current data if the problem persists.

**Closed by beorn7** 2024-11-26 11:07 UTC
