### ISSUE TITLE
config reloads cause huge increase in memory

### ISSUE THREAD

**Issue by jhorwit2** [prometheus/prometheus#3858] opened 2018-02-17 16:10 UTC
**What did you do?**

I updated the config in a way that should not noticeably impact cpu/memory (updated the scrape timeout from 5s to 10s). 

**What did you expect to see?**

I expected the scrape timeout to increase, which it did and I expected CPU/memory usage to remain the same.

**What did you see instead? Under which circumstances?**

Memory spikes at reload time

![image](https://user-images.githubusercontent.com/3876739/36342894-f2fc3c18-13d2-11e8-97ab-1d64ebdab8fa.png)

I've noticed this happen with any config change as did the memory usage. The series created/removed and appended samples per second had no fluctuation.

**Environment**

* System information:

Running the prometheus 2.2.0-RC0 docker container from dockerhub
Host is `Linux 4.1.12-112.14.13.el7uek.x86_64 x86_64`

* Prometheus version:

```
prometheus, version 2.2.0-rc.0 (branch: HEAD, revision: 1fe05d40e4b2f4f7479048b1cc3c42865eb73bab)
  build user:       root@f7abb25edc70
  build date:       20180213-11:40:47
  go version:       go1.9.2
```

**Comment by jhorwit2** [comment] 2018-02-17 16:13
I should add I've noticed this on 2.1.0 as well. It causes OOMs once prometheus has enough data.

**Comment by brian-brazil** [comment] 2018-02-17 16:57
This is expected when you change your target labels, we need to create new chunks for all the new metrics.

**Comment by jhorwit2** [comment] 2018-02-17 16:59
@brian-brazil That's understandable, but I'm not changing any target labels in this scenario. The only thing i updated was the global scrape timeout (i had nothing timing out before i just wanted to prove this is why it was increasing).

**Comment by brian-brazil** [comment] 2018-02-17 17:07
In that case this was probably coincidental, 15M new chunks is going to take ~15GB of RAM. That's what the graphs you originally had in this bug indicates to me.

**Comment by jhorwit2** [comment] 2018-02-17 17:08
@brian-brazil the reason I removed that graph is I've since run it a couple more times and don't see a correlation between memory chunks increasing and the memory increase.

**Comment by jhorwit2** [comment] 2018-02-17 17:10
![image](https://user-images.githubusercontent.com/3876739/36343546-6efa9d98-13db-11e8-9d34-4ccf803fb3c3.png)

![image](https://user-images.githubusercontent.com/3876739/36343551-7ee37cb6-13db-11e8-84a5-168eee68ea04.png)

I ran another test at ~11:25 which saw an increase in memory but no increase in memory chunks. The config change was decreasing the scrape timeout from 15s to 10s.

**Comment by fabxc** [comment] 2018-02-19 12:34
This is probably caused by re-creating all scrape loops on reload: https://github.com/prometheus/prometheus/blob/404b306fb9d5c0976cc83f0dff39254c0918493e/scrape/scrape.go#L223-L239

In the past this was fairly un-invasive as loops didn't hold any meaningful memory state. But now we actually keep rather big caches per loop for our scrape performance optimisations. 
So I suppose one could say the spike on reload is still a lot less than the general baseline would be without those caches – but ideally it still wouldn't happen of course.

I think it should be safe to hand over the entire scrape cache object to the new loop and thus avoiding the whole issue. But it needs some careful consideration.

**Comment by simonpasquier** [comment] 2018-09-06 15:30
Closing it as a duplicate of #3112.

**Closed by simonpasquier** 2018-09-06 15:30 UTC
Labels: component/scraping, kind/enhancement, not-as-easy-as-it-looks
