### ISSUE TITLE
Support Nacos SD configurations

### ISSUE THREAD

**Issue by TsingLiang** [prometheus/prometheus#7688] opened 2020-07-29 11:48 UTC
Nacos provides a set of simple and useful features enabling developers to realize dynamic service discovery, service configuration, service metadata and traffic management. Now it is widely used with 13.3k stars
Its official website: https://nacos.io/en-us/index.html
github: https://github.com/alibaba/nacos

**Comment by roidelapluie** [comment] 2020-07-29 11:52
duplicate of #7539 , thanks for showing up iterest!

**Closed by roidelapluie** 2020-07-29 11:52 UTC
