### ISSUE TITLE
limiting storage usage, instead of setting -storage.tsdb.retention?

### ISSUE THREAD

**Issue by fanyangCS** [prometheus/prometheus#3999] opened 2018-03-22 10:16 UTC
Is there a way to limit the storage usage?  setting data retention time is somehow problematic in a scenario where the number of exporter changes greatly in a short period of time.

**Comment by brian-brazil** [comment] 2018-03-22 10:26
Dupe of #968

**Closed by brian-brazil** 2018-03-22 10:26 UTC
