### ISSUE TITLE
Add ability to collapse all Targets page headings at once

### ISSUE THREAD

**Issue by mattmendick** [prometheus/prometheus#7497] opened 2020-07-01 21:03 UTC
## Proposal
On the Targets page in the Prometheus web UI, the `show less` and `show more` buttons are great to hide and show the endpoints beneath the job names. It is also great that they remember their settings across page loads. However, if a configuration has a large number of job names, having a button or an option of some sort to expand or collapse all of the elements at once would be helpful.

**Comment by roidelapluie** [comment] 2020-07-02 20:15
Thanks! It is a dupe of #6127

**Closed by roidelapluie** 2020-07-02 20:15 UTC

**Comment by mattmendick** [comment] 2020-07-02 20:22
🤦 sorry I couldn't find it originally - thanks!
