### ISSUE TITLE
feature: Support loading file for Consul Token

### ISSUE THREAD

**Issue by damoun** [prometheus/prometheus#6140] opened 2019-10-15 13:45 UTC
## Proposal

I use vault as a secret storage solution and I think it could be useful to support loading the consul token from a file like the `bearer_token_file`. For exemple, the Marathon SD already support it.

What do you think ?
If you like it, I could start working on a PR.

Thanks

**Comment by rockyluke** [comment] 2019-10-15 19:19
I love the idea!

**Comment by roidelapluie** [comment] 2020-01-21 23:00
The issue is that the upstream consul library never re-reads the file again. Would that still suit your need?

https://github.com/hashicorp/consul/blob/c91d0fa2c9629d74e5fe70e4acf9351f5c22858d/api/api.go#L305

**Comment by brian-brazil** [comment] 2020-01-21 23:23
That's not in line with how we do such files elsewhere, and I can see that causing confusion.

**Comment by gouthamve** [comment] 2020-05-25 14:23
We went through this issue in our bug scrub and this might be possible by switching to a httpTransport passed to the consul client.

@roidelapluie Could you investigate the issue further, and tag it appropriately? As you've looked at this last.

**Comment by beorn7** [comment] 2021-03-01 18:07
Closing this as it is now superseded by #8551

**Closed by beorn7** 2021-03-01 18:07 UTC
Labels: component/service discovery, kind/enhancement

**Comment by roidelapluie** [comment] 2021-06-11 13:50
This is being worked on as part of #8924
