### ISSUE TITLE
Add FastCGI interface to secure prometheus (with unix domain socket)

### ISSUE THREAD

**Issue by michael-doubez** [prometheus/prometheus#5160] opened 2019-01-30 22:20 UTC
## Proposal
**Use case. Why is this important?**

Currently, when trying to secure Prometheus/AlertManager on a non-containerized architecture, the only way to secure it is binding on localhost and using a reverse-proxy (like nginx).
But, the interface is still exposed on localhost interface and there is no way to restrict the access with basic-auth or tls client auth.

**FastCGI**

A good middle-ground solution would be to serve the requests using fastcgi. The module "net/http/fcgi" is readily available and fast-cgi seamlessly integrates with major http servers.

On unix, the security would be provided by using unix domain sockets whose access rights can be controlled. On windows, there would be named pipes; although I am not sure it is as common as unix flavor.

**Comment by brian-brazil** [comment] 2019-01-30 23:35
Dupe of #4068. This is not something we plan on adding.

**Closed by brian-brazil** 2019-01-30 23:35 UTC
