### ISSUE TITLE
caller=stdlib.go:89 component=web caller="http: superfluous response.WriteHeader call from github.com....

### ISSUE THREAD

**Issue by BegoniaGit** [prometheus/prometheus#8904] opened 2021-06-08 09:17 UTC
**What did you do?**
Using Thanos-Query to connect Prometheus in a SideCar mode, but finding that Prometheus will cause Prometheus to make the following error logs. And at the moment query data is very slow.
I found several things:
1. Only some Prometheus will have a very slow phenomenon every 2 hours.；
2. Error logs almost simultaneously fixed several Prometheus instances；
```
level=error ts=2021-06-08T07:47:06.750Z caller=stdlib.go:89 component=web caller="http: superfluous response.WriteHeader call from github.com/opentracing-contrib/go-stdlib/nethttp.(*statusCodeTracker).WriteHeader (status-code-tracker.go:17" msg=)
level=error ts=2021-06-08T07:47:06.751Z caller=stdlib.go:89 component=web caller="http: superfluous response.WriteHeader call from github.com/opentracing-contrib/go-stdlib/nethttp.(*statusCodeTracker).WriteHeader (status-code-tracker.go:17" msg=)
level=error ts=2021-06-08T07:47:06.865Z caller=stdlib.go:89 component=web caller="http: superfluous response.WriteHeader call from github.com/opentracing-contrib/go-stdlib/nethttp.(*statusCodeTracker).WriteHeader (status-code-tracker.go:17" msg=)
level=error ts=2021-06-08T07:47:06.884Z caller=stdlib.go:89 component=web caller="http: superfluous response.WriteHeader call from github.com/opentracing-contrib/go-stdlib/nethttp.(*statusCodeTracker).WriteHeader (status-code-tracker.go:17" msg=)
level=error ts=2021-06-08T07:47:06.932Z caller=stdlib.go:89 component=web caller="http: superfluous response.WriteHeader call from github.com/opentracing-contrib/go-stdlib/nethttp.(*statusCodeTracker).WriteHeader (status-code-tracker.go:17" msg=)
level=error ts=2021-06-08T07:47:06.932Z caller=stdlib.go:89 component=web caller="http: superfluous response.WriteHeader call from github.com/opentracing-contrib/go-stdlib/nethttp.(*statusCodeTracker).WriteHeader (status-code-tracker.go:17" msg=)
level=error ts=2021-06-08T07:47:06.932Z caller=stdlib.go:89 component=web caller="http: superfluous response.WriteHeader call from github.com/opentracing-contrib/go-stdlib/nethttp.(*statusCodeTracker).WriteHeader (status-code-tracker.go:17" msg=)
level=error ts=2021-06-08T07:47:06.956Z caller=stdlib.go:89 component=web caller="http: superfluous response.WriteHeader call from github.com/opentracing-contrib/go-stdlib/nethttp.(*statusCodeTracker).WriteHeader (status-code-tracker.go:17" msg=)
```
This figure shows the problem of PROMETHEUS query, and there is a problem that the fixed cycle is extremely slow：
![image](https://user-images.githubusercontent.com/34222824/121157928-8d79c600-c87c-11eb-9f27-13fc8a0d4c22.png)

**Environment**
 aliyun k8s

* Prometheus version:
prometheus: 2.27.1
thanos: 0.20.2

**Comment by roidelapluie** [comment] 2021-06-08 15:15
Thank you. This is a duplicate of #6139 .

**Closed by roidelapluie** 2021-06-08 15:15 UTC
